### ISSUE TITLE
Uploading (PDF) files w/ Firefox 17.0.1 can break pages

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#1609]
One of my users managed to break several pages by uploading a PDF file from the frontend using Firefox 17.0.1. (I will make him test the current version 18 as well and report back, but anyway the issue is interesting an can be fixed easily.)

What happened was that the mimetype was saved to tha database as `"application/pdf"` instead of `application/pdf`. The quotes, of course, broke the XML output, because the attribute had double quotes, like `...type=""application/pdf""...`

To fix this I changed [a single line in class.xmlelement.php](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.xmlelement.php#L347) (in the `setAttribute` function) from:

```
$this->_attributes[$name] = $value;
```

 to:

```
$this->_attributes[$name] = trim($value, '\"');
```

Of course this might be fixed in the Upload field as well. But the above will prevent breaking the XML for **any** defective (i.e. quoted) attribute values.

If you like this fix, I can send a pull request, of course. Just wanted to discuss it first.

**Comment by nitriques** [comment]
I had this bug in a recent project where we do not use Sym's frontend engine. It's this kind of code that I can't live without .. ;)

**Comment by michael-e** [comment]
:-)
