### ISSUE TITLE
Show Associations

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2082]
If a section contains an associative field (like select boxes, tag lists or SBL fields with dynamic values), there is usually an option to display associations in the entry indexes. I'm not sure if I'm missing something obvious but it seems like we are storing this setting two times in different places and with different logic:

- first, we store it on a per field base in the table belonging to the field,
- second, we store it globally in the section association table.

Fields store, if the associations _should be shown_.
Symphony stores, if the associations _should be hidden_.

That doesn't make sense to me. From a logical point of view, I think fields should not store this at all because associations are handled by the core.

**Can anyone give any insights why this is currently set up the way it is?** 
There certainly are reasons for this setup, are there? And what happens if the settings are contradictory? E. g. one saying to show the other saying to hide associations.

**Comment by brendo** [comment]
Stupid me. As part of the Field creation, all settings from the Field's table is applied as the base configuration for the field. The removal of `show_association` from the Field means that the Field no longer knows whether to show the association or not (hence symphonycms/selectbox_link_field#75, and now that Taglist and Select Box fields also have no idea). 

The `SectionManager` class does not have the ability to retrieve this value based on Field ID either, and even if it did, the question is whose job is it get the value? Should the `FieldManager` now have a dependency to go off and check Associations? Or is it the Field's job? Should the `FieldManager` query the `SectionManager` to return the setting for this Field ID?

Leaning on the former. It used to be it's job and it probably should still be.

**Comment by nitriques** [comment]
> Leaning on the former. It used to be it's job and it probably should still be.

I agree.
