### ISSUE TITLE
Deleting an author doesn't require password of committer

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2131]
As soon as you create an author or manager, you see the new yellow bar telling "Please confirm changes to this author with your password." Which works, kind of. :-) But deleting the author/manager doesn't require a committer's password at all — isnt deleting a change to the author as well?

**Comment by nitriques** [comment]
This has been fixed in f7a5406dd1142febceb636c206d042ab675abdee :+1:
