### ISSUE TITLE
Entry expects Author ID

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2152]
We've just come across an oddity in how Entries are created.

We now use some custom PHP to validate Entry data from the frontend, which allows us to create entries in many sections. This code creates a new Entry object, and populated the data as expected, before committing it to the database with the `commit()` method.

The problem arose whereby there was no Author ID for the entry, and Symphony threw a fatal error stating the the column has no default value.

Why is the `entries` table requiring an Author ID in the first place? How can this ever be populated from the frontend?

**Comment by nitriques** [comment]
> The entry class should set the author ID to 1 if it is missing.

It now does, see 64b2b7f4f6

> If you create an Entry object yourself, and commit it, that function never gets called.

Yes, commit will now get a default value of '1';
