### ISSUE TITLE
MySQL strict mode

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2190]
I am fed up with having to switch of MySQL strict mode on my servers because we keep sending integers as strings.

Can we have a diligent check to make sure that if we are sending IDs through to the database we convert them to integers? A varchar field will happily accept an integer, but not the other way around.

**Comment by brendo** [comment]
Closing, please raise a new issue if there are further instances of this occurring.

**Comment by designermonkey** [comment]
Will do if I spot them.
