### ISSUE TITLE
Custom events: 

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2203]
protected function __trigger(){
if($result->getAttribute('result') == "success") 
{
ERROR: Symphony Fatal Error: Call to a member function getAttribute() on a non-object

**Comment by andrewminton** [comment]
Any further thoughts on this? We're also experiencing this error with the latest build and are looking for an updated solution to post data to multiple sections in this way.

**Comment by nitriques** [comment]
> Should we be using $this->execute() instead

I think so yes.
