### ISSUE TITLE
Fresh installation: Request rejected, invalid cross-site request forgery token

### ISSUE THREAD

**Issue by DavidOliver** [symphonycms/symphony-2#2204]
After a fresh installation of 2.5, my first visit to the Symphony backend via the 'take me to...' or whatever it's labelled button resulted in:

> Access Denied
> 
> Request was rejected for having an invalid cross-site request forgery token.
> 
> Please go back and try again.

After a couple of refreshes, the problem went away and I'm now in Symphony.

**Comment by DavidOliver** [comment]
Update on this: after installing from the 2.7.x branch I didn't seem to have this issue this time. I then ran the '2.7.0.beta1' update Symphony was telling me about from the admin area, which reported success, but then instead of the admin page I got 'Request was rejected for having an invalid cross-site request forgery token.'

Re-accessing the page by re-requesting the admin page (not refreshing so as not to resend POST) allowed me access to the admin area.

**Comment by nitriques** [comment]
Ok thanks, I'll try to reproduce.

**Comment by nitriques** [comment]
I do not seem to be able to reproduce. I've tested it with PHP 7 and 5.6, and it works..

**Comment by cmnstmntmn** [comment]
@nitriques might have something to do with this #2524

**Comment by nitriques** [comment]
Ok thanks. Still pretty weird.

**Comment by nitriques** [comment]
@DavidOliver Ever had the "luck" to get that bug again ?

**Comment by DavidOliver** [comment]
@nitriques, I haven't done any new installations since June. I can try again if you like. If so, which branch should I test?

**Comment by nitriques** [comment]
@DavidOliver Please test branch `2.7.x`. Thanks ! (Sorry for the late response)

**Comment by nitriques** [comment]
Still have not been able to reproduce, closing. Feel free to comment/reopen if the problem persits
