### ISSUE TITLE
General class in documentation still missing

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2230]
I thought I'd fix that already, but it seems like the `General` class still refuses to show up in the doc.

https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.general.php

http://www.getsymphony.com/learn/api/2.5.0/toolkit/general/
http://www.getsymphony.com/learn/api/2.5.1/toolkit/general/

I do not know why....

**Comment by brendo** [comment]
Upon building the 2.6.0 documentation, both these quirks are fixed, the General and Lang documentation is generated.

**Comment by nitriques** [comment]
AWESOME !!! :+1: Thanks!
