### ISSUE TITLE
X-Frame-Options is deprecated

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2248]
As per https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

> Note: The frame-ancestors directive from the CSP Level 2 specification officially replaces this non-standard header. CSP's frame-ancestors has been supported since Gecko 4.0 but is not supported across all browsers. Though X-Frame-Options is not an official standard it is widely supported and can be used in conjunction with CSP.

So I think it should be wise to add the new values too.

https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives

**Comment by cylkee** [comment]
If this is to be continued to be forced on the front-end, please could you open up a setting in preferences to simply disable on the front-end, or ideally the ability to specify X-Frame-Options: ALLOW-FROM values, and/or equivalent CSP mode.  Thank you.

**Comment by nitriques** [comment]
@cylkee why not override them in your .htaccess file ?

**Comment by cylkee** [comment]
Thanks for the tip, and I'd like to, but I've tried `Header set ...` without success so I'm inclined to think my host has not installed mod_headers.

**Comment by nitriques** [comment]
That's sad. But yeah we should provide sensible defaults with a possibility of overriding them.

**Comment by cylkee** [comment]
Thanks.

I've tried on a different host with mod_headers installed.  In .htaccess if I try:

`Header set X-Frame-Options "ALLOW-FROM http://www.example.com"`

The header output is:

`X-Frame-Options: SAMEORIGIN, ALLOW-FROM http://www.example.com`

This causes a conflict for a web browser and it falls back to DENY.  To test further I tried:

`Header unset X-Frame-Options`

But the headers still output:

`X-Frame-Options: SAMEORIGIN`

It was using Symphony 2.6.3

I'm expecting `set` to work as per http://httpd.apache.org/docs/current/mod/mod_headers.html which should replace the header, not append.

**Comment by nitriques** [comment]
You could try to build a custom extension and register to `FrontendPreRenderHeaders` delegate and change the value (see #2480)

**Comment by nitriques** [comment]
This should take 30 min to do ;)

**Comment by cylkee** [comment]
I could, but I think it would take me more than 30 minutes ;)  Instead, from #2480, I learnt I was missing the `always` in:

`Header always set X-Frame-Options "ALLOW-FROM http://www.example.com"`

**Comment by nitriques** [comment]
>  but I think it would take me more than 30 minutes ;) 

Maybe ;) 

>  I learnt I was missing the always in:

**Comment by cylkee** [comment]
> So this fixes your problem ?

Subject to testing, yes, thanks.  My loose understanding is that `X-Frame-Options: ALLOW-FROM` support is patchy, back through the browser versions.  If so, I suppose I can just use `always` in:

`Header always unset X-Frame-Options`

**Comment by nitriques** [comment]
If you want yes!

**Comment by michael-e** [comment]
Coming back to the original issue, I don't think that X-Frame-Options is deprecated.

https://wiki.mozilla.org/Security/Guidelines/Web_Security#X-Frame-Options

So yes, `Content-Security-Policy` is a successor to `X-Frame-Options` and it should be added in Symphony. But keeping the X-Frame-Options header as well is still recommended.

**Comment by nitriques** [comment]
I think we should add `X-Content-Type-Options: nosniff` and `X-XSS-Protection: 1; mode=block` as deploying CSP would be a real pain. @michael-e if you agree on this, I'll do it for 2.7.x.

As for @cylkee I am afraid that the only thing right now would be to create an extension for this or use the Apache stuff

**Comment by nitriques** [comment]
We should also add `Referrer-Policy: same-origin` for the backend only.

**Comment by michael-e** [comment]
> I think we should add `X-Content-Type-Options: nosniff` and `X-XSS-Protection: 1; mode=block`

Yes!

> We should also add `Referrer-Policy: same-origin` for the backend only.

Sounds good.

**Comment by nitriques** [comment]
Great.
