### ISSUE TITLE
MySQL 5.0

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2254]
As per Oracle's statement on http://dev.mysql.com/doc/refman/5.0/en/

```
MySQL 5.0 Reference Manual
End of Product Lifecycle. Active development for MySQL Database Server version 5.0 has ended.
```

I think we should set our requirements to 5.5 since 5.7 is out already. I often send clients to http://www.getsymphony.com/ in order for them to get the latest requirements and I hate to still see 5.0 in there.

Please tell us your thoughts on this!

**Comment by brendo** [comment]
Done.

**Comment by nitriques** [comment]
Thanks!
