### ISSUE TITLE
Problem with data source generation on Windows

### ISSUE THREAD

**Issue by miferval** [symphonycms/symphony-2#2259]
On line 1367 of symphony/content/contents.blueprintsdatasources.php 
$dsShell = preg_replace(array('//', '/(\t+[\r\n]){2,}/'), '', $dsShell);
the  '/(\r\n){2,}/'  part cause problems, at least with my configuration.

The first line of the data-source data file that is generated 

<?phprequire_once TOOLKIT . '/class.datasource.php';class datasourcetest extends SectionDatasource

have the <?php tag and the require_once, without space between theme so the page crash with a 
Symphony Fatal Error: Class 'datasourcetest' not found

if I remove the '/(\r\n){2,}/' from the replace expression everything works fine

**Comment by nitriques** [comment]
Good catch Brendan!
