### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by psychoticmeow** [symphonycms/symphony-2#2261]
Although the [voting period](https://wiki.php.net/rfc/php7timeline#vote) isn't over yet, it looks as though the next major PHP release will be around October/November next year. Since I'm always at the bleeding edge with these things, I'm creating this issue to track the status of breaks and to help everyone keep some idea of the work that needs doing.

It's also worth noting that work on PHP 5.7 is also underway, although I wouldn't expect many changes this time around.

**Comment by nitriques** [comment]
Version 2.7.x should be PHP 7 compatible. Yeah!
