### ISSUE TITLE
Website issue: JIT Image manipulation documentation

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2281]
This article is out of date: http://www.getsymphony.com/learn/concepts/view/jit-image-manipulation/ 

I know there are a bunch of others articles that are out of date but I click on that one 90% of the time (since it's the first result for 'jit image' in Google) so I would appreciate if somebody could update it: simply paste the missing details from the repo https://github.com/symphonycms/jit_image_manipulation would be enough (adding mode 4 and 5) 

Adding a link to the repo on github on that page would also help .. 

Many Thanks!

**Comment by brendo** [comment]
This has been updated by @allen

**Comment by nitriques** [comment]
Yup thanks @allen
