### ISSUE TITLE
Website issue: can't login on symphonyextensions.com

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2284]
I can no longer login on [symphonyextensions.com](http://symphonyextensions.com) to manage my extensions or add new extensions. Revoking access on GitHub didn't help either (might have caused the issue in the first place).

**Comment by nitriques** [comment]
So this is fixed, lol. Please use [the network repo](https://github.com/symphonists/symphony-extensions-network) to report those things in the future.
