### ISSUE TITLE
Website issue: Lint tool vs. documentation

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2285]
Not sure which one is wrong, but the [lint tool](http://symphonyextensions.com/lint/) and the [documentation](http://symphonyextensions.com/schemas/extension/1.0/) on [symphonyextensions.com](http://symphonyextensions.com) disagree on certain things.

**Comment by nitriques** [comment]
Migrated to https://github.com/symphonists/symphony-extensions-network/issues/18
