### ISSUE TITLE
Symphony warning when datetime field is both required and empty/invalid

### ISSUE THREAD

**Issue by johnpuddephatt** [symphonycms/symphony-2#2303]
I have a required DateTime field with date ranges enabled. 

When content is submitted through a frontend form, the following error is returned if both start and end values are missing/invalid:

`Symphony Warning: trim() expects parameter 1 to be string, array given`
The error originates from line 191 of class.event.section.php.

I've had a quick look and think I can roughly figure out what's happening - it appears the datetime values being tested are 2D arrays, so although array_reduce is used on line 86, trim is still acting upon an array (one-dimensional), hence the error. At least that's what I *think* is going on.

p.s. I've hacked together a workaround for now, but can't quite figure out a proper solution. My PHP is quite limited...

**Comment by brendo** [comment]
Is this the actual [DateTime field](http://symphonyextensions.com/extensions/datetime/) or the core Date field? Assuming the first?

Also, which version of Symphony are you running?

**Comment by johnpuddephatt** [comment]
Sorry, I should have been clearer: yes the DateTime field. I wasn't sure whether it was the extension or the core at fault so it was 50-50 whether I posted there or here.

Oh, and version 2.5.2.

**Comment by brendo** [comment]
No worries. At first look, it's a Symphony issue, so good work on the coin toss ;)

**Comment by nitriques** [comment]
@johnpuddephatt Does @brendo's commit fixes your issue ?

**Comment by johnpuddephatt** [comment]
Appears to have done the trick, yes.

Thanks :+1:

**Comment by nitriques** [comment]
Great!
