### ISSUE TITLE
ASSETS_URL constant

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2307]
We're working with a broken up version of Symphony here, and to make the changes in file locations work properly, we've added an `ASSETS_URL` constant, like we did with `APPLICATION_URL`.

It's allowed (along with other changes) for us to completely restructure Symphony.

If people are ok with this, I can submit a PR with the necessary changes.

**Comment by jensscherbl** [comment]
Backend assets?

**Comment by designermonkey** [comment]
yup.

**Comment by jensscherbl** [comment]
+1

**Comment by brendo** [comment]
go for it

**Comment by designermonkey** [comment]
My playing with this stuff has shown where the installer doesn't use constants correctly, so I will fix that in the PR too. I'll commit them separately in case they want to be cherry picked.

**Comment by nitriques** [comment]
Thanks @designermonkey !

**Comment by brendo** [comment]
Hey @designermonkey. Any updates on this change? Looking to push an RC1 out shortly and I reckon this should be in it.

**Comment by designermonkey** [comment]
5 mins-ish, I'll do it now

Brendan Abbott wrote:

**Comment by designermonkey** [comment]
#2329
