### ISSUE TITLE
Extension Compatibility

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2308]
Maybe this has to do with the new semantic versioning syntax, but the backend doesn't correctly display compatibilities and incompatibilities:

![bildschirmfoto 2015-01-08 um 11 22 33](https://cloud.githubusercontent.com/assets/25466/5661163/d3881606-9728-11e4-9a76-2c4f60376c16.png)

- Where is that `p` comming from in the requirement message?
- Why is Textbox flagging the `2.6` requirement although this is `2.6.0-beta.2`?

**Comment by brendo** [comment]
I don't know the answer to the first, but for the second it's because a
beta is not a final release. So 2.6.0-beta.1 is less than 2.6.0.

**Comment by nilshoerrmann** [comment]
> So 2.6.0-beta.1 is less than 2.6.0.

While that makes sense mathematically, it's not obvious to the human mind in my eyes …

**Comment by nilshoerrmann** [comment]
Hm, this seems to be more complex: If I define `2.6.0-beta.1` or `2.6.0-beta.2` as the extension's minimum requirement, it is still flagged as imcompatible.

**Comment by jensscherbl** [comment]
Thought about this as well. Marking compatibility with a pre-release version of the core doesn't make much sense, but Symphony should handle it correctly nevertheless.

> beta is not a final release. So 2.6.0-beta.1 is less than 2.6.0.

In this case everything is handled correctly, but marking requirement for 2.6.0-beta.1 doesn't work either.

https://github.com/herrera-io/php-version

**Comment by nitriques** [comment]
On a related note: I think that extensions without any max values should have a different visual feedback than those who have one.

**Comment by nilshoerrmann** [comment]
It seems like our compatibility check just didn't take the semver syntax into account. I pushed a fix for that.

> On a related note: I think that extensions without any max values should have a different visual feedback than those who have one.

I don't think this is a good idea. It's the developers responsibility to set these values correctly. If a developer doesn't set a maximum value he say: "I think this will work for all future versions." If this is not likely to be true, a maximum value should be set. Having different visual styles will always make the developers decision doubtful.

**Comment by jensscherbl** [comment]
> It's the developers responsibility to set these values correctly.

I Agree.

**Comment by nitriques** [comment]
> Having different visual styles will always make the developers decision doubtful.

Yeah you're right, we are so lazy.
