### ISSUE TITLE
DS named "index" breaks styling

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2311]
I don't remember why, but as it seems, Symphony adds the handle of a Data Source as a class to the `body` of the DS Editor. If you have a DS named `index`, this results in the following broken styling:

![bildschirmfoto 2015-01-09 um 13 55 08](https://cloud.githubusercontent.com/assets/25466/5680029/a8d96b00-9807-11e4-9f88-759e8b618792.png)

Symphony uses `.index` to identify the table views in the backend so I'm not sure how to fix this without breaking half of the system.

**Comment by michael-e** [comment]
LOL, a DS named "index"? Do you try to supersede me in doing crazy things?

**Comment by nilshoerrmann** [comment]
Shouldn't have worked with you that long last year ;)

**Comment by michael-e** [comment]
That was my first thought as well. :-))

**Comment by nilshoerrmann** [comment]
:ambulance: (Going to the doctor know.) :fire_engine: :police_car:

**Comment by michael-e** [comment]
My doctor said it's irreversible.

**Comment by nilshoerrmann** [comment]
:disappointed:

**Comment by nitriques** [comment]
You guys are funny :P

**Comment by brendo** [comment]
Given it's 2.6.0, we could potentially add a `ds-` prefix to the classname. I imagine this flaw is also with Events as well.

**Comment by brendo** [comment]
Not an easy one to fix. The context of the page (derived from the URL path) is automatically added to the body via the `AdministrationPage` class. At this point, it has no idea what each of the context values represent so it's pretty difficult to append `ds` or `event` to the start of them.

A possible solution would be to change the DS/Event indexes to generate URL's like `datasources/edit/ds-handle` and then have the `ds-` stripped. I don't like this too much though. Other solution is to go the other way and prefix all our classes with `sym-` and hope that people don't start creating DS's called Sym Index ;)

**Comment by michael-e** [comment]
So what shall we do? I'd vote for prefixed classes (i.e. no "hacking"). A DS named "Sym Index" is really unlikely to occur, compared to "Index". @nilshoerrmann?

**Comment by nilshoerrmann** [comment]
Conceptually, it would be best to use classes for styling purposes only and add context information in dedicated `data` attributes. But that's a breaking change.

**Comment by nitriques** [comment]
> Conceptually, it would be best to use classes for styling purposes only and add context information in dedicated data attributes.

It's funny because the class attribute was created before CSS and it was meant to 'classify' elements, which is what we are doing.

Funny stuff apart, does anybody knows which part of the code relies on the class ? 

And both solutions looks ok to me. Maybe do the renaming for 2.6 and data- for 3.0 ?

**Comment by nilshoerrmann** [comment]
> Maybe do the renaming for 2.6 and data- for 3.0 ?

Independend of the solution we pick, this cannot be changed before Symphony 3.0 in my eyes because we'll change a public interface (classes used as identifier in this case).

**Comment by nitriques** [comment]
Ok I would vote for the data-attribute then since it easier to get from js.

**Comment by jensscherbl** [comment]
Should be added to the [3.0.0][1] milestone.

[1]: https://github.com/symphonycms/symphony-2/milestones/3.0.0

**Comment by nitriques** [comment]
@jensscherbl There you go!
