### ISSUE TITLE
Installer code still uses tabs for indentation

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2313]
We should use 4 spaces as per PSR.

@brendo Can I do it directly into integration or should I send a PR ?

**Comment by brendo** [comment]
You can fix this directly, it's low risk :)

**Comment by nitriques** [comment]
Ok, but after my work on the installer is pulled in, to avoid conflicts :)

**Comment by nitriques** [comment]
In progress...

**Comment by nitriques** [comment]
Confirming that only line feeds were added: https://github.com/DeuxHuitHuit/symphony-2/commit/f7d607f00630ff3cb08f4902fe2cfab33267f852?w=0

**Comment by nitriques** [comment]
Same for this one: https://github.com/DeuxHuitHuit/symphony-2/commit/eca1f41c95bc4a74af4e4f319ca879fc4a0cac8e?w=0

Done.
