### ISSUE TITLE
XSLT processor issue on Local Windows installs XAMPP and WAMP

### ISSUE THREAD

**Issue by andrewminton** [symphonycms/symphony-2#2316]
Using integration branch to test local builds and have experienced an odd issue after install.. none of the XSLT processing transforms are working on frontend pages.

    XSLTProcessor::importStylesheet():
        compilation error: file file:///C:/xampp/htdocs/sym-git/ line 3 element import
        xsl:import : invalid URI reference C:\xampp\htdocs\sym-git/workspace/pages/home.xsl
    XSLTProcessor::transformToXml():
        No stylesheet associated to this object

**Comment by andrewminton** [comment]
The pages template is actually just the generated page.xsl file with no additions or edits by myself.

Any clue as to what could be happening here?

**Comment by andrewminton** [comment]
Here's the error log from the main log file after install when accessing frontend page:

    
01/13/2015 12:57 pm > UNKNOWN: SymphonyErrorPage 0 - Line: 178 - XSLTProcessor::transformToXml(): No stylesheet associated to this object on line 634 of C:\xampp\htdocs\sym-git\symphony\lib\core\class.symphony.php
01/13/2015 12:57 pm > UNKNOWN: SymphonyErrorPage 0 - Line: 164 - XSLTProcessor::importStylesheet(): compilation error: file file:///C:/xampp/htdocs/sym-git/ line 3 element import
Line: 164 - XSLTProcessor::importStylesheet(): xsl:import : invalid URI reference C:\xampp\htdocs\sym-git/workspace/pages/home.xsl
Line: 178 - XSLTProcessor::transformToXml(): No stylesheet associated to this object on line 634 of C:\xampp\htdocs\sym-git\symphony\lib\core\class.symphony.php

**Comment by jensscherbl** [comment]
I think this is my fault. Looks related to #2298.

@brendo How are situations like this (where pathes are combined from an absolute and a relative part) handled elsewhere?

**Comment by brendo** [comment]
@andrewminton Are you able to confirm @jensscherbl's fix?

**Comment by andrewminton** [comment]
@brendo applying @jensscherbl ' fix locally fixes the issue.. I believe this is good to be mergeed

**Comment by brendo** [comment]
So it handles the WAMP/XAMMP case you outlined [here](https://github.com/symphonycms/symphony-2/pull/2317#commitcomment-9263909)?

**Comment by andrewminton** [comment]
Yes correct. :) child folder installs etc..

**Comment by brendo** [comment]
Great, thanks!
