### ISSUE TITLE
Date field: field setting »Display time« should be honored in index view too

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2319]
When I have a date field only used to show dates without time that works fine in the edit view. In the index list I get arbitrary times that might confuse my customer :)

**Comment by nitriques** [comment]
Oups!

**Comment by nitriques** [comment]
@animaux Can you please confirm that a942068 fixes the problem ?

@brendo @michael-e can you review please ?

**Comment by animaux** [comment]
Seems to work! Thanks for the quick fix. 2.6 feels like lovely so far :)

**Comment by nitriques** [comment]
My pleasure! We hope it is!

**Comment by nitriques** [comment]
@animaux Can you please test my latest commit ? I've refactored the thing. Thanks!

**Comment by animaux** [comment]
Looks good!

**Comment by nitriques** [comment]
Awesome thanks.

**Comment by animaux** [comment]
No no no. Thank *you!*

:)

**Comment by nitriques** [comment]
:smile:

**Comment by brendo** [comment]
Looks good, thanks @nitriques

**Comment by nitriques** [comment]
My pleasure.
