### ISSUE TITLE
Filter entries by date-field is broken

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2320]
Publish filtering generates the following url-params when I filter on a date field. Looks like there is an escaped whitespace missing here.

    ?filter[date]=later%20than2015-01-17

when I manually change the URL to

    ?filter[date]=later%20than%202015-01-17

the filter works. So I guess this is what it should be instead.

**Comment by nitriques** [comment]
Oups! I'll check this too ASAP.

**Comment by nitriques** [comment]
Thanks for all this testing!!

**Comment by animaux** [comment]
I’m brave and developing two new sites on `2.6.0beta2`already :) it’s fun!

**Comment by nitriques** [comment]
Great!

**Comment by nitriques** [comment]
@animaux Can you please test the latest integration branch please ?

**Comment by animaux** [comment]
Seems to work well, merci!

**Comment by nitriques** [comment]
Great!
