### ISSUE TITLE
Autoloading & Composer

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2330]
@brendo 

Never thought of this before, but...

Does it really make sense to have a custom autoloader and an optional Composer autoloader? I mean, if we treat Symphony as standalone software and not as a PHP package that requires Composer to be installed, shouldn't we include the vendor folder in our repository anyway and only use Composer internally for development? Following this approach, we could just always include the autoloader created by Composer.

**Comment by brendo** [comment]
Implemented.
