### ISSUE TITLE
Why are handles created for array values of page parameters?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2332]
If a page parameter is an array (and only then), Symphony creates additional handles for the values (instead of simply using `item` elements).

So, for example, Symphony creates:

```xml
<page-types>
	<item handle="index">index</item>
</page-types>
```

Wouldn't the following be enough?

```xml
<page-types>
	<item>index</item>
</page-types>
```

The handles are generated in https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.frontendpage.php#L525.

If anybody thinks that these handles are useful, please tell us. Otherwise I suggest to remove them.

**Comment by nitriques** [comment]
> If anybody thinks that these handles are useful, please tell us. 

I do think so. Make sure that string comparison are always lowercase.

I do think that the handle should *always* be there, not only when it's an array...

**Comment by michael-e** [comment]
> Make sure that string comparison are always lowercase.

The parameter values that I have seen have been lowercase anyway!

**Comment by michael-e** [comment]
OK, I am not right.I have, for example:

```xml
<page-title>News</page-title>
<cookie-xsrf-token>EbHOOojOE7yO4l6pXuKJu1Z/eZg</cookie-xsrf-token>
```

So yes, parameter values are not lowercase by default. But is this needed? Filtering data sources always works with the value, not with the handle. So the handles are useless, unless you need them in XSLT, right?

Do you have an example of the handle being useful? I can't think of one, unless you want top hardcode "handle-ized" comparisons in your templates.

**Comment by nitriques** [comment]
> The parameter values that I have seen have been lowercase anyway!

I saw horrible things... 

> But is this needed?

I like it very much when I have the value and an handle.

> So the handles are useless, unless you need them in XSLT, right?

Right.

> unless you want to hardcode "handle-ized" comparisons in your templates.

For some quick and dirty fixes, this is sometimes needed. I know it's not the best way of doing things, but it make bug fixing trivial sometimes.

Also, we use page-types for lots and lots of things in our XSL templates.

**Comment by michael-e** [comment]
> Also, we use page-types for lots and lots of things in our XSL templates.

Same here, I have a lot of crazy page types!

Still, I don't think that parameters should have handles…

**Comment by nitriques** [comment]
> Still, I don't think that parameters should have handles…

Then we should get rid of them. Always.

**Comment by michael-e** [comment]
Waiting for @brendo's expertise. :-) If he's on my side, I will be happy to send a pull request.

**Comment by nitriques** [comment]
:smile:

**Comment by brendo** [comment]
Problem is, how will you know when to generate a handle and when not to generate a handle?

**Comment by michael-e** [comment]
The suggestion was to remove the handles completely.

**Comment by brendo** [comment]
Yes but some param values need handles so you can construct URL's :)

**Comment by michael-e** [comment]
Any examples? (If yes, why does Symphony only add handle attributes for parameters that are arrays?)

**Comment by nitriques** [comment]
> some param values 

Are we not talking only about page-types ? I understand that we do not need handles for page-types, but I really need them for page-params or url-params...

**Comment by michael-e** [comment]
Correct me if I am wrong, but as far as I know and see, we don't have `handle` attributes for url-params or any other parameters — except those params that are arrays (i.e. have multiple values). Please tell me examples of where you see handle attributes, or where you would like to see them.

**Comment by nitriques** [comment]
>  but as far as I know and see, we don't have handle attributes for url-params or any other parameters

You're right.

>  Please tell me examples of where you see handle attributes

As you said. Multiple pages-types creates handles

> or where you would like to see them.

Url parameters values.

**Comment by michael-e** [comment]
I never had the idea to use handles of URL parameters anyway, because:

* As a developer I can make URL parameters to my liking. If I need the params to filter datasources, I will use IDs or title handles anyway.
* Using handles instead of the original parameter values for some logic in XSLT would mean that several URLs would show the same outcome (because several values will generate the same handle).

**Comment by nitriques** [comment]
You're right @michael-e 

But I still find that handles are safer to use in some cases.

**Comment by michael-e** [comment]
I just can't imagine which "cases" that might be. :-)

If we can't find a consensus on this matter, I will simply hack my Symphony installation to remove the handles altogether (it's just one line of code after all). But before I close this issue, I would like to hear what others think, e.g. @brendo, @nilshoerrmann?

**Comment by nitriques** [comment]
Yeah I'd love to hear what others think too!

> I just can't imagine which "cases" that might be. :-)

Let's say I want to create a css class with the content of a user defined value. I'll use the handle since the value may contain spaces.

Another case would be filtering: user can input anything and I want to save filtered results to local storage: I would then use the handle as the key.

Yeah I know I could do this some other way, but I really like the fact that value comes with a handle version.

**Comment by nilshoerrmann** [comment]
Two thoughts:

1. Just because I don't have a use case, that doesn't mean there isn't one.
2. Thinking of no. 1 and consistency throughout the system, it makes sense to have handles (for single _and_ multiple types).

**Comment by michael-e** [comment]
1. Agreed. That's why I ask, trying to find one that I find useful.
2. Yes, __if__ we say that parameters and data (nodes made section names etc.) are nearly the same and should be treated in the same way. Just, that's not my understanding.

**Comment by nilshoerrmann** [comment]
> if we say that parameters and data (nodes made of section names etc.) are nearly the same

Parameters have a 	split personality because they live in the pool and in the xml. It's the chicken or the egg problem. I think it would be consequent to offer handles in the XML.

**Comment by michael-e** [comment]
> Let's say I want to create a css class with the content of a user defined value. I'll use the handle since the value may contain spaces.
>
> Another case would be filtering: user can input anything and I want to save filtered results to local storage: I would then use the handle as the key.

Both examples might be use cases for URL parameters (which don't have handles currently). So this leads us to a feature request: 

* either "URL params should have handles" 
* or "All params should have handles".

My issue was to clean up the current inconsistent state by removing the superfluous handles. Do you really want to clean up by adding even more of these handles? (Forgive me, I know the answer, but hope never dies.)

**Comment by nilshoerrmann** [comment]
You should have stayed silent, old man ;)

**Comment by michael-e** [comment]
Yep, I should simply have hacked my installation(s).

**Comment by jensscherbl** [comment]
> Parameters have a split personality because they live in the pool and in the xml.

Will be XML only starting with the next major version (because breaking change). At least that was the consensus from a previous discussion following another issue with pool parameters.

**Comment by brendo** [comment]
Sorry, I've been away.

So, yes, `handle` is currently only created for parameter arrays. This is inconsistent because if the parameter is not an array, no `handle` is added.

It may be possible that the parameter values are not always handles to start with. The `FrontendParamsResolve` and `FrontendParamsPostResolve` delegates allow extensions to add in whatever parameters they please and there is no specification that these must be handles.

So there's a choice to be made (which you've highlighted above!):

- Make all parameters have `handle` attributes (which works with the recommendation to use /data/params XPath instead of the variable notion)
- Remove the `handle` attributes from arrays and consistently have all parameters just as the value

I feel the first is a more robust solution.

**Comment by nitriques** [comment]
I would also vote for `Make all parameters have handle attributes` in 2.6.0 :smile:

**Comment by michael-e** [comment]
It makes me a bit sad, because I have the feeling that we "pervert" parameters, somehow. To me the params XML part looks much straighter without any handles. I understand @nitriques use cases, but still, don't we encourage people to use parameters in a wrong way? I can already hear people ask "why doesn't a parameter's handle work for filtering datasources?". This addition will make it harder for developers to understand how params work in Symphony.

**Comment by nitriques** [comment]
Would it be a good idea to offer a config parameter to turn it off ? I do not like to make @michael-e sad. :sparkles:

**Comment by nilshoerrmann** [comment]
> This addition will make it harder for developers to understand how params work in Symphony.

I don't think you're right here, Michael. The reason why things get harder to understand is the fact that Symphony will move from `$params` to `/data/params`. I know the reasons for this move but if you compare the two concepts, `$params` are easy because they just map a name to a string while XML always allowed complex nested structures.

> Would it be a good idea to offer a config parameter to turn it off ? I do not like to make @michael-e sad. 

Two comments:

1. While Symphony always gave developers the freedom to create whatever they wanted, the system itself always had an opinion. Making everything configurable, makes things arbitrary.
2. Independent of how you will handle this inconsitency in the end, always decide based on facts and not on feelings. You will not be able to make everyone happy while still building a fucussed system.

And keep in mind this is actually a secondary issue.

**Comment by michael-e** [comment]
I will try to explain my argument a bit better. Currently, in Symphony:

1. Parameters are availabe on the PHP level (data sources).
2. Parameters are available to the XSLT processor directly—technically this is called "parameters as arguments" (according to [this post](https://github.com/symphonycms/symphony-2/issues/2141#issuecomment-50145118) by @allen). Allen suggested to completely remove this, but it has not been done. I will probably open an issue for that.
3. Parameters are included in the XML output.

Now, all three parameter types represent the same "content". Type 1 or type 2 doesn't have handles. It's just key/value pairs. Including handles in type 3 gives us a modified (i.e. inconsistent) representation.

**Comment by nitriques** [comment]
As a developer, I understand that normal values do not have handles. But in XML, I kind of expect to have a `@handle` attribute...

**Comment by brendo** [comment]
Handles will be removed from all parameters. Because this is a breaking change, it must occur in 3.0.0

**Comment by michael-e** [comment]
Thanks, @brendo. I can send a pull request, of course. But how do we deal with PRs for Symphony 3.0? Will there be separate integration branches for 2.6 and 3.0? Or do we just hold the PRs back until "hopefully final 2.6" has been released? Or shall we push dedicated feature branches (which is only possible for core team members, AFAIK)?

**Comment by brendo** [comment]
I'm hoping once the 2.6 RC is released that I can create a `3.0.0` branch and a `2.6.x` hotfix branch (#2268). That will allow these things to be applied rather than sit in open issues.

**Comment by michael-e** [comment]
Sounds great, thanks a lot!

**Comment by brendo** [comment]
A PR can be supplied for this change now :)

**Comment by michael-e** [comment]
I will do, just give me 2 or 3 days.

**Comment by michael-e** [comment]
@brendo: I would like to send a PR. But to which branch? Both, 2.6.x and integration (3.x)? Or can I simply send the PR to 2.6.x, and you will cherry-pick it to integration?

**Comment by brendo** [comment]
It's a potentially breaking change so won't feature in `2.6.x`, so submit against `integration`.

**Comment by michael-e** [comment]
Done.
