### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2336]
Re https://github.com/symphonycms/docs.getsymphony.com/issues/5

I think the project would benefit from having this file. Github's integration with it is cool and it would state clearly what we want from a PR.

- PSR0/1
- Commented code
- No whitespace changes

Any other suggestions ?

**Comment by nitriques** [comment]
-  separate pull requests for each topic (?)

**Comment by michael-e** [comment]
I think that cleaning up trailing whitespace should be OK or even encouraged, but that should always be in a dedicated commit.

> separate pull requests for each topic (?)

Yes, if topics are really different, e.g. "compatibility" and "feature enhancement/fix".

**Comment by nitriques** [comment]
>  but that should always be in a dedicated commit.

Yeah for sure. I am not against it, just not mixed with other changes.

**Comment by brendo** [comment]
[Here's something prepared earlier](https://github.com/symphonycms/symphony-2/wiki/Contributing-to-Symphony)

**Comment by nitriques** [comment]
Awesome Brendan, it will be a great starting point. I'll see what I can do.

**Comment by nitriques** [comment]
Closed via d68b132606c3aab638e87dd55cfcc68a62741b5a
