### ISSUE TITLE
Investigate using `transformToDoc` rather than `transformToXML` for the XSLT Processor

### ISSUE THREAD

**Issue by brendo** [symphonycms/symphony-2#2337]
This [thread](http://www.getsymphony.com/discuss/thread/108893/) on the forums leads to an interesting discovery in how the generation of documents occurs in Symphony. At present, we utilise the `XsltProcessor::transformToXml` method, which takes our `DomDocument` with XSL and XML, and outputs a string of XML. This XML is echoed as the output of the page. This function makes use of the `<xsl:output>` element in the stylesheet to help customise some of the output, but also enforces that we HTML5 style elements cannot be used (among other things..maybe?)

What might be a better approach is to use `XsltProcessor::transformToDoc`, which will return a `DomDocument` object. To get an output, we can call `DomDocument::saveHTML`, which will return the output in a HTML friendly way. From reading the manual, this may allow named entities to be used and HTML5 style elements (no closing tag for `<meta>` etc.).

Some investigation and testing is required to see what impact this has various documents, including those where the output format is not HTML (for example JSON or CSV).

**Comment by nitriques** [comment]
Interesting...  I wonder 

1. What are the perf implication (in my mind, xml is faster than html)
2. Will I get the same guarantee that my output is valid ? (well closed tags by example)

**Comment by brendo** [comment]
Closing. This makes no difference at all.
