### ISSUE TITLE
Parameters as arguments (using $param in XSLT without declaring it) should be removed

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2338]
There has been a [discussion about best practice](https://github.com/symphonycms/symphony-2/issues/2141) in XSLT templating regarding parameters some time ago. In this discussion, @allen [explained](https://github.com/symphonycms/symphony-2/issues/2141#issuecomment-50145118) the technical concepts and [suggested to remove "parameters as arguments"](https://github.com/symphonycms/symphony-2/issues/2141#issuecomment-50146270) from Symphony.

I am all for it. Clean that stuff up, finally. Removing `$param` type parameters will, of course, break XSLT stylesheets that do not yet adhere to the "good practice", but developers can fix this easily.

Related: https://github.com/symphonycms/symphony-2/issues/2332#issuecomment-72176600

**Comment by nitriques** [comment]
I would also be all for it. Using `$param` syntax is error prone, since if the parameter is not defined, XSLT would fail.

Using a real xpath expression is way better IMHO.

But I would keep the $param syntax for DS ...

**Comment by michael-e** [comment]
> But I would keep the $param syntax for DS …

Sure. Initially these params are built in PHP, so we should use them directly at this level, without making a detour.

**Comment by nitriques** [comment]
Perf!

**Comment by brendo** [comment]
Developers are going to hate this change. Purists will love it. But most will hate it. Regardless, it's the right thing to do so it will be removed.

**Comment by michael-e** [comment]
Well said.

**Comment by brendo** [comment]
It works well moving towards a world where #2302 exists. It won't always be possible to 'create parameters' that are accessible by templates.

**Comment by ijy** [comment]
Or maybe even a world where #1463 exists as a prelude to #2302.

**Comment by jensscherbl** [comment]
> Developers are going to hate this change. Purists will love it. But most will hate it. Regardless, it's the right thing to do so it will be removed in 3.0.0

+1

**Comment by bernardodiasc** [comment]
Always got divided what way to work with. Having only one way seems the right way to go.

> Using $param syntax is error prone, since if the parameter is not defined, XSLT would fail.
> Using a real xpath expression is way better IMHO.

+1
