### ISSUE TITLE
String of custom admin path causes conflict with datasource / events names

### ISSUE THREAD

**Issue by marciotoledo** [symphonycms/symphony-2#2339]
Hi, 

I used 'back' as custom admin path to a new project.
When I was trying create a datasource with name "feedback" an error was returned.

The lastest stable version: 2.5.2

https://gist.github.com/anonymous/12ddd1f8dc4f4a39555e

On this parte of error:
"Symphony Fatal Error: Could not find Data Source *feedcreated*. If it was provided by an Extension"

The string was broken 'feedcreated'.

If I change de name to 'fedback', the error return 'fedcreated', so maybe the problem is about 'back' as I used on admin path.

Another information, the datasource / event with name 'feedback' was created but when try edit, same error again.

If need more information, let me know.

**Comment by nitriques** [comment]
I think I found it.

What do you get if you replace [this line](https://github.com/symphonycms/symphony-2/blob/2.5.2/symphony/lib/boot/bundle.php#L45) with this one.

```php
if (isset($_GET['symphony-page']) && strpos($_GET['symphony-page'], $adminPath, 0, 1) === 0) {
```

Notice the extra 1 parameter in the strpos call ?? This will limit the replacement to only one (your's get two replacement!!)

Does it fix the problem ?

@jensscherbl This kind of fix would get release as 2.5.3 with the new branching model ? I am willing to fix both integration a the 2.5.x branch.... How should I do it ?

**Comment by nitriques** [comment]
Sorry, just tested my fix and it obviously does not work.
Been looking around and it seems like we have to choice.

1. Use `preg_replace`
2. Use this, which looks less nice, but is faster

```
$pos = strpos($haystack,$needle);
if ($pos !== false) {
    $newstring = substr_replace($haystack,$replace,$pos,strlen($needle));
}
```

From: http://stackoverflow.com/questions/1252693/using-str-replace-so-that-it-only-acts-on-the-first-match

And I think that this should go in `General` as `str_replace_first`

**Comment by brendo** [comment]
Use `preg_replace`. I favour readability of code than milliseconds.

**Comment by nitriques** [comment]
Thanks Brendan.
