### ISSUE TITLE
Sorting numbers in entry tables

### ISSUE THREAD

**Issue by nathanhornby** [symphonycms/symphony-2#2342]
I have a feeling that this will have been discussed before, there might even be  a convention I'm unaware of, but should this be the expected/presumed sort order for a column like this?

![screen shot 2015-02-04 at 11 13 09](https://cloud.githubusercontent.com/assets/1975168/6039448/f3482328-ac5e-11e4-8919-df744e97b44e.png)

Is this simply due to the field type being used? (As **Order Entries** treats numbers as chronological when sorting)

Of course I appreciate that in many circumstances this is exactly how you'd want it ordered - I'm wondering how that could be best second-guessed?

Maybe there's a number field that handles this scenario better?

**Comment by nathanhornby** [comment]
Ooh, and I've immediately run into an issue at the DS end - how would I output these entries in number order? As the DS ordering works the same way as the entry table (which makes sense).

**Comment by jensscherbl** [comment]
> Is this simply due to the field type being used?

Yep, input field is sorted as text.

> Maybe there's a number field that handles this scenario better?

[Exactly][1].

[https://github.com/symphonycms/numberfield/tree/integration][1]

**Comment by nathanhornby** [comment]
I am such an idiot - the number field is right there - in the core!

**Comment by jensscherbl** [comment]
> I am such an idiot - the number field is right there - in the core!

It was never part of the bundle and first party extensions aren't properly listed or documented anywhere, so not your fault.

**Comment by nathanhornby** [comment]
That's very kind of you @jensscherbl  :)
