### ISSUE TITLE
Deprecation of old values

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2343]
When is the old style of DS params being deprecated? It's not causing any issue, but it bothers me that it's still there. :)

**Comment by jensscherbl** [comment]
3.0.0

**Comment by brendo** [comment]
Just to clarify what 'old style of DS params' is. You're talking about the duplication of the parameter when a datasource only has a single parameter: `$ds-handle.field-handle` and `$ds-handle`. Right?

**Comment by designermonkey** [comment]
Yup. When we moved to allowing multiple params, this was set to be deprecated. That was literally years ago now.

**Comment by brendo** [comment]
These have been removed on `integration`.
