### ISSUE TITLE
URL params regression

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2344]
URL parameters are represented in the param pool by appending a number to the end if they are an array.

I remember we discussed this before (i can't remember when) and agreed it was to be represented the same as any other array value in the param pool, so nested `item` nodes in xml and a comma separated list in the runtime params.

Is this a regression that it isn't like this? I think so.

```
current behaviour:

url: ?distance[]=3-to-5&distance[]=over-5

<url-distance.1>3-to-5</url-distance.1>
<url-distance.2>over-5</url-distance.2>

$url-distance.1	= '3-to-5'
$url-distance.2	= 'over-5'

expected behaviour:

url: ?distance[]=3-to-5&distance[]=over-5

<url-distance>
    <item handle="3-to-5">3-to-5</item>
    <item handle="over-5">over-5</item>
</url-distance>

$url-distance = '3-to-5, over-5'
```

The current behaviour means that it is impossible to collectively access the parameters in the xml without knowing the names, and exactly how may there are in the url (unless I'm missing something). This is bad.

**Comment by nitriques** [comment]
>  This is bad.

true that.

**Comment by designermonkey** [comment]
It's not a regression, it was never actually done.

- #1348
- #1807

Bad dogs. :)

**Comment by nitriques** [comment]
:dog: :(

**Comment by brendo** [comment]
Closing in favour of #1807, it has the history.
