### ISSUE TITLE
error when resetting password for backend users

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2345]
how to reproduce the bug:

1. go to /symphony
2. click: Retrieve password?
3. wait for the email, and click the link

then you'll get [this error](http://www.ucarecdn.com/2d175645-190f-451f-ae7f-387090724733/)

SymphonyCMS 2.5.2

**Comment by nitriques** [comment]
Yup this already has been fixed in 2.6.0 via https://github.com/symphonycms/symphony-2/commit/830fe42ca9f3b23072ff7b964f53a250fbb358a5 by @michael-e 

You can apply the patch yourself on your 2.5.2 install if you want.

@JensScherbl would this also be candidate for 2.5.3 ?

**Comment by jensscherbl** [comment]
> @JensScherbl would this also be candidate for 2.5.3 ?

- Bugfix for existing functionality?
- Doesn't change too much, therefore low risk of introducing new issues?
- Doesn't introduce breaking changes?

Then yes, *2.5.x*.

- New functionality?
- Bigger internal changes?
- Doesn't introduce breaking changes?

Then *2.6.0* (or *2.7.0* if *2.6.0* is already feature frozen).

- Does introduce breaking changes?

Then *3.0.0*.

**Comment by nitriques** [comment]
Ok perf. @brendo Would you release a 2.5.3 version if I prepare a branch for it ? I would cherry-pick a bunch of commits in a 2.5.x branch tomorrow if you want to.

**Comment by brendo** [comment]
Yes.

**Comment by cmnstmntmn** [comment]
i applied the patch but there are two scenarios:

1. **applying the patch after failed attempts** i get this error (
![screen shot 2015-02-06 at 02 13 43](https://cloud.githubusercontent.com/assets/2312755/6072100/1b183a08-ada6-11e4-80ed-10ccf066f0da.png)

2. **tested on a virgin user, with no reset password attempts** it works

**Comment by nitriques** [comment]
Hum...

@brendo Looking at this commit 7b74a6e6 I see that in system authors we have the ` OR `author_id` = '".$author_id."'` SQL construct but in content.login we do not have it. Is there a reason why ? I think that even if the user already has a valid token, if he generates another one, it should delete the old one (since we only allow one token per author == good)

This is why @cmnstmntmn add a bug on his user... Is there a reason why we do not have it ?

**Comment by brendo** [comment]
I'm not sure that's it. Reading the login code, all expired tokens are removed from the database when a reset is initialised. We then ask for the token that is not expired, and is assigned to the Author ID.

If the return from that is 'false', then a token is generated using openssl or just via `mt_rand`. Therefore it would seem highly unlikely that a token could be generated for an Author that is identical.

I'll take a look shortly.
