### ISSUE TITLE
Release 2.5.3

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2346]
I've started a [2.5.3 release picking bug fixes since 2.5.2 release](https://github.com/DeuxHuitHuit/symphony-2/compare/2.5.x) and a 2.5.3 milestone. I hope to be able to release it on Monday the Feb 9.

@brendo I create a quick wiki for the 2.5.x release. Should I create a forum discussion now or Monday ?

Following this release, I propose to clean up some branches in the org's repo.

I also propose to redirect all WIP in a new branch called 2.6.x and keep up-to-date a separate 3.0.x branch: this will allows PR on 3.0.x to be sent at the right place.

I also propose to delete integration branch after the 2.6.0 release.

re: #2268

**Comment by brendo** [comment]
Focus on 2.5.3 first, erring on the side of caution with the commits that cherry-picked.

I would drop out 97dc044, 160cd75,  f857170,  1c0e966,  e9b3eec

Migrating to #2268 should be a second step. Whilst I agree that `integration` should be deleted and `2.6.x` and `3.0.x` branches created, I'm cautious about doing so before 2.6 is released. I'm expecting the prospect of `3.0.x` will lead to a number of ambitious and exciting pull requests that will distract from finalising the 2.6 release.

**Comment by brendo** [comment]
> Should I create a forum discussion now or Monday

Create the forum thread when the RC is available (2.5.3 will go straight to RC).

**Comment by jensscherbl** [comment]
What about a `2.7.0` branch?

**Comment by nitriques** [comment]
Ok @brendo I agree with you. I'll start a fresh 2.5.x branch ASAP with less commits. I will also do it by starting with OLD commits first. Since I am so dumb, I started with the newest first... arwg :(

> What about a 2.7.0 branch?

Rephrasing @brendo 

> will lead to a number of ambitious and exciting pull requests that will distract from finalising the 2.6 release.

I agree with that, even for 2.7.x

**Comment by nitriques** [comment]
But I can't stop to wonder why you do not want does commits...  There are bug fixes... I can see the "breaking change" as "it does not do the same thing it did before", but what it did before was wrong...

**Comment by brendo** [comment]
- 97dc044 No previous reports of this error leads me to believe that people are already working around it.
- 160cd75 This is a new feature and has risk of more bugs
- f857170 Admittedly zero risk but it is a change of functionality that a Manager might be unaware of
- 1c0e966 & e9b3eec Handle a new situation of numeric keys, hence new functionality

> What about a 2.7.0 branch?

Kidding right? You want the small team to handle a 2.5.3, a 2.6.0, a 2.70 and a 3.0.0? I do not want this overhead.

**Comment by nitriques** [comment]
Ok Thanks Brendan for the clarifications.

**Comment by nitriques** [comment]
> No previous reports of this error 

So we should only deal with issues and PR then? I just want to make it right :smile:

**Comment by brendo** [comment]
The purpose of a 2.5.3 is to fix critical functionality, eg. This functionality is so broken that you shouldn't have to go to 2.6 to have it resolved.

For me, this would be 2.5.3, released immediately (a day to verify build amongst ourselves):

-  f717c74, e39349c8d961bf82123651aa92bc511186d77767, f81ccbf2aff441851d1981ea9fa2ad6cdb2b7dbf
-  8d614fd
-  07e658b
-  65a2171

The rest would fall into the 2.6 RC, which is ready whenever we're ready to compile the build.

**Comment by nitriques** [comment]
Ok I'll push something soon (like in the next 15 minutes)...

**Comment by nitriques** [comment]
Sorry for the delay but reading the commit log was longer then I though.

@brendo I would add those, in that order too.

- https://github.com/symphonycms/symphony-2/commit/b3e0626f1c6a7ab6c5202fe5f51ee15759ed541a
- https://github.com/symphonycms/symphony-2/commit/eb558f6e995f8ba151dd0ab59cc42a12f2126063
- https://github.com/symphonycms/symphony-2/commit/f130bf52885ef7fe7a1bf3f162708d9db04de4a7
- https://github.com/symphonycms/symphony-2/commit/a942068a5daf5d837b9c7288b84fb6303e272e28
- https://github.com/symphonycms/symphony-2/commit/4be39896da0d29f11b77ac51b15ca558486abb99

This would make 2.5.3 more worth to update too (at least, fore me) :smile:

**Comment by jensscherbl** [comment]
> You want the small team to handle a 2.5.3, a 2.6.0, a 2.70 and a 3.0.0? I do not want this overhead.

Not sure... `2.5.x` would be done after `2.6.0` is released, so it would be `2.6.x`, `2.7.0` and `3.0.0`. After `2.7.0` it would be `2.7.x`, `2.8.0` and `3.0.0`, depending on how many non-breaking things come up during development for `3.0.0` that would justify such releases before the new major version drops.

**Comment by nitriques** [comment]
@brendo I've updated [my 2.5.x branch](https://github.com/DeuxHuitHuit/symphony-2/compare/2.5.x)

I added all the other commits I've mentioned except 4be3989 which was conflicting.

The only thing missing would be me to `git push upstream 2.5.x`

Please also review the [2.5.3 commit](3083a04).

**Comment by nitriques** [comment]
> Please also review the 2.5.3 commit.

Well the date if off now. But is everything else ok ?

**Comment by nitriques** [comment]
2.5.3 RC is out http://www.getsymphony.com/discuss/thread/109811/ 

Official date release for 2.5.3 should be 2015/02/19 (in one week).

**Comment by nitriques** [comment]
2.5.3 is out! https://github.com/symphonycms/symphony-2/tree/2.5.3

**Comment by nitriques** [comment]
Also posted on the forum: http://www.getsymphony.com/discuss/thread/109869/

@brendo The release notes on the website still says (RC). Could you remove it please ? Thanks!
