### ISSUE TITLE
2.6 entry filtering via a linked entry

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2348]
Feature Request: If I use the nice and shiny new filtering interface and want to filter an entries list by a linked section (association field/select box link) I need to use the `id` for this to work. 

It would be useful to be able to filter by text from the selected field in the linked section, for example a `title`.

**Comment by nitriques** [comment]
I think @brendo already tackled that, at least, for the select_box_link.

Check the latest integration branch, it has [this commit](https://github.com/symphonycms/selectbox_link_field/commit/780d775d14e22ec8c5db1e1c9f76bd32a9567441)

Each fields needs to tell the filtering system how to get to the values...

Can this issue be closed then ?

**Comment by animaux** [comment]
@brendo could this be applied the same way to the `association field` then?

**Comment by animaux** [comment]
Calling @nilshoerrmann —> https://github.com/symphonists/association_field/issues/17

**Comment by brendo** [comment]
SBL and Association Field have the fix in their `integration` branches, so I'm happy to close this.

**Comment by animaux** [comment]
Joy!
