### ISSUE TITLE
New filter interface: Filtering on values containing commas returns no results

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2349]
Using the new entry filters (integration branch), filtering on values containing commas always returns no results. It works fine for values without commas.

**Comment by michael-e** [comment]
The filter works if I escape the commas with a backslash, e.g search for `Apples\, Peanuts and more`.

**Comment by nitriques** [comment]
Wow... I really wonder why escaping it with a \ makes it work...

**Comment by brendo** [comment]
Unfortunately our interface doesn't cater for this use case and the other use case that I implemented in #2290. The Feature Request in #2290 was to be able to filter by multiple values. This bug report is to *not* treat the comma as a multiple value separator and instead use the entire string.

As I said, the current interface does not allow both.

**Comment by michael-e** [comment]
Wouldn't it be enough to make the Javascript escape commas inside values when inserting the string which has been taken from the suggestion list? It wouldn't look perfect, but it would at least work!

**Comment by nitriques** [comment]
> Wouldn't it be enough to make the Javascript escape commas inside values when inserting the string which has been taken from the suggestion list? It wouldn't look perfect, but it would at least work!

I do not mind having javascript escaped values.

**Comment by brendo** [comment]
So the proposal is when a value is selected from the suggestions list, all commas in that value will be escaped and therefore visible in the UI?

**Comment by michael-e** [comment]
Yes, that is my proposal. It's pretty simple, and it makes things work. I wouldn't mind that the commas are visible in the UI.

**Comment by nitriques** [comment]
@brendo why not use [encodeURIComponent](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/encodeURIComponent) instead of string.replace ?

**Comment by michael-e** [comment]
Because it won't work.

It will encode `,` as `%2C`, but that doesn't work. We need `\,`.

**Comment by nitriques** [comment]
> Because it won't work.

That's a good reason. Thanks Micheal for showing me how I can suck :smile: 

My concern was: is there any other characters that would need escaping ?

**Comment by michael-e** [comment]
Not that I am aware of at the moment.

**Comment by nitriques** [comment]
Ok thanks!

**Comment by michael-e** [comment]
I noticed that the fix is incomplete, because it will only replace the first occurence of a `,`. We need to replace 'em all.

**Comment by michael-e** [comment]
I did a quick and dirty test (hacking the minified JS file), and it looks to me as if

```js
value.split(',').join('\\,')
```

would do the trick.

**Comment by michael-e** [comment]
Should I send a pull request? Or is there a better idea?

**Comment by nitriques** [comment]
Please send the PR and @brendo will review it
