### ISSUE TITLE
UI for changing author language is gone

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2350]
Did I missed something, or it's really gone ?

Running the latest integration code gives this

![image](https://cloud.githubusercontent.com/assets/771169/6131475/49fb8772-b11a-11e4-98cf-7c5d5e12f252.png)

**Comment by nitriques** [comment]
Nevermind, I did not had any languages installed.

**Comment by andrewminton** [comment]
Interesting list of Section links across the top.. do they relate to actual sections?

**Comment by nitriques** [comment]
> do they relate to actual sections?

Yes! It's my "dev" setup, where I do most of the work :)
