### ISSUE TITLE
MySQL timeout more friendly...

### ISSUE THREAD

**Issue by marciotoledo** [symphonycms/symphony-2#2351]
My server are having some problems about mysql, so I have 2 projects.
primedominios.com with 2.3 or older version 
and 
feedbacker.com.br with 2.5.2

So this are the timeout error screens, the older version is most friendly.

![screen shot 2015-02-11 at 19 25 05](https://cloud.githubusercontent.com/assets/185046/6156892/59b4f454-b224-11e4-8947-18b7c37481a4.png)

![screen shot 2015-02-11 at 19 25 09](https://cloud.githubusercontent.com/assets/185046/6156895/5d37fd42-b224-11e4-8781-20b73557f4ea.png)

**Comment by nitriques** [comment]
Do they run on the same server ? Are you connected Symphony in any case ?

Do you have different php.ini files for the two sites ?

**Comment by brendo** [comment]
Pretty sure this regression is fixed on integration

**Comment by nitriques** [comment]
Great.
