### ISSUE TITLE
Server connection Issues with uncommon hostname

### ISSUE THREAD

**Issue by twiro** [symphonycms/symphony-2#2352]
I am currently setting up a symphony page on a **Strato**-server that has the following hostname for its database:

    localhost:/tmp/mysql5.sock

Strato is a quite popular hosting company in germany, so I guess others might have this issues too:

**1. Problem: The installer doesn't accept this format**
I worked around this by simply not using it and setting up a manually configured copy of the page.

**2. Problem: I can't establish a working database connection with this format**
Trying to access the page after configuring it manually throws the following error:

    Warning: mysqli_connect(): (HY000/2002): Connection refused in .../symphony/lib/toolkit/class.mysql.php on line 315
    Warning: mysqli_ping() expects parameter 1 to be mysqli, boolean given in .../symphony/lib/toolkit/class.mysql.php on line 260

I solved this problem by setting the hostname as "localhost" and followed [this guide](http://blog.markusheisterberg.de/webdesign/1und1-server-und-mysqli/) in declaring the sockets separate in the **index.php**:

    ini_set ( 'mysql.default_socket', '/tmp/mysql5.sock' );
    ini_set ( 'mysqli.default_socket', '/tmp/mysql5.sock' );

That worked - though it felt hacky.

I could establish a working database connection, everything seemed to work as expected and I nearly forgot about it... until a few days later I tried to use JIT and couldn't get a single image to show up - no matter what I tried, 500 Server Errors all around. I finally followed @brendo's advice in [this thread](http://www.getsymphony.com/discuss/thread/96848/1/) and changed the error-settings.

Turned out to be the server connection again:

    Warning: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/tmp/mysqld.sock' (2) in .../symphony/lib/toolkit/class.mysql.php on line 315
    Warning: mysqli_ping() expects parameter 1 to be mysqli, boolean given in .../symphony/lib/toolkit/class.mysql.php on line 260

JIT doesn't seem to use the seetings in the **index.php**, so I included them in the **image.php**-file of the JIT-extension too.

That worked too - but felt even more hacky.

So I decided to post this as an official issue and ask for advice if there either already is a clean way to handle such uncommon hostnames or - if not - if symphony's database-setup could be updated to accept a hostname like this.

**Comment by nitriques** [comment]
Do they support php.ini file in your www root ? I would solve it that way.

mysql.default_socket=/tmp/mysql5.sock
mysqli.default_socket=/tmp/mysql5.sock

But your current solution is not hacky BTW. There setup is not the default one and pho provides the ini setting for custom setups.

**Comment by brendo** [comment]
After a little bit of reading, what @nitriques has said is about right. Setting the host to `localhost` and then having the socket configured from the `php.ini` seems to be recommended by the PHP docs. 

With PDO, sockets can be supported directly in DSN (`mysql:unix_socket=/tmp/mysql.sock;dbname=testdb`) but as Symphony doesn't use PDO this can't be used just yet.

**Comment by nitriques** [comment]
Great! PDO FTW. I'll then close this issue since we can't fix that in the core yet and our PDO usage will support it.

**Comment by twiro** [comment]
Thanks for your feedback - It doesn't look like the host supports a custom php.ini, so I guess I'll just leave it that way as everything seems to work now as expected.

But looking forward to the PDO-Implementation - good to know this will be addressed in the future.

**Comment by nitriques** [comment]
> It doesn't look like the host supports a custom php.ini

Most I am aware of do. That's sad :(.
