### ISSUE TITLE
2.6.0: Integration has been rebased

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2353]
I've just rebased integration on top of master (which is 2.5.3)

https://github.com/DeuxHuitHuit/symphony-2/tree/integration 

I did not pushed into @symphonycms remote in order to let time for people to test it.

I will push next **Monday, Feb 23rd**. I will also fix the 2.6.x tags that were "lost" after the rebase.

After that, anybody wishing to pull integration will have to `git pull upstream integration --force` in order to rewrite their local history. You also will have to `git push origin integration --force` to update your remote.

I've also synced 2.6.x with integration before doing the rebase so we can have a safe backup.

**Comment by andrewminton** [comment]
+1 :) thanks for info.

**Comment by nitriques** [comment]
If you do not want to fuss with git, here a quick way to do it. (it's quick because it's 100% conflict free!)

(origin = your github remote (fork), upstream = deuxhuithuit/symphony-2 repo)

```
git fetch --all
git checkout master
git pull upstream master
git push origin master
git branch -D integration
git push origin :integration
git checkout -b integration
git pull upstream integration
git push origin integration
```

**Comment by brendo** [comment]
Just hold off on this for a tick. It may be more beneficial to use to simply merge rather than rebase.

**Comment by nitriques** [comment]
> Just hold off on this for a tick

Yup, that's why I've only pushed it in my repo. Rebase 190 commits is not super awesome.

> It may be more beneficial to use to simply merge rather than rebase.

I did tried it. It's worst IMHO, because you get multiple duplicated commits each in a different tree. 

git blame is useless after the merge... So I would prefer to have a one time trick to update my local repo instead of breaking git blame. At least, after the rebase, reading history is easy.

But in understand fully your concerns.

**Comment by brendo** [comment]
I went with the merge, which lets us carry on quickly :)

**Comment by nitriques** [comment]
Ok then. But the tree looks awful though! But I understand that this makes it easier for everybody.

**Comment by nitriques** [comment]
And beware: Lots of commit are now double: f30d95f vs 5b3f58d,
