### ISSUE TITLE
Association Interface Drag/Drop

### ISSUE THREAD

**Issue by jonmifsud** [symphonycms/symphony-2#2356]
Another feature request I'm willing to implement but looking for some feedback before issuing PR's.

The old SubSection Manager had drag & drop functionality where one would provide 'drop text' and the item could be dragged into a textarea or an input with the necessary value and/or html.

With the new Association UI this has been dropped off but it's a very useful feature for content management. Think dragging images from an Association Interface, and some other complicated types such as an entry-embedabble slideshow.

I'm putting this feature request in the core for 2 reasons.

1. The associations UI looks for `aui-selector-sortable` for sorting. Presumably looking for `draggable` or `droppable`would have to work in the same way.

2. The drop text would have to be defined somewhere, I'm not sure if this should be within the field such as Association Field, or within the symphony association table, making this feature available for all associations.

3. Association UI + all the newer extensions use Symphony provided JS functionality such as `symphonyOrderable`, would this mean that a new `symphonyDraggable` / `symphonyDroppable` would have to be provided?

Finally the naming of it, as it does both dragging & dropping.

**Comment by nitriques** [comment]
1. Yes!
2. Within the field is the way to go. It's really easier to get to the data.
3. No. Look at the datetime extensions. We use what Symphony provides but do not export anything. We try to keep the core small, with minimal set of features.

**Comment by brendo** [comment]
My kneejerk reaction to this request is "oh god, SSM is slowly being migrated into the core". Once I get over that I'll respond back with something more constructive :)

**Comment by jonmifsud** [comment]
@brendo certainly not the scope of adding SSM into the core :)

Drag & Drop seems the most intuitive way to allow dropping of things into the content area. But certainly open to better solutions - thinking out loud an additional 'attach function' to a markdown editor interface which links to Association Fields could also be an option.

**Comment by nitriques** [comment]
> oh god, SSM is slowly being migrated into the core.

LOL!

**Comment by jonmifsud** [comment]
Closing this as I possibly found a better solution. Using the Association Section UI within the text areas for embedding. Will share once cleaned up a bit more.
