### ISSUE TITLE
Forgotten Password is broken

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2359]
Line 532 of `class.Symphony.php` should be:

```php
            self::Database()->delete('tbl_forgotpass', sprintf(" `token` = '%s' ", $token));
```

I don't know how long this has been broken.

This should be an emergency point release, and should be done very quickly IMO.

**Comment by nitriques** [comment]
It's supposed to be fixed... https://github.com/symphonycms/symphony-2/issues/2345 and https://github.com/symphonycms/symphony-2/commit/830fe42ca9f3b23072ff7b964f53a250fbb358a5

What version are you testing ?

**Comment by designermonkey** [comment]
The latest stable release. I won't use integration anymore.

If it's been fixed already then why is it not released as a point already? This is getting ridiculous now. Minor point release bug fixes like that should be out of the door faster than 20 days!

**Comment by nitriques** [comment]
> This is getting ridiculous now. 

I agree. @brendo and I must have missed this commit when did 2.5.3.

I think we should release 2.5.4 with this single commit in it.

**Comment by jensscherbl** [comment]
> I won't use integration anymore.

You shouldn't have to for minor bugfixes like this.

> I think we should release 2.5.4 with this single commit in it.

+1

**Comment by nitriques** [comment]
Upon @brendo's approval, I could get it out by tomorrow.

**Comment by brendo** [comment]
Yeah it can be pushed out in a single commit as 2.5.4

**Comment by nitriques** [comment]
Ok perfect Brendan I'll do this.

Ok I'll merge again integration with master ?

**Comment by brendo** [comment]
Yeah, I'd checkout 2.5.x, `cherry-pick` that 830fe42ca9f3b23072ff7b964f53a250fbb358a5 (can't believe we both missed it, it was the whole point of that release :cry:), and then bump to 2.5.4. `integration` will then get merged with `master`.

**Comment by brendo** [comment]
No wait. This was fixed in 2.5.3. https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.symphony.php#L532 via 5d16037683c73b950606b1df703c6d02cb7a9b77

@designermonkey can you please confirm what version you are running?

**Comment by designermonkey** [comment]
Ah. It's `2.5.2`. I was sure this was updated, but then I have so many different versions running. :(

**Comment by jensscherbl** [comment]
> Ah. It's 2.5.2.

So let's move on to discuss @designermonkey's punishment... :)

**Comment by nitriques** [comment]
> So let's move on to discuss @designermonkey's punishment... :)

I'd say make him play with package management systems.... https://twitter.com/designermonkey/status/570925570697105408
