### ISSUE TITLE
Date Field: "date" column should be removed

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2361]
As @nilshoerrmann [pointed out in a different thread](https://github.com/symphonycms/symphony-2/issues/2360#issuecomment-76220694), the Date Fields "date" column is not used anymore. So it should be removed.

**Comment by nitriques** [comment]
I would propose this to be 2.7.0 ? Can it be 2.6.0 ?

**Comment by michael-e** [comment]
2.6.0 has RC status, so I suggest to do it in 2.6.1 (and 2.7, of course).

**Comment by nitriques** [comment]
Great.

**Comment by nitriques** [comment]
Fixed in 1377797
