### ISSUE TITLE
Class 'Symphony' not found

### ISSUE THREAD

**Issue by jdsimcoe** [symphonycms/symphony-2#2362]
I keep getting this error:

```
Fatal error:  Class 'Symphony' not found in /Users/jdsimcoe/Sites/atheycreek/symphony/lib/boot/bundle.php on line 18, referer: http://atheycreek.dev/
```

Not sure what is driving it.

**Comment by brendo** [comment]
Is this with `2.6.0.rc-1` or with `2.5.3`? If it's the former, can you check if you have an [`autoload.php`](https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/boot/autoload.php) file and your [index.php matches](https://github.com/symphonycms/symphony-2/blob/integration/index.php)?

**Comment by jdsimcoe** [comment]
It's with `2.6.0.rc-1`. I do have an `autoload.php` file and the `index.php` file matches.

**Comment by brendo** [comment]
And running PHP 5.3+ I assume? When does this error occur? Just accessing your homepage?

**Comment by jdsimcoe** [comment]
Yeah PHP 5.5+. But I’m not seeing the error anymore.


--

simko.io

**Comment by jdsimcoe** [comment]
What is a `/vendor/autoload.php` file? Why would I need that? Is this a new thing to Symphony `2.6.0`?

**Comment by brendo** [comment]
> What is a /vendor/autoload.php file? Why would I need that? Is this a new thing to Symphony 2.6.0?

Symphony 2.6 allows for installation via Composer, so there are two different possible autoload routes.

> Yeah PHP 5.5+. But I’m not seeing the error anymore.

That's strange/scary?

**Comment by jdsimcoe** [comment]
@brendo Well I have since updated `JIT` and `s3upload_field` so either of those could have fixed it.

> Symphony 2.6 allows for installation via Composer, so there are two different possible autoload routes.

Does this mean it would be possible to deploy Symphony via Heroku?

**Comment by brendo** [comment]
> Does this mean it would be possible to deploy Symphony via Heroku?

No. Unfortunately as I just discovered. The other hurdle here is Postgres and the parsing of database information. That should be a little easier with PDO support.

**Comment by jdsimcoe** [comment]
> The other hurdle here is Postgres and the parsing of database information.

Why is Postgres a hurdle? I am running several instances of Craft CMS on Heroku, using ClearDB:

https://medium.com/@aj1215/craft-cms-on-heroku-79b991665b0b

They parse the Clear DB config settings in Heroku like so:

```php
$url=parse_url(getenv(“CLEARDB_DATABASE_URL”));

return array(
  ‘server’ => $url[“host”],
  ‘user’ => $url[“user”],
  ‘password’ => $url[“pass”],
  ‘database’ => substr($url[“path”],1),
  ‘tablePrefix’ => ‘craft’,
);

It works beautifully. Have you tried something like this with Symphony?

**Comment by jdsimcoe** [comment]
ClearDB has a free 5MB `MySQL` tier.

**Comment by brendo** [comment]
Hurdle as in, wouldn't work out of the box without applying the `parse_url` logic inside your `config.php` file (which would mean setting config to read-only once it's in production so it couldn't be overridden)

**Comment by jdsimcoe** [comment]
:+1: Got it!
