### ISSUE TITLE
Delegate: SectionPostDelete

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2364]
Should there not be a post delete delegate too?

I'm trying to develop something that fires after all create/edit/delete actions in sections and entries, and can't because there aren't a full set of delegates :(

**Comment by brendo** [comment]
That seems like an odd omission!

**Comment by nitriques** [comment]
> Should there not be a post delete delegate too?

I think so, yes.

**Comment by designermonkey** [comment]
Thanks.
