### ISSUE TITLE
Massive amount of SQL work going on

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2365]
I've been toying with an idea I've had for a while, and monitoring all of the SQL queries that happen at certain times when using the admin, and I've come across some interesting facts that I would like to share...

1. Changing a Section's Nav Group, will resave *every single Field* associated with the Section. Wow.
2. Changing the order of Sections in the index list, will resave every single Section, and in turn every single Field associated with those Sections. Even more wow.

This is bonkers, an no offence meant to those who have coded it, but bloody hell.

**Comment by munki-boy** [comment]
So we didn't need the "resave entries" extension after all? :)

**Comment by designermonkey** [comment]
No, this is schema stuff, not entries stuff. It's to do with how Sections are built, not how Entries are added to the Sections.

The Fields and Sections always maintain their ID, but all the rows describing them are flushed out and re-created every single time.

**Comment by munki-boy** [comment]
Thought that might be the case, seems weird, I'd thought the nav group arbitrary.  It's only used for the backend menus?

**Comment by designermonkey** [comment]
This is all backend operation, not front-end.

When a section or field is updated, we delete the row in the DB and then re-create it. IMO, this is a lot of overhead that isn't needed. It's that which causes what I'm seeing.

When the only data to change is one tuple in the sections table, we really shouldn't be removing and recreating all associated rows in field tables, and even in the section associations table too :s

**Comment by munki-boy** [comment]
Does the one change currently achieve the same result as re-creating everything? I mean is it simple to change the SQL routine to not re-create all the items.

**Comment by designermonkey** [comment]
The `SectionManager` only has one routine for a save, all or nothing. To sort this, it would have to know to choose a different routine dependant on whether fields had changed, or just meta attached to the section.

I don't know if it's achievable, so @brendo will have to say really.

**Comment by munki-boy** [comment]
Well I've learned a little bit more, I did encounter the SectionManager messing about with the Twitter extension. cheers mate. 

Off-topic but while you're here, do you think recursiveArrayIterator is a good way to consume incoming tweets?

**Comment by brendo** [comment]
How are you tracking the SQL queries John? As far as I can see, when you reorder a Section on the index, the number of SQL queries generated is equal to the number of Sections in your system.

1. [On orderable.stop](https://github.com/symphonycms/symphony-2/blob/master/symphony/assets/js/src/backend.views.js#L101) make an ajax request to `/symphony/ajax/reorder/` with all the Sections and their new positions
2. [Reorder page](https://github.com/symphonycms/symphony-2/blob/master/symphony/content/content.ajaxreorder.php#L51) loops over all the Sections...
3. [... calls SectionManager::edit](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.sectionmanager.php#L59-L65) which issues a single SQL query

---

And yes, updating any details on the Section Edit page causes all fields to update their settings. What must be kept in mind above all here is that these are __extremely__ simple queries and the effort to try and do a comparison to find what has changed per field is likely to be more than what it's worth. To do so, each Field that is submitted would need to be loaded from the database (using FieldManager) to get all it's settings. A loop would do a comparison to find out what values are different and then craft an selective `UPDATE` query. What's interesting here is that it's still going to result in a similar number of queries :)

Let's consider a section of 15 queries and the proposed use case, just updating the Navigation Group from the Section Editor and not updating the field settings. The absolute difference will be nil :)

Existing | Queries | New | Queries
----------- | ----------- | ----- | ---------------
`UPDATE` for every field | 15 | `SELECT` for every field | 15
 | | `UPDATE` for changed fields | 0
*Total* | 15 | *Total* | 15

So in the end, yes, I agree in principal that's it's odd. In practice, I'm not sure it's worth resolving.

**Comment by nitriques** [comment]
> So in the end, yes, I agree in principal that's it's odd. 

Totally.

> In practice, I'm not sure it's worth resolving.

Me neither. Also, it all in the backend... I would rather try to optimize frontend things first.
