### ISSUE TITLE
Composer rollback

### ISSUE THREAD

**Issue by brendo** [symphonycms/symphony-2#2368]
Well this is embarrassing. Whilst playing with Heroku, I thought I'd try out 2.6's new composer functionality, which had disappointing results.

Symphony uses the `.htaccess` and as such, relies on the file system more than I realised. We also have two dedicated `index.php` bootstrap files, one for normal use, and one for installation. Both these don't play well with the idea that Symphony is loaded as a component of another project.

At this stage, I don't think we can promote Symphony as being installable via Composer.

This brings about #2363. We could use Composer solely for our internal purposes, which removes the need for our own autoloader (a plus). 

I'm not sure how this works practically though, I'm guessing we'd ignore the `composer.json` file and just commit the `composer.lock` file. We wouldn't submit the package on Packagist, so users wouldn't be able to add it as dependency, composer would exist solely as a way for us to generate the autoloader.

I have aborted the 2.6.0 release for now (it's on `master`, but untagged), so we can solve this. Thoughts?

/cc @jensscherbl  @nitriques

**Comment by brendo** [comment]
I've gone ahead and merged #2363 which @jensscherbl originally suggested. Aside from this the build remains the same. Testing from `integration` confirms this. At this stage `composer.json` is still left in the repo, but I think that's ok as long as we don't promote Composer installation.

> But on the other hand, Symphony is a standalone product, not a library, package or framework, so running Composer locally to install dependencies shouldn't be a requirement to use the product.

This comment really struck home and then the penny dropped.

**Comment by jensscherbl** [comment]
> Both these don't play well with the idea that Symphony is loaded as a component of another project.

I didn't even realize that this was your intension. Now it all makes sense.

> At this stage composer.json is still left in the repo, but I think that's ok as long as we don't promote Composer installation.

I would even say we should leave it there, so developers familiar with composer can use it to add their own, project specific dependencies.
