### ISSUE TITLE
When updating, the »vendor«-folder is needed too.

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2371]
When updating from `Symphony ≤ 2.5` Contrary to the instructions still in the [readme](https://github.com/symphonycms/symphony-2#updating-via-the-old-fashioned-way), the `vendor`-folder is needed too.

**Comment by nitriques** [comment]
I do not see any instruction regarding the `vendor` folder in the readme... which line ?

**Comment by animaux** [comment]
That’s what I meant to say. It’s *not* mentioned, but the installation fails without the vendor-folder.

**Comment by nitriques** [comment]
Oh ok. Then I think we should add it.

**Comment by johnpuddephatt** [comment]
+1
