### ISSUE TITLE
Unwanted files in the downloadable 2.6.0 zip file

### ISSUE THREAD

**Issue by aVandalInShorts** [symphonycms/symphony-2#2372]
I downloaded the zip file from http://www.getsymphony.com/download/ and I got a folder name "2.6.0" which is the documentation according to @nitriques. And I also had a (probably) unwanted ".DS_Store" file.

**Comment by nitriques** [comment]
@brendo I never use this file... But I looked weird to me...

**Comment by ijy** [comment]
.DS_Store files are just Mac specific files which relate to the _view_ information in that directory. They're created automatically and most likely just crept in by mistake to the packaged app. It's probably a good idea to add it to the `.gitignore` file to make sure they don't creep in again.

**Comment by nitriques** [comment]
>  to add it to the .gitignore file to make sure they don't creep in again.

I do not think that it's git related... It's the zip file hosted on getsymphony.com, not github's zip file...

**Comment by brendo** [comment]
Whoops, sorry about that, I zipped the folder up after having generated the documentation. Usually I do the zip and then generate the documentation.. I'll update ASAP.

**Comment by brendo** [comment]
Done! Thanks for reporting.

**Comment by cmnstmntmn** [comment]
a direct link to github zip (master branch) would be less redundant and
never have to be changed.

El viernes, 13 de marzo de 2015, Brendan Abbott <notifications@github.com>
escribió:

> Closed #2372 <https://github.com/symphonycms/symphony-2/issues/2372>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symphonycms/symphony-2/issues/2372#event-251409022>.
>


-- 
thumb typed

**Comment by brendo** [comment]
Except the zip file includes the bundled extensions ;)

**Comment by nitriques** [comment]
Thanks Brendan!
