### ISSUE TITLE
Migration to 3.0.0

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2373]
Since we are now working on 3.0.0, I would like to address the issues of migration.

We are planning to make breaking changes (I am thinking about handles specially).

Will we create all the migration code ? 

I think we should and I would like to have everybody's opinion on that matter.

**Comment by andrewminton** [comment]
Are we talking migration of core or data?

**Comment by nitriques** [comment]
Code + Data.

I mean, we need to first figure out if we want an upgrade path from 2.x to 3.x... And what should be included or not :smile:

**Comment by brendo** [comment]
Migration code (should we choose to help migrate things) will live in [the migration file](https://github.com/symphonycms/symphony-2/blob/integration/install/migrations/3.0.0.php).

I think it will need to be approached on a case by case basis.

**Comment by nitriques** [comment]
> I think it will need to be approached on a case by case basis.

Yeah that's for sure. But can we all agree that we should try to make migration from 2.x to 3.x easy as possible ?

**Comment by michael-e** [comment]
+1

**Comment by jensscherbl** [comment]
Should be added to the [3.0.0][1] milestone.

[1]: https://github.com/symphonycms/symphony-2/milestones/3.0.0

**Comment by jensscherbl** [comment]
I think we have to restructure the installers `index.php` and/or the `bundle.php`, making the updater more independent and run it as early as possible.

There's a new `order` column in the `extensions_delegates` table in `3.0.0`. Problem is, the `ExtensionManager` class, with an SQL statement in its constructor that uses this new column, is called before the updater runs, resulting in a Symphony Fatal Database Error.

Not sure how to solve this, or if there are any other possible breaking points.

**Comment by nitriques** [comment]
Finally, the migration will be possible only from 2.7.x LTS.
Lower version will need to first update to the LTS version, and then update to 3.0.0
