### ISSUE TITLE
[2.6] "Invalid argument" when DB is not available

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2374]
When the database is not available (e.g. when I didn't start the server :), there comes up a following warning:

    Symphony Warning: Invalid argument supplied for foreach()
    
    An error occurred in .../symphony/lib/boot/func.utilities.php around line 193
    ...
    (193) foreach ($_SESSION as $contents) {
    ...

Maybe there should be another type of warning or check?

**Comment by nitriques** [comment]
I've added the "Fix found" label in order to "tag" issues as fixed but let them open until the commits gets merged into master. It this ok ?

**Comment by brendo** [comment]
Nice idea :) We should release a 2.6.1 shortly.

**Comment by nitriques** [comment]
> We should release a 2.6.1 shortly.

Great! Jens as a nice PR that would fit 2.6.1.

**Comment by jurajkapsz** [comment]
Fix tested, is OK.

Thanks a lot!
