### ISSUE TITLE
XSL import fails when Windows path contains a space

### ISSUE THREAD

**Issue by koolaid1551** [symphonycms/symphony-2#2375]
There is an issue with this commit https://github.com/symphonycms/symphony-2/commit/dc211a791af9082f753fbd95edf9bcd1a23c0808

Windows fails to import and xsl when there is a space in the path(i.e. "C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\")

I have to revert the line back to `<xsl:import href="./workspace/pages/' . basename($page['filelocation']).'"/>` in order to get 2.6.0 to work on windows

**Comment by koolaid1551** [comment]
@brendo is there a reason why symphony uses full paths?  For example if I replace `define('DOCROOT', '__DIR__);` with `define('DOCROOT', '.');` everything appears to work.

**Comment by brendo** [comment]
It's generally safer to know the absolute path.

I don't know why Unix and Windows produce different output here (or if it's
just I've never used a space in a folder before).

**Comment by koolaid1551** [comment]
FYI the full error is 

XSLTProcessor::importStylesheet():
    compilation error: file file:///C:/Program%20Files%20(x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/symphony/ line 3 element import
    xsl:import : invalid URI reference C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/symphony/workspace/pages/blog.xsl
XSLTProcessor::transformToXml():
    No stylesheet associated to this object


I tried replacing the spaces with '%20' and '+' but neither seemed to work.

**Comment by jensscherbl** [comment]
Will have a look at this. Sorry... :(

**Comment by jensscherbl** [comment]
This is not a windows problem, failed on Unix as well. XSLT has issues with spaces in URLs.

@koolaid1551 Can you please try my fix and report back if it works?

**Comment by koolaid1551** [comment]
@jensscherbl  Your fix does not work for me on windows.

```
XSLTProcessor::importStylesheet():
    I/O warning : failed to load external entity "C:/Program%20Files%20(x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/symphony/workspace/pages/blog.xsl"
    compilation error: file file:///C:/Program%20Files%20(x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/symphony/ line 1 element import
    xsl:import : unable to load C:/Program%20Files%20(x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/symphony/workspace/pages/blog.xsl
XSLTProcessor::transformToXml():
    No stylesheet associated to this object
```

**Comment by koolaid1551** [comment]
I got it working by adding the file protocol 

See https://github.com/symphonycms/symphony-2/pull/2380
