### ISSUE TITLE
Autoloader issues with extension that uses own autoloader

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2378]
I have a project with an extension that uses its own composer autoloader (and vendor folder). This worked fine until [the vendor folder was included in Symphony](https://github.com/symphonycms/symphony-2/commit/87bd0e00381421b3d6dfcf7d4ab68ab25bd052fc), which simplified the autoloading. (Before this commit, Symphony obviously used its own autoloader in my installation, because there was no vendor folder for Symphony at all.)

But now autoloading of the extension is completely broken. 

Is it not possible to have two autoloaders (and vendor folders) in one project?

I would really like to keep the extension as a subproject, separate from Symphony (and Symphony's autoloader).

**Comment by jensscherbl** [comment]
I did a quick test with `2.6.0` and the [CommonMark extension][1], which also uses its own vendor folder and autoloader. I didn't run into any issues at all, so I guess the problem is something else.

[1]: https://github.com/jensscherbl/commonmark

**Comment by michael-e** [comment]
I will take a look at how the CommonMark extension does it! Maybe I can find a significant difference.

**Comment by jensscherbl** [comment]
> I will take a look at how the CommonMark extension does it! Maybe I can find a significant difference.

FYI... I had to require the autoloader in the text formatter instead of the extension driver, but also included it in the extension driver for testing purposes, with no issues.

**Comment by michael-e** [comment]
LOL, I found it!

My extension used a relative path like `require_once 'vendor/autoload.php';`. Changing that to `require_once EXTENSIONS . '/extension_name/vendor/autoload.php';` solved it!

**Comment by michael-e** [comment]
Thanks, Jens, for the quick feedback!

**Comment by jensscherbl** [comment]
I recently ran into another issue with extensions and composer autoloading. It's not a core issue, and not specific to one extension, so no idea where to discuss this. Any suggestions?

**Comment by nitriques** [comment]
> and not specific to one extension

That would be here then...
