### ISSUE TITLE
Core Fields

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2379]
Just wondering... Now that work on [3.0.0][4] has started, is there any reason why we should continue to separate core fields (author, checkbox, date, input, select, taglist, textarea, upload) from fields that are first party extensions ([selectbox link][1], [number][2], [email][3])?

I'm thinking either removing fields from the core all together and making every field an extension, or including all first party fields in the core.

[1]: https://github.com/symphonycms/selectbox_link_field
[2]: https://github.com/symphonycms/numberfield
[3]: https://github.com/symphonycms/email_field
[4]: https://github.com/symphonycms/symphony-2/milestones/3.0.0

**Comment by brendo** [comment]
Yeah it's possible, but there's not much to gain and it makes the initial installation more of a chore.

**Comment by jensscherbl** [comment]
Which one? :)

**Comment by michael-e** [comment]
I like the idea, we might even consolidate things. For example:

* The Upload fields should have "Unique Upload" functionality as an option.
* Same for the Input field. One shouldn't need the Unique Input field (extension) anymore.

@brendo: Regarding fields like "email", I agree that there is nothing to gain. Too special. But I always wondered why the Selectbox Link is not part of the core. Dealing with data is an essential strength of Symphony, and this field enables you to build normalized data structures.

**Comment by jensscherbl** [comment]
> I like the idea, we might even consolidate things.

+1

> The Upload fields should have "Unique Upload" functionality as an option.

Upload field already creates unique filenames.

> Regarding fields like "email", I agree that there is nothing to gain. Too special.

If it's too special, it shouldn't be maintained by the core team and find a new maintainer. What about the number field?

**Comment by michael-e** [comment]
> What about the number field?

+1. It's also about "dealing with data", thus shows Symphony's capabilities.

> Upload field already creates unique filenames.

That is not what the "Unique Upload field" does. It appends a timestamp to overcome any caching issues. With the standard Upload field, when a file is deleted first, then uploaded again, you will have the same filename.

**Comment by jensscherbl** [comment]
> it makes the initial installation more of a chore.

What about making all fields an extension and include these in the bundle along with the other first party extensions? Would be the logical next step after removing all extensions from the core.

**Comment by michael-e** [comment]
Honestly, shouldn't we distribute an easy-to-use package? We removed the default workspace, we removed the "core extensions"… doesn't all this make it harder for Symphony beginners?

I am big fan of a small core, as long as it works out of the box and shows the strength of Symphony (without adding any extra stuff).

**Comment by jensscherbl** [comment]
> Honestly, shouldn't we distribute an easy-to-use package?

Yeah, that's what the bundle is for. People can either download it from [getsymphony.com][1] or checkout the [bundle branch][2] when using git.

[1]: https://github.com/symphonycms/symphony-2#via-the-old-fashioned-way
[2]: https://github.com/symphonycms/symphony-2#via-git

**Comment by michael-e** [comment]
Still, I don't get the idea of stripping fields from the core. What is the big picture?

**Comment by nitriques** [comment]
> Still, I don't get the idea of stripping fields from the core. What is the big picture?

Add the new extensions in the bundle I guess...

**Comment by michael-e** [comment]
But the __big__ picture is? Have a core that doesn't do anything?

**Comment by nitriques** [comment]
> Have a core that doesn't do anything?

I think so, yes!

**Comment by jensscherbl** [comment]
> But the big picture is? Have a core that doesn't do anything?

A core that provides a common infrastructure for stuff like fields, text formatters, data sources, events, event filters, etc. A clean slate that holds everything together.

What you're talking about and what the "core" was before `2.4`, a standalone Symphony with most of the first party extensions already included and ready to go, is now the [bundle][1].

I agree that there are certain things that should be provided by the core. Like filtering and ordering entries, for example. Sometimes, adding functionality to parts of the core that should have been there in the first place just feels ugly and wrong.

But fields, text formatters, data sources, events, event filters, etc. are designed to be modular, are designed to be added.

[1]: https://github.com/symphonycms/symphony-2/tree/bundle

**Comment by designermonkey** [comment]
Taking fields out of the core actually would add more overhead, as each one would need to be loaded via an extension, which means the extension manager; More processing time and overhead. It would mean more code, more config... PITA

The core should reflect the fields of an HTML form as best it can, but with additions like: SBL and IMO the number field.

I say the number field, as it is there to allow proper data storage for numeric values, which is unachievable with a text based field. I've always said it should be in the core.

Also, I think everyone was acutely aware of my disagreement with removing bundled extensions. It has made my dev work a PITA now.

**Comment by designermonkey** [comment]
If it needs to be more modular, and lean, then the installer needs to allow a dev to download and install extensions and fields, otherwise, developing with Symphony is becoming more and more annoying and time wasting in setup.

**Comment by michael-e** [comment]
+1

Setting up Symphony shouldn't be(come) hermetism.

**Comment by jensscherbl** [comment]
> Taking fields out of the core actually would add more overhead, as each one would need to be loaded via an extension, which means the extension manager; More processing time and overhead. It would mean more code, more config... PITA

You mean, like all the other fields Symphony encourages you to install as an extension?

> Also, I think everyone was acutely aware of my disagreement with removing bundled extensions. It has made my dev work a PITA now.

Why don't you use the [bundle][1]?

> If it needs to be more modular, and lean, then the installer needs to allow a dev to download and install extensions and fields, otherwise, developing with Symphony is becoming more and more annoying and time wasting in setup.

Or, you know, we could simply provide a ready-made [bundle][1].

> Setting up Symphony shouldn't be(come) hermetism.

Did I mention the [bundle][1]? :)

[1]: https://github.com/symphonycms/symphony-2/tree/bundle

**Comment by michael-e** [comment]
Bundle or not, I don't get the point of tearing the system apart without any need, even accepting performance drops (mentioned by @designermonkey) and potentially additional release work for the dev team.

> The core should reflect the fields of an HTML form as best it can, but with additions like: SBL and IMO the number field.

Exactly.

**Comment by jensscherbl** [comment]
Btw. this isn't even my own idea. Just pushing for it because it makes a lot of sense to me, from an architectural point of view.

@brendo mentioned this to me a while ago (when we met in Cologne, if I remember correctly). It was actually @allen's idea.

Now seems to be the right time to do it.

**Comment by designermonkey** [comment]
I think it was my idea about three years ago ;P There's a closed ticket where I discussed it with Allen, but now after more experience, I disagree with my younger self. :D

**Comment by brendo** [comment]
I think effort can be redirected into more tangible changes than this. It doesnt improve the experience for authors or developers.

**Comment by jensscherbl** [comment]
@designermonkey

> There's a closed ticket where I discussed it with Allen

I'm still interested in doing this. Any chance you can point me to this discussion?

**Comment by michael-e** [comment]
I think that we should respect @brendo's decision.

**Comment by jensscherbl** [comment]
> I think that we should respect @brendo's decision.

Sure, I wouldn't push anything to the repo without @brendo's blessing anyway. Doesn't mean it prevents me from trying things out in my own fork... ;)

> I think effort can be redirected into more tangible changes than this.

What about moving the other first party fields ([selectbox link][1], [number][2], [email][3]) to the core as well?

[1]: https://github.com/symphonycms/selectbox_link_field
[2]: https://github.com/symphonycms/numberfield
[3]: https://github.com/symphonycms/email_field

**Comment by jensscherbl** [comment]
> @designermonkey Any chance you can point me to this discussion?

Nevermind, [found it][1].

[1]: https://github.com/symphonycms/symphony-2/issues/788

**Comment by brendo** [comment]
> Just to clarify, what about the second option, moving other first party fields (selectbox link, number, unique input, email) to the core as well?

No to all, except perhaps the Number field. Entry linking has many options (Reference Link, SSM, Association Field), so baking in SBL to the core is potentially wasteful if someone wants to use a different solution. Unique Input and Email are too specialised.

**Comment by jensscherbl** [comment]
> except perhaps the Number field.

+1

> Entry linking has many options

Wasn't the plan here that all these options should extend the select box link / association field going forward? Otherwise, point taken.
