### ISSUE TITLE
De-normalisation

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2381]
This is something I've mentioned before, and it's something that needs considering now v3 is in sight.

Theoretically, normalisation of databases is a great thing. In practice, it causes problems, especially while migrating databases between servers.

There have been many times when I've neglected to delete all tables before importing changes from local DBs, and found schemas to be incorrect in the data tables. This is all down to the normalisation of entries data.

I would opt for a single table over hundreds of tables with IDs in the name:

```
sym_fields_input_schema (was sym_fields_input)
sym_fields_input_data (was sym_entries_data_xxx)
```

The data tables would simply require one extra column, being the `entry_id` to identify which entry the data is for.

It would be a bit of work, and would mean *all* fields need updating, but that's the point of a major release after all.

**Comment by designermonkey** [comment]
Just to add, I will be doing this in our custom Symphony as keeping the current schema is just not a feasible option for an upcoming project.

**Comment by brendo** [comment]
No. This won't be implemented

**Comment by designermonkey** [comment]
No discussion or reason why?

**Comment by brendo** [comment]
It's another non tangible change that provides minimal to no benefits for authors and developers. Symphony uses a normalized table structure, that's just how it is. The idea of the mega tables is not nice, and it introduces a coupling we don't currently have (or want)

**Comment by nitriques** [comment]
I agree with @brendo on this. Having multiple small tables is faster too.
