### ISSUE TITLE
Add ctype support in General::intval

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2383]
I've found those to be quite useful.

http://php.net/manual/en/function.ctype-digit.php

Maybe we should consider using it here: https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.general.php#L1622-L1628 ?

**Comment by brendo** [comment]
> Checks if all of the characters in the provided string

This is potentially the only quarm here, passing an integer to `General::intval` wouldn't work like it currently does :)

**Comment by nitriques** [comment]
Well, what I meant was:

Check ctype_digit before doing the regexp ;)

**Comment by jensscherbl** [comment]
> passing an integer to General::intval wouldn't work like it currently does

Current function works with strings and integers, `ctype_digit` would only work with strings.

>  This method makes sure that the value is a valid positive integer representation

Shouldn't the regex be `'/^[0-9]+$/i'` then?

**Comment by nitriques** [comment]
> Still wouldn't work.

Why ?

> Shouldn't the regex be '/^[0-9]+$/i' then?

Yes it should. The change was made in fdb39fb

**Comment by jensscherbl** [comment]
> Why ?

`is_numeric` checks if the value, string or integer, is numeric (only contains digits and `+` or `-`). The regex then checks if the value is positive (only contains digits).

Thinking about it, `is_numeric` seems a bit redundant here, regex alone should handle everything just fine.

`ctype_digit` can't be used because it only works with strings and fails if your original value already is an integer.

**Comment by nitriques** [comment]
> Thinking about it, is_numeric seems a bit redundant here, regex alone should handle everything just fine.

You're right. The weird part: how does php handle doing regexp on numeric types ?

> ctype_digit can't be used because it only works with strings and fails if your original value already is an integer.

Like I said:  "Check ctype_digit before doing the regexp ;)"

I had perf in minde, but I now think it's an overhead...

**Comment by jensscherbl** [comment]
> Like I said: "Check ctype_digit before doing the regexp ;)"

I'll try again... If the value is an integer, `ctype_digit` will return false, even if the value is numeric and positive. In such a case, the regex wouldn't even be executed.

If the value is a string on the other hand, `ctype_digit` would already check if the value is numeric and positive, so we wouldn't even need the regex in that situation.

Makes sense now?

**Comment by nitriques** [comment]
> I'll try again... If the value is an integer, ctype_digit will return false, even if the value is numeric and positive. In such a case, the regex wouldn't even be executed.

I was thinking about:

```php
if (is_string($value) && ctype_digit($value)) {
   return intval($value);
}
elseif (/* old code*/ { ... }
```

**Comment by jensscherbl** [comment]
> I was thinking about

So we add more code in order to use another function sometimes, and in cases where that function doesn't work we fall back to our existing code that works in all situations? Think about it... ;)

**Comment by nitriques** [comment]
> Think about it... 

.... :bulb: 

> I had perf in mind, but I now think it's an overhead...

... I guess that's no soup for me then. :rice:
