### ISSUE TITLE
Tag List associations not working

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2385]
The `Display associations in entries table` option doesn't seem to work as intended on the [2.6.x branch](https://github.com/symphonycms/symphony-2/tree/2.6.x). The publish index table kinda breaks (see screenshot below) and the associations drawer remains empty.

![screen shot 2015-03-21 at 13 30 57](https://cloud.githubusercontent.com/assets/1640033/6765026/982cd8f6-cfce-11e4-8243-ecd0cc274e1e.png)

**Comment by brendo** [comment]
Just to check, are you using a related section for the suggestions? None, or Existing have no effect.

**Comment by jensscherbl** [comment]
> Just to check, are you using a related section for the suggestions?

Yes. The values I use for suggestions come from another tag list field in another section.

Just updated to `2.6.1` including [0c92f79][1], problem still exists.

[1]: https://github.com/symphonycms/symphony-2/commit/0c92f79bb0347b5ccca7abe026808f09f8744b51

**Comment by brendo** [comment]
Hmm, what's your Section setup? I've got:

- Comments, with Taglist field (display existing values)
- Blog, with Taglist field (set to take in values from Comments: Taglist, display associations)

I can't replicate the issue.

**Comment by jensscherbl** [comment]
> Hmm, what's your Section setup?

I replicated your setup and could reproduce the issue.

![screen shot 2015-03-22 at 13 08 07][1]
![screen shot 2015-03-22 at 13 09 05][2]
![screen shot 2015-03-22 at 13 09 52][3]

I also noticed something especially weird. When I edit and re-save the `Comments` section, it deactivates the `display associations` option in the `Blog` section.

[1]: https://cloud.githubusercontent.com/assets/1640033/6769278/0c081a3a-d095-11e4-9a79-232c1ebafa75.png

[2]: https://cloud.githubusercontent.com/assets/1640033/6769279/1fe9d886-d095-11e4-8d87-1cb612742ca5.png

[3]: https://cloud.githubusercontent.com/assets/1640033/6769282/3c1ccd74-d095-11e4-8663-53ef2d2396f4.png

**Comment by brendo** [comment]
> When I edit and re-save the Comments section, it deactivates the display associations option in the Blog section.

A section association can only exist if another section is in play. The checkbox has no effect, and cannot even be remembered if 'none' or 'existing' are selected. This is because of changes to remove the `show_association` value from the field and leave it into the `tbl_section_associations` (#2083).

> I replicated your setup and could reproduce the issue.

Ah, got it now.

**Comment by jensscherbl** [comment]
> A section association can only exist if another section is in play. The checkbox has no effect, and cannot even be remembered if 'none' or 'existing' are selected.

Understood, but how does it relate to my scenario?

Another section IS in play, and it showed the associations after setting everything up. Well, at least it tried, ignoring the issues pictured in the screenshots above.

But after changing something else in the `Comments` section, like adding another field, it no longer shows the associations. I have to go back, edit the `Blog` section and check `display associations` again.

Not sure if this is expected when you know how it's implemented. But from a user/developer perspective, this looks buggy and completely unrelated.

**Comment by brendo** [comment]
I'm really not sure how to solve this one. 

- Associations can only work with Sections. If "existing values" is used, associations are not relevant, but unfortunately we don't have a UI to handle this dynamic scenario
- If an entry has multiple values associated with it, which is common with a tag list, what is the actual expected display on the associated section? While we have selected 'Tag 1', the associated entry actually contains the full values 'Tag 1', 'Tag 2', 'Tag 3'. Should it be the count of associated entries?

**Comment by brendo** [comment]
I can modify the Taglist field in a couple of ways:

- `fetchAssociatedEntrySearchValue` will return an single of handles, instead of an array of values
- `fetchAssociatedEntryCount` will accept the string, turn it back to an array and then issue a query to count each value, summing as it goes by.

This feels wrong, but I can't fathom how else to handle many to many relationships.

**Comment by jensscherbl** [comment]
> Associations can only work with Sections. If "existing values" is used, associations are not relevant, but unfortunately we don't have a UI to handle this dynamic scenario

I think this isn't actually a problem, seems pretty clear to me.

> If an entry has multiple values associated with it, which is common with a tag list, what is the actual expected display on the associated section? While we have selected 'Tag 1', the associated entry actually contains the full values 'Tag 1', 'Tag 2', 'Tag 3'. Should it be the count of associated entries?

Count of associated entries sounds right to me.

**Comment by brendo** [comment]
This is a bit of an iceberg as in fixing this, I discovered 59fec35, which then lead to the discovery [here](https://github.com/symphonycms/symphony-2/issues/2331#issuecomment-95012036). So in terms of your initial bug, things should be resolved. But it has uncovered other issues which are not going to be able to be fixed in 2.6.2.

**Comment by jensscherbl** [comment]
> So in terms of your initial bug, things should be resolved.

Thanks, will try soon.

> But it has uncovered other issues which are not going to be able to be fixed in 2.6.2

`2.6.3` then? Or `3.0.0` only?

**Comment by nitriques** [comment]
Should be fixed in 2.7.0!!!

**Comment by jensscherbl** [comment]
> Should be fixed in 2.7.0!!!

Awesome! Works as expected now.

**Comment by nitriques** [comment]
Great! We still have #2713 to fix tho ;)
