### ISSUE TITLE
JS-Error in list view when using date field

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2388]
When using a date field in an installation recently updated from 2.2.5 to 2.6.1 I get the following JS-Error in the console:

    [Error] TypeError: undefined is not a function (evaluating 'moment().utcOffset()')
      (anonym funksjon) (symphony.min.js, line 97)
      each (symphony.min.js, line 14)
      each (symphony.min.js, line 14)
      (anonym funksjon) (symphony.min.js, line 97)
      execute (symphony.min.js, line 32)
      dispatch (symphony.min.js, line 32)
      dispatch (symphony.min.js, line 32)
      parse (symphony.min.js, line 37)
      render (symphony.min.js, line 96)
      (anonym funksjon) (symphony.min.js, line 97)
      k (symphony.min.js, line 24)
      fireWith (symphony.min.js, line 24)
      ready (symphony.min.js, line 24)
      g (symphony.min.js, line 14)

**Comment by animaux** [comment]
As a sidenote: this error stops other scripts from working in the list view.

**Comment by brendo** [comment]
Interesting, looks like we missed adding `moment` to the anonymous function to ensure it's available.

**Comment by nitriques** [comment]
@animaux Can you confirm that you have moment 2.9.0 in your setup ?

utcOffset is new in this version. And I am not able to reproduce the error.

**Comment by animaux** [comment]
2.9.0 is included in `symphony.min.js` the error is in list view with a section including the following settings for the date field (first field in section):

Default date [yes]

[ x ] Display time
[ x ] Show calendar
[   ] Make this a required field
[ x ] Display in entries table

Hope this helps.

**Comment by nitriques** [comment]
I can't figure out what's causing a 100% decoupled call from our code to fail.

I mean, I can run `moment().utcOffset()` in any website that requires moment.

> Can you confirm that you have moment 2.9.0 in your setup ?

What I meant by that is: are you sure you uploaded/replace the file on the server (if it's not a local machine)... 

Because I still can reproduce it...

![image](https://cloud.githubusercontent.com/assets/771169/6788618/2c99aaca-d171-11e4-83e5-a77e754b27e7.png)
![image](https://cloud.githubusercontent.com/assets/771169/6788631/3ccc3ce6-d171-11e4-8036-196a1be9e723.png)

**Comment by animaux** [comment]
Cheers Nicolas,

I’m sure it’s uploaded on the server (plus I had the same error on a local server too).

![skjermbilde 2015-03-23 kl 20 40 21](https://cloud.githubusercontent.com/assets/446874/6788945/2150d3d8-d19d-11e4-913c-397531ea158a.png)

You screenshots show the section-editor and the entry-editor only. I don’t get any errors there either. It’s only in the entry-list:

![skjermbilde 2015-03-23 kl 20 39 22](https://cloud.githubusercontent.com/assets/446874/6788976/551842b4-d19d-11e4-9884-44d4ffe34bcd.png)

Are you seeing this too?

**Comment by nitriques** [comment]
Nope... 
![image](https://cloud.githubusercontent.com/assets/771169/6789064/e7527a16-d173-11e4-8db9-79bb7b33f4e9.png)

Which version of Safari are you running ?

**Comment by animaux** [comment]
+ Safari 7.1.4 (9537.85.13.7)
+ Mac OS X 10.9.5

**Comment by animaux** [comment]
Error shows up in FFdevedition too.

**Comment by animaux** [comment]
D’oh, should have done this before, I deactivated all the extensions that insert js and voilá. The error is gone …

Moving this here: https://github.com/symphonists/unpublishedfilter/issues/7

Thanks, and sorry for wasting your time guys!
