### ISSUE TITLE
SQL error on update to "3.0.0"

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2391]
I just try to run the `integration` branch on a 2.6 setup and I get

> Symphony Fatal Database Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't2.order' in 'field list'

This error is raised when trying to go to /install/index.php so I can't run the migration script...

re #2373

**Comment by nitriques** [comment]
Closed with #2389

**Comment by nitriques** [comment]
Well, it seems like #2389 does not solves the problem. I do not know why it was working yesterday after I pulled #2389, but doing so with the current integration branch still yields the same result

```
Symphony Fatal Database Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't2.order' in 'field list'
An error occurred while attempting to execute the following query
SELECT SQL_CACHE t1.name, t2.page, t2.delegate, t2.callback, t2.order FROM `sym_extensions` as t1 INNER JOIN `sym_extensions_delegates` as t2 ON t1.id = t2.extension_id WHERE t1.status = 'enabled' ORDER BY t2.delegate, t2.order, t1.name
```

First thing, why are we ordering by delegate name BEFORE order ?

Second thing, why is there no migration script to add the new order column ?

Thirdly, I had to comment out line 37

```php
require_once DOCROOT . '/symphony/lib/boot/bundle.php';
```

The extension manager was not able to initialise... because of the missing column. How can we break that circle ?

@jensscherbl @brendo do you run into the same issue?

**Comment by jensscherbl** [comment]
> do you run into the same issue

No, but I usually start with a clean core and add extensions afterwards.

**Comment by nitriques** [comment]
Ok, but my problems occurs on updating, not on install.

**Comment by jensscherbl** [comment]
> Ok, but my problems occurs on updating, not on install.

Didn't update to `integration` yet.

**Comment by brendo** [comment]
This is because #2354 doesn't have the accompanying migration yet :)

**Comment by nitriques** [comment]
Oh ok then.
