### ISSUE TITLE
Tiny little suggestion DS-Editor help

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2393]
Why not mention that you can add a default value in a DS-Filter. I find it’s quite an essential function that could have saved me some headaches if I found out about it ealier. Why not change:

    Use {$param} syntax to filter by page parameters.

to:

    Use {$param} syntax to filter by page parameters. You can add a default filter value {$param:default} if the $param is not set.

**Comment by nitriques** [comment]
+1

**Comment by jensscherbl** [comment]
Data source filters can do [a lot more][1] and I don't think we can or should cram everything in there.

-1

[1]: http://www.getsymphony.com/learn/concepts/view/data-source-filters/

**Comment by michael-e** [comment]
@jensscherbl is right. It's impossible to suggest all the goodies here. Here are some more examples (from my projects):

* `regexp:{$year:.*}-{$month:.*}`
* `earlier than 2 months ago`
* `{$member-id:0}`
* `69806,69803,69799,69673,69671,69637,69627,69614,69612,69610,71144,68842`
* `{$url-banner2089:$ds-system-banner-no-1-own:0},{$url-banner2089:$ds-system-banner-no-1-cs:0}`
* `$etm-entry-id:$url-id`

What about a link to the documentation?

**Comment by animaux** [comment]
Ok, I’m starting to see the range of the problem … a link sound good. But I guess then there are a dozen other places where links should be then. Hmnn.

@michael-e interesting! :)

**Comment by nitriques** [comment]
> What about a link to the documentation?

Where is that documentation ?

**Comment by animaux** [comment]
In Jens’ [link](https://github.com/symphonycms/symphony-2/issues/2393#issuecomment-86169164). I wasn’t aware that it was up to date …

**Comment by michael-e** [comment]
> @michael-e interesting! :)

You bet. These examples are from my famous "big system". One Symphony installation powering 450 (connected) websites, still counting!

**Comment by cmnstmntmn** [comment]
not to mention that some fields may behave different from others.
-1

El miércoles, 25 de marzo de 2015, michael-e <notifications@github.com>
escribió:

> @michael-e <https://github.com/michael-e> interesting! :)
>
> You bet. These examples are from my famous "big system". One Symphony
> installation powering 450 (connected) websites, still counting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symphonycms/symphony-2/issues/2393#issuecomment-86193790>
> .
>


-- 
thumb typed

**Comment by animaux** [comment]
Ok, ok, I’m convinced. Closing this :)

**Comment by animaux** [comment]
@michael-e starting work on a symphony installation to power 9 different site these days :)

**Comment by jensscherbl** [comment]
> I wasn’t aware that it was up to date …

It isn't (judging by the screenshots), but the filtering hasn't really changed over the last few years... ;)

**Comment by animaux** [comment]
Hmm, somehow I was missing out on this then …

**Comment by michael-e** [comment]
> starting work on a symphony installation to power 9 different site these days :)

Cool!

**Comment by nitriques** [comment]
I have a Symphony setup that contains more than 4000 fields. Which means more than 4000 tables in the Database ;)

**Comment by michael-e** [comment]
I can not beat that. Even my "big system" has no more than 820 fields. :-(

**Comment by nitriques** [comment]
It's a crazy website too ;) One section has 200+ fields and yes, it's a registration form ....

**Comment by michael-e** [comment]
LOL! People really want to spend the rest of their lifes with a registration?

**Comment by animaux** [comment]
Oh dear, sounds like a mess to take of :)

**Comment by jensscherbl** [comment]
Currently working on a long-term project where Symphony powers city guides for 17+ cities, with satellite pages for 500+ businesses and standalone domains for several newspaper publishers.

**Comment by munki-boy** [comment]
meh, I've more recursive SSM in my early work than that :)

**Comment by munki-boy** [comment]
Starting my first BIG web form and section tomorrow, I'll report back when I counted the fields...

**Comment by animaux** [comment]
Not sure if these are the kind of challenges I’d like to tackle :)

**Comment by brendo** [comment]
Whoa whoa, the original idea is a good one. Default parameters are gems that I think only half the community know exist! All fields support this functionality, it's agnostic of the fields.

> Use {$param} syntax to filter by page parameters. You can add a default filter value {$param:default} if the $param is not set.

@michael-e's examples are now partially covered by the field filter helpers. Fields like date include the predicates for the `later than`, `earlier than` etc. All fields include the `regexp:`, `not-regexp`. Fields like textbox include `not: `. 

At the very least I think we should add that and perhaps a 'Read more about Data Sources' link that goes to the Symphony docs page.

**Comment by michael-e** [comment]
@jensscherbl:

> Currently working on a long-term project where Symphony powers city guides for 17+ cities, with satellite pages for 500+ businesses and standalone domains for several newspaper publishers.

You will beat me—if it works. But I am not sure if you can beat @nitriques' registration form (with 200+ fields). :-)

**Comment by jensscherbl** [comment]
> You will beat me—if it works.

Don't worry, yours is much more complex... ;)

**Comment by nitriques** [comment]
> People really want to spend the rest of their lifes with a registration?

They sure do! It even cost them 60$ to send the form!

**Comment by brendo** [comment]
> Use {$param} syntax to filter by page parameters. A default value can be set using {$param:default}.

How does this wording sound in the various translations? It's a little more succinct than @animaux's original suggestion, but hopefully gets across the same point.

I don't think a link to the documentation is necessary in hindsight as the additional information that page provides is mostly covered with the filtering suggestions. Keep in mind that all fields support this out of the box, Symphony handles this before the value is passed to the field.

**Comment by nitriques** [comment]
Great!

**Comment by animaux** [comment]
> Use {$param} syntax to filter by page parameters. A default value can be set using {$param:default}.

Verwenden Sie {$parameter}, um mit Seitenparametern zu filtern. Ein Standardwert kann mit {$param:default} definiert werden.

**Comment by brendo** [comment]
Well that's more verbose than I would of guessed but that's the beauty of languages :) I'll push the change, it's for the better.

**Comment by animaux** [comment]
Cheers!
