### ISSUE TITLE
Add NO-BREAK SPACE to transliterations for @handle generation

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2396]
I always end up adding `' ' => '-',` in the `lang-german`-extension, but I feel this should be in the core since NO-BREAK SPACEs are an important tool for typography and shouldn’t break handles if used.

Right now they are apparently not transliterated at all which makes handles unusable for URLs f. e.:

`<titel-de handle="entwicklung-des-querwege e v">Entwicklung des QuerWege e. V.</titel-de>`

**Comment by brendo** [comment]
Closed due to #2106.

**Comment by animaux** [comment]
brill!
