### ISSUE TITLE
Association UI

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2397]
![screen shot 2015-03-31 at 15 35 35](https://cloud.githubusercontent.com/assets/221344/6921320/fbc0736a-d7bb-11e4-9809-740104ae56f3.png)

The three lines denote drag and drop, but the editor icon is over them so when a client is clicking them it edits the entry.

Not a great UI element as it seems to say one thing and do another.

**Comment by jensscherbl** [comment]
Wrong issue tracker?

**Comment by munki-boy** [comment]
+1, even weirder with a thumbnail instead of text/title

**Comment by designermonkey** [comment]
I assumed that with @nilshoerrmann not contributing any more, and this being baked into the core that the core team would need to know.

**Comment by jensscherbl** [comment]
> I assumed that with @nilshoerrmann not contributing any more, and this being baked into the core that the core team would need to know.

[Apparently not.][1]

[1]: https://github.com/symphonycms/symphony-2/issues/2379#issuecomment-84150821

**Comment by nilshoerrmann** [comment]
Feel free to post this in the extension's repository. 
There are a few other open issues that we will look into over the next months, too.

**Comment by brendo** [comment]
Closing, the UI is provided by [https://github.com/hananils/association_ui_editor](hananils/association_ui_editor)
