### ISSUE TITLE
Discarding SQL errors when editing entries

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2401]
Ok I've been dealing with this bug since Symphony 2.2.x, but since it can't be reproduced, I never bother to try to fix it.... until today.

_Sometimes_, the user saves the entries, it works. Then going back to the list: everythings crashes. In most of the case, it's a Textbox field or multilingual field was crashing because it was receiving arrays instead of strings in the $data variable.

I was able to basically boil it down to [this](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.entrymanager.php#L183). I think the DELETE do not works (timeout or something) but this gets ignored and later inserts successfully creates duplicate information. Note that this problems rarely happens on my servers (but mostly on poor clients shared hosting plan).

Since nothing is commented in those function, it's hard to be 100% sure about why it's been implemented that way. From what I've tested, it's only because some field do not have data tables.

I know that we already talk about DELETE + INSERT vs UPDATE cases and I do not want to go into that debate again.  We've also talked about the extension's developers who must enforce uniqueness on the `entry_id` column and still think the status quo is the best option. But I think we need to stop ignoring errors when deleting data...

Here's the patch I've applied to my client's symphony:

``` php
try {
       $tableName = 'tbl_entries_data_' . $field_id;
       $tableExists = count(Symphony::Database()->fetch(sprintf("SHOW TABLES LIKE '%s'", $tableName))) == 1;
       if ($tableExists) {
           Symphony::Database()->delete($tableName, sprintf("
               `entry_id` = %d", $entry->get('id')
           ));
       }
} catch (Exception $e) {
    Symphony::Log()->pushExceptionToLog($e, true);
    throw $e;
}
```

And I've moved [those lines](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.entrymanager.php#L161-L169) at the end of the function.

Question: This function returns a boolean which is always true. Should we return false instead of re-throwing the exception ?

@michael-e I am ready for your comments (hahaha)

**Comment by brendo** [comment]
> From what I've tested, it's only because some field do not have data tables.

Hmm, if the field has no data tables, then [these lines](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.entrymanager.php#L186-L188) should cause it to bail out and not attempt to insert any data.

> Here's the patch I've applied to my client's symphony:

Out of curiosity, what sort of exceptions have been logged as the result of this change? Are they timeout related?

> And I've moved those lines at the end of the function.

Any reason for this? I can't see why this would cause any issues being at the start or at the end of the function.

> Question: This function returns a boolean which is always true. Should we return false instead of re-throwing the exception ?

I think the Exception was 'thrown' (and then commented out) while trying to debug the problem initially. This problem is really challenging to debug, so hopefully your logging sheds some light. Nevertheless, perhaps we should introduce transactions before and after the loop. If any exception is thrown, we'll rollback the transaction and return false with the exception message.

I don't think this is going to fix the issue, but it is going to bring the problem to the surface.

**Comment by nitriques** [comment]
> Hmm, if the field has no data tables, then these lines should cause it to bail out and not attempt to insert any data.

Well, it does not...

> what sort of exceptions have been logged as the result of this change? Are they timeout related?

Did not catch any since I put it in production.

> Any reason for this? 

Yes, time won't change if an errors happens.

> Nevertheless, perhaps we should introduce transactions before and after the loop

We would need to switch everything to InnoDB, which supports transactions but is way slower.

> I don't think this is going to fix the issue, but it is going to bring the problem to the surface.

This is why it's not a PR ;) I will try to gather as much data as possible on that subject.

**Comment by brendo** [comment]
> Hmm, if the field has no data tables, then these lines should cause it to bail out and not attempt to insert any data.
> Well, it does not...

Well this needs to be fixed ASAP then, we should find what is being sent through!

**Comment by nitriques** [comment]
Yup, can'T wait to see what I get in the logs.

**Comment by nitriques** [comment]
Had the problem again. Nothing in the logs... :(

Starting to look like a DB connection problem.... I've added a bunch of logs to try to find what's causing this issue...

**Comment by brendo** [comment]
Did this even amount to any further information?

**Comment by nitriques** [comment]
> Did this even amount to any further information?

Sadly not. But #2471 might be it....

**Comment by nitriques** [comment]
This have been worked on a lot in #2659 so I'll close this one.
