### ISSUE TITLE
Wrong error message when trying to change own username

### ISSUE THREAD

**Issue by aVandalInShorts** [symphonycms/symphony-2#2405]
When trying to change my username, even though there is no other user with that name, it returns this message.

![symphony-bug](https://cloud.githubusercontent.com/assets/5823666/7204283/dc9bcb20-e4ee-11e4-874c-4a060a9c38d1.jpg)

**Comment by michael-e** [comment]
Confirmed on Symphony 2.6.1. Which version have you tried?

**Comment by nitriques** [comment]
2.6.1.

**Comment by brendo** [comment]
Got it :)

**Comment by moretaste** [comment]
Same error and fix for e-mail

**Comment by brendo** [comment]
Yep, that's in 6a1dffa7000761f87e6ee3cb7f6f1f66f0058cc1 :+1:

**Comment by moretaste** [comment]
Ok, haven't seen that commit
