### ISSUE TITLE
Create new entry with prepopulated Select Box Link is broken

### ISSUE THREAD

**Issue by andrrr** [symphonycms/symphony-2#2408]
In a table view, after filtering entries by parent entry linked with SBL, "Create new" button lead to the wrong url. I have fixed it changing line 430 in content.publish.php to: 
```
if (!ctype_digit($value) && method_exists($field, 'fetchIDfromValue')) {
```
Not sure if this is the best solution because there are some related issues in issues list, but it works for me

![2015-04-26 17 17 36](https://cloud.githubusercontent.com/assets/67981/7338453/f627943a-ec54-11e4-8586-f055f90df2d0.png)

**Comment by nitriques** [comment]
@nilshoerrmann Would you mind confirming the proposed fix ? Thanks!

**Comment by nilshoerrmann** [comment]
I'm not sure if I can help in this context – better ask @brendo to check this case.

**Comment by nitriques** [comment]
Ok thanks Nils.

**Comment by cylkee** [comment]
Still seeing this issue in 2.6.2.  I bumped [this thread](http://www.getsymphony.com/discuss/thread/110041/) a month ago, but got ignored..?  Thank you.

**Comment by brockpetrie** [comment]
@cylkee you can try implementing the proposed fix at line 430 in content.publish.php (https://github.com/symphonycms/symphony-2/blob/master/symphony/content/content.publish.php#L430)

I ran into this same problem, and fixed it the same way. The only quirk is that this change assumes that the digit being passed through filtering is an ID, which may not necessarily be the case. For example, you might be filtering against the string '3', which actually is associated with entry ID 2 or something. Hell of an edge case probably, but I haven't thought through the implications in detail.

**Comment by cylkee** [comment]
Thanks, @brockpetrie.  I've temporarily implemented @andrrr's suggested fix and the UI appears to be working as expected.

**Comment by nitriques** [comment]
@cylkee @andrrr Would you mind sending a PR for review please ? Thanks!

**Comment by cylkee** [comment]
@nitriques Apologies, I'm not Git-literate.  I'm guessing you mean a Pull Request, but I've no idea how to go about such a thing.  I only post on Github because issues seemed to be ignored/forgotten on getsymphony.com/discuss.

**Comment by brendo** [comment]
Thanks for the patience @cylkee. I've pushed your fix to the 2.6.x branch which will released as 2.6.3 within a week!

**Comment by cylkee** [comment]
Thank you, @brendo.

**Comment by nitriques** [comment]
@cylkee Yeah that's what I've meant! But hey, thanks for reporting it on github, it is the right places for bugs.
