### ISSUE TITLE
Automatic password migrating broken

### ISSUE THREAD

**Issue by nils-werner** [symphonycms/symphony-2#2413]
At the time `cryptography` was written (2,5 years ago) [10,000 iterations](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/cryptography/class.pbkdf2.php#L28) was the recommended setting. [Nowadays people recommend settings up to 10x the size of that.](http://chargen.matasano.com/chargen/2015/3/26/enough-with-the-salts-updates-on-secure-password-schemes.html)

As a reminder what iterations does: It wastes time and computation power, basically. The most common hashes are optimised for speed, but a fast algorithm is also more quickly brute-forceable. PBKDF2 implements an iterations count to basically arbitrarily raise the computational cost and slow down the algorithm. So while hardware gets faster, you may to make the algorithm slower to keep the computation time constant.

I recommend setting iterations to 90,000 and in two-three years time to 800,000.

**Comment by brendo** [comment]
Sounds fine to me. What impact would this have over existing passwords? Would they need to be migrated from the existing 10,000 iteration hash?

**Comment by nils-werner** [comment]
Yup. It will happen automatically though (next login will validate against old hash and create a new one)

**Comment by jensscherbl** [comment]
Just curious, assuming I have a site on the same server hardware as 2,5 years ago, would this noticeably slow down things for a single user (login etc.)?

**Comment by nils-werner** [comment]
Yes, it will slow things down. If it will be "noticeable" depends: How fast was the validation before? It will now be 9x slower. This could mean

 - 0.1s -> 0.9s, not really noticeable
 - 1s -> 9s, noticeable

Thinking about this it might be interesting to gather some metrics before changing the value, actually. You may run [this gist](https://gist.github.com/nils-werner/d70ae5e233dbd5142d3b) on your server to see the speeds.

On my desktop machine the first hash returns in 0.03 seconds, the second one in 0.3 seconds (not noticeable I would say).

**Comment by michael-e** [comment]
> Old passwords will still validate fine.

> Migration will happen automatically: next login will validate against old hash and create a new one.

I tested it, and it works for both (Symphony and Members) __only if you log out__ before the iterations value gets changed. However, if you are logged in, things will break (and I had to use the password reset mechanism in Symphony and Members).

**Comment by nils-werner** [comment]
Wow, that's not what it was designed to work like...

**Comment by michael-e** [comment]
OK, so we need a (manual or automatic) migration mechanism like this:

* delete __all sessions__ from the database
* then immediately change the iterations value

Right?

**Comment by michael-e** [comment]
Or did you mean that it's a bug?

**Comment by nils-werner** [comment]
It's a bug.

**Comment by michael-e** [comment]
OK, so it's broken.

* my Symphony author worked fine until I logged out — then I was unable to login.
* Members logged me out (I think on the second request after the change), and I was unable to login.

**Comment by nils-werner** [comment]
What exactly did you change? The `const` in that file or some data in the database?

**Comment by michael-e** [comment]
I only changed the constant.

**Comment by michael-e** [comment]
Regarding performance: I tried the gist on a small vServer, and I get:

* 0.077142953872681
* 0.7177939414978

**Comment by brendo** [comment]
Locally, on a Macbook Air:

- 0.075292110443115
- 0.59065985679626

I can confirm @michael-e's findings. While I'm logged in, the session appears to be updated, but logging out and then trying to log in again fails. I'm currently debugging the PBKDF2 `compare` function, which seems to creating a different hash to that which is stored in the database.

**Comment by brendo** [comment]
I thought it might be this [line](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/cryptography/class.pbkdf2.php#L71) not referring to the local `$keylength` variable, but changing this doesn't seem to do the trick. It always seems to the actual hash generated is different, even though the parameters look to be consistent.

**Comment by nils-werner** [comment]
I cannot reproduce what you're reporting:

    $input = "PBKDF2v1|10000|efe80e027fde361f699c|jG50givg2Vs4NxiPFzs3F463B+FMEuHlNW4qSoI2b9o62VAVxrhS5A==";    
    var_dump(PBKDF2::compare("foo", $input));
    var_dump(PBKDF2::requiresMigration($input));

yields, for iterations = 10k

    bool(true)
    bool(false)

and for iterations = 100k

    bool(true)
    bool(true)

**Comment by brendo** [comment]
Yep, that's correct. Until you logout and try to log back in.

**Comment by nitriques** [comment]
Great thing @nils-werner, I wanted to do the exact same thing.

**Comment by nitriques** [comment]
I would also add that waiting 1 second for a password generation is ok IMO. Time and memory hard problems for security is way better than space complexity.

**Comment by michael-e** [comment]
I agree that up to 1s is no prob.

Now we just have to find out why migration doesn't work for users who stay logged in.

**Comment by nitriques** [comment]
Totally

**Comment by nitriques** [comment]
The problem is that migration needs to happen only when the user inputs its clear text password. If not, that breaks the shit.

I can confirm that changing SALT_LENGTH, KEY_LENGTH and ITERATIONS results in a migration. But changing  ALGORITHM does nothing.
