### ISSUE TITLE
Integration is broken

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2416]
Integration branch seems to be in pretty bad shape. Mostly related to unfinished database changes, I guess. For example, I can't even create a new page without running into exceptions. Not a good state to be in for other developers to work on.

I created a [2.7.x branch][1] and [milestone][2] for backwards compatible changes and feature additions, and updated the due date for the [3.0.0 milestone][3] to a more realistic date.

Doesn't necessarily mean we have to actually release a `2.7.0` if `3.0.0` gets back on track soon enough, but at least developers have something to work with and issue pull requests against.

[1]: https://github.com/symphonycms/symphony-2/tree/2.7.x
[2]: https://github.com/symphonycms/symphony-2/milestones/2.7.0
[3]: https://github.com/symphonycms/symphony-2/milestones/3.0.0

**Comment by brendo** [comment]
Effort is better put in correcting `integration` than diverting effort to
2.7. I will not be back porting any features to 2.x. Community is welcome
too, but personally I have no interest in doing so, its time to move
forward.

**Comment by jensscherbl** [comment]
> I will not be back porting any features to 2.x.

Agreed, no need to backport anything from `3.0.0` to `2.7.x`. This is just meant as a more stable branch for adding new changes and features that don't break compatibility.

> its time to move forward

Totally agree.

If `integration` had been stable enough to work with, I would have used `integration` instead.

> Effort is better put in correcting `integration`

Sure, but if I have to put in half a day to debug and fix unfinished work from others before getting to work on my own changes, that's not a very good starting point for moving forward.

**Comment by nitriques** [comment]
@brendo @jensscherbl Do not hesitate to tell me to fix things or do things. I am mostly doing maintenance these days and can only fix what I know about.

**Comment by jensscherbl** [comment]
> Do not hesitate to tell me to fix things or do things. I am mostly doing maintenance these days and can only fix what I know about.

Thanks :)

#2418
#2415

**Comment by nitriques** [comment]
@jensscherbl I'll see what I can do!
