### ISSUE TITLE
Creating a new page throws an error

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2419]
> **Symphony Recoverable Error:** Argument 3 passed to MySQL::fetchRow() must be of the type array, string given, called in .../public/symphony/lib/toolkit/class.pagemanager.php on line 896 and defined

And

> An error occurred in .../public/symphony/lib/toolkit/class.mysql.php around line 465

After the first attempt to create a new page, the error also shows up when trying to access

- `.../blueprints/pages/`
- `.../blueprints/datasources/`
- `.../blueprints/events/`

**Comment by brendo** [comment]
Fixed
