### ISSUE TITLE
JS-Error with select-box + association-field and values with ampersands

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2423]
The following setup creates a JS-Error in the entry-editor:
- Symphony 2.6.1
- Association UI: Selector 1.1.1

I have a section with a `select box field` that links to another section’s title which is a regular `text input field`. In the editor of the first section I get a JS error if I have title values in the linked section’s title containing an ampersand and `selector:search` is selected as »Association Interface«.

```
[Error] TypeError: undefined is not an object (evaluating 'a.length')
each (symphony.min.js, line 14)
success (aui.selector.publish.js, line 227)
k (symphony.min.js, line 24)
fireWith (symphony.min.js, line 24)
c (symphony.min.js, line 25)
(anonyme Funktion) (symphony.min.js, line 26)
```

**Comment by twiro** [comment]
> _I have a section with a **select box field** that links to another section’s title_

You actually mean **[Association Field](https://github.com/symphonists/association_field)**, don't you?

I noticed some [similar errors](https://github.com/hananils/association_ui_selector/issues/47#issuecomment-105874679) with the same setup and think the error derives from the extension, not from symphony itself - have you tried deactivating the selector ui and using association field with the basic selectbox interface?

**Comment by jonmifsud** [comment]
I might have already fixed this / have an improvement for association
field. I can double check later

**Comment by twiro** [comment]
> _I might have already fixed this / have an improvement for association field. I can double check later_

Sounds good - thank you!
Association field could definitively could need some more love - still slumbers in beta state and hasn't been really published/promoted/documented anywhere since it's appearance...

**Comment by nitriques** [comment]
Closing since this is related to the extension
