### ISSUE TITLE
Optimize Error Handler to not throw useless "headers already sent" error

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2424]
See [commit comments](https://github.com/symphonycms/symphony-2/commit/d361f366b66be0b45194e2acd15c6ed8589c2408#commitcomment-11099736).

**Comment by nitriques** [comment]
Should we assign it to our favorite Brendan ?

**Comment by michael-e** [comment]
Wise men say: Let @brendo assign it. :-)

**Comment by nitriques** [comment]
Hahaha. I'll follow what the wise man says.

**Comment by brendo** [comment]
This can be tested on `2.6.x` @michael-e

**Comment by michael-e** [comment]
I must try and remember how to provoke the issue. :-(

**Comment by michael-e** [comment]
Ok, that looks good to me. Instead of:

> Symphony Warning: Cannot modify header information - headers already sent by…

my script can now throw the following Symphony error, for example:

> Symphony Fatal Error: No suitable engine object found
