### ISSUE TITLE
[integration] Delegates cause fatal errors

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2437]
Our code doesn't define the `Administration` or `Frontend` mode by loading classes until after the loader has run, so the code at line `159` in `class.symphony.php` is now invalid until a class is actually used.

I think this has been an issue for some time, as it is triggered when a delegate is fired that has any listeners. The `ExtensionManager` can't complete as it is looking for the `Engine` which isn't defined yet. I'm talking specifically about the `ModifySymphonyLauncher` and new `ComposerReady` delegates.

I've recently defined `APP_MODE` as a constant in the `index.php` file, so my thoughts are to use this instead of `class_exists`?

Any thoughts @brendo, @jensscherbl, @psychoticmeow?

**Comment by designermonkey** [comment]
The PR tackles it. I tried to use `true` as the second parameter of `class_exists` but it doesn't feel right. I think it would always say `Administration` exists.

**Comment by nitriques** [comment]
Does it means that I can't 'fake' Administration just by requiring it in a php-cli script ?

Or should I now just define APP_MODE myself ?

**Comment by designermonkey** [comment]
That's a good question. The constant would need to be defined, and this happens in the `index.php` file. It doesn't use `define_safe` either, as that function is defined yet, so editing the file would be needed.

**Comment by nitriques** [comment]
Will try out and comment if it's a problem.
