### ISSUE TITLE
Add a `clearstatcache()` call in `General::writeFile`

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2447]
This would ensure we do not hit the stat cache when checking if a file (and its directory) are writable. See http://php.net/manual/en/function.clearstatcache.php. I would add it as the first statement in `General::writeFile` and add this precision to the doc. 

I have a PR pending for another related issue, I would like to include this fix in if its ok with @symphonycms/core

**Comment by brendo** [comment]
Fine by me, I think @DavidOliver has done a similar fix somewhere else in the codebase for a similar reason.

**Comment by nitriques** [comment]
There you go!

**Comment by DavidOliver** [comment]
> I think @DavidOliver has done a similar fix somewhere else in the codebase for a similar reason.

Wasn't me, guv.

**Comment by nitriques** [comment]
@DavidOliver well, do you think it's a good idea ?

**Comment by DavidOliver** [comment]
@nitriques, yep. :-)

**Comment by nitriques** [comment]
Great!
