### ISSUE TITLE
Issues with PDO and our data

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2448]
Since the PDO upgrade, using the `query` function from the database classes means that we can't pass `null` as a value any more.

PDO expects an actual value for a column, or to use `bindValue` and explicitly set `PDO:: PARAM_NULL` for the type. As we don't use that in `query` we can't define the type properly, and get errors instead.

So, the manager classes need to migrate over to using `prepare` and `bindValue` to function correctly again. I would be uncomfortable in allowing a `0` to go through to the table in place of `null` as this could have consequences further down the line that we don't know yet.

**Comment by designermonkey** [comment]
I have tried to save an entry today, that has Publish Tabs in it. Publish Tabs don't send any data through, but PDO is still expecting a value to be present; The value it recieves is `''` (an empty string).

```
Symphony Fatal Database Error: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'value' at row 1
An error occurred while attempting to execute the following query
INSERT INTO `sym_entries_data_11` (`entry_id`, `value`) VALUES (?,?)
Backtrace
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.database.php:745]
    Database->error();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.database.php:535]
    Database->q();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.mysql.php:427]
    Database->insert();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.entrymanager.php:209]
    MySQL->insert();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.entry.php:311]
    EntryManager::edit();
[/data/sites/cms.nigella.local.embarknow.net/symphony/content/content.publish.php:1434]
    Entry->commit();
[/data/sites/cms.nigella.local.embarknow.net/symphony/content/content.publish.php:374]
    contentPublish->__actionEdit();
[/data/sites/cms.nigella.local.embarknow.net/symphony/content/content.publish.php:350]
    contentPublish->__switchboard();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/toolkit/class.administrationpage.php:464]
    contentPublish->action();
[/data/sites/cms.nigella.local.embarknow.net/symphony/content/content.publish.php:345]
    AdministrationPage->build();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/core/class.administration.php:212]
    contentPublish->build();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/core/class.administration.php:479]
    Administration->__buildPage();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/boot/func.utilities.php:189]
    Administration->display();
[/data/sites/cms.nigella.local.embarknow.net/symphony/lib/boot/func.utilities.php:171]
    symphony_launcher();
[/data/sites/cms.nigella.local.embarknow.net/public/index.php:35]
    symphony();
```

**Comment by designermonkey** [comment]
Adding PDO was supposed to make our API so much easier, but instead, after looking through the relevant classes, it is so much more complicated. I really want to help debug and fix this, but I have no idea where to even start.

**Comment by jensscherbl** [comment]
> Adding PDO was supposed to make our API so much easier, but instead, after looking through the relevant classes, it is so much more complicated.

Thought the same thing, but I assumed this is only a rough first step and a long way to go until release. To be more specific, I don't really understand why there are two database classes now, `class.database.php` and `class.mysql.php`, where one is mostly a wrapper around the other.

**Comment by brendo** [comment]
Yep, there's still a way off to go to clear it up and have it production ready. It's a little bit more effort than I thought it'd be, but the hard part is done :)

> I don't really understand why there are two database classes now, class.database.php and class.mysql.php.

That's me being a little ambitious/naive by thinking eventually there will be `class.postgres.php`, `class.sqlserver.php`.

**Comment by designermonkey** [comment]
There's nothing naive about being ambitious :)

I've kind of fixed my immediate issue, by forcing the Publish Tabs field locally to send `null`, but weirdly, it's `null` values in the PageManager that cause the initial issue.

Very confused, but definitely sure we need to re-address how we process queries.
