### ISSUE TITLE
Regex for extended top level domain email addresses

### ISSUE THREAD

**Issue by andrewminton** [symphonycms/symphony-2#2456]
It has just been pointed out to me that a number of site we have using Symphony is refusing to validate certain email addresses. Turns out those email addresses are in the new extended family of top level domains.. '.london' '.paris' '.tokyo' etc.. 

The regex for emails doe snot cater for these extended domain names and I'm wondering what others are doing to get over this hicup?

**Comment by michael-e** [comment]
What exactly do you mean by "validate"? Are there issues sending emails from the core, or with Email Newsletter Manager?

**Comment by andrewminton** [comment]
It's front end forms rejecting these emails when trying to submit into a section.. and also backend (symphony) section when creating a new entry that contains an email address field... Does the current email regex cater for these extended character top level domains?

**Comment by michael-e** [comment]
Ah, field validation! But I don't see any issues here, I can even save `tester@tester.tester`. And also looking at the regex, I see no reason why it shouldn't work, it simply says "at least two characters after the dot".

**Comment by andrewminton** [comment]
Ok, maybe it's the age of the Symphony build and the character preferences.. it's Symphony 2.0.6. Wondering if there was a change in the regex since then.. closing as it's deemed not a Symphony specific issue per se.

**Comment by michael-e** [comment]
You can simply throw the current email regex into your validation field. Here it is:

    /^\w(?:\.?[\w%+-]+)*@\w(?:[\w-]*\.)+?[a-z]{2,}$/i

**Comment by andrewminton** [comment]
Thanks @michael-e  :)
