### ISSUE TITLE
Admin ajax post - 403 Forbidden

### ISSUE THREAD

**Issue by axpro** [symphonycms/symphony-2#2460]
When importing a CSV using "Import/Export CSV" in 2.6.2 I get a 403 Forbidden in the front-end and the following in logs/main:

    UNKNOWN: SymphonyErrorPage 0 - Request was rejected for having an invalid cross-site request forgery token.<br/><br/>Please go back and try again. on line 181 of symphony/lib/toolkit/class.xsrf.php

I think it worked till this commit: https://github.com/symphonycms/symphony-2/commit/1e41aab65c9631688ce78f1830c851db856462b2

Unfortunately, being mostly a frontend guy, I can't debug further and I don't know if it's a Symphony issue or an extension issue.

Thanks

**Comment by nitriques** [comment]
I assume you are using this https://github.com/TwistedInteractive/importcsv ?

The bug's in that project...

If you would like to fix it, check this similar bug in another extension: https://github.com/symphonists/tracker/pull/30

**Comment by axpro** [comment]
Thanks :+1:

**Comment by nitriques** [comment]
My pleasure!
