### ISSUE TITLE
MySQL::tableExists does not work

### ISSUE THREAD

**Issue by psychoticmeow** [symphonycms/symphony-2#2462]
I've not had a chance to debug this, but it isn't returning the correct results.

```
    public function tableExists($table)
    {
        $results = $this->fetch('SHOW TABLES LIKE ?', null, array(), array(

            $table
        ));

        return (is_array($results) && !empty($results));
    }
```

**Comment by nitriques** [comment]
What result is it returning ?

**Comment by brendo** [comment]
Need more information, it's returning expected results for existing tables and non existing tables for me (Symphony 2.6.2)

**Comment by nitriques** [comment]
Yup I can confirm that it works.
