### ISSUE TITLE
A zero value shown as 'None' in publish index tables

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2463]
A have a value of `0` in a `Number Field`, and the publish index table shows as `None` instead of the value `0`. The same goes for the standard `Text Field`.

I expected to see a `0` in the overview, `cause thats an actual value amongst others.

Sym 2.6.2

**Edit:** Changed the formerly used "empty" term to the correct one `None`.

**Comment by nitriques** [comment]
I think it's my fault. I like `empty()` too much.

Does it fixes both problems to change [this line](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.field.php#L1001) with

```php
if (General::strlen($value) > 0 && $defaultValue != null) {
```

**Comment by michael-e** [comment]
I can not replicate this on 2.6.2. My publish index table shows `None` if there is no value, which is OK for Text Fields IMHO.

Regarding the Number Field, of course `0` should be shown as `0`.

**Comment by nitriques** [comment]
@michael-e Yes but 0 in a text field should still display 0, not none.

**Comment by michael-e** [comment]
Ah, sorry.

**Comment by nitriques** [comment]
No prob.

**Comment by jurajkapsz** [comment]
> shows `None` if ...

Sorry, yes, `None` it is. I quickly translated my slovak translation to a term of "empty" to describe the default value label used for no values.

> if (General::strlen($value) > 0 && $defaultValue != null) { ...

This change actually renders all values as `None`.

**Comment by nitriques** [comment]
> This change actually renders all values as None.

Ahahaha. Sorry, it should be:

```php
if (General::strlen($value) == 0 && $defaultValue != null) {
```

**Comment by jurajkapsz** [comment]
> Ahahaha. Sorry, it should be ...

Ok, that works fine :) Great, thanks :)

**Comment by jurajkapsz** [comment]
Maybe this could be added to the `2.6.3` release?

**Comment by nitriques** [comment]
Yes, I'll send a PR right now.

**Comment by nitriques** [comment]
Done.

**Comment by jurajkapsz** [comment]
Great, thanks!

**Comment by jurajkapsz** [comment]
Is this included for 2.6.3 ? I don't see it in the milestone. Probably it is, but visually not assigned ... sorry, just wanna check.

**Comment by brendo** [comment]
Yep it will be :)

**Comment by jurajkapsz** [comment]
Cool, thanks :)
