### ISSUE TITLE
Publish Filtering change

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2467]
We have had 3 clients now complain that the filtering system always defaults to `is` rather than `contains`.

I have tried to figure out how to change it, but failed miserably. Can this be done?

**Comment by nitriques** [comment]
Did you tried changing the order of this array ?
https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/lib/toolkit/class.field.php#L1185-L1208

**Comment by brendo** [comment]
Field's provide the filtering options, so the order comes from the Field. Changing the array @nitriques has linked to will do the job... but it's per *field*, so it can't be guaranteed that `contains` will be first for every single field.

**Comment by designermonkey** [comment]
Thanks for the clarification guys.
