### ISSUE TITLE
Datasources on Windows error on creation

### ISSUE THREAD

**Issue by jmoont** [symphonycms/symphony-2#2468]
I get the following when creating a datasource:

`<?phpclass datasourcefooter extends SectionDatasource`

The space between the <?php and the start of the class is stripped.
I believe this is caused by line 1405 of content.blueprintsdatasources.php

#2259 has looked into this before but I don't believe the solution is working.
I am using Symphony 2.6.2 on Windows 8.1 and PHP 5.5.12

**Comment by brendo** [comment]
Calling on any Windows Symphony users to help test this one, I don't have a Windows environment handy!

**Comment by nitriques** [comment]
Me neither... maybe @andrewminton does ?

**Comment by andrewminton** [comment]
I only encountered this issue when using XAMP on local setups.. WAMP was fine.. so there maybe more to it than Symphony install itself.

**Comment by nitriques** [comment]
@jmoont Can you confirm that your git setup translates LF into CRLF ?

**Comment by jmoont** [comment]
ok - that sounds like it could be the problem - i will look into it and let you know.
J

**Comment by nitriques** [comment]
Great thanks.

**Comment by jmoont** [comment]
My git setup is correctly translating LF into CRLF - sorry that wasn't the issue.

**Comment by jmoont** [comment]
would it not make more sense to write the replacement on line 1405 as
`preg_replace(array('/<!--[\w ]++-->/', '/(\t+[\r\n]){2,}/', '/(\r\n){2,}/'), '$1', $dsShell);`

so it replaces multiple line breaks with a single one

**Comment by nitriques** [comment]
Please check this: https://github.com/symphonycms/symphony-2/issues/2259

Wouldn't it be a regression ?

**Comment by jmoont** [comment]
i already referenced that in my original post. i'm not suggesting removing the regexp just adding a replacement instead of a blank string.

**Comment by nitriques** [comment]
Hum, sorry about that. So the only change would be to add the $1 replacement ?

**Comment by jmoont** [comment]
yes - have you checked on a Linux OS what that change does?

**Comment by nitriques** [comment]
@jmoont Yup, does not change a thing. I'll send a PR. Thanks!

**Comment by brendo** [comment]
Thanks!
