### ISSUE TITLE
When editing entries, Symphony will have time slots without data

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2472]
When editing existing entries (see `EntryManager::edit`), Symphony will iterate over all fields, delete existing data first, then insert a new row for the field's data. So there will always be a small time slot without data.

This caused massive headaches for me the other day, because I experienced simultaneous processes which edited entry data, but every one of them relied on data being available. My solution was to stop using `EntryManager::edit`. Instead I added an additional unique key to the table and updated data using `Symphony::Database()->insert($data, 'tbl_entries_data_' . $field_id, true);` (where `true` will make Symphony add `ON DUPLICATE KEY UPDATE` to the query).

Still, after having applied this hackish fix, I asked myself: Why doesn't Symphony lock the table?

Like so, basically:
- `LOCK TABLES tbl_entries_data_{$field_id} WRITE`
- delete data
- insert data
- `UNLOCK TABLES`

Is there any reason against this?

**Comment by brendo** [comment]
Interesting. I can probably shed some light on this.

The reason why `INSERT ON DUPLICATE KEY UPDATE` is not the preferred manner for inserting data is that it does not handle when any field schema changes, or partial information. Deleting all data first ensures that there is a clean slate for the entry.

> Why doesn't Symphony lock the table?

Probably because the use case was considered an edge case. For the majority of Symphony sites, having no data for a second or two is unlikely to result in any problems (we could be very wrong here).

I'm curious, are you able to try converting the affected field tables from `MyISAM` to `InnoDB` and seeing how the system responds? `InnoDB` has better locking support out of the box, so I'd be interested in seeing how it handles the same situation without us having to be deliberate (could be the same, just curiosity).

**Comment by michael-e** [comment]
> The reason why `INSERT ON DUPLICATE KEY UPDATE` is not the preferred manner for inserting data is that it does not handle when any field schema changes, or partial information. Deleting all data first ensures that there is a clean slate for the entry.

Understood and agreed.

> For the majority of Symphony sites, having no data for a second or two is unlikely to result in any problems

I also agree with that, simply because I have never noticed the behaviour before. (The time slot between deleting the database row and writing the row is probably much smaller, far less than 0.01s.)

But if it happens, you may not notice it easily, because it doesn't mean having no data at all. The process is repeated field by field, so at certain points in time there will be no data for one of the fields. So if you lose data, it will be **per field**.

This is how it can happen, looking at two "edit" processes and one field only. Each process attempts to read the entry's data, then delete and write DB rows for each field:

* Process 1 reads entry data
* Process 1 deletes the DB row for Field 1
* Process 2 reads entry data (Field 1 is empty at this point!)
* Process 1 writes the row for Field 1 (Field 1 has correct data)
* Process 2 deletes the DB row for Field 1
* Process 2 writes the row for Field 1 (Field 1 is empty!)

> `InnoDB` has better locking support

But currently Symphony doesn't lock at all! We just delete a row, then add a row, and the database will allow read operations in between, no matter which storage engine is used. I don't think that there could be any difference with `InnoDB`.

Testing this systematically is a bit tricky. You have to hit the time slots. But, well, it might be possible to write a CLI script which forks some (parallel) edit processes nearly simultaneously. I might increase the number of processes until data loss happens likely. (I must be a bit careful because each of the forked processes will have a complete Symphony object, so there might be RAM issues.) I will try.

**Comment by jensscherbl** [comment]
#2434

**Comment by michael-e** [comment]
That PDO stuff is over my head. Anyway, I am talking about this part of the `EntryManager` class:

```php
// Iterate over all data for this entry, deleting existing data first
// then inserting a new row for the data
foreach ($entry->getData() as $field_id => $field) {
    if (empty($field_id)) {
        continue;
    }

    try {
        Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
            `entry_id` = %d", $entry->get('id')
        ));
    } catch (Exception $e) {
        // Discard?
    }

    if (!is_array($field) || empty($field)) {
        continue;
    }

    $data = array(
        'entry_id' => $entry->get('id')
    );

    $fields = array();

    foreach ($field as $key => $value) {
        if (is_array($value)) {
            foreach ($value as $ii => $v) {
                $fields[$ii][$key] = $v;
            }
        } else {
            $fields[max(0, count($fields) - 1)][$key] = $value;
        }
    }

    foreach ($fields as $index => $field_data) {
        $fields[$index] = array_merge($data, $field_data);
    }

    Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
}
```

As you see, there is `delete`, then `insert`. In between, the database has no data for the field.

Is this behaviour changed by the commit you referenced?

**Comment by michael-e** [comment]
I verified two things:

1. I __can__ enforce issues using background scripts as mentioned above. But the issues depend on how your script tries to save the entry. I will explain in more detail below.
2. I __can__ solve these issues by locking the table at the beginning and unlocking it at the end. However, I am not a specialist in MySQL or MySQL sessions, so don't take my word for this trick having no side effects.

Using the code from `EntryManager::edit` (as posted in my latest comment above), and running several processes in parallel, something unexpected may happen: You may get a lot of identical rows in your database table, especially with SBL fields. Here's an example:

<img width="657" alt="bildschirmfoto 2015-07-29 um 14 15 07" src="https://cloud.githubusercontent.com/assets/40072/8962608/cc30c898-361b-11e5-9e41-e4ff3c826825.png">

This is due to the fact that all the parallel processes will attempt to delete the row, and all these processes will save a new row (_assuming_ that the old one has been deleted)—the outcome depends on the "timing", obviously.

In my case, however, there was custom code in my event to manipulate the value of a field. Simplified, I did something like the following:

```php
$entry_data = $entry->getData();
$new_field_data = some_array_manipulation($entry_data[$field_that_will_have_issues]);
$entry->setData($field_that_will_have_issues, $new_field_data);
// ...
// ...
// Here comes the relevant part from `EntryManager::edit`
foreach ($entry->getData() as $field_id => $field) {
// …
```

The difference: Now the data for a field will be set (but empty) if no row has been found in the database. In this case the "timing issue of parallel edit processes" may result in actual data loss.

I feel that we should really fix this (even in the 2.6 branch), so I would like to have some ideas/comments on the table locking. In my tests I added it to `EntryManager::edit` like so:

```php
// Code taken from `EntryManager::edit`
foreach ($entry->getData() as $field_id => $field) {
    if (empty($field_id)) {
        continue;
    }

    try {
        Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
        Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
            `entry_id` = %d", $entry->get('id')
        ));
    } catch (Exception $e) {
        // Discard?
    }

    if (!is_array($field) || empty($field)) {
        continue;
    }

    $data = array(
        'entry_id' => $entry->get('id')
    );

    $fields = array();

    foreach ($field as $key => $value) {
        if (is_array($value)) {
            foreach ($value as $ii => $v) {
                $fields[$ii][$key] = $v;
            }
        } else {
            $fields[max(0, count($fields) - 1)][$key] = $value;
        }
    }

    foreach ($fields as $index => $field_data) {
        $fields[$index] = array_merge($data, $field_data);
    }

    Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
    Symphony::Database()->query('UNLOCK TABLES');
}
```


Does anybody have an idea about potential side effects of table locking?

**Comment by michael-e** [comment]
Ooops, is there is a dangerous mistake in my  code above? Could it be that the table stays locked under certain circumstances?

**Comment by michael-e** [comment]
This might be better:

```php
foreach ($entry->getData() as $field_id => $field) {
    if (empty($field_id)) {
        continue;
    }

    try {
        Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
        Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
            `entry_id` = %d", $entry->get('id')
        ));
    } catch (Exception $e) {
        // Discard?
    }

    if (!is_array($field) || empty($field)) {
        Symphony::Database()->query('UNLOCK TABLES');
        continue;
    }

    $data = array(
        'entry_id' => $entry->get('id')
    );

    $fields = array();

    foreach ($field as $key => $value) {
        if (is_array($value)) {
            foreach ($value as $ii => $v) {
                $fields[$ii][$key] = $v;
            }
        } else {
            $fields[max(0, count($fields) - 1)][$key] = $value;
        }
    }

    foreach ($fields as $index => $field_data) {
        $fields[$index] = array_merge($data, $field_data);
    }

    Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
    Symphony::Database()->query('UNLOCK TABLES');
}
```

**Comment by michael-e** [comment]
@brendo:

> I'm curious, are you able to try converting the affected field tables from MyISAM to InnoDB and seeing how the system responds?

I did, and it doesn't make any difference (confirming the assumption in my first response)

In short, I think:

* Either we use InnoDB and transactions (in the Integration branch, which will become Symphony 3, or Symphony 4 — I prefer the latter version number, BTW)
* or we lock the tables (in Symphony 2.x)

**Comment by nitriques** [comment]
Locking the table is BAD!!! You are blocking ALL entries.

You absolutely need to use transaction with locking, or else you might end up with slowness instead of "no data for less than 0.01s"

So the only option is "Either we use InnoDB and transactions", without locking (cause the tx already protects us by allowing un-comiited reads)

**Comment by michael-e** [comment]
In my current project I already had two severe bugs which, in the end, were caused by this design flaw.

Changing the storage engine and implementing transactions is not an option for Symphony 2.x., IMHO. So you suggest that we don't solve this for Symphony 2.6?

If @brendo thinks the same, I will probably implement table locking just on my side, in my project. I really don't want to be hit by this again. If you are dealing with a lot of data and more or less simultaneous processes, this flaw is no fun.

**Comment by nitriques** [comment]
> So you suggest that we don't solve this for Symphony 2.6?

I think we can't solve it. Any "solution" would cause undesirable side effects.

>  I will probably implement table locking just on my side, in my project. I really don't want to be hit by this again.

Please report any bugs you encounter as this makes me really curious.

>  If you are dealing with a lot of data and more or less simultaneous processes, this flaw is no fun.

I totally understand that and this design flaw has been making me nervous since day one. But I was not (and still not) able to figure out how to solve it without transactions.

**Comment by jonmifsud** [comment]
Agree it's a flaw but table locking could block high volume sites esp if
there are a lot of writes.

**Comment by michael-e** [comment]
I can (and will) do some benchmarks, for example for re-saving entries using a background process. But can you tell me, apart from being potentially slow, do you expect other potential side effects for the [implementation I posted above](https://github.com/symphonycms/symphony-2/issues/2472#issuecomment-126009747)?

**Comment by nitriques** [comment]
> Agree it's a flaw but table locking could block high volume sites esp

Yup. Locking the whole table is bad for high volume sites.

And correct me if I am wrong, but simply locking locks both reads AND writes.

**Comment by michael-e** [comment]
> And correct me if I am wrong, but simply locking locks both reads AND writes.

Given the situations I experienced, I need exactly this, so I suggested `LOCK TABLES table_name WRITE`. According to the manual this prevents write and read operations by other sessions:

> Only the session that holds the lock can access the table. No other session can access it until the lock is released.
> –https://dev.mysql.com/doc/refman/5.6/en/lock-tables.html

**Comment by nitriques** [comment]
Yeah this can't be a solution for high volume sites.

**Comment by michael-e** [comment]
As I said, I will try and do some benchmarking in order to find out how slow the table locks are. But before I try, please tell me: Do you expect other side effects? (Apart from the risk that a table may stay locked if a process dies before being finished...)

**Comment by jonmifsud** [comment]
I don't think so, my guess is that tables would be locked/released one at a
time, so I don't think you'll hit a deadlock where multiple tables are
locked by the same user. (might be wrong) Re high volume sites if you have
datasource caching in addition to this it might actually be able to handle
it. Reason being if the cache doesn't invalidate at least till all the
entry is cleared up there wouldn't be any locked tables. If you hit a block
might be worth trying it out.

**Comment by michael-e** [comment]
OK, I think I will give it a try. The system is in production, with more than 100 users (Members using "frontend editing") and a lot of background jobs etc., so it will be a good test. And if things break, I will definitely get noticed. :-))

**Comment by jonmifsud** [comment]
Yeah I guess that scenario would be a good test especially if you have
multiple users saving at the same time

**Comment by michael-e** [comment]
FYI: I have benchmarked editing of 1000 entries by re-saving them. These entries do have some fields, so it takes some time:

* 52 seconds using `EntryManager::edit` "as it is"
* 60 seconds locking the table for each field (as posted above)

In other words: Locking the table for each field before deleting and re-inserting the row(s) means an increase by 15 percent. That's not a high price to pay. Just saying…

**Comment by michael-e** [comment]
(Of course, in my test, in had to pull the entries from the database as well—paginated, 25 at a time—, so the duration increase for the editing process alone will be higher than 15 percent.)

**Comment by michael-e** [comment]
I should add that even while the background process is re-saving the entries, I don't feel any issues in the frontend displaying the same entries. So although most of the time one of the section's tables will be locked, MySQL can handle the (waiting) READ queries well, and process them in time slots between locks.

**Comment by michael-e** [comment]
Testing now in a real-world-scenario, i.e. "production" :-)

Just out of curiosity, isn't this issue a so-called Race Condition?

**Comment by jonmifsud** [comment]
Yes exactly, it would be a race condition. hopefully you don't encounter
any.

**Comment by michael-e** [comment]
I have! That's why I started this thread. :-)

**Comment by kmeinke** [comment]
one transaction / lock free solution could be a (limited) multi version data model.

the new values would be inserted into the field tables - using some kind of version number to keep em separate from the current version. 

the current version per entry per field could be max(version). that is simple but would mean new values go life as soon they are written - may be undesirable / inconsistent

an alternative could be to update a current_version column in the entry table as a final step - to activate all new fields at once. 

tho this means to always update every field of an entry - or find some clever way to encode the version per field 

one way to encode a version per field would be a bitmask with one bit for each field - allowing 2 versions - fully satisfying the use case. 

the old version can be deleted - or kept around for a rollback feature. I would avoid to keep to much versions around in this model - performance will suffer hard soon, because all the old data is in the way on every fracking read.

version ID is a great candidate for caching - to offset a performance hit due to the need to query the current version - tho that may not even necessary.

**Comment by kmeinke** [comment]
oh... to soften the compatibility hit - perhaps it's even possible to encode the version in the entry_id it self - most current stuff should handle it as a black box without future function and would continue to work the an id like 35245v1

would't work with the bitmask idea tho - cause this idea modifies the way the where clause is written.

**Comment by michael-e** [comment]
InnoDB and transactions are planned for the next major version of Symphony. But for Symphony 2.x implementing such a fundamental change is too dangerous IMHO.

So I was looking for a simple solution, and that is table locks. Still I don't understand why they should be so bad in this scenario. If the decrease in speed was a true issue (because your website is so write-intensive), you would surely have much bigger issues without threse locks.

**Comment by kmeinke** [comment]
I dont think its "so" bad. I think as a simple solution its the most cheap. :) 

btw.. i think your code snippet shown 6 days ago - risks to leak the lock. every single line that can throw an exception must be catched - you must guarantee to UNLOCK in all posible cases (one reason this kind of stuff is considered 'bad' ;)

	try {
		foreach ($entry->getData() as $field_id => $field) {
			Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
			//all the deleting, inserting and stuff...
		}
	} finaly {
		Symphony::Database()->query('UNLOCK TABLES');
	}

**Comment by michael-e** [comment]
Thanks for pointing that out, I will try and make this more bullet-proof. However, I have the feeling that @nitriques and @brendo consider this change too dangerous and prefer to keep the race condition.

**Comment by michael-e** [comment]
FYI: The following is the `EntryManager::edit`function that I am testing (in production) now. For every field, all the hard work is wrapped in the `try` statement.

I am still unsure how to deal with exceptions. At the moment I am just pushing them to the log, but maybe they should also be thrown to the frontend? Suggestions very welcome.

```php
public static function edit(Entry $entry)
{
    // Update modification date.
    Symphony::Database()->update(
        array(
            'modification_date' => $entry->get('modification_date'),
            'modification_date_gmt' => $entry->get('modification_date_gmt')
        ),
        'tbl_entries',
        sprintf(' `id` = %d', $entry->get('id'))
    );

    // Iterate over all data for this entry, deleting existing data first
    // then inserting a new row for the data
    foreach ($entry->getData() as $field_id => $field) {
        if (empty($field_id)) {
            continue;
        }

        try {
            Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
            Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
                `entry_id` = %d", $entry->get('id')
            ));

            if (!is_array($field) || empty($field)) {
                Symphony::Database()->query('UNLOCK TABLES');
                continue;
            }

            $data = array(
                'entry_id' => $entry->get('id')
            );

            $fields = array();

            foreach ($field as $key => $value) {
                if (is_array($value)) {
                    foreach ($value as $ii => $v) {
                        $fields[$ii][$key] = $v;
                    }
                } else {
                    $fields[max(0, count($fields) - 1)][$key] = $value;
                }
            }

            foreach ($fields as $index => $field_data) {
                $fields[$index] = array_merge($data, $field_data);
            }

            Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
        } catch (Exception $e) {
            Symphony::Database()->query('UNLOCK TABLES');
            Symphony::Log()->pushExceptionToLog($e, true);
        }

        Symphony::Database()->query('UNLOCK TABLES');
    }

    return true;
}
```

**Comment by nitriques** [comment]
@michael-e 

What about this (no tested). I'd rather have the unlock in a finally block. For really safe calls, you should even add a try catch in the catch and in the finally. Exceptions are crazy.

```php
public static function edit(Entry $entry)
{
    // Update modification date.
    Symphony::Database()->update(
        array(
            'modification_date' => $entry->get('modification_date'),
            'modification_date_gmt' => $entry->get('modification_date_gmt')
        ),
        'tbl_entries',
        sprintf(' `id` = %d', $entry->get('id'))
    );

    // Iterate over all data for this entry, deleting existing data first
    // then inserting a new row for the data
    foreach ($entry->getData() as $field_id => $field) {
        if (empty($field_id)) {
            continue;
        }
        $didLock = false;
        try {
            $didLock = Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
            Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
                `entry_id` = %d", $entry->get('id')
            ));

            if (!is_array($field) || empty($field)) {
                Symphony::Database()->query('UNLOCK TABLES');
                continue;
            }

            $data = array(
                'entry_id' => $entry->get('id')
            );

            $fields = array();

            foreach ($field as $key => $value) {
                if (is_array($value)) {
                    foreach ($value as $ii => $v) {
                        $fields[$ii][$key] = $v;
                    }
                } else {
                    $fields[max(0, count($fields) - 1)][$key] = $value;
                }
            }

            foreach ($fields as $index => $field_data) {
                $fields[$index] = array_merge($data, $field_data);
            }

            Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
        } catch (Exception $e) {
            Symphony::Log()->pushExceptionToLog($e, true);
        } finally {
            if ($didLock) {
                Symphony::Database()->query('UNLOCK TABLES');
            }
        }
    }

    return true;
}
```

**Comment by michael-e** [comment]
I like the `$didLock` stuff (probably it should be written `$did_lock` in Symphony). But using `finally` makes the script [PHP 5.5+ only](http://php.net/manual/en/language.exceptions.php), unfortunately. Lifting the requirement that much with a small core hack seems a bit strange to me.

**Comment by nitriques** [comment]
> makes the script PHP 5.5+ only,

WTF !!!!

> Lifting the requirement that much with a small core hack seems a bit strange to me.

Yeah. Just do not use it then. In theory, it does not have any purpose: code AFTER the try catch would run anyhow. But since exception handling is so hard, finally has some purpose.

**Comment by michael-e** [comment]
Thanks for your help, @nitriques!

**Comment by nitriques** [comment]
My pleasure.

**Comment by michael-e** [comment]
FYI: My current version is:

```php
public static function edit(Entry $entry)
{
    // Update modification date.
    Symphony::Database()->update(
        array(
            'modification_date' => $entry->get('modification_date'),
            'modification_date_gmt' => $entry->get('modification_date_gmt')
        ),
        'tbl_entries',
        sprintf(' `id` = %d', $entry->get('id'))
    );

    // Iterate over all data for this entry, deleting existing data first
    // then inserting a new row for the data
    foreach ($entry->getData() as $field_id => $field) {
        if (empty($field_id)) {
            continue;
        }

        $didLock = false;
        try {
            $didLock = Symphony::Database()->query('LOCK TABLES tbl_entries_data_' . $field_id . ' WRITE');
            Symphony::Database()->delete('tbl_entries_data_' . $field_id, sprintf("
                `entry_id` = %d", $entry->get('id')
            ));

            if (!is_array($field) || empty($field)) {
                if ($didLock) {
                    Symphony::Database()->query('UNLOCK TABLES');
                }
                continue;
            }

            $data = array(
                'entry_id' => $entry->get('id')
            );

            $fields = array();

            foreach ($field as $key => $value) {
                if (is_array($value)) {
                    foreach ($value as $ii => $v) {
                        $fields[$ii][$key] = $v;
                    }
                } else {
                    $fields[max(0, count($fields) - 1)][$key] = $value;
                }
            }

            foreach ($fields as $index => $field_data) {
                $fields[$index] = array_merge($data, $field_data);
            }

            Symphony::Database()->insert($fields, 'tbl_entries_data_' . $field_id);
        } catch (Exception $e) {
            Symphony::Log()->pushExceptionToLog($e, true);
        }

        if ($didLock) {
            Symphony::Database()->query('UNLOCK TABLES');
        }
    }

    return true;
}
```

**Comment by nitriques** [comment]
thanks for sharing @michael-e 

Did you ran in any problems yet ?

**Comment by michael-e** [comment]
My tests looked good, and now it's in production. I guess the client will tell me when it breaks. :-))

**Comment by nitriques** [comment]
Well, check your logs ! :P (I've made this if you're lazy: http://symphonyextensions.com/extensions/system_log_link/)

**Comment by michael-e** [comment]
I would probably find the log file, but: What should I search for? (If the table remains locked, I will get noticed anyway.)

**Comment by nitriques** [comment]
Any exception that can occur.
The catch clause should log it `Symphony::Log()->pushExceptionToLog($e, true);`

Check for `User Notice: (.+)Exception`

> If the table remains locked, I will get noticed anyway.

Yeah that's true...

**Comment by michael-e** [comment]
Thanks!

**Comment by michael-e** [comment]
FYI: I have been using the above table locking in a production system since september without issues. It's not my biggest system, but after all it has more than 100 authors working on 100.000 entries (think of it as some kind of web-based address database).

Now I will apply the patch to my "big system" and report back.

**Comment by jonmifsud** [comment]
awesome looking forward to results.

**Comment by michael-e** [comment]
Hopefully results will be NULL. :-))

**Comment by nitriques** [comment]
Can't wait for the results!

But hopefully we would be able to release the PDO implementation, which has transactions ...

**Comment by michael-e** [comment]
Locking tables during delete/insert might be interesting for 2.7, though.

**Comment by nitriques** [comment]
That's true.

**Comment by michael-e** [comment]
No known accidents until now. (I would get a call, that's for sure!)

Still we should let this run in my big system another 2 weeks or so, just to be sure.

**Comment by nitriques** [comment]
Perfect!

**Comment by michael-e** [comment]
Up to now I haven't experienced any problems with [the above code](https://github.com/symphonycms/symphony-2/issues/2472#issuecomment-143007830) running in my two biggest Symphony installations.

**Comment by nitriques** [comment]
That's great news. Wanna prepare a PR (or is there one already I can't seem to find ?)

**Comment by michael-e** [comment]
I can send a PR if you like!

**Comment by nitriques** [comment]
Yes please! Thanks again!
