### ISSUE TITLE
x-frame-options & access-control-allow-origin

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2480]
Is it really such a good idea to set [`x-frame-options` and `access-control-allow-origin`][1] headers by default?

From my understanding, this changes the default browser behaviour, and things like loading a Symphony page into an `iframe` on another site wouldn't work as expected.

And if you really want to keep it, could it at least be set before the `FrontendPreRenderHeaders`delegate so it can be removed by an extension?

In my opinion, this is another situation where Symphony just makes an assumption what might be best for the developer, and makes it hard to get rid of the forced core behaviour.

[1]: https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.frontendpage.php#L240

**Comment by nitriques** [comment]
> In my opinion, this is another situation where Symphony just makes an assumption what might be best for the developer

This IS what's best. But yeah, I would agree that an Extension should be able to remove them.

The Symphony philosophy to "never prevent devs from doing what they want" is important, but implementing best practices should also be our concern.

Making this extensible, but with good defaults, is the way to go IMHO.

**Comment by jensscherbl** [comment]
> This IS what's best.

That's just your opinion... ;)

> but implementing best practices should also be our concern

Changing default browser behaviour isn't best practice, in my opinion.

> but with good defaults

I'd say it's the concern of the browser vendors to decide what the default behaviour should be.

**Comment by nitriques** [comment]
> That's just your opinion... ;

No, it's an established best practice ;) But I understand what you mean.

> Changing default browser behaviour isn't best practice, in my opinion.

If it's for security, yes it is. Just like HSTS (which change the browser default by enforcing https)

> I'd say it's the concern of the browser vendors to decide what the default behaviour should be.

I do not think this is browser vendor related. It's more of an app thing. 

That being said, I totally understand you concern and I would like to have a way to be able to customize the "default" header. But I think our current defaults are good.

**Comment by michael-e** [comment]
> things like loading a Symphony page into an `iframe` on another site wouldn't work as expected

This is the reason why it has been implemented. And I don't think that there is an assumption about what's best for the developer. The question is about security, in other words: What's best for users/visitors/authors? In my eyes these headers are indeed best practice nowadays.

So I agree with @nitriques: Make it easily removable (what about a config option?), but keep the current "best practice headers" as the default.

**Comment by nitriques** [comment]
> what about a config option?

Could be a nice place to set the default. But allowing extension to do logic before adding/removing headers is more flexible.

**Comment by jensscherbl** [comment]
> what about a config option?

Yet another config option, are you serious? Sorry ;)

No, we don't need a config option. Just make it consistent with the other "default" headers, so they can be easily removed and overwritten in a predictable and consistent manner...

    $this->addHeaderToPage('X-Frame-Options', 'SAMEORIGIN');
    $this->addHeaderToPage('Access-Control-Allow-Origin', URL);

    /**
     * This is just prior to the page headers being rendered, and is suitable for changing them
     * @delegate FrontendPreRenderHeaders
     * @param string $context
     * '/frontend/'
     */
    Symphony::ExtensionManager()->notifyMembers('FrontendPreRenderHeaders', '/frontend/');

I really don't care that deeply about this specific thing. It's just yet another instance where Symphony just does something, and if I don't want it, I have to work around it or remove it.

What set Symphony apart from other systems and made it so great for me was that it usually did things the other way around.

Don't make assumptions, extend where appropriate.

Nowadays, I have to write more and more extensions just to revert forced core behaviour.

**Comment by nitriques** [comment]
@jensscherbl Did you tried to remove them via .htaccess ?

**Comment by jensscherbl** [comment]
> Did you tried to remove them via .htaccess ?

I just removed them from the core.

**Comment by nitriques** [comment]
Ok. I could argue that this could be placed in the .htaccess too (instead of in the php itself).

> Nowadays, I have to write more and more extensions just to revert forced core behaviour.

The other way around exists too. Look at anti_brute_force. Would you want all of this things to go into the "hardened security" extension ?

It's a matter of opt-in vs. opt-out, and this is always hard to get right, impossible to get it right for everybody's needs.

**Comment by jensscherbl** [comment]
> Did you tried to remove them via .htaccess ?

Right thing would be to *set* them via `.htaccess`, not to *remove* them via `.htaccess`.

> Ok. I could argue that this could be placed in the .htaccess too (instead of in the php itself).

Agreed! ;)

> The other way around exists too. Look at anti_brute_force. Would you want all of this things to go into the "hardened security" extension ?

If it interferes with the frontend and there's a valid use case where it might not be the wanted or expected behaviour, yes.

> It's a matter of opt-in vs. opt-out, and this is always hard to get right, impossible to get it right for everybody's needs.

And that's why Symphony usually being *opt-in* instead of *opt-out* was so great.

**Comment by nitriques** [comment]
Ok, I totally understand your concern. I, too, prefer opt-in that opt-out: but it's an harder thing to do, code, test, ...

I'd like to see what @brendo thinks about this.

**Comment by jensscherbl** [comment]
> And I don't think that there is an assumption about what's best for the developer. The question is about security, in other words: What's best for users/visitors/authors?

But isn't this (what's best for users) the responsibility of developers? Just like enabling compression, redirecting to `https` or setting appropriate caching headers?

**Comment by michael-e** [comment]
OK then, but what about preventing SQL injection? Shouldn't this be the sole responsibility of the developer as well? :-)

What I want to say is: When it comes to security, it's really hard to draw the line, isn't it?

**Comment by jensscherbl** [comment]
> OK then, but what about preventing SQL injection? Shouldn't this be the sole responsibility of the developer as well?

Ironically, this actually *is* opt-in via [XSS Filter][1] and instead *should* be baked into each and every database query by default.

Difference is, can you think of a use case where you actually want to allow SQL injections?

[1]: https://github.com/symphonycms/xssfilter

**Comment by nitriques** [comment]
> What I want to say is: When it comes to security, it's really hard to draw the line, isn't it?

+1000000

> should be baked into each and every database query by default instead.

Can't do that. I need to be able to XSS myself sometimes.

> Difference is, can you think of a use case where you actually want to allow SQL injections?

No, and any solution that depends on it is profoundly flawed. Except if you are coding a SQL query runner/editor.

**Comment by michael-e** [comment]
Anyway: We all agree that it should be possible to remove those headers, which means you can use them or not. So should we spend our time in a discussion about the right default? When it comes to Symphony's philosophy, I like to rely on @allen's and @brendo's opinion.

**Comment by jensscherbl** [comment]
> So should we spend our time in a discussion about the right default?

I'm not the one who's opposing all my proposals... ;)

**Comment by michael-e** [comment]
You wouldn't wait for a comment, would you?

**Comment by munki-boy** [comment]
Can someone tell me how to change the access control via .htaccess?  I've been editing the core for months.  I only want my google maps from one site in an iframe on the other.  A little while back the different browsers didn't seem to support the x-frame-options properly so I had to disable the whole thing.

**Comment by nitriques** [comment]
Header always unset Access-Control-Allow-Origin

See http://httpd.apache.org/docs/2.2/mod/mod_headers.html

**Comment by nitriques** [comment]
Or to allow it

Header always set Access-Control-Allow-Origin "*"

**Comment by brendo** [comment]
This is the block that currently exists:

```php
            /**
             * This is just prior to the page headers being rendered, and is suitable for changing them
             * @delegate FrontendPreRenderHeaders
             * @param string $context
             * '/frontend/'
             */
            Symphony::ExtensionManager()->notifyMembers('FrontendPreRenderHeaders', '/frontend/');

            // If not set by another extension, lock down the frontend
            if(!array_key_exists('x-frame-options', $this->headers())) {
                $this->addHeaderToPage('X-Frame-Options', 'SAMEORIGIN');
            }
            if(!array_key_exists('access-control-allow-origin', $this->headers())) {
                $this->addHeaderToPage('Access-Control-Allow-Origin', URL);
            }
```

In other words, if you want to set them to something more specific for your application, then do so (such as @nitriques example which would work for an API). If you don't, we'll help lock down your installation. We were recommended to set these headers by a company that specialised in security penetration testing. Usually this would of been a one off change for that installation, potentially added by an extension, however I decided to bake it into the core by default to save others who go through the same security testing rigmarole the hassle. Usually, being more secure is appreciated then less secure, but I can understand where people are coming from.

We could go to something more like @jensscherbl has suggested by setting them by default and then you can remove them if that better suits. Either way you're going to have to listen for the same delegate, but the latter is probably easier for those who don't want to set a default at all, they just want the header removed.

**Comment by munki-boy** [comment]
@nitriques thanks :)

**Comment by jensscherbl** [comment]
> Either way you're going to have to listen for the same delegate, but the latter is probably easier for those who don't want to set a default at all, they just want the header removed.

Exactly. I think the [change I proposed][1] isn't even a breaking change. Should I open a pull request against `2.6.x`? It's not exactly a hotfix, but fixes the unexpected situation that you currently can't remove a header with `FrontendPage::removeHeaderFromPage` from the `FrontendPreRenderHeaders` delegate.

[1]: https://github.com/symphonycms/symphony-2/issues/2480#issuecomment-130358812

**Comment by brendo** [comment]
Sure

**Comment by nitriques** [comment]
Great!

**Comment by jensscherbl** [comment]
Thanks!
