### ISSUE TITLE
Prepopulate not working

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2483]
Is it just me, or does prepopulating a Select Box Link field not work? I'm trying to create a new entry from a filtered publish table, but the prepopulate parameter is set to `0` instead of the filter value.

I thought this was a core issue and not a Select Box Link issue, so sorry if I'm wrong here.

**Comment by jensscherbl** [comment]
Using Symphony `2.6.2` (current release version) by the way.

**Comment by twiro** [comment]
Afaik this has been fixed in integration and will be in the 2.6.3-release: https://github.com/symphonycms/symphony-2/issues/2408

But as this is a quite crucial bug it would be great to see the fix release soon...

**Comment by brendo** [comment]
Do you have steps to reproduce? I just tried the following which worked:

1. Go to Publish Index for Section A (Projects)
2. Click on the SBL column (Related Project Items) for first entry
3. Goes to a filtered view of Project Items. URL is `/publish/project-items/?filter[project]=38`
4. Click on 'Create New'. URL is `/publish/project-items/new/?prepopulate[28]=38` and I can confirm the SBL is prepopulated with the appropriate value

**Comment by jensscherbl** [comment]
> Afaik this has been fixed in integration and will be in the 2.6.3-release: #2408

Thanks, works in the `2.6.x`-branch. Sorry, didn't check. Never occurred to me something like this wouldn't be released as soon as possible...

> 2.6.3 will be released within a week. #2466 is the only blocker, and at this stage, we'll push on without it.

Great to hear. I think there's no need for patch releases to wait for other, unrelated issues to be fixed. There can always be a `2.6.4` and `2.6.5` release with additional fixes.

**Comment by nitriques** [comment]
> There can always be a 2.6.4 and 2.6.5 release with additional fixes.

Yup.
