### ISSUE TITLE
Redirect issue for datasources and events

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2485]
Getting a redirect error (browser error) for `../blueprints/datasources/` and `../blueprints/events/` when using the `2.6.x` branch. Works with `master`. Can someone confirm this?

**Comment by michael-e** [comment]
Yep, confirmed.

**Comment by jensscherbl** [comment]
It's caused by [this][1]. @nitriques @brendo 

[1]: https://github.com/symphonycms/symphony-2/pull/2470

**Comment by michael-e** [comment]
Hmmm, I still have the redirect error if I remove the placeholder. Are you really sure?

**Comment by michael-e** [comment]
(I mean the `$1` replacement, sorry for being unprecise.)

**Comment by jensscherbl** [comment]
Check out the commit before this commit and see if it works.

**Comment by michael-e** [comment]
It still works for me some commits later than the one you mentioned: e8e92cdaaafa788f1e223e15b5c1656b6c72b7cc

**Comment by michael-e** [comment]
If you use Safari, be careful with the caching. It may cache those redirects.

**Comment by jensscherbl** [comment]
Yeah, using Safari. So, is e8e92cd the breaking commit then?

**Comment by michael-e** [comment]
I haven't found it yet. It's hard for me to find the right one, because I always have to re-apply some commits on top — I hacked Symphony, a bit.

**Comment by jensscherbl** [comment]
Hold on, I'll do it (again) so you only have to confirm what I come up with.

**Comment by michael-e** [comment]
Found it! This is the commit which introduced the issue: 2ee98b19867be043b9275048c2e94ac728ac0bb0

**Comment by jensscherbl** [comment]
Yep, same here.

**Comment by michael-e** [comment]
Now all we have to do is find out why. You might be better than me with that.

**Comment by michael-e** [comment]
Comment out [this line](https://github.com/symphonycms/symphony-2/blob/2ee98b19867be043b9275048c2e94ac728ac0bb0/symphony/lib/toolkit/class.resourcespage.php#L42), and things start working again. Don't ask me why.

**Comment by jensscherbl** [comment]
You're always two steps ahead of me...

**Comment by michael-e** [comment]
Sometimes I am fast in finding things. Solving issues may be a different thing.

**Comment by jensscherbl** [comment]
I'll look into it.

**Comment by michael-e** [comment]
Thanks!

**Comment by michael-e** [comment]
Funny, this works:

```php
$sort = is_null($sort) ? null : General::sanitize($sort);
```

So we have a problem with `null` values. What the hell does `General::sanitize` return?.

**Comment by jensscherbl** [comment]
It has nothing to do with `General::sanitize`, it's because `$sort` (and therefore `null` sometimes) is passed by reference and you can't assign a new value to `null`.

**Comment by michael-e** [comment]
(BTW, sorry, my head didn't stop working fast enough. It was just a shot in the dark. I still appreciate if you can fix this properly.)

We might have more issues than this one. Can you check the whole commit systematically? And send a proper fix?

**Comment by jensscherbl** [comment]
Your fix actually is the proper fix, came up with the same thing. But I'm wondering why `$sort` is sanitised while `$order` and `$params` still isn't. Oversight? @brendo

**Comment by michael-e** [comment]
Thanks for explaining the issue. Should we fix it and open another issue for `$order` and `$params`? Or rahter wait for @brendo ?

**Comment by jensscherbl** [comment]
I'd say we fix and merge it so the `2.6.x` branch is in a working state again, but leave this open for @brendo to review.

**Comment by michael-e** [comment]
Can you send a pull request? And do you have pull permissions? (If not, I think that i can pull it.)

**Comment by jensscherbl** [comment]
Can do.

**Comment by michael-e** [comment]
Thanks.

**Comment by brendo** [comment]
Cheers for debugging and patching this guys! As you figured out, it was an oversight from me.

**Comment by michael-e** [comment]
During the discussion above @jensscherbl raised the question why `$sort` is sanitised while `$order` and `$params` still isn't. Oversight? @brendo

**Comment by brendo** [comment]
> During the discussion above @jensscherbl raised the question why $sort is sanitised while $order and $params still isn't. Oversight? @brendo

I just went through and have a quick review of where these arguments are being used.

*/system/extensions/*
- `$order` is not persisted to the database and instead used to do an internal PHP sort. A malicious value has no impact here as it's reduced to the PHP constants `SORT_ASC` or `SORT_DESC`
- `$params` is not used at all.

*/system/authors/*
- `$order` is again reduced to either `asc` or `desc`. A malicious value will result in a `desc` sort order
- `$params` is not used at all

*/system/publish/*
- `$order` is reduced to `RAND`, `ASC` or `DESC`. A malicious value will result in 'asc' sort order
- `$params` is used to hold the filters. These are built by the fields, the column name is sanitised, but the value is passed through to the field's `buildDSRetrievalSQL` function. All core fields use `Database->cleanValue` on the value.

*DS/Events*
- Similar to Extensions, the `$order` is reduced to `SORT_ASC` or `SORT_DESC`
- `$params` is not used.

**Comment by jensscherbl** [comment]
@brendo Good to know, thanks a lot for taking the time.

**Comment by nitriques** [comment]
Wow guys, thanks.
