### ISSUE TITLE
Database issues with number field

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2487]
`2.6.x` branch is giving me a **Fatal Database Error** when adding a new [Number field][1] to a section.

The message is `Table 'sym_entries_data_x' already exists`. Kinda weird because the statement starts with `CREATE TABLE IF NOT EXISTS`.

I'm posting this as a core issue instead of a Number field issue since the core is not supposed to break compatibility for minor and patch releases.

Any ideas?

[1]: https://github.com/symphonycms/numberfield

**Comment by michael-e** [comment]
I can not confirm that. I tried adding a Number field to a new section as well as adding one to an existing section. No errors. Can you indeed reproduce this issue? Can you post the steps?

**Comment by jensscherbl** [comment]
Thanks for checking. Will investigate further and report back later, off to the gym now.

**Comment by jensscherbl** [comment]
Nevermind. Not sure what caused the issue exactly, but had something to do with a wrong `.htaccess` file  in the wrong place. Sorry for the false alarm.

**Comment by michael-e** [comment]
No prob—glad that it was a false alarm!

**Comment by jensscherbl** [comment]
Issue popped up again today. So it had nothing to do with the wrong `.htaccess` after all. Instead, seems to be a [database issue][1]. Thought I share it here in case anyone else runs into this.

[1]: http://stackoverflow.com/questions/10538908/schrödingers-mysql-table-exists-yet-it-does-not

**Comment by michael-e** [comment]
How bad.

**Comment by nitriques** [comment]
Awful bug. Thanks for sharing @jensscherbl
