### ISSUE TITLE
Date field doesn't accept only a year

### ISSUE THREAD

**Issue by moretaste** [symphonycms/symphony-2#2491]
If you fill in only a year in the date field the result is:

```
<opleiding-1-van iso="1970-01-01T01:33:03+01:00" timestamp="1983" time="01:33" weekday="4" offset="+0100">1970-01-01</opleiding-1-van>
```

Only the timestamp accepts the input.

**Comment by nitriques** [comment]
Well, the date field is there to contain a valid date. A single digit is a valid timestamp, as you could see. I do not think there is a way to solve it.

You should year a numeric field instead.

**Comment by michael-e** [comment]
@moretaste posted the following example ouput:

    <opleiding-1-van iso="1970-01-01T01:33:03+01:00" timestamp="1983" time="01:33" weekday="4" offset="+0100">1970-01-01</opleiding-1-van>

I think: If the date doesn't have the intended year value, the timestamp shouldn't have it either. The values should be the same for all representations.

So we have a bug here. Should we open another issue for that?

**Comment by nitriques** [comment]
@michael-e entering a timestamp IS valid. 1983 is a valid timestamp.

**Comment by michael-e** [comment]
Ah, I see, the timestamp correlates to the iso date `1970-01-01T01:33:03+01:00`? Sorry, I had not seen that! (In other words: I thought that the output is not consistent, but it actually is.)

**Comment by moretaste** [comment]
I dont get this really the output still gives a date of 1970-01-01 in the back-end.

So I have a recruitment form where people can input there experience and education. They dont remember the day and month they start it, fills in only the year. The iso say ok +things but the data stored and called with the xsl:value-of shows 1970-01-01.

How can I explain the client that?

**Comment by nitriques** [comment]
Yes the output is ok. 1983 is interpreted as 1983 seconds after the epoch, which is `1970-01-01T01:33:03+01:00` :) 

@moretaste You could also use 1983-01-01

**Comment by nitriques** [comment]
> How can I explain the client that?

The data model is just wrong. You're using a date when the thing you need only a an integer. Numeric field would do the job.

> I dont get this really the output still gives a date of 1970-01-01 in the back-end.

1970-01-01 is the epoch. 1983 is interpreted as second from 1970-01-01 00:00:00

**Comment by michael-e** [comment]
> Numeric field would do the job.

Yep, or even a text input field with numeric validation.

**Comment by nitriques** [comment]
> Yep, or even a text input field with numeric validation.

This is what the numeric field is, more or less :P

**Comment by moretaste** [comment]
I understand the epoch but the backend shows 1970-01-01.

![image](https://cloud.githubusercontent.com/assets/857982/9531783/0fb7b3e4-4d08-11e5-9f25-89fc59063187.png)

I expected that the backend should translate it to an 'human-understandable' date

In this way I should told the client to type ?debug, find the date, go to an online converter and find it out

**Comment by michael-e** [comment]
> This is what the numeric field is, more or less :P

No, the Number Field is much better with numeric sorting! :-)

But in this case (always 4 digits, right?) alphabetic sorting can do it (if one needs sorting at all).

@moretaste: I would use an Input Field which requires 4 digits.

**Comment by moretaste** [comment]
In that case we could have only a text input field and some regexp magic. No need for other fields in that way. 

My only question is why the backend doesnt translate the epoch to human readable time?

**Comment by michael-e** [comment]
Well, it does! `1983` (epoch) is the same as `1970-01-01T01:33:03+01:00` (iso).


Do you have a Mac? In the terminal, type `date -r 1983`, and you will see!

**Comment by moretaste** [comment]
Check the screen shot. Symphony date field doesn't

I'm not a programmer so technically I understand and believe it's 200% ok. But the client (the noob) sees a date of 01/01/1970.

With my common sense the date field should say the date is invalid because I miss a day and a month or should convert the date to an human readable date.

**Comment by nitriques** [comment]
@moretaste Giving the user this ability would require to drop the timestamp support, which I am totally against. It's either one or the other, it can't be both.

> With my common sense the date field should say the date is invalid because I miss a day and a month or should convert the date to an human readable date.

It IS valid!!! Unless we drop the timestamp support...

:smile:

**Comment by nitriques** [comment]
> Do you have a Mac? In the terminal, type date -r 1983, and you will see!

Or any other unix and unix like (linux) 

> I expected that the backend should translate it to an 'human-understandable' date

That's exactly why you see 01/01/1970 01:33. That's the human readable version of the 1983 timestamp.

**Comment by moretaste** [comment]
![image](https://cloud.githubusercontent.com/assets/857982/9532475/2bfbb916-4d0c-11e5-87c2-5d9aa1cb73fd.png)

This is what the client sees. That is not valid for a client.

**Comment by moretaste** [comment]
Ok last try ... why if I input 01-01-1983 the backend shows 01/01/1983 00:00:00

If you can explain that difference I will stop whining about this and use for the rest only the text input and textarea field in case of more than 10 words.

**Comment by munki-boy** [comment]
@moretaste I think @nitriques is saying when you input just "1983" you are inputting 1983 seconds not 1983 years since A.D.

This is news to me but good to know.

**Comment by michael-e** [comment]
As @nitriques said above: PHP/Symphony will interprete `1983` as "seconds since", but it will interprete `01-01-1983` as `1983-01-01` (in yyyy-mm-dd format). The latter contains year, month and day. The first one contains just a number.

To me the question is not if we should drop timestamp support and try to interpret 4-digit numbers as years (which is what @moretaste expects). We would still have to add a default month and day in order to save a valid date, thus the result would still be wrong data from a technical point of view.

These are not "dates", technically, and there are probably many more:

* a year (as in your example)
* a birthday (because you would never "localize" it and start it at 10:00 p.m. just because you have moved.)

**Comment by munki-boy** [comment]
What about a format selector in the backend so it would or wouldn't expect different types?

**Comment by nitriques** [comment]
> These are not "dates", technically, and there are probably many more:

Totally.

> a birthday

:smile: We had fun on that one @michael-e remember ? Timezone info CAN'T be removed from a date, since the EPOCH is UTC.

**Comment by moretaste** [comment]
4 digits is not a valid date so the field should return an invalid value in that case.

> as "seconds since"
yup got that, my assumption was idd or the field accepts only the year or will gives an error for invalid input

**Comment by nitriques** [comment]
> will gives an error for invalid input

IT IS VALID !!!

Years are not dates. Months are not dates for the same reason. Would you also expect to get 12 = decembre ?

**Comment by moretaste** [comment]
Ok for programmers it is valid. But the casual visitor and client is not a programmer.

In that way the date field (excuse me for the words) sucks to be usable in the front-end.

Got the message now and forcing the visitor to input a complete date is the only way.

**Comment by munki-boy** [comment]
If it's just for storing some numbers in date format why use the date field.

**Comment by moretaste** [comment]
@munki-boy Well image fields are for images, text input for text and dates for uhm dates :-)

Validation of dates, some math for time between dates (experience 4 years for example). I'm not so robotic as a programmer is. It is technical true, but an average human dont't understand it. My assumption was idd as @michael-e says that the field should validate a year, a year and a month etc. or otherwise should reject input if it wasn't a full date.

The next time I probably would choose another approach, something with a regexp to check if the format at least got the desired structure of an human date.

**Comment by nitriques** [comment]
> Ok for programmers it is valid. But the casual visitor and client is not a programmer.

PHP code can't make that difference...

> Got the message now and forcing the visitor to input a complete date is the only way.

No, you could change your model (section) and create a simple php migration script if needed.

**Comment by munki-boy** [comment]
I understand it's to do with the words "date field" but in your math how would it be if my experience was from 31 dec 1983 so I just put 1983 then someone else put say 5th aug 1983 I would win with 8 months 5 days more experience, but it would be wrong, not because of the date field. 

It must be made to be accurate to work your way by having strict and known format.

**Comment by moretaste** [comment]
@nitriques Completely agree. It was my assumption that wasn't right. The website has to go live tomorrow and beside some content this was the last issue. 

For now a date picker should solve it. For the future I have to think sometimes more 'programmatically'

**Comment by nitriques** [comment]
> For now a date picker should solve it. 

Yup! But only the UI/UX part...

> For the future I have to think sometimes more 'programmatically'

I do not think it's a mater of programming: it's more a matter of data modeling, i.e. what your data type is, how should it be kept in the DB, what Math you will need to do on it.

**Comment by jensscherbl** [comment]
So, did I get this right, if someone enters an invalid date (like only the year), the input is interpreted as a unix timestamp? Now that's confusing. I kinda understand where the frustration comes from. Anything we can do about that for `3.0.0`?

**Comment by nitriques** [comment]
>  the input is interpreted as a unix timestamp?

Yes: it's ALWAYS a timestamp. https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/fields/field.date.php#L526

It's been that way for as long I can remember.

> Now that's confusing. I really understand where the frustration comes from. 

Me too.

> Anything we can do about it for 3.0.0?

I really think that a timestamp is a valid date, since all dates are actually timestamps.

But, UX wise, I also understand that no user ever predicts this, so it's broken.

`3.0.0` is allowed to break things, so I would not mind changing it. But right now, **this is not a bug, it's a feature**.

I would be open to discussed:

1. Adding a 'allow timestamp' checkbox
2. Refusing it all together, since no user should ever use it... Dev can use tools to convert or poke at the data themselves.
3. Adding a validator the the field

Jens, are we still planning do no field implementation in the core in `3.0.0` ?

**Comment by michael-e** [comment]
Adding a a validator could solve the biggest UX issue in Symphony 2, without breaking anything.

**Comment by moretaste** [comment]
Changing the behaviour of the given date to the same behaviour as the prepopulated date solves it for me right now. https://github.com/moretaste/symphony-2/blob/d4565bb8ff55b0d60ee60584304d5da2b3a4019b/symphony/lib/toolkit/fields/field.date.php#L537

So maybe an option in the backend to choose the behaviour (as epoch / not as epoch) can solve it for the future without major changes?

**Comment by michael-e** [comment]
Still, this would allow to save data which are different from the input. Am I right? For example, when inputting `2015`, the field would save `2015-01-01 00:00:00`? This might be dangerous, because later you can not decide if this value means the year or the exact date. (This is why I argued against using a date field in your case).

From an author's point of view, isn't it puzzling that every "year" value gets the 1st of January attached to it?

**Comment by moretaste** [comment]
The use case here is a form to apply for a job with fields like education and experience. 

If someone can't remember in what month he starts with an education he can only input the year. If he remember the month he can input the complete date. The 01-01 date isn't an issue in this case. 

So I have to support both complete date and only year. The date field seems to fit there the most. 

Otherwise - I think - I had to make seperate fields for day, month and year. But I have 4 rows for education and 4 rows for experience with a from date and a till date. That would be alone for the date 48 fields. Or probably a field with an hell of a regexp.

**Comment by michael-e** [comment]
And if someone inputs `2015`, how can you differentiate that from a `2015-01` input? Once the date is saved, you will never know if the month has been input or not.

**Comment by moretaste** [comment]
Agree that there is no difference but if someone inputs month 01 what is the purpose to be sure if that was the input? How can we be sure if someone inputs 08-28-2015 that he really meant to input today's date? I don't see a caveat in this.

It is to the client to ask/check all the input from the form during a possible interview.

**Comment by michael-e** [comment]
Your data is broken, because it presumes a precision which may not have been desired. It's a big difference to say "well, that was in 1979" or "that was on January 1st 1979". Your data will not reflect this difference.

Maybe someone can explain this better than me?

**Comment by jensscherbl** [comment]
@moretaste Date field is not the right field for your use case. Even if it was possible to enter only the year, it would have to "fill the gaps" (assuming a month and a day) to get a valid date. @michael-e and @nitriques are right here.

>  it is not a bug, it's a feature.

Yeah, got that.

> I really think that a timestamp is a valid date, since all dates are actually timestamps.

Doesn't really matter in what format dates are stored internally. But after some testing, the date field seems to be pretty clever about taking any kind of date format and converting it. So taking a timestamp as well is actually not as confusing as I thought. It's just another date format. After thinking about it, I'd leave it this way now.

**Comment by moretaste** [comment]
> "well, that was in 1979" or "that was on January 1st 1979". 

Agree that there is a difference. But for this use case it is no problem. True that it isn't a solid solution and not a general solution

> @moretaste Date field is not the right field for your use case. Even if it was possible to enter only the year, it would have to "fill the gaps" (assuming a month and a day) to get a valid date. @michael-e and @nitriques are right here.

What are the options?

**Comment by jensscherbl** [comment]
> For example, when inputting 2015, the field would save 2015-01-01 00:00:00? This might be dangerous, because later you can not decide if this value means the year or the exact date.

While we are discussing this, that's also how it currently works for time. There's an option for not displaying the time, but since everything is stored as a timestamp internally (according to @nitriques), it always assumes the current time if time is not explicitly given.

Would be better/cleaner to have separate `Date` and `Datetime` fields, in my opinion.

**Comment by michael-e** [comment]
> Would be better/cleaner to have separate Date and Datetime fields, in my opinion.

+1

**Comment by moretaste** [comment]
and a year field :-)

**Comment by jensscherbl** [comment]
> What are the options?

The solution you mentioned would work (having separate fields for year, month and day, while keeping month and day optional). I think that's also how most social network sites do it.

To avoid redundancy, I'd have a separate section for this sort of information. One entry per thing. A bit more complex to set up the form events, but also cleaner and more flexible in the long run.

**Comment by jensscherbl** [comment]
Oh, and I usually use an extra number field to preserve the correct order, if not explicitly given by another field (as in your case).

**Comment by michael-e** [comment]
Inputting year, month and date separately also means that you don't expect the resulting "date" to be localized, right? That is why I mentioned birthdays, in the discussion above.

Thinking about it a bit more, even the possibility to not display the time in the current Date Field is terribly dangerous. When inputting a date without time, I wouldn't expect this to get localized. But exactly this will happen.

So I tend to say: In Symphony 3, remove the ability to not display the time. It is misleading. If you only need year/month/date (or only a year), you should not use a date field, because all you have is numbers or strings (unlocalized).

**Comment by jensscherbl** [comment]
> and a year field :-)

[Already exists][1]. ;)

[1]: https://github.com/symphonycms/numberfield

**Comment by jensscherbl** [comment]
> So I tend to say: In Symphony 3, remove the ability to not display the time. It is misleading. If you only need year/month/date (or only a year), you should not use a date field, because all you have is numbers or strings (unlocalized).

Let's open a separate issue for that discussion.

**Comment by michael-e** [comment]
Done.

**Comment by moretaste** [comment]
Ok, lets close this discussion. Thanks all for the thinking, explanation and advice.

The conclusion is date field does not fit for the goal I would achieve and seperate (number)fields should do the job better.

The workaround I make solves it for now (budget, time and deadline), but isn't robust because it had to fill gaps (day, month) that are assumptions.

Last question @jensscherbl the extra section handles the repeatable fields? The visitor can have more than one education. How to achieve that without making (in this case) 48 fields in a section (which also means 48 inputs in the form and 48 outputs in the e-mail template)? 

Maybe we need fields that can be repeatable (I remember a discussion about that where I think the conclusion was that it has a great impact on the database)

**Comment by jensscherbl** [comment]
> Last question @jensscherbl the extra section handles the repeatable fields? The visitor can have more than one education. How to achieve that without making (in this case) 48 fields in a section (which also means 48 inputs in the form and 48 outputs in the e-mail template)?

You'd have a section for "education & work experience" or something. This section would have  

- **year from** *required*
- **month from** *optional*
- **day from** *optional*
- **year to** *optional*
- **month to** *optional*
- **day to** *optional*
- **type** *education, work*
- **title**
- **description**

This way, each "experience" is one entry in this section. You can easily iterate over experiences and add as many as you like, not limited to just 4.

> Maybe we need fields that can be repeatable

Everything repeatable fields could do is already possible with linked sections.

**Comment by moretaste** [comment]
But how do you do that at the front-end in the form? The input is from a front-end form?

**Comment by jensscherbl** [comment]
Sorry, haven't done that in a while, so I can't answer this right away without putting too much time and work into it. But it's possible. Maybe someone else can help you with that on the forum.

**Comment by moretaste** [comment]
Ah k no problem. This isn't the place also for it. It was just curiosity.

**Comment by jensscherbl** [comment]
But I'll have to do something similar in an upcoming project soon. Maybe remind me in a week or two, would be a good topic for a tutorial.
