### ISSUE TITLE
Invalid HELO domain name

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2497]
Sending emails over SMTP doesn't work with Symphony (2.6.3) on my current host. I'm getting the following log entry:

    UNKNOWN: Email Gateway Error (SectionEvent): Invalid HELO domain name

Works fine with [Swift Mailer][1] in the same environment, also works fine when sending through the same SMTP from local (MAMP).

I'm on PHP 5.6 and the SMTP server requires authentication.

Any ideas how to fix this?

@creativedutchmen @michael-e @brendo 

[1]: http://swiftmailer.org/

**Comment by michael-e** [comment]
Unfortunately, we lost the ability to `git blame` when the core code was re-formatted to comply with PSR-2 formatting rules. But I took the time and did a manual comparison of the file in question (which is `/symphony/lib/toolkit/class.smtp.php`) and have not found any significant changes since Symphony 2.3.

This, a t least, tells me that the problem has not been caused by any recent changes.

So the issue might have to do with your email provider as well. Things get a bit complicated now.

If you look at `class.smpt.php`, you will notice that any greeting message, i.e. the `HELO` or `EHLO` (the more modern variant) command, is sent together with an IP address. Ideally, servers should send a fully-qualified domain name (FQDN), but according to some quick tests email clients don't do this either (probably because personal computers don't have any useful domain names), but send a (local) IP address (which is pretty useless — but anyway…).

In order to shed some light on your issue, could you hack both the `_ehlo` and the `_helo` function in the above file and test the following cases?

* send a typical local IP address different from `127.0.0.1` (e.g. `192.168.2.100`)
* send the public IP address of your server
* send an FQDN (which doesn't need to exist) in the form `foo.example.com`
* send the real FQDN of your server

Alternatively, you could connect to your email server via Telnet and do these tests manually:

```sh
$ telnet mail.example.com 25
Trying 123.45.67.89...
Connected to mail.example.com.
Escape character is '^]'.
220 mail.example.com ESMTP Postfix (Debian/GNU)
HELO
501 Syntax: HELO hostname  # HELO has been rejected
HELO 127.0.0.1
250 mail.example.com  # HELO has been accepted
quit
221 2.0.0 Bye
$
```

The results will hopefully tell us more about what your email provider expects.

**Comment by michael-e** [comment]
Oh, one more thing: It would be good to know the actual `HELO`/`EHLO` command that your server sends. So could you add s.th. like the following line to your `_ehlo` and `_helo` function?

```php
file_put_contents('/var/www/maschine/workspace/debug.txt','HELO [' . $this->_ip . ']' . "\r",FILE_APPEND);
```

resp.

```php
file_put_contents('/var/www/maschine/workspace/debug.txt','EHLO [' . $this->_ip . ']' . "\r",FILE_APPEND);
```

**Comment by jensscherbl** [comment]
I'm onto it. Be patient, I'm slow... ;)

**Comment by jensscherbl** [comment]
> This, a t least, tells me that the problem has not been caused by any recent changes.

No, it also didn't work in a much older project I recently migrated to this new environment.

>  It would be good to know the actual HELO/EHLO command

    HELO/EHLO [SunOS localhost 5.10 Generic_142901-13 i86pc]

Works after removing the brackets, by the way.

Swift Mailer uses the virtual host (example.com) instead.

> send a typical local IP address different from 127.0.0.1 (e.g. 192.168.2.100)
> send the public IP address of your server

Works with brackets and actual IP addresses, both `127.0.0.1` and the public IP address.

> send an FQDN (which doesn't need to exist) in the form foo.example.com
> send the real FQDN of your server

Works without brackets.

**Comment by jensscherbl** [comment]
So the fix seems to be removing the brackets, but not sure if this might cause issues in other environments or goes against the recommended standard.

Swift Mailer seems to only use a [domain and no brackets][1], but [includes brackets][2] when an IP address is used as fallback.

[1]: https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Transport/EsmtpTransport.php#L304
[2]: https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L25

**Comment by michael-e** [comment]
> Swift Mailer seems to only use a domain and no brackets, but includes brackets when an IP address is used as fallback

Which seems correct to me.

Always using an IP address (with brackets) — as Symphony does it — may not be ideal, but it works (as your tests confirmed). So to me the question is: Why don't you have an IP address in your `HELO`, but `SunOS localhost 5.10 Generic_142901-13 i86pc`?

Do you have shell access to the server? I yes, what is the result of

```sh
php -r "echo gethostbyname(php_uname('n'));"
```

(It's used in [these lines](https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/lib/toolkit/class.smtp.php#L85-L89)).

**Comment by jensscherbl** [comment]
> what is the result of

It's `SunOS localhost 5.10 Generic_142901-13 i86pc`.

**Comment by michael-e** [comment]
Aha! Might be related [to this](http://stackoverflow.com/a/19796250)? Can you test the alternative?

**Comment by jensscherbl** [comment]
> Can you test the alternative?

    string(4) "freg"

oO

**Comment by michael-e** [comment]
Hui. Can you try the proper lowercase function names?

**Comment by jensscherbl** [comment]
Already did. Looks like the hostname is `freg` and `gethostbyname` just fails (returns the hostname in that case).

**Comment by jensscherbl** [comment]
It's STRATO's distributed shared hosting platform, by the way.

![infografik_strato_shared_webhosting_plattform](https://cloud.githubusercontent.com/assets/1640033/9760227/98e6d0d8-56f3-11e5-8be1-d3a179cfee17.jpg)

**Comment by jensscherbl** [comment]
So, do I get this right that the issue is that Symphony expects my server to return an IP address, but it doesn't? So it's my servers fault. But Symphony's implementation isn't really good either, because it always uses an IP address instead of a domain name, like Swift Mailer does?

**Comment by michael-e** [comment]
Yes, it looks like it's either a PHP issue on SunOS, or simply an issue an the server when trying to resolve the own (short) name.

> But Symphony's implementation isn't really good either, because it always uses an IP address

Yes, it's not perfect nor "beautiful". It's pragmatic. Two things to keep in mind:

1. As stated earlier, using an IP address is what local email clients will do as well, so there shouldn't be issues with this when sending mails (as long as there is a valid IP address in the `HELO`).
2. When running Symphony on localhosts (for development), you won't find a valid FQDN in many cases. So things would get more complicated if Symphony attempted to find an FQDN first (and use the IP address as fallback). It's perfectly possible, but it's more hassle.

I suggest to concentrate on the IP issue first. Could we maybe:

1. Replace `gethostbyname(php_uname('n'))` with `gethostbyname(gethostname())` (because Symphony is PHP 5.3+).
2. In the code, test if the result is a valid IP address.
3. Use 127.0.0.1 as fallback.

Whyt do you think?

**Comment by jensscherbl** [comment]
Just curious, why do we bother using `gethostbyname(...)` at all if `127.0.0.1` is already good enough?

**Comment by michael-e** [comment]
Good question. I have no answer for this. As far as I remember, all this code was written by @creativedutchmen. But yes, I think that any __local IP__ is really useless to a remote server, so we might hardcode `127.0.0.1` as well.

**Comment by michael-e** [comment]
(Which is against the idea of a `HELO` command, of course.)

**Comment by jensscherbl** [comment]
Using a battle tested library like Swift Mailer instead of rolling our own implementation might also not be such a bad thing going forward.

**Comment by creativedutchmen** [comment]
Interesting question, and as I recall, we are using the real IP because "we're supposed to". I believe, but can't recall the details, that some mailservers refuse to send email when the IP is set to 127.0.0.1

On Swift: have you seen how bloated it is, and how badly it performs with different encodings? Really. It sucks.

**Comment by michael-e** [comment]
I haven't looked at Swift Mailer for a long time, but at the time when the email core code was written, Swift Mailer was a bloated library, much bigger than the Symphony core. So we said: If we can do it in a few lines, why should we rely on an external library?

**Comment by michael-e** [comment]
Ah, @creativedutchmen was faster. :-)

**Comment by jensscherbl** [comment]
> have you seen how bloated it is

> I haven't looked at Swift Mailer for a long time, but at the time when the email core code was written, Swift Mailer was a bloated library, much bigger than the Symphony core. So we said: If we can do it in a few lines, why should we rely on an external library?

Sure. But as more and more Symphony developers jump ship, do we really have the resources to maintain all that low level plumbing ourselves going forward?

**Comment by creativedutchmen** [comment]
> do we really have the resources to maintain all that low level plumbing ourselves going forward? 

Do we have to? This is the first issue on the SMTP lib I've seen, with a relatively easy fix. I'd say this takes little work compared to keeping a recent Swift and updating the API every time Swift changes.

**Comment by michael-e** [comment]
You nailed it, @creativedutchmen.

**Comment by jensscherbl** [comment]
> I'd say this takes little work compared to keeping a recent Swift and updating the API every time Swift changes.

Well, yeah, not maintaining your own implementation is always less work than updating an external library... ;)

But let's stop this discussion for now and go back to the issue.

What do you think, is this situation something that should be handled by Symphony? And if so, what's the proper solution? Trying to use a domain name and fall back to `127.0.0.1`? Trying to get the actual IP and fall back to `127.0.0.1`? Using `127.0.0.1` by default?

**Comment by creativedutchmen** [comment]
> Well, yeah, not maintaining your own implementation is always less work than updating an external library... ;)

Exactly:) And since the SMTP standard isn't going anyway, I'd say we don't have to either.

> But let's stop this discussion for now and go back to the issue. What do you think, is this situation something that should be handled by Symphony?

Sure. If it breaks, it breaks. Using a domain name, falling back to the IP, falling back to 127.0.0.1 would be my preferred solution. However, I can live with using the IP and falling back to 127.0.0.1, as I think that would be easiest.

**Comment by michael-e** [comment]
Find an FQDN isn't trivial at all in PHP, Stackoverflow says. Unless we have a great idea for this, we might concentrate on the IP address stuff. It has always 

I admit, currently Symphony on my Debian server uses "127.0.0.1", so the current code doesn't return a super-useful IP in my case. Could it be that we find local IP addresses exclusively?

My suggestion is:

* try to find the public IP address
* fallback 1: local IP address
* fallback 2: `127.0.0.1`

**Comment by jensscherbl** [comment]
> Find an FQDN isn't trivial at all in PHP, Stackoverflow says.

`$_SERVER['HTTP_HOST']`? Or did I miss something important here?

**Comment by creativedutchmen** [comment]
Hmm, we could try something like this:

Try the domain name on the mailserver. If it accepts it: great! If it doesn't, try 127.0.0.1.

`$_SERVER` doesn't work for background processes like the ENM uses.

**Comment by jensscherbl** [comment]
What about defining the domain/IP explicitly in the preferences, with `127.0.0.1` as the default?

**Comment by creativedutchmen** [comment]
Yes, that's perfect.

**Comment by michael-e** [comment]
Sounds great. How to call it? "Greeting hostname"? Or "HELO host"?

**Comment by jensscherbl** [comment]
> Try the domain name on the mailserver. If it accepts it: great! If it doesn't, try 127.0.0.1.

Mhh. I think your suggestion was actually better than mine with the preference setting. Swift Mailer's [code for getting the domain name][1] is actually pretty simple, I think we can just use that.

[1]: https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L462

**Comment by michael-e** [comment]
@creativedutchmen said that `$_SERVER` isn't available for background processes as used by the ENM. So we would always "fall back" when sending mass emails.

I like the preference setting even more, because a developer can actually determine how the `HELO` will be.

**Comment by jensscherbl** [comment]
> So we would always "fall back" when sending mass emails.
> some mailservers refuse to send email when the IP is set to 127.0.0.1

Ah yes, get it now.

**Comment by michael-e** [comment]
The more I think about it, the more I like the preference idea. Ideally the helo name should be an FQDN, and the simplest way to achieve this (in every "situation") is a preference setting. It means less code in the email core, but more flexibility and bullet-proofness.

**Comment by creativedutchmen** [comment]
+1

**Comment by nitriques** [comment]
+1000 guys amazing geek thread. telnet FTW.

**Comment by michael-e** [comment]
:-) Have you never tried to send an email using telnet? It's eye-opening!

**Comment by nitriques** [comment]
> :-) Have you never tried to send an email using telnet? 

Yes I did! I've also browsed the web using telnet. Upload a file on a FTP server too :)

>  It's eye-opening!

True !

**Comment by michael-e** [comment]
@jensscherbl: Could you care for a pull request (using your "preferences" idea)? Or is there any other volunteer?

**Comment by jensscherbl** [comment]
@michael-e It's on my list, just didn't have the time to actually do it yet.

**Comment by nitriques** [comment]
Bumped to 2.7.0

**Comment by michael-e** [comment]
Isn't this a bugfix, so shouldn't we try to get it into Symphony 2.6.5?

**Comment by nitriques** [comment]
Yes it can.

**Comment by michael-e** [comment]
@jensscherbl: Do you have time to code the proposed solution (preference setting)? I am not sure if I can do it, so maybe we'd have to push it into a later release otherwise.

**Comment by michael-e** [comment]
I took a look. It will be a a bit tricky, and we will have to rename some variables (like `$options['local_ip']` or `$this->_ip`) for a proper solution. I may try and implement it, but I am not sure how fast I will be.

@nitriques: Don't wait for this PR if 2.6.5 is ready to be released. We can still implement it in 2.6.6 or 2.7.

**Comment by nitriques** [comment]
Perfect. Also, I saw that there are some unused field in the SMTP class, like $to.

**Comment by michael-e** [comment]
Short story: I tried to implement the preferences setting for the HELO hostname today. I don't think that we can fix this without changing/breaking the API. So I suggest 3.0 as the milestone.

Long story (see https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/lib/toolkit/class.smtp.php#L47-L87): The constructor of the `SMTP` class has `$options['local_ip']`. This would have to be renamed if we say that an FQDN is the best value for this. We can't change the behaviour regarding this option without breaking the public API, so we'd have to add a new option (e.g. `$options['helo_hostname']`) at least, making everything more complicated. Given the fact that this issue has not come up very often, I suggest to not fix it in a bugfix release.

**Comment by michael-e** [comment]
I couldn't give up on this. So now I have a suggestion in the "fix-2497" branch in my repo: https://github.com/michael-e/symphony-2/tree/fix-2497. It's just 2 commits, please take a look. @jensscherbl, it would be great ig you could test this on your server.

I will send a PR if you want me to.

**Comment by nitriques** [comment]
> I suggest to not fix it in 2.6.5.

Agreed.

> Drop unused variables

Thanks!

But regarding [this](https://github.com/symphonycms/symphony-2/compare/2.6.x...michael-e:fix-2497?expand=1#diff-a9c0a15ad4cffad7e0a58a91f12baef7R85) you did retain the old behavior didn't you ? So it could go into 2.6.5 after all!

**Comment by michael-e** [comment]
Yes, in the end I did retain old behaviour, so I would send a PR to 2.6.x if it looks OK for you (and @jensscherbl).

**Comment by michael-e** [comment]
Or send it right away and make @jensscherbl break it. :-)

**Comment by nitriques** [comment]
LGTM ! :shipit: I very like when @jensscherbl breaks things. A good tester does break things.

**Comment by michael-e** [comment]
Here it is: https://github.com/symphonycms/symphony-2/pull/2539

**Comment by jensscherbl** [comment]
Sorry guys, no longer using Symphony in my current project (in favour of some old school custom coding after a rough Symphony based prototype), so no time to contribute at the moment.

**Comment by michael-e** [comment]
Never mind, it has already been pulled. Fingers crossed! (Well, I tested it.)

**Comment by michael-e** [comment]
@nitriques: The new email setting should be mentioned in the release notes.

**Comment by nitriques** [comment]
Yes totally.
