### ISSUE TITLE
Publish Filter : "between mode" (x to y) not working

### ISSUE THREAD

**Issue by twiro** [symphonycms/symphony-2#2499]
I was just checking if number field is fully compatible with the current 2.6.3 release and noted that publish filtering doesn't throw any results when using the "between mode".

Looks like the filtering-url is constructed the wrong way.
If i try to filter inbetween a range of "1" and "3" the resulting URL looks like this: 

```
.../publish/entries/?filter[number]=x to y 1 to 3
```

If I manually edit the URL to...

```
.../publish/entries/?filter[number]=1 to 3
```

...everything works as expected.

**Comment by nitriques** [comment]
This looks more like a number field issue since declaring which filter is supported by each field can be customized (see https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.field.php#L1178-L1208)

Or I do no understand what's the problem...

**Comment by twiro** [comment]
I tried to fix this, but stumbled upon a bigger conflict along the way:

---

### A) Trying to fix the field

Number-field defines the "between"-filter [in these lines](https://github.com/symphonycms/numberfield/blob/master/fields/field.number.php#L230-L237). As described above this doesn't work because the `filter`-value `x to y` gets included in the URL when using the between-comparison.

As filtering works when removing "**x to y**" from the URL, I simply tried to change [line 232](https://github.com/symphonycms/numberfield/blob/master/fields/field.number.php#L230-L237) and set the `filter`-value to `' '`.

**Result:** Filtering works as expected, but as the filter-value is used as actual `value`-attribute of the comparison mode selectbox-options I now had two options with the same value `' '`. That obiously doesn't work - when choosing the **between**-mode publish filtering gets confused and displays the help-text of the **is**-mode.

So as each filtering option has to come with a unique `filter`-value by design I don't see a way to solve this with the filter-settings of the field.

---

### B) Trying to fix the core

My other attempt to solve this was to prepare the core to properly get along with the filtering settings of number-field.

I replaced [line 138 of **symphony.filtering.js**](https://github.com/symphonycms/symphony-2/blob/master/symphony/assets/js/src/symphony.filtering.js#L138) with the following code:

	// Comparison mode "between" (x to y)
	if (comparison.replace(/\s+/g, '') == 'xtoy') {
		value = 'filter[' + query.attr('name') + ']=' + $.trim(query.val());
	
	// Other comparison modes
	} else {
		value = 'filter[' + query.attr('name') + ']=' + comparison + $.trim(query.val());
	}

_**Note:** Simply writing `(comparison == 'x to y')` didn't work for me. I guess cause of the spaces..._


**Result:** Regarding the basic filtering process everything works fine - when using the **between**-mode the url no longer gets constructed with a prefixed **x to y** in the filter-value.

**But:** After performing the filter process the comparison-mode-selectbox no more shows the right value as selected option. It says **is** instead of **between**. So setting the right value for the selectbox after relaoding the page seems to depend on a matching "key" in the url.

---

### Conflict Conclusion

 - Both **"is"** and **"between"**-comparison-modes work without prefixing their filter values in the url.
 - Symphony's Publish Filtering expects every mode except **is** to have a prefix in the url.

So this can't be fixed without changing one of these behaviors. 

It might be an idea to introduce a prefix ("between"?) for the between-mode _(see following example)_, but that would introduce a different filtering-syntax than in the datasource-editor:

    .../publish/entries/?filter[number]=between 1 to 3

@brendo - do you have an idea how this could be solved in a clean & solid way? You introduced the **between**-publish-filtering mode in number field a while ago and I haven't seen it beeing used anywhere else (date fields could do so, but that might get pretty complicated interface-wise...)

As this is not a critical bug I would suggest to simply remove the "between"-comparison-mode from number field if a reasonable solution would be to complicated.

**Comment by nitriques** [comment]
> Symphony's Publish Filtering expects every mode except is to have a prefix in the url. ... It might be an idea to introduce a prefix ("between"?)

I think that's the best idea.

**Comment by twiro** [comment]
>> Symphony's Publish Filtering expects every mode except is to have a prefix in the url. ... It might be an idea to introduce a prefix ("between"?)

> I think that's the best idea.

Thought about this a little more and came to the conclusion that it might not be such a great idea to introduce a new filtering syntax _(may it only be one additional word in the url parameters)_ just for fixing a shortcoming in the publish filtering interface.

I've set up a [branch](https://github.com/twiro/symphony-2/tree/publish-filter-data-attributes) to play around with this and came up with a solution that looks pretty reasonable and backwards-compatible to me - didn't do much testing yet, but at a first glance everything works as expected. One needs to remove "x to y" from the number fields filter settings though to make the "between"-mode work as expected. But that's what this is all about ;)

I would really like to get some feedback from you and possibly @nilshoerrmann and @brendo as well _(as they invented most of the filtering stuff)_ before sending a PR for this... does it make sense concept-wise? Does the code look valid? And could it possibly break publish filtering in scenarios I haven't thought of?

I'll just copy & paste the description of my commit for further details:

----

### [Publish Filtering : Increase flexibility of comparison modes](https://github.com/twiro/symphony-2/commit/6e764d1653b9146fcc76b492fc1546a0640fecc8)

The current markup of the „comparison mode“-selectboxes in the publish filtering interface doesn’t allow for multiple modes that don’t have a filter prefix (like „regexp:“, „greater than:“, etc.) as it uses the prefix as unique identifier (option value).

The default comparison mode „is“ is expected as the only mode without a filter prefix. But filter modes like „between“ („$x to $y“) as included in Number Field (and possibly date fields too) don’t have a prefix either and therefore won’t work with the current code.

This PR changes that behavior by shifting to the filter title as unique identifier and adding the filter prefix as optional data-attribute that’s only used for building the actual filtering-url-parameters.

Old Behavior:
- Filter title is used as option title
- Filter prefix is used as value-attribute

New Behavior:
- Filter title is used as option title
- Filter title is used as value-attribute
- Filter prefix is included as data-attribute

---
### Screenshot : Number Field Filter Options - Before & After

![comparison-modes-selectbox](https://cloud.githubusercontent.com/assets/870227/12202157/ac6176d8-b628-11e5-9d45-1d2a687c7c77.png)

---

Will do some more testing on sunday...

**Comment by nilshoerrmann** [comment]
> I would really like to get some feedback from you and possibly @nilshoerrmann and @brendo as well (as they invented most of the filtering stuff) before sending a PR for this...

Sorry guys, I won't be of any help here. Haven't thought about this stuff since it landed in the core …

**Comment by nitriques** [comment]
@twiro It's an interesting solution but I really hate those pesky hard coded indexes ($comparisons[$key][0] = $comparison[2];) has it is error-prone. Can we structure the data in a better way ?

**Comment by twiro** [comment]
Thanks for your feedback guys!

> Can we structure the data in a better way ?

I hope so - actually It looks a lot cleaner to build the intended array directly in the `createFilterComparisons`-function:

https://github.com/symphonycms/symphony-2/compare/master...twiro:publish-filter-data-attributes?expand=1

The resulting markup is the same as before (see screenshot above), so this should work as well.
Does this look ok to you?

**Comment by nitriques** [comment]
I does looks better! 

But I still do not understand why we need to change the value of the select element since we do not use it as POST value but only read from it in javascript (I am maybe missing something here...)

**Comment by twiro** [comment]
> But I still do not understand why we need to change the value of the select element since we do not use it as POST value but only read from it in javascript (I am maybe missing something here...)

You're right, it's only used by javascript - but the script uses the `value`-attribute to show the matching help-text for the currently selected comparison mode. This doesn't work with multiple options that share the same value.

I could have changed the script that does the matching and use the actual readable content/title of each selectbox option as unique identifier, but using a unique value and an additional data-attribute for the optional filter-prefix simply looked like the cleaner and more logical way to do this to me.

**Comment by nitriques** [comment]
> but the script uses the value-attribute to show the matching help-text for the currently selected comparison mode.

Oooo! I'd rather see the value be the url part and the data-attribute to be used a the help text!

**Comment by twiro** [comment]
> Oooo! I'd rather see the value be the url part and the data-attribute to be used a the help text!

[I changed it!](https://github.com/symphonycms/symphony-2/compare/master...twiro:publish-filter-data-attributes?expand=1)
Now the filter "title" is used as unique identifier via `data-comparison`-attribute while the actual filter "value/prefix" (for constructing the url-filtering-params) is used as the `value`-attribute in the comparison mode selectboxes.

The result (for the default input field) looks something like that now:

![comparison-modes-data-attributes](https://cloud.githubusercontent.com/assets/870227/12518137/f015a82c-c136-11e5-9dee-ee2a2ed3143b.png)

I still need to test this a little more intense, but it defintively solves the initial issue with having multiple filtering comparisons with the same "value/prefix".

**Comment by nitriques** [comment]
Great! ready to send a PR ?

**Comment by nitriques** [comment]
@twiro Ping! ready to send a PR ?

**Comment by twiro** [comment]
> _Ping! ready to send a PR ?_

I do think so :) 

Took some time because of [intense testing](https://github.com/symphonycms/symphony-2/issues/2564), but my fix seems to work just fine! 
Should I Submit a PR against the 2.7-branch?

**Comment by nitriques** [comment]
> Should I Submit a PR against the 2.7-branch?

Yes please!

**Comment by twiro** [comment]
Finally... https://github.com/symphonycms/symphony-2/pull/2577

My changes are based on 2.6.4... I tried `git merge upstream/master` before submitting my PR, but  as other changes to `content.publish.php` were made in the meantime that obviously didn't work - and beeing a git noob I didn't want to start fiddling around with branches ;)

Is it ok that way or is there anything that needs to be changed?

**Comment by nitriques** [comment]
> Is it ok that way or is there anything that needs to be changed?

I'll be able to squash this into a commit so nothing needs to be done on your part. Thanks!

**Comment by twiro** [comment]
> _I'll be able to squash this into a commit so nothing needs to be done on your part. Thanks!_

Perfect - thank you Nicolas!

**Comment by nitriques** [comment]
Merged!
