### ISSUE TITLE
System dates may be systematically wrong if Daylight Saving Time is used in your timezone

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2501]
When the system timezone uses DST (Daylight Saving Time), system dates (created/modified) will experience systematic offsets. Since the problem is in `class.entrymanager.php`, this will probably also produce wrong filtering results (when filtering on system dates).

### Example

Assume that you have two entries, like so:

    mysql> SELECT * FROM `sym_entries` WHERE `id` IN (2157,13964);
    +-------+------------+-----------+---------------------+---------------------+---------------------+-----------------------+
    | id    | section_id | author_id | creation_date       | creation_date_gmt   | modification_date   | modification_date_gmt |
    +-------+------------+-----------+---------------------+---------------------+---------------------+-----------------------+
    |  2157 |          7 |         3 | 2011-11-28 16:11:20 | 2011-11-28 15:11:20 | 2011-11-28 16:11:20 | 2011-11-28 15:11:20   |
    | 13964 |          7 |         1 | 2012-05-25 14:24:05 | 2012-05-25 12:24:05 | 2012-05-25 14:24:05 | 2012-05-25 12:24:05   |
    +-------+------------+-----------+---------------------+---------------------+---------------------+-----------------------+
    2 rows in set (0.00 sec)

Note that the first entry is in winter (here: +01:00), the second entry is in summer (DST, here: +02:00).

If your current time offset is +02:00 (DST), outputting the system dates of these entries to XML will show:

```xml
<entry id="2157">
    <system-date>
        <created iso="2011-11-28T15:11:20+01:00" time="15:11" weekday="1" offset="+0100">2011-11-28</created>
        <modified iso="2011-11-28T15:11:20+01:00" time="15:11" weekday="1" offset="+0100">2011-11-28</modified>
    </system-date>
</entry>
<entry id="13964">
    <system-date>
        <created iso="2012-05-25T14:24:05+02:00" time="14:24" weekday="5" offset="+0200">2012-05-25</created>
        <modified iso="2012-05-25T14:24:05+02:00" time="14:24" weekday="5" offset="+0200">2012-05-25</modified>
    </system-date>
</entry>
```

For the first entry, system dates are wrong by one hour.

(If your current time offset is +01:00, it will be the other way 'round — the second entry will be wrong.)

### Solution

I tracked this down, and the issue is in `class.entrymanager.php`:

```sql
$sql = "
    SELECT  ".($group ? 'DISTINCT ' : '')."`e`.id,
            `e`.section_id, e.`author_id`,
            UNIX_TIMESTAMP(e.`creation_date`) AS `creation_date`,
            UNIX_TIMESTAMP(e.`modification_date`) AS `modification_date`
    FROM `tbl_entries` AS `e`
    $joins
    WHERE 1
    ".($entry_id ? "AND `e`.`id` IN ('".implode("', '", $entry_id)."') " : '')."
    ".($section_id ? "AND `e`.`section_id` = '$section_id' " : '')."
    $where
    $sort
    ".($limit ? 'LIMIT ' . intval($start) . ', ' . intval($limit) : '');

$rows = Symphony::Database()->fetch($sql);
```

When reading the system date, the query uses MySQL's `UNIX_TIMESTAMP` function. This has caused issues before (https://github.com/symphonycms/symphony-2/issues/1726), and they were fixed in (b9ff8fc0fe9d53dae2f9a8b5c9ce6d2abeb9a90e) by setting the time zone when connecting to MySQL.

The problem with this solution is: It doesn't take DST into account. So the timestamp returned by MySQL will be wrong (by 3600 seconds) for the example entry above.

I don't know when the `UNIX_TIMESTAMP` function was introduced, but it must be very old. Thinking about it (and doing some tests), I am convinced that it is no good idea at all and should be removed. Given the saved dates, Symphony will do everything correctly on the PHP level (using `DateTimeObj::get('c', $entry['meta']['creation_date'])` when setting the entry's creation date, similar for the modification date), and it is harmful to attempt to convert these dates in MySQL in advance.

If we were writing a new Symphony, we would probably save system dates together with time offsets, which would be more bullet-proof. Fortunately, there is a simpler fix for the current implementation of system dates.

I suggest to:

1. Remove the `UNIX_TIMESTAMP` function from the above query.
2. Remove (undo) b9ff8fc0fe9d53dae2f9a8b5c9ce6d2abeb9a90e (i.e. don't use MySQL's time zone feature at all). Note that we don't need to set a MySQL timezone if we don't convert dates in MySQL. (We have one possible side effect here, see below.)

This would result in the following (correct) output:

```xml
<entry id="2157">
    <system-date>
        <created iso="2011-11-28T16:11:20+01:00" time="16:11" weekday="1" offset="+0100">2011-11-28</created>
        <modified iso="2011-11-28T16:11:20+01:00" time="16:11" weekday="1" offset="+0100">2011-11-28</modified>
    </system-date>
</entry>
<entry id="13964">
    <system-date>
        <created iso="2012-05-25T14:24:05+02:00" time="14:24" weekday="5" offset="+0200">2012-05-25</created>
        <modified iso="2012-05-25T14:24:05+02:00" time="14:24" weekday="5" offset="+0200">2012-05-25</modified>
    </system-date>
</entry>
```

Of course, you will get the same system date results every time you use `get('creation_date')` or `get('modification_date')` on an entry object, because the issue (and the proposed fix) happen at the earliest possible stage.

**I can send a pull request for this if nobody has serious concerns.**

### Side effects

Only one other file in the Symphony core uses MySQL's `UNIX_TIMESTAMP` function: `class.cacheable.php`. Looking at the code, I find it extremely dangerous anyway, because saved timestamps are built on the PHP side, but evaluated using the MySQL function. This should be changed, independently from the above issue, to always do it in PHP.

**I'd prefer this to get fixed by @brendo or @nitriques.** (We should open a separate issue for that if you think that I am on the right track here.)

**EDIT:** After thinking twice and testing, I don't see an issue with `class.cacheable.php` anymore. Simply using `UNIX_TIMESTAMP()` in a query will not involve any timezone logic in MySQL (because the timestamp itself is not localized).

**Comment by nitriques** [comment]
Short Anwser: The current state of affairs is the way Window's event viewer works. When DST changes, all timestamps are shown an hour earlier than they appear.

> I can send a pull request for this if nobody has serious concerns.

Please, send it. I would happy to discuss/test it. But I would start by getting rid of the UNIX_TIMESTAMP call but keeping the settimezone (to lower the risk of having a backlash?) I'd love to have @brendo's feedback on this since he's the actual guy who fixed #1726

>  on an entry object, because the issue (and the proposed fix) happen at the earliest possible stage.

Maybe off a little, but I can live with that!!!

> SELECT * FROM `sym_entries` WHERE `id` IN (2157,13964);

The dates are ok in the DB at least. I hope

```sql
SELECT  ".($group ? 'DISTINCT ' : '')."`e`.id,
            `e`.section_id, e.`author_id`, `creation_date`, `modification_date`
```

yeilds the right date right ?

**Comment by nitriques** [comment]
BTW @michael-e you may also encounter the same problems with the date field, and Nil's datetime field that both uses UNIX_TIMESTAMP.

**Comment by michael-e** [comment]
> The dates are ok in the DB at least. I hope …

Yes, I am using the following actively (in a live system, which is a good test, isn't it?), and it works perfectly:

```sql
SELECT  ".($group ? 'DISTINCT ' : '')."`e`.`id`,
		`e`.`section_id`,`e`.`author_id`,
		`e`.`creation_date` AS `creation_date`,
		`e`.`modification_date` AS `modification_date`
```

> you may also encounter the same problems with the date field, and Nil's datetime field 

No, these fields do not use MySQL's `UNIX_TIMESTAMP()` function. Anyway, I have not found any problems with dates that are saved including the time offset. These are handled correctly on the PHP level. The problem with system dates is that they are saved **without the offset**, so reading/converting them requires more carefulness. In this case: Don't convert them in MySQL, because Symphony (the PHP level) will do it right.

I am rather sure that @brendo will also honor the suggested removal of `Database()->setTimeZone` because it can only ever help if you convert dates on the MySQL level (using `UNIX_TIMESTAMP()`, for example), and that's exactly the most dangerous thing you can do (especially if the MySQL timezone is "fixed", i.e. doesn't honor DST). Currently I can only find two occurences in the core (see above), and we shouldn't wait for more popping up. :-)

**Comment by brendo** [comment]
> I am rather sure that @brendo will also honor the suggested removal of Database()->setTimeZone because it can only ever help if you convert dates on the MySQL level (using UNIX_TIMESTAMP(), for example), and that's exactly the most dangerous thing you can do (especially if the MySQL timezone is "fixed", i.e. doesn't honor DST).

Actually no, I believe this function must remain to ensure that functions such as `NOW()` continue to function. Our logic in `setTimeZone` will handle DST, so that should be fine.

I'm ok with removing the `UNIX_TIMESTAMP()` function... but it's a breaking change and needs to be done as part of Symphony 3. The `EntryManager::fetch` method accepts a `$buildentries` parameter which will return an array of the raw SQL result, so existing code may be relying on the `creation_date` and `modification_date` being a UNIX timestamp rather than a full date.

**Comment by michael-e** [comment]
I am afraid that I have not explained the issue well enough. I'll try again, keeping it as short as possible.

> existing code may be relying on the creation_date and modification_date being a UNIX timestamp

Thanks for the heads up! My suggestion did not take this into account. But in order to get correct timestamps, we must create the timestamp in PHP, not in MySQL (see below).

> I believe this function must remain to ensure that functions such as `NOW()` continue to function.

I haven't seen MySQL's `NOW()` function anywhere in Symphony, but anyway. For extension developers, setting a timezone for the MySQL connection may have been seductive, so—at least theoretically—one might have been tempted to use MySQL datetime functions. Given this, I agree that removing `Database()->setTimeZone` is a breaking change (and should be done in 3.0).

Still, removing `UNIX_TIMESTAMP()` is the opposite of "breaking", it's a bugfix:

> Our logic in `setTimeZone` will handle DST, so that should be fine.

No. Let me try with a short table. "Output" means the result of the MySQL query, "DST" means "daylight saving time". We are reading system dates for two entries:

current time offset | output for entry 1 (saved with standard offset) | output for entry 2 (saved with DST offset)
----- | ----- | -----
standard | correct | **incorrect** (+1 hour)
DST (+1 hour) | **incorrect** (-1 hour) | correct

As you see, the problem is the mixture of time offsets in the DB. There is no _single correct time offset_ for the conversion.

We could fix this bug in a backwards-compatible way by removing `UNIX_TIMESTAMP()` from the query, then building the unix timestamp in PHP. (Symphony's `DateTimeObj` can add the correct missing time offset to a saved value.)

**Comment by michael-e** [comment]
I fixed @brendo's findings and re-invented the timestamp format for system dates, calculated in Symphony:

```php
$sql = "
	SELECT  ".($group ? 'DISTINCT ' : '')."`e`.`id`,
			`e`.`section_id`,`e`.`author_id`,
			`e`.`creation_date` AS `creation_date`,
			`e`.`modification_date` AS `modification_date`
	FROM `tbl_entries` AS `e`
	$joins
	WHERE 1
	".($entry_id ? "AND `e`.`id` IN ('".implode("', '", $entry_id)."') " : '')."
	".($section_id ? "AND `e`.`section_id` = '$section_id' " : '')."
	$where
	$sort
	".($limit ? 'LIMIT ' . intval($start) . ', ' . intval($limit) : '');

$rows = Symphony::Database()->fetch($sql);

// Return UNIX timestamps as it has always been (Re: #2501)
foreach ($rows as &$entry) {
	$entry['creation_date'] = DateTimeObj::get('U', $entry['creation_date']);
	$entry['modification_date'] = DateTimeObj::get('U', $entry['modification_date']);
}
unset($entry);
```

Now the function should behave like before—except the results being correct:

current time offset | output for entry 1 (saved with standard offset) | output for entry 2 (saved with DST offset)
----- | ----- | -----
standard | correct | correct
DST (+1 hour) | correct | correct

**Comment by michael-e** [comment]
I will send a pull request shortly, with the fix above. I will also add a comment to deprecate `Database()->setTimeZone` and mark it for removal in Symphony 3.

Good news: There is no need to change `class.cacheable.php` (as suspected initially), because it does not _convert_ dates in MySQL. It just uses `UNIX_TIMESTAMP()` (without a given date value), so timezone logic will not be involved — a timestamp itself is not localized. I added a comment about this to my initial post.

**Comment by jensscherbl** [comment]
Can't really get my head around this issue to be honest, so no comment on the actual issue or the work you've done from me (but thanks if it works ;).

> I haven't seen MySQL's NOW() function anywhere in Symphony, but anyway.

If I'm not completely mistaken, `now` can be used in data source filters. At least that seems to work for me,  hope I'm not relying on any nasty side effects here.

**Comment by michael-e** [comment]
> `now` can be used in data source filters

Thanks for mentioning this. This functionality is not affected at all, because this is PHP/Symphony's "now". And even if it was MySQL's `NOW()` — that would be a correct timestamp, because @brendo's fix for #1726 will always set the **correct MySQL time offset for the current date(time)**.

The issue only affects system dates for Symphony entries, because these dates are the only ones which are saved **without explicitely adding the time offset** (e.g. `+01:00`). The string will be simply be `2015-10-16 12:00:00`, for example, but it will have an offset from GMT:

* For a date in "winter" (standard offset of the timezone) the offset of the saved string will be the standard offset — **no matter when you save this string** (winter/summer). This is Symphony behaviour when saving an entry.
* For a date in "summer" (DST) the offset of the saved string will be the DST offset.

Now, when reading/converting these system dates into a "timezone-aware realm", simply using the time offset of the current date (as it is done for the MySQL connection) will yield wrong results. My fix uses Symphony's `DateTimeObj`, which will "append/assume" the correct offset (DST/non-DST).

My fix works. However, I would suggest to handle these created/modified dates differently in Symphony 3:

* There is no sense in always saving two date values, one with time offset, another one as GMT.
* System dates should be saved including the explicit offset, e.g. `2016-10-10T12:00:00+01:00`. This would make incorrect conversion much less likely.

**Comment by michael-e** [comment]
@brendo: IMHO my PR is no longer a breaking change but merely a bugfix. The function behaves exactly like before, the only difference is that the timestamps are correct. Can we change the milestone to 2.6.4?

**Comment by nitriques** [comment]
Ref #2369 I think it's actually the only possible fix. All timestamps conversion are now made in PHP so it's easy to reason about. Let MySQL only store data and return it as-is.

**Comment by nitriques** [comment]
I would do 2.7.0 with this...

**Comment by jensscherbl** [comment]
> I would do 2.7.0 with this...

Sounds reasonable. I guess `2.6.4` would also be ok, but given the complexity of the change and possible side effects, `2.7.0` would be more appropriate.

**Comment by nitriques** [comment]
Great! I would not mind either.
