### ISSUE TITLE
Create 2.6.4 and 2.5.4 releases

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2503]
@brendo Would you mind creating a wiki page on what's need to be done in order to create a release ? and add it [here](https://github.com/symphonycms/symphony-2/wiki#building) ?

I no particular order, I think of:

- build assets and commit them
- update composer (?)
- merge 2.6.x into master
- merge 2.6.x into integration
- update bundle
- create zip 
- ... ?

Thanks.

**Comment by brendo** [comment]
Have you got [this](https://github.com/symphonycms/symphony-2/wiki/Building-Symphony) working locally?

**Comment by brendo** [comment]
https://github.com/symphonycms/symphony-2/wiki/Releasing-Symphony :+1:

**Comment by nitriques** [comment]
> Have you got this working locally?

Yup. But I can't upload it to the website :(

> :+1:

:+1: This is EXACTLY want I needed.

> We don't have a process for generating/having two 'current' releases though, which is what will be required for 2.6.4 and the 2.5.3 release.

I'll just create a tag and the zipball. What happens we you'll upload it to the site ? IDK.

**Comment by nitriques** [comment]
@brendo Here's a script for updating all extensions in the bundle https://gist.github.com/nitriques/fc72b8d521e79bb34108

We have two pending PR before we can ship 2.6.4 and I can do it tomorrow.

**Comment by nitriques** [comment]
- [ ] Create a new migration for the new version, eg. 2.6.4 which should implement getVersion and getReleaseNotes methods
- Update the version constant in the project:
- [ ] package.json
composer.json
- [ ] .htaccess (optional)
- [ ] install/index.php
- [ ] install/includes/htaccess.txt (optional)
- [ ] LICENCE (optional)
- [ ] symphony/assets/js/src/symphony.js (optional)
- [ ] Update the README.md file, replacing the version constant and updating any metadata as required
Create a commit, usually Release 2.6.x and push to the corresponding branch. Testing at this point is recommended!

- [ ] Checkout the master branch and merge in the 2.6.4
- [ ] Create an associated tag for the release, eg. 2.6.4
