### ISSUE TITLE
Focus on 3.0.0

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2510]
> I have lots of new delegate ideas for 2.7.0 (so Jens' happy which makes me happy)

While it's ok regarding semantic versioning, I also agree with @brendo that it would be better to concentrate on a stable `3.0.0` release first. We already have lots of pending improvements, legacy clean-up and bug fixes on integration.

New delegates might be a nice addition, but it's less important imo and can always be introduced in a `3.x.0` release later.

@nitriques @michael-e

**Comment by michael-e** [comment]
Agreed, if 3.0 is released in the next 3 months or so, and if there is an upgrade path from Symphony 2. Under these conditions I can even live with closing the feature set of 2.x completely.

However, I had the impression that there is no clear vision what 3.0 is/will be. This may be the reason why people love to work on 2.x.

**Comment by nitriques** [comment]
> Agreed, if 3.0 is released in the next 3 months or so,

I really do not think this will happen. That's why I wanted to move forward with a couple a new things that could be part of a 2.7.0 release.

> However, I had the impression that there is no clear vision what 3.0 is/will be

Same here. I feel like it's more @brendo's territory. But we've made some nice changes that could be released instead of sleeping...

**Comment by jensscherbl** [comment]
Closing in favor of [our new roadmap][1].

[1]:  https://github.com/symphonycms/symphony-2/milestones
