### ISSUE TITLE
Confusion regarding usage of constants

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2513]
In `content.publish.php`, the `__actionNew` and `__actionEdit` functions both use `__ENTRY_FIELD_ERROR__` and `__ENTRY_OK__` constants. However, the usage is inconsistent:

* in `__actionNew` we find `Entry::__ENTRY_FIELD_ERROR__` and `Entry::__ENTRY_OK__`
* in `__actionEdit` we find `__ENTRY_FIELD_ERROR__` and `__ENTRY_OK__`

`__ENTRY_FIELD_ERROR__` and `__ENTRY_OK__ ` [are deprecated](https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/lib/boot/defines.php#L284-L298), so this should be fixed.

I will send a PR.

**Comment by brendo** [comment]
Good find, thank you!

**Comment by nitriques** [comment]
Closed via #2514
