### ISSUE TITLE
Dependant Data Sources return no results

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2515]
https://github.com/symphonycms/symphony-2/commit/cbeca16ee0ff34c975683b6f2bd11ee728f65579 has broken dependant datasources, they may return no results. <strike>The problem is in [this line](https://github.com/symphonycms/symphony-2/commit/cbeca16ee0ff34c975683b6f2bd11ee728f65579#diff-7b1c0614581c083a06e31f0d3c4c13fdR979)</strike>

**Comment by michael-e** [comment]
But why???

**Comment by michael-e** [comment]
The problem is definitely in `class.frontendpage.php`. But I don't manage to get it right.

**Comment by michael-e** [comment]
Thanks!

**Comment by nitriques** [comment]
> I am lost. :-(

@michael-e check [this](https://github.com/symphonycms/symphony-2/commit/cbeca16ee0ff34c975683b6f2bd11ee728f65579#commitcomment-13939500) :)

**Comment by michael-e** [comment]
Thanks! Will you send a pull request to replace the quotes?

**Comment by nitriques** [comment]
There: 16dc3b8 Like a cowboy.

**Comment by michael-e** [comment]
:-)
