### ISSUE TITLE
Add Gitter sidecar to getsymphony.com

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2516]
Would this be a good idea ?

https://sidecar.gitter.im/ ?

**Comment by jonmifsud** [comment]
I would think so if there's someone around on Gitter it would be good. The
problem would be if nobody is around to answer chats. we don't want to look
like there's nobody in a position to help. I think we can give it a shot
and evaluate?

**Comment by nitriques** [comment]
> The problem would be if nobody is around to answer chats. 

I read it almost every morning

> I think we can give it a shot and evaluate?

That's my proposition

**Comment by nitriques** [comment]
This is done!
