### ISSUE TITLE
Wrap SQL error message in CDATA

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2518]
Like [here](https://github.com/symphonycms/symphony-2/blob/master/symphony/template/blueprints.datasource.tpl#L51).

It should be

``` php
$result->appendChild(new XMLElement('error', 
    General::wrapInCDATA($e->getMessage() . ' on ' . $e->getLine() . ' of file ' . $e->getFile())
));
```

@jensscherbl is that a breaking change ? It never contained xml... (I feel it's a bug fix, since it can crash the whole frontend because xml bla bla bla)

**Comment by jensscherbl** [comment]
> @jensscherbl is that a breaking change ?

Is this just for real exceptions, like SQL errors? Then no. Or also for expected results, like an empty result set or not executed data sources because of parameters etc. Then yes.

**Comment by nitriques** [comment]
It's for all of them, so it is. Bump to 2.7.0
