### ISSUE TITLE
2.6.4 installation does not redirect to login after is complete

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2522]
after installing (for both, git install or zip download)

let's say i set the admin path to **dashboard**
after the installation is complete, i hit the button to go at the login form, but i get:

*"Page not found" The page you requested, /dashboard/, does not exist.*

same

if i try to acces the login form the old fashion way **/symphony** i can see the form, but the form redirects also to a 404 page

*The page you requested, /dashboard/login/, does not exist.*

**Comment by michael-e** [comment]
Confirmed. Hopefully @nitriques has an idea how this happened.

**Comment by nitriques** [comment]
What I experienced was that the form action attribute was set to the correct value, i.e. my custom admin path. The config.php file contained my value as the admin path.

I've made a lot of diff in the last 45 minutes and could not find a single line that would explain this change in 2.6.4.

I could not find any code that replaces the path in the .htaccess file tho.... And that's the only thing need to change that 404 to a working url....

@michael-e can you confirm tha fixing the .htaccess fixes the problem ?

**Comment by nitriques** [comment]
This does not helper either.. https://github.com/symphonycms/symphony-2/commits/master/install/includes/htaccess.txt

**Comment by munki-boy** [comment]
@nitriques yes it didn't write the custom admin path in .htaccess in two places I can find.

**Comment by munki-boy** [comment]
Does work fine in 2.6.3 clean install. As usual I'm on win x64 WAMP :)

**Comment by nitriques** [comment]
I can't find the code that does this in 2.6.3... total mistery..

**Comment by munki-boy** [comment]
In symphony\lib\boot\bundle.php: 

lines under "// Handle custom admin paths, #702" are different, is it there?

**Comment by munki-boy** [comment]
Swapping those lines from 2.6.3 to 2.6.4 does fix the problem while both sites are already installed.  I'm not able to see if that causes other problem.

**Comment by nitriques** [comment]
Yes but they should do the same thing... that's VERY weird... Also, it's not htaccess related...

> Swapping those lines from 2.6.3 to 2.6.4 does fix the problem while both sites are already installed.

So the htaccess rewrite do contains your custom path ?

**Comment by munki-boy** [comment]
The .htaccess doesn't contain my custom path in this test and AFAIK it's not supposed to change in the .htaccess

Under 2.6.3 you can visit custom path with the standard .htaccess that only shows the standard path rewrites. 

Here is my current 2.6.4 that is working with the 2.6.3 version of // Handle custom admin paths, #702 code.

    ### ADMIN REWRITE
    RewriteRule ^symphony\/?$ index.php?mode=administration&%{QUERY_STRING} [NC,L]

    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^symphony(\/(.*\/?))?$ index.php?symphony-page=$1&mode=administration&%{QUERY_STRING}   [NC,L]



I did get confused in my first comment above about .htaccess because I'd edited myself to try and "get in". so put "ignore this...".

**Comment by munki-boy** [comment]
Something's wrong when I login though....  wait a minute...

**Comment by munki-boy** [comment]
Since I made the code change 2.6.4 is asking to upgrade from 2.6.3 to 2.6.4 very weird, I'm going to do a quick 2.6.4 re-install to be sure.

**Comment by munki-boy** [comment]
FF cache? not sure what happened but yes I can definitely confirm the 2.6.3 code does the fix as I described above.  Here's a screen grab with working backend on custom path "admin".
![screen](https://cloud.githubusercontent.com/assets/4517581/11507576/8aaec350-984c-11e5-9853-957f2a0e0fa0.jpg)

:)

**Comment by nitriques** [comment]
Ok thanks a lot @munki-boy I'll check this ASAP.

**Comment by munki-boy** [comment]
Thanks @nitriques for all your work :+1:

**Comment by nitriques** [comment]
My pleasure, thanks for debugging this with me.

And just to be sure, we are talking about those line right ?

![image](https://cloud.githubusercontent.com/assets/771169/11507832/e18ea704-9823-11e5-86b6-e725f8041ef3.png)

**Comment by nitriques** [comment]
Does it enters the if statement ?

**Comment by munki-boy** [comment]
This is the block in 2.6.3 

![code](https://cloud.githubusercontent.com/assets/4517581/11507994/86c0c4b2-984e-11e5-988d-d34c86a4aef3.jpg)

**Comment by munki-boy** [comment]
If you copy it and overwrite the same block in 2.6.4 it works - still I don't know why it changed or if it will cause another problem elsewhere.

**Comment by nitriques** [comment]
> still I don't know why it changed 

I would crash the system completely if you pass a nicely crafted url... see #2504

**Comment by munki-boy** [comment]
Safely in localhost for now :)

**Comment by munki-boy** [comment]
What about the installer does edit the .htaccess to the custom path?  Also makes default path unavailable when custom path is chosen. Better for security?

**Comment by nitriques** [comment]
> What about the installer does edit the .htaccess to the custom path? 

From what I can see in the code, I never did: everything was handled by php...

>  Also makes default path unavailable when custom path is chosen. Better for security?

I think I would, but the possibility that it crashed your .htaccess file is high...

**Comment by munki-boy** [comment]
Oh yes, because the admin path is available to edit anytime in the config.php and not just at install time.

**Comment by munki-boy** [comment]
The if statement in 2.6.3 evaluates to 0 and in 2.6.4 it evaluates to 1 so if block doesn't run in 2.6.4?

**Comment by munki-boy** [comment]
No, that depends on a custom path set or not...

**Comment by munki-boy** [comment]
I think there's an extra '/' before custom path in 2.6.4 that makes the if block not run.

        var_dump(getCurrentPage());
        var_dump($_GET['symphony-page']);die;

string '/admin/' (length=7)

string 'admin/' (length=6)

**Comment by nitriques** [comment]
Damn! You found it ! At least, it's not my fault hahaha https://github.com/symphonycms/symphony-2/blame/cd6ee3adf51881f9e540011d806531121111534b/symphony/lib/boot/func.utilities.php#L82

It's really important to use superglobals less and less... So I'll check every calls to `getCurrentPage()` introduced in 2.6.4, Thanks!

**Comment by nitriques** [comment]
Well it kind of is my fault tho.. ;)

**Comment by munki-boy** [comment]
Hey, did I just 'contribute' :)

**Comment by nitriques** [comment]
You certainly did!

**Comment by brendo** [comment]
Good debugging guys!

**Comment by cmnstmntmn** [comment]
does 2.6.4 branch will get fixed or, will land, later, in 2.6.5 ?

**Comment by brendo** [comment]
It'll land in 2.6.5, 2.6.4 will be swiftly replaced.

**Comment by nitriques** [comment]
> Good debugging guys!

He indeed beat both of us :) I'am working on the fix right now

**Comment by nitriques** [comment]
Based on the diff between [2.6.3 and 2.6.4](https://github.com/symphonycms/symphony-2/compare/2.6.3...2.6.4) The only place where we need patching is in [the bundle](https://github.com/symphonycms/symphony-2/compare/2.6.3...2.6.4#diff-0b4d9877953cc72392c6f1986b21503dR34)

[getCurrentPage()](https://github.com/symphonycms/symphony-2/blob/cd6ee3adf51881f9e540011d806531121111534b/symphony/lib/boot/func.utilities.php#L82) will always return a value that starts with / so I'll add a check for this.

**Comment by nitriques** [comment]
Please check the commit message ! Thanks again @munki-boy !

**Comment by munki-boy** [comment]
Thanks @nitriques I'm going to look now :)

**Comment by nitriques** [comment]
@munki-boy Thanks! Please report any bugs :+1:

**Comment by munki-boy** [comment]
I did give it a quick try and seems to work ok.  I'm not actually using it in production, just thought I'd try to squash a bug with you. Just learning stuff :+1: 

@cmnstmntmn might give it a proper test?

**Comment by nitriques** [comment]
Thanks!

**Comment by brendo** [comment]
Just a sidenote that this _shouldn't_ have any side effects. With PHP5.2 support, this change would of caused issues as PHP 5.2 could not derive a date from an unknown format.

**Comment by nitriques** [comment]
@brendo wrong issue ? This is not date related...

**Comment by andrewminton** [comment]
Would this account for issues I experienced with 2.6.4 using a custom admin url? I set it to 'manage' instead of 'symphony' on the install page and didn't get redirected but saw an error page stating that the page did not exist.

**Comment by munki-boy** [comment]
@andrewminton Yes that's the bug we found, just grab @nitriques patched version and it works fine.
