### ISSUE TITLE
$arguments has extra '...' characters on integration

### ISSUE THREAD

**Issue by andrewminton** [symphonycms/symphony-2#2528]
I'm guessing these '...' characters should not be in the code?

https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.database.php#L105

and 

https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.database.php#L147

and 

https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.database.php#L157

After installing a local copy and attempting an install I encountered the error that lead me to these 3 lines.

Once removed, the install went ahead fine.

**Comment by nitriques** [comment]
Hum... @brendo  ?

**Comment by brendo** [comment]
That my friends is the splat operator, aka [variadic functions](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics) available in PHP 5.6.

Integration was going to target PHP 5.6+ (a just move given that PHP 7 is now released).

**Comment by andrewminton** [comment]
Thanks for info. Just thinking about the release cycle and the adoption of php 5.6 out in the wild. Is it worth some sort of fallback?

**Comment by nitriques** [comment]
> Is it worth some sort of fallback?

At this stage, I do not think so!
