### ISSUE TITLE
404 on all pages except index page... ?

### ISSUE THREAD

**Issue by AeonFr** [symphonycms/symphony-2#2531]
I've just finished installing symphony on my localhost on ubuntu. I grabbed the code from this repository and then proceed as it's instructed in the [install symphony](http://www.getsymphony.com/learn/tutorials/view/install-symphony/) tutorial (I also cloned the default workspace from github).

Now, when the installation got finished a message appeared saying... would you like to access your admin page now? or something alike, and.. BUM! 404 page...

So I thought... I should have used the default admin page! I  check'd my `config.php` and .htaccess files as sugested in issue @2522. But the real strange thing is that I can definitely see the index page of my blog, but if I click on "Archive", "About", "Comments", the post tile ("A primer to Symphony 2's default theme") I get 404 errors.

My installation is not in the document root by the way, but I don't think that's what causing issues.
 
Another weird behaviour I've noticed is that when I enter `/symphony` apache throws a directory listing... Isn't that insecure?  
After noticing this I've enabled mod_rewrite typing `sudo a2enmod rewrite` in the console (if I type again, it says `Module rewrite already enabled`). I have restarted apache after enabling the module. But everithing listed above hasn't changed. I still get 404 errors and I can still see the structure of the symphony folder by entering `/symphony`

**Comment by michael-e** [comment]
In your Apache configuration, you should have `Options -Indexes` and `AllowOverride all`, e.g.:

	<Directory /var/www/www.example.com/>
		Options -Indexes
		AllowOverride all
		Order allow,deny
		Allow from all
	</Directory>

(On shared hosts, these are standard.)

**Comment by nitriques** [comment]
> Another weird behaviour I've noticed is that when I enter /symphony apache throws a directory listing... Isn't that insecure?

This is the default behavoir of Apache. Like @michael-e said `Options -Indexes` in the htaccess should fix the problem.

>  I still get 404 errors and I can still see the structure of the symphony folder by entering /symphony

Can you show us the content of your .htaccess file ?

**Comment by AeonFr** [comment]
Hi, my apache config already had the AllowOverride set to All
```
<Directory />
	# Options FollowSymLinks
	Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Order allow,deny
	Require all granted
</Directory>
```

Here's my _.htaccess_
```
### Symphony 2.6.x ###
Options +SymLinksIfOwnerMatch -Indexes

<IfModule !mod_rewrite.c>
    SetEnv HTTP_MOD_REWRITE No
</IfModule>

<IfModule mod_rewrite.c>

    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine on
    RewriteBase /short_stories/symphony

    ### SECURITY - Protect crucial files
    RewriteRule ^manifest/(.*)$ - [F]
    RewriteRule ^workspace/(pages|utilities)/(.*)\.xsl$ - [F]
    RewriteRule ^(.*)\.sql$ - [F]
    RewriteRule (^|/)\. - [F]

    ### DO NOT APPLY RULES WHEN REQUESTING "favicon.ico"
    RewriteCond %{REQUEST_FILENAME} favicon.ico [NC]
    RewriteRule .* - [S=14]

	### IMAGE RULES
	RewriteRule ^image\/(.+)$ extensions/jit_image_manipulation/lib/image.php?param=$1 [B,L,NC]

	### CHECK FOR TRAILING SLASH - Will ignore files
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_URI} !/$
    RewriteCond %{REQUEST_URI} !(.*)/$
    RewriteRule ^(.*)$ $1/ [L,R=301]

    ### URL Correction
    RewriteRule ^(symphony/)?index.php(/.*/?) $1$2 [NC]

    ### ADMIN REWRITE
    RewriteRule ^symphony\/?$ index.php?mode=administration&%{QUERY_STRING} [NC,L]

    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^symphony(\/(.*\/?))?$ index.php?symphony-page=$1&mode=administration&%{QUERY_STRING}   [NC,L]

    ### FRONTEND REWRITE - Will ignore files and folders
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*\/?)$ index.php?symphony-page=$1&%{QUERY_STRING}    [L]

</IfModule>
######
```
Symphony is installed on /short_stories/symphony (relative to DocumentRoot)

**Comment by michael-e** [comment]
Glad that you figured it out!

**Comment by nitriques** [comment]
Great!
