### ISSUE TITLE
Unify the styling of non-editable fields (simple label+value-pairs) in the publish area

### ISSUE THREAD

**Issue by twiro** [symphonycms/symphony-2#2532]
While [updating](https://github.com/symphonists/system_date_fields/pull/14) the "**System Date Fields**" extension the question came up how a field that only exists out of a label and an uneditable (and short) value should be properly styled.

![screen shot 2015-12-15 at 13 56 58](https://cloud.githubusercontent.com/assets/870227/11811148/f94e4f8c-a333-11e5-9b18-0ea61b95da3d.png)

There seems to be no proper styling solution yet, and while I first proposed to at least align the styling to what extensions like **members** and **member last visit** already do I must admit that I actually don't think they're doing it right in "hijacking" the right-floated `<i>`-element that's used for marking a field as optional. Not only does this tear apart label and value more than reasonable (especially in the main column), but also creates a big gap beneath due to the default minimum height of a field.

![screen shot 2015-12-15 at 11 13 44](https://cloud.githubusercontent.com/assets/870227/11810813/56ada91e-a331-11e5-8702-728d67624a84.png)

I mocked up some possible solutions and do post them here, cause this concerns multiple fields/extensions and therefore the styling should better be provided by the core and then be adopted by all affected extensions.

---

### A) Adopt the styling of reflection field

![screen shot 2015-12-15 at 10 37 24](https://cloud.githubusercontent.com/assets/870227/11810539/1f725da2-a32f-11e5-992a-91e0b4e1595a.png)

This would solve the alignment- and gap-issues described above.
But despite the grey color it looks too editable & input-like in my eyes.

---

### B) Intensify the readonly/uneditable-look

![screen shot 2015-12-15 at 10 40 15](https://cloud.githubusercontent.com/assets/870227/11810558/3f10bf82-a32f-11e5-916c-83ad4b3fceb9.png)

Combining this with a soft grey background works better, but still the input-like look feels a little exagaggerated for this type of data...

---

### C) Return to a less input-like look

![screen shot 2015-12-15 at 10 37 15](https://cloud.githubusercontent.com/assets/870227/11810562/460d3f54-a32f-11e5-963f-64e6cf042ef5.png)

Removing the border while keeping the bigger and greyed out font as well as the default height/alignement-behavior feels like the right solution to me - everything is properly aligned, it's easy so separate between the label and the value of the field and it doesn't imply to be something editable.

---

I also thought about placing the system dates as a kind of meta-info in the footer area next to the save-button (I actually like the idea), but that might be problematic for other fields like the one from members.

@nitriques - ok with solution C? I could send a PR for 2.6.5 and also try to set up PRs for the affected extensions.

**Comment by nitriques** [comment]
Yeah go ahead for solution C.

It's only a matter of adding a new css class right ? And extension will be able to build on that ?

**Comment by twiro** [comment]
> _Yeah go ahead for solution C._

Great - will do so tomorrow!
You already have a date in mind for releasing 2.6.5?

> _It's only a matter of adding a new css class right ? And extension will be able to build on that ?_

Exactly. One additonal class that offers the shown styling and can be adopted by all extensions that display simple & uneditable label/value-pairs.

I guess this has to go in [symphony.forms.css](https://github.com/symphonycms/symphony-2/blob/master/symphony/assets/css/src/symphony.forms.css) and might share most of the styling with the first set of rules. Might ask Nils about some advice regarding "smyphony css best practices" though.

**Comment by nitriques** [comment]
> You already have a date in mind for releasing 2.6.5?

I would try to do it tomorrow... (thursday)

> I guess this has to go in symphony.forms.css and might share most of the styling with the first set of rules.

Right!

**Comment by twiro** [comment]
Hey Nicolas - will be back at work at around 3am (GMT) and take care of this!

[ von unterwegs ]

**Comment by nitriques** [comment]
Thanks!

**Comment by nitriques** [comment]
Merge and release with [2.6.5](https://github.com/symphonycms/symphony-2/releases/tag/2.6.5)
