### ISSUE TITLE
Request was rejected for having an invalid cross-site request forgery token.  Please go back and try again.  in PHP7.0

### ISSUE THREAD

**Issue by nonozone** [symphonycms/symphony-2#2533]
I just recently upgraded to php7.0, install a new symphonycms, when I login the backgend, after I enter the account and  password,it notice:

```
Access Denied

Request was rejected for having an invalid cross-site request forgery token.

Please go back and try again.
```

And,I had added this code in config.php,but the problem has not been solved

```
'token_lifetime' => '15 minutes',
'invalidate_tokens_on_request' => null,
```

Debian 8/PHP7.0-FPM/Mysql-server-5.5

**Comment by nitriques** [comment]
> I just recently upgraded to php7.0,

Right now, php 7.0 is not supported (I never tester it)

Coud you try setting `'enable_xsrf' => 'no',` in the symphony section of the config.php file ?

**Comment by nonozone** [comment]
I set ```'enable_xsrf' => 'no' ```,and I enter the username and passwd,there is no error, but can not log in the backend.

**Comment by nitriques** [comment]
Any errors in your error_log file ? Or in symphony's logs ?

**Comment by nitriques** [comment]
And are you running 2.6.4 (latest master branch) ?

**Comment by nonozone** [comment]
in  logs/main 
···

105 12/16/2015 11:50 am > User Notice: FrontendPageNotFoundException 1024 - The page you requested, <code>/favicon.ico/</code>, does not exist. on line 328 of /srv/www/n.fob.im/public_html/symphony/lib/toolkit/class.frontendpage.php
106 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
107 12/16/2015 11:50 am > User Notice: FrontendPageNotFoundException 1024 - The page you requested, <code>/favicon.ico/</code>, does not exist. on line 328 of /srv/www/n.fob.im/public_html/symphony/lib/toolkit/class.frontendpage.php
108 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
109 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
110 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
111 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
112 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
113 12/16/2015 11:50 am > Warning: GenericErrorHandler 2: session_decode(): Session is not active. You cannot decode session data on line 198 of file /srv/www/n.fob.im/public_html/symphony/lib/core/class.session.php
···

yes 2.6.4

**Comment by nitriques** [comment]
> Warning: GenericErrorHandler 2: session_decode(): Session is not active. 

This is the problem. You should stick to php 5.6 for now in order to use symphony...

**Comment by nonozone** [comment]
It does not matter, this is just my local testing.

**Comment by brendo** [comment]
Keep in mind that [there are several](http://php.net/manual/en/migration70.incompatible.php) backwards compatible changes that will need to be made to the Symphony codebase so that it's PHP 7 compatible.

I might have a poke around at doing this over the Xmas/New Year break out of curiosity.

**Comment by nitriques** [comment]
@brendo Thanks!

We should then updates the website with

`PHP 5.3 through 5.6`

And the readme too. Right ?

**Comment by brendo** [comment]
Yeah, that's a good idea, would probably save some heartache for new developers.

**Comment by nitriques** [comment]
Great. I think I can update it with my new acces ? :) It's not in the backend right ?

**Comment by nitriques** [comment]
This should be fixed with #2552 :)

**Comment by rc1** [comment]
While Symphony 2.6.7 is the download on the website, changing the text on the website saying "PHP 5.3 or above" would be a help for everyone

**Comment by nitriques** [comment]
@rc1 It's been done, see #2652 Thanks!
