### ISSUE TITLE
Create 2.6.5 release

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2535]
AFAIK, there have been some important bugfixes in the 2.6.x branch. I suggest to release Symphony 2.6.5

**Comment by twiro** [comment]
+1 for a 2.6.5-release for christmas :)

@nitriques - do you think about updating [**export ensemble**](https://github.com/symphonycms/export_ensemble/issues/22) before releasing a new version/bundle? Thank you!

**Comment by nitriques** [comment]
Yes! I planned it before x-mas, but could not afford the time to do it properly.

I will try to do it ASAP.

**Comment by nitriques** [comment]
Here are the steps that needs to be made so you guys can follow my progress :)

- [ ] Create a new migration for the new version, eg. 2.6.5 which should implement getVersion and getReleaseNotes methods
- Update the version constant in the project:
- [ ] package.json
- [ ] composer.json
- [ ] .htaccess (optional)
- [ ] install/index.php
- [ ] install/includes/htaccess.txt (optional)
- [ ] LICENCE (optional)
- [ ] symphony/assets/js/src/symphony.js (optional)
- [ ] Update the README.md file, replacing the version constant and updating any metadata as required
- [ ] Create a commit, usually Release 2.6.x and push to the corresponding branch. Testing at this point is recommended!
- [ ] Checkout the master branch and merge in the 2.6.5
- [ ] Create an associated tag for the release, eg. 2.6.5
- [ ] FIx bundle download
- [ ] Generate doc
- [ ] Upload doc

**Comment by brendo** [comment]
Let me know if you want a hand with this. We need to get this out ASAP.

**Comment by nitriques** [comment]
> Let me know if you want a hand with this.

I should be ok with most of it thanks! The biggest problem is with the current download button on getsymphony.com which always points to the master branch (instead of the uploaded version)

**Comment by nitriques** [comment]
@brendo Could you generate and upload the doc for 2.6.4 since I can't do it ? And maybe the same for 2.6.5 .. ?

**Comment by brendo** [comment]
Done for 2.6.4. I'll do 2.6.5 once it's released.

**Comment by brendo** [comment]
> I should be ok with most of it thanks! The biggest problem is with the current download button on getsymphony.com which always points to the master branch (instead of the uploaded version)

Don't stress about this. No one has noticed it for several years!

**Comment by diomed** [comment]
what do you think about updating moment.js which is currently on v. 2.10.6 while symphony still has 2.9.0
https://github.com/symphonycms/symphony-2/blob/master/symphony/assets/js/lib/moment.min.js

**Comment by brendo** [comment]
I think it's a good idea so long as there are no breaking changes

**Comment by nitriques** [comment]
@diomed Yes it will be done, but not in a patch release ;) Thanks!

> Don't stress about this. 

There isn't ;)

**Comment by nitriques** [comment]
@brendo Thanks for the docs :rocket:

**Comment by munki-boy** [comment]
> Don't stress about this. 

Sorry it was me again, spotted it while downloading a copy then mentioned it on Gitter. No hassle ;)

**Comment by nitriques** [comment]
@munki-boy No we found it before you hahaha ;)

**Comment by brendo** [comment]
This needs to go out this week. #2522 is a fairly poor experience for users and with the new year there may be new users evaluating us for the first time. This isn't a great first impression.

**Comment by nitriques** [comment]
@brendo I'd like to do it tomorrow. I've been busting my ass on some bugs in clients projects since the beginning of 2016 which delayed this. If you feel like it's urgent and want to do it, please go ahead.

**Comment by nitriques** [comment]
@brendo It's out! Would you mind generating the doc and uploading it please ?

**Comment by nitriques** [comment]
It's out! http://www.getsymphony.com/download/releases/version/2.6.5/

**Comment by michael-e** [comment]
Great, thank you very much!

**Comment by nitriques** [comment]
My pleasure :)

**Comment by twiro** [comment]
Thank you very much for releasing 2.6.5 Nicolas...

>  updating export ensemble for @twiro :)

...and updating **export ensemble** especially for me ;)
I do hope others benefit as well :)

**Comment by nitriques** [comment]
Hehehe I like to make things personal ;)
