### ISSUE TITLE
Include Core Email API docs in Symphony Wiki?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2540]
A long time ago I started this: https://github.com/michael-e/core-email-api-docs

@nitriques, what do you think about including these in the Wiki? (I think that meanwhile only the "developer-documentation" file is interesting, the rest might be thrown away.)

Or should we transfer the whole repo to the Symphony owner?

**Comment by nitriques** [comment]
Yes please add it to [the wiki](https://github.com/symphonycms/symphony-2/wiki)

I think you can merge both of your files into a single one ! And add the entry on the wiki home page !!

You should have access to it.

**Comment by michael-e** [comment]
Will do.

**Comment by nitriques** [comment]
Thanks!

**Comment by michael-e** [comment]
Done: https://github.com/symphonycms/symphony-2/wiki/Email-in-Symphony

I also added a link to the wiki's homepage. I didn't know where to put it, so I created a completely new section. Please feel free to improve this.

**Comment by nitriques** [comment]
That's perfect Micheal, thanks!

**Comment by michael-e** [comment]
You're welcome!
