### ISSUE TITLE
Updater fails to fix Date Fields

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2541]
There must have been a change in the Date Field somewhere between Symphony 2.3.6 anbd 2.6.5. Now, the `pre_populate` column can contain words like "now" and must be left empty if you don't want to pre-populate.

I updated some websites, and the former values "yes" and "no" were left in the database fields. Both will result in the current date being populated.

The updater should remove "no" values and replace "yes" with "now".

**Comment by nitriques** [comment]
@michael-e could you find the exact version where this breakage occurred ? I'll try to fix it.

**Comment by michael-e** [comment]
Here it is: https://github.com/symphonycms/symphony-2/blob/master/install/migrations/2.4.0.php#L54

**Comment by nitriques** [comment]
Thanks! Should we patch the 2.4.0 file ? Or do it in a new release ?

**Comment by michael-e** [comment]
Best would be both. :-)

* For 2.4.0 migration, do the right stuff.
* For the next release, check if it has been done right; if not, do it .

**Comment by nitriques** [comment]
Hum I do not see any problems with doing it twice, but I do not like the code duplication...

**Comment by michael-e** [comment]
If you want to be sure that it works for everybody, hmmm…

BTW, it was @brendo: https://github.com/symphonycms/symphony-2/commit/28afcf4dc95a93ca55cdf9c8d22f3b6dc0a73c74

**Comment by nitriques** [comment]
Interesting...

**Comment by brendo** [comment]
Hmm, the update is a little dodgy, but as the comments suggest on the commit the field goes to handle the old values. What I didn't account for was `no` :(

**Comment by michael-e** [comment]
No prob, mate. Most of the time I run into this little quirks. :-))

**Comment by nitriques** [comment]
@brendo How (or where) would you fix it?

**Comment by nitriques** [comment]
@brendo Ping mate sorry! I would need your help on how to deal with it...

**Comment by brendo** [comment]
Two possible solutions:

- Patch the date field [about here](https://github.com/symphonycms/symphony-2/commit/28afcf4dc95a93ca55cdf9c8d22f3b6dc0a73c74#diff-b6f08cd640a009880b2c2bd30b224783R360) so it'll handle 'yes' => 'now', 'no' => null, otherwise the value of pre_populate.
- Update the existing migration after the table has changed to change all 'yes' values to 'now', and to null any rows that have 'no'.

**Comment by nitriques** [comment]
Ok thanks mate.

**Comment by nitriques** [comment]
Well, looking at the current code Brendan mention we are ok. [But this would need a fix](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/fields/field.date.php#L529) and [here](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/fields/field.date.php#L610) and multiple other places.

So let's fix the installer in 2.7.0 and change Brendan's line ;) Thanks
