### ISSUE TITLE
Readonly dashboard authors

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2542]
as an enhancement, there would be great to limit user's access to sections entries, 
per section or globally; as is implemented in [django admin](http://i.stack.imgur.com/hnXei.png).

**Comment by jonmifsud** [comment]
There is an extension which does take care of Author roles, I'm aware it might be due some love. If you're in urgent need for this ping me within the coming weeks, to see your exact needs and if the extension covers your needs as is.

**Comment by andrewminton** [comment]
I've updated Author Roles and there is a pull request in discussion at the moment to fix a little bug. I have it working on 2.6.4 locally.

**Comment by twiro** [comment]
> I've updated Author Roles and there is a pull request in discussion at the moment to fix a little bug. I have it working on 2.6.4 locally.

That's great @andrewminton ! I'm about to update an older site that makes heavy use of this extension and wasn't sure if that would work. Great to know it does :)

On another note: I recently contacted [Twisted Interactive](https://github.com/TwistedInteractive) regarding maintenance/ownership of one of their long unmaintained extensions ([reflected upload field](https://github.com/TwistedInteractive/reflecteduploadfield)) and they told me they'd be ok with transferring ownership to me _(though it hasn't happened yet - will have to ask again next week)_.

I also proposed to transfer ownership of their two most popular (and also unmaintained) extensions **[author roles](https://github.com/TwistedInteractive/author_roles)** and **[import csv](https://github.com/TwistedInteractive/importcsv)** to the symphonists-account - but maybe you want to jump in regarding **author roles** if you're actively using & maintaining it?

**Comment by munki-boy** [comment]
@twiro Maybe mention Import CSV on Gitter because me and @animaux were just using Remote DS and XML Importer.  I'm a bit behind on my job and didn't get everything working yet but I think the integration branch of XML Importer now does everything Import CSV did.  Maybe Import CSV only needs legacy support? @animaux might confirm better.

**Comment by nitriques** [comment]
@cmnstmntmn Some nice people will open source a solution I've worked with them that will solve this.

We just need to release [some new delegates](https://github.com/DeuxHuitHuit/symphony-2/tree/authors-del) and this could only be done for 2.7.x ... stay tune!

> to the symphonists-account 

@twiro I've ask them too, but never got an answer... But I think it would be better to move them under your name ;)

**Comment by jonmifsud** [comment]
hah @nitriques looking forward to see what delegates you're adding I've
added a delegate before for membership management let me know when you add
the PR as I might have something different I'd like to add.

**Comment by nitriques** [comment]
@jonmifsud Perfect!

**Comment by cmnstmntmn** [comment]
just great, great, great!

**Comment by nitriques** [comment]
:D It's section based AND entries based (meaning some users only see and subset of all entries)

**Comment by jonmifsud** [comment]
same here I had something like that... but interested to see what you came
up with :)

**Comment by nitriques** [comment]
This as been done in #2686
