### ISSUE TITLE
Deprecate DynamicXMLDatasource?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2543]
Maybe I have overseen something, but shouldn't the DynamicXMLDatasource (`/symphony/lib/toolkit/data-sources/class.datasource.dynamic_xml.php`) be deprecated? It isn't used in Symphony anymore, because this functionality has been superseded by the Remote Datasource extension.

**Comment by jonmifsud** [comment]
I second Michael's suggestion - I don't think we want to keep it as a
legacy component indefinitely

**Comment by nitriques** [comment]
There you go guys :+1:

**Comment by michael-e** [comment]
Thanks a lot!

**Comment by michael-e** [comment]
BTW, I think that many issues will be closed automatically when PRs are accepted. So is it useful to tag others "Fixed in 2.6.x" and leave them open (like this one)?

**Comment by nitriques** [comment]
>  many issues will be closed automatically when PRs are accepted

If the commit contains `fixed #issue` or `closes #issue` yes it does, but only when the commit gets pulled into master (not when the PR is merged)

>  "Fixed in 2.6.x"

It makes filtering easier for me, that's all ;)

**Comment by michael-e** [comment]
Ah, thanks for explaining!

**Comment by nitriques** [comment]
> Ah, thanks for explaining!

My pleasure  :)

**Comment by brendo** [comment]
From memory you can't actually create or edit dynamic xml data sources anymore from the UI. That's been that way for a little while I think :)

**Comment by brendo** [comment]
Yep, we mention it in the [2.6](http://www.getsymphony.com/download/releases/version/2.6.0/) release notes that it's deprecated, so you could definitely update the copy to reflect that it was deprecated in 2.6

**Comment by nitriques** [comment]
Thanks @brendo for this rectification. It's been fixed ;)
