### ISSUE TITLE
Add delegate to allow manipulations before checking a field's post data

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2545]
Several examples of advanced manipulations of post data and/or field behaviour have been disussed in the past. Right now, I have once again worked on the idea of having "conditionally required" fields (depending on the post data of other fields).

My idea is to use a custom extension (which may contain hardcoded rules for a single website, why not...).

I added a delegate in `class.entry.php`:

``` php
public function checkPostData($data, &$errors = null, $ignore_missing_fields = false)
{
    $status = Entry::__ENTRY_OK__;
    $section = SectionManager::fetch($this->get('section_id'));
    $schema = $section->fetchFieldsSchema();

    foreach ($schema as $info) {
        $message = null;
        $field = FieldManager::fetch($info['id']);

        Symphony::ExtensionManager()->notifyMembers(
            'EntryPreCheckPostFieldData',
            class_exists('Administration', false) ? '/backend/' : '/frontend/',
            array(
                'field' => &$field,
                'post_data' => &$data
            )
        );

        if ($ignore_missing_fields && !isset($data[$field->get('element_name')])) {
            continue;
        }

        if (Field::__OK__ !== $field->checkPostFieldData((isset($data[$info['element_name']]) ? $data[$info['element_name']] : null), $message, $this->get('id'))) {
            $status = Entry::__ENTRY_FIELD_ERROR__;
            $errors[$info['id']] = $message;
        }
    }

    return $status;
}
```

This allows me to do the following in an extension (which subscribes to the delegate):

``` php
/**
 * Before checking a field's POST data,
 * manipulate the field object or POST data.
 *
 * @uses EntryPreCheckPostFieldData
 * @param string $context
 * @return void
 */
public function entryPreCheckPostFieldData($context)
{
    if ($context['post_data']['someselectboxlinkfield'] === '303368'
        && ($context['field']->get('id') === '415' || $context['field']->get('id') === '1315')) {
        $context['field']->set('required', 'yes');
    }
}
```

As you see, I have created two "conditionally required" fields. More might be possible. :-)

I post this here to discuss if the delegate is a useful addition to the Symphony core. Maybe it can even be improved.

**Comment by nitriques** [comment]
I like it very much.

I would add the $error variable and the $section variable in there too.

**Comment by michael-e** [comment]
Yes, you are right. I will prepare something… the delegate needs a comment as well.

**Comment by nitriques** [comment]
Indeed. No stress ;)

**Comment by michael-e** [comment]
What about this?

```php
/**
 * Prior to checking a field's post data.
 *
 * @delegate EntryPreCheckPostFieldData
 * @since Symphony 2.7.0
 * @param string $context
 * '/backend/' resp. '/frontend/'
 * @param object $section
 *  The section of the field
 * @param object $field
 *  The field, passed by reference
 * @param array $post_data
 *  The post data, passed by reference
 * @param array $errors
 *  The errors, passed by reference.
 */
Symphony::ExtensionManager()->notifyMembers(
    'EntryPreCheckPostFieldData',
    class_exists('Administration', false) ? '/backend/' : '/frontend/',
    array(
        'section' => $section,
        'field' => &$field,
        'post_data' => &$data,
        'errors' => &$errors
    )
);
```

BTW, to which branch should I send a PR for this?

**Comment by michael-e** [comment]
One thing that came to my mind: Passing the complete errors array by reference makes this rather error-prone. Sort of "We hope you know what you do." We might think about passing only the error of the field in question (which is `$errors[$field->get('id')]` in this context, or simply `$errors[$info['id']]`). But on the other hand, this would make it less flexible.

What do you think?

**Comment by jonmifsud** [comment]
Quite frankly I hope anyone playing with delegates and creating extensions
knows what they're doing or at least reads some documentation / how the
stuff works. If it's a question of it not being documented I guess we just
make a small note in the wiki at the very least.

**Comment by nitriques** [comment]
> But on the other hand, this would make it less flexible.

I though about the same thing and concluded the same as @jonmifsud did...

Also, `$errors[$field->get('id')]` might not exists so passing null by reference would crash (?)

**Comment by michael-e** [comment]
OK, so shall I send a PR? To which branch?

**Comment by michael-e** [comment]
Integration, right?

**Comment by nitriques** [comment]
Could you submit it against the newly 2.7.x branch ? I need to rebase integration and update my php setup in order to do so...

**Comment by michael-e** [comment]
Sure, I will submit against 2.7.x.

**Comment by nitriques** [comment]
Thanks.

**Comment by michael-e** [comment]
[Done](https://github.com/symphonycms/symphony-2/pull/2549)

**Comment by nitriques** [comment]
Thanks!
