### ISSUE TITLE
Publish Filtering: Duplicate help texts for default comparison mode "is"

### ISSUE THREAD

**Issue by twiro** [symphonycms/symphony-2#2546]
While working on some tweaks for the publish filtering interface i noticed that all core field types had duplicate help texts for the default comparison mode "is" in the html.

As only one help text (per filtering instance) is visible in the publish filtering interface one doesn't notice this until a field has a custom/different help text ([like number field does](https://github.com/symphonycms/numberfield/blob/master/fields/field.number.php#L208)). In this case the wrong (default) help text shows up instead of the right (custom) one.

The problem seems to derive from [these lines](https://github.com/twiro/symphony-2/blob/master/symphony/content/content.publish.php#L267-L272) as the filter help text for the default comparison mode „is“ is already provided by the [default field class since Symphony 2.6.0](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.field.php#L1178-L1208).

Removing these lines solved the problem for me and worked as expected with the core fields and some other extensions I'm currently testing the publish filtering interface with (number field, reflection field, association field).

@nitriques - As this bug isn't directly related to the [other issue](https://github.com/symphonycms/symphony-2/issues/2499) with the publish filtering interface I thought a separate PR would be the way to go... am I right or should I simply include this in the other PR (which is still in the works...)?

**Comment by nitriques** [comment]
Do as you wish ;) Thanks!

**Comment by twiro** [comment]
> _Do as you wish ;) Thanks!_

Submitted a separate PR as the other filtering stuff might take me a few days more before I can submit something!

And sorry for the first PR against the master branch... still a git(hub)-noob!

**Comment by nitriques** [comment]
No worries. Thanks.
