### ISSUE TITLE
Prepopulation not working for create new link in associations drawer

### ISSUE THREAD

**Issue by johnpuddephatt** [symphonycms/symphony-2#2550]
In 2.6.5, I have a Select Box field with dynamic values and have "Display associations in entries table" enabled.

Clicking "Create New" in the associations drawer (see screenshot below) doesn't work properly – the relevant field isn't pre-populated. Passing the value (e.g 'Percy') in the query string instead of the id (16 in this case) does work – it seems that the prepopulation of the selectbox will only work with a value rather than an ID, but the association drawer is trying to use an ID?

![screen shot 2016-01-27 at 09 23 42](https://cloud.githubusercontent.com/assets/8030910/12603032/7a4db09a-c4e1-11e5-92f6-429fb3d5cb63.jpg)

The filter link is also incorrect in the same way:

![screen shot 2016-01-27 at 09 23 38](https://cloud.githubusercontent.com/assets/8030910/12603126/6757b80e-c4e2-11e5-9ffc-14693bf798c2.jpg)

Outside of the associations drawer things are working properly, as the value is passed rather than the ID, e.g:

![screen shot 2016-01-27 at 09 23 05](https://cloud.githubusercontent.com/assets/8030910/12603160/ae4581e2-c4e2-11e5-9939-9eb3f3b16c54.jpg)

This is resulting from a very simple setup so hopefully easily to reproduce!

**Comment by nitriques** [comment]
Hum thanks @johnpuddephatt I'll look it up ASAP.

**Comment by nitriques** [comment]
Re #2650

**Comment by nitriques** [comment]
@johnpuddephatt this has been fixed in 2.7.x !
