### ISSUE TITLE
EntryManager::fetchByPage has no param to set sorting

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2553]
Sorting of paginated entries is a "global state" for the EntryManager.

When using `EntryManager::fetchByPage`, it's not possible to define a sorting directly in the function call. The sorting of entries will depend on two protected static variables of the EntryManager, `$_fetchSortField` and `$_fetchSortDirection`.

These variables can be set with public methods, e.g.`EntryManager::setFetchSorting`.

You may get surprising results if, for example, you are using delegates and callbacks while looping over entries (fetched using `fetchByPage`). If any sub-process calls `EntryManager::setFetchSorting`, this will influence the sorting/ordering of `EntryManager::fetchByPage`.

There are only two solutions to this: Either you must set the desired sorting manually (e.g. at the end of every loop in your script), or — much more elegant — we add a parameter to the `fetchByPage` method which allows to set the sorting with each call.

Note: `fetch` has a param called `$enable_sort` — you can switch off sorting here (which is no good idea, because the resulting sorting is undetermined).  `fetchByPage` has no such param.

**Comment by nitriques** [comment]
I am glad to report that this will be fixed in 3.0.0 :)

**Comment by nitriques** [comment]
This is now fixed, because fetchByPage and setFetchSorting are deprecated !
