### ISSUE TITLE
TMP dir logic may pollute Apache's error log

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2554]
In **certain virtual host environments** the TMP dir logic in `/symphony/lib/boot/defines.php` may pollute Apache's error log with warnings similar to this:

> Sat Jan 30 22:43:47 2016] [warn] [client 91.200.12.11] mod_fcgid: stderr: PHP
Warning:  is_writable(): open_basedir restriction in effect. File(/tmp) is not
within the allowed path(s): (/srv/www/htdocs/web1234/example.com/:/srv/www/htdocs/tmp/web1234/:/usr/share/php5/) in
/srv/www/htdocs/web1234/example.com/symphony/lib/boot/defines.php
on line 110

As pointed out by a [comment on php.net](http://php.net/manual/de/function.sys-get-temp-dir.php#97044), `sys_get_temp_dir` does not account for virtualhost-specific modifications to the temp path and/or `open_basedir` — it will return `/tmp`.

So in Line 108:

```php
$dir = @sys_get_temp_dir();
```

`$dir` will be `/tmp`.

Then in line 110:

```php
if ($dir == false || !is_writable($dir)) {
```

`is_writable` will throw the warning (at least on newer PHP versions, 5.6 in this case).

The fix would be simple: use `@is_writable`.

I can send a PR (to 2.7.x?) if you agree with this fix.

**Comment by michael-e** [comment]
Regarding the branch to send the PR to: Will we have another 2.7.x release? (In this case we might add it there as well.)

**Comment by michael-e** [comment]
Sorry for spoiling the version numbers. I fixed them in the posts above.

**Comment by nitriques** [comment]
>  Will we have another 2.6.x release? 

Spoiler alert: Yes. So yes please go ahead.

**Comment by michael-e** [comment]
PR sent to the 2.6.x branch. I guess you will rebase 2.7.x when the time comes?

**Comment by nitriques** [comment]
Thanks!

>  I guess you will rebase 2.7.x when the time comes?

Yes!
