### ISSUE TITLE
2.6.6: Backend entry filtering is broken

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2557]
In Symphony 2.6.6, the filtering of entries in the backend is broken completely.

[This line](https://github.com/symphonycms/symphony-2/commit/eec98f8e06af0e1fc1badf3e67f707c0d38dce98?diff=unified#diff-374faaf17dd66381b4bff10a1d7f0326R13) breaks it. :-(

Why? Using `General::intval` is no good idea, because it will return `-1` for empty values. The backend filtering doesn't set `$_GET['limit']`, so `$limit` will be `-1`. This results in an invalid SQL query containing `LIMIT -1`.

I suggest to push a fix and release a new Symphony version ASAP.

**Comment by nitriques** [comment]
Damn. This fix was there to prevent SQL injection... sorry about that.

`General::intval` is way safer then `intval` tho since it checks for validity. We had problems with `intval` that parses string like '1.1' and '1test' as a valid int (when it's not).

**Comment by nitriques** [comment]
@michael-e Could you test 291d1f3 before I release 2.6.7 ?

Thanks. And *sourry* again.

**Comment by michael-e** [comment]
Confirmed that https://github.com/symphonycms/symphony-2/commit/291d1f3cedac74899af8af1bdfbdf8a11815e25c fixes this issue.

**Comment by michael-e** [comment]
BTW, when have you posted this? I received your email some minutes ago, but Github states that you posted two hours ago. Do they have an email issue?

**Comment by nitriques** [comment]
> Do they have an email issue?

Maybe! I did posted it this morning. I'll release 2.6.7 shortly. Thanks!

**Comment by nitriques** [comment]
> Do they have an email issue?

Yes they do, I experienced the same thing.

**Comment by nitriques** [comment]
There you go: https://github.com/symphonycms/symphony-2/releases/tag/2.6.7

**Comment by michael-e** [comment]
Big thanks! Will update all the systems out there now.

**Comment by michael-e** [comment]
Done. All systems are on Sym 2.6.7! :-))

**Comment by nitriques** [comment]
:D
