### ISSUE TITLE
Table prefix replacement also happens on the values

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2562]
I do not know how to fix it, but any values containing tbl_something will get transformed....

**Comment by michael-e** [comment]
Cool find!

**Comment by nitriques** [comment]
Indeed. And that's the 2nd today haha

**Comment by brendo** [comment]
The magic all happens on [this line](https://github.com/symphonycms/symphony-2/blob/cd6ee3adf51881f9e540011d806531121111534b/symphony/lib/toolkit/class.mysql.php#L532), so fixing this may be possible by adjusting the regular expression :)

**Comment by nitriques** [comment]
> so fixing this may be possible by adjusting the regular expression :)

I know... but that's going to be pretty hard !

**Comment by nitriques** [comment]
Thinking about this, PDO will resolve the problem since values and queries are separated. Postponing to 3.0.0
