### ISSUE TITLE
Add a delegate to add custom cells in the datasource index

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2563]
As per https://github.com/symphonists/cacheabledatasource/issues/20

**Comment by jonmifsud** [comment]
@nitriques are you working on the Cachable Datasource? As I might want to share my current state on that so we don't duplicate efforts.

**Comment by nitriques** [comment]
>  are you working on the Cachable Datasource?

Not at the moment! Please go ahead! I can review code!

**Comment by jonmifsud** [comment]
Ok :) I'll see if I can have a look at the code and issue a PR - Client had
no complaints been running for Months. Using Cachable storing stuff in the
database for now. But have a memcached driver which is waiting for a
Sysadmin go-ahead for months...

**Comment by nitriques** [comment]
> Sysadmin go-ahead 

LOL.

**Comment by jonmifsud** [comment]
Yeah basically I don't really manage the servers for this client - if I had
someone available with the basics he would probably take over from the
current freelance sys-admins way too slow to respond to stuff. But I don't
have the time to take certain config responsibilities myself in particular
with the time difference...

**Comment by nitriques** [comment]
That's true
