### ISSUE TITLE
XSRF: Problem if the token contains the plus sign (+) char

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2567]
If the XSRF token contains the `+` character, the servers interprets it like a whitespace.

We have two solutions:
1. Url encode the xsrf parameter in Symphony.Utilities.getXSRF()
2. Never issue xsrf token with unsafe chars.

I would rather see option 2.

@brendo is there a reason on why we would need a + in the xsrf token ?

**Comment by michael-e** [comment]
Great find. Solution #2 sounds reasonable to me.

**Comment by brendo** [comment]
I work with Symfony2 a lot these days, and Solution 2 is what they also implement:

https://github.com/symfony/security/blob/master/Csrf/TokenGenerator/UriSafeTokenGenerator.php

**Comment by nitriques** [comment]
Sold then. Thanks!

**Comment by nitriques** [comment]
@brendo could you do a quick review of the commit please ? Thanks!

**Comment by nitriques** [comment]
See also d6118c0ed35497406cf0d24304d5f9a7407bbb55
