### ISSUE TITLE
[PHP7]  Symphony Fatal Error: Uncaught TypeError

### ISSUE THREAD

**Issue by SebastianKaminski** [symphonycms/symphony-2#2575]
I'm getting error when enable PHP7 mode by adding line `AddType application/x-httpd-php70 php` to .htaccess file. I'm using Symphony from 2.7.x branch.

Please see below:

![ss](https://cloud.githubusercontent.com/assets/7227870/13723658/21f7001e-e86c-11e5-9b8d-5f6d17ee807c.jpg)

**Comment by nitriques** [comment]
`2.6.7` does not supports PHP7.

Can you try the `2.7.x` branch please ?

**Comment by SebastianKaminski** [comment]
Hi @nitriques , I'm afraid that using 2.7.x branch didn't helped.

**Comment by brendo** [comment]
Nah @nitriques, there's still a bit to do to make Symphony happy on PHP 7, check out [the migration guide](https://secure.php.net/manual/en/migration70.incompatible.php).

This one is related to the new `Throwable` interface which errors and exceptions extend.

**Comment by nitriques** [comment]
Thanks guys

**Comment by nitriques** [comment]
This should be fixed 6f42cbd76f25c86a78626d2e7dc0354ba2000186 and 28c21343759cc7fcd99511ac96fb3c7374ca6f32

@SebastianKaminski would you mind testing the `2.7.x` branch again ?
