### ISSUE TITLE
Remove selectize.js from core?

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2576]
Working on the AI-Selector/Editor I tried to fix a problem which is probably rooted in `selectize.js` rather than the AI-interface extensions:

Apparently the **remove** button is not shown on single selects (e. g. selects with only one selection possible). I always found was that was a problem in the current `association_ui_selector` implementation. You have to use backspace to remove a single entry, which is pretty unintuitive. A simple remove button would be much better.

If I get it right it has been fixed here: https://github.com/selectize/selectize.js/pull/799/commits/16245c38aea618c2e837571ed862f8b28b6ddafb 

This has probably not made it’s way into Symphony 2.6.7? Not sure about other breaking changes in selectize.js especially since I have no idea where else it is used in the backend.

So the final question is: can we update selectize.js? And what version should it be included in?

**Comment by animaux** [comment]
@nitriques @jonmifsud ok, in order to make selectize.js work for single-select-remove-buttons in the AI selector, I need a hack in one of it’s plugins. Since it really looks like it’s not used anywhere else by symphony anymore – should we remove it from the core then?

**Comment by nitriques** [comment]
Yes. Will be done in 3.0.0

**Comment by nitriques** [comment]
Done in 978990b9d6

**Comment by animaux** [comment]
`\o/` The world from next tuesday is already here!
