### ISSUE TITLE
Proposition: remove the domain name from the workspace param

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2591]
This has been bugging me since a long time. The protocol + domain name part of the parameter should not be there. Any objection ? It should not break anything...

**Comment by munki-boy** [comment]
But won't that just leave "workspace"?

**Comment by michael-e** [comment]
I hate the `$workspace` parameter. As it is currently, is completely superfluous. You can do anything with the `$root` parameter. I never use `$workspace`.

Keeping the parameter and removing protocol and domain is no good idea, simply because the value will always be `workspace`. The workspace is not configurable, but hardcoded throughout the system. Search Symphony for the word "workspace", and you will see what I mean.

My suggestion would be to either remove the parameter (breaking change) or make it configurable. Using it without protocol and hostname would a breaking change as well for many websites, so it would also require a major version bump.

**Comment by moretaste** [comment]
I use $workspace a lot in templates. A configurable option like the admin-path sounds as best of two worlds. But as @michael-e said declaring a variable with $root/workspace or whatever will do the trick also. 

Waist of time to spend a lot of attention to this or make it configurable for those who likes to have fancy names for it. Workspace sounds for me good.

**Comment by munki-boy** [comment]
I've used it a lot in image templates for no good reason other than I saw it in a template when I was learning. Perhaps make a note for people to grep it out of their templates if they upgrade Sym or my pics for example wouldn't load. 

No hassle to find&replace though.

**Comment by nitriques** [comment]
I agree with you @michael-e. Let's make it configurable then.

**Comment by michael-e** [comment]
Cool.

**Comment by nitriques** [comment]
But then again

> As it is currently, is completely superfluous.

This is not true if I install symphony in a sub directory. I need /directory/workspace . This is why it's still needed even if not configurable.

> if they upgrade Sym or my pics for example wouldn't load.

That's why I want to go from 'proto://domain.tld/workspace' to '/workspace'

**Comment by nitriques** [comment]
> but hardcoded throughout the system.

We could at least start by with creating a constant named `WORKSPACE_URL` ? and then make it configurable ?

**Comment by munki-boy** [comment]
> That's why I want to go from 'proto://domain.tld/workspace' to '/workspace' which should not break anything.

Yep :)

**Comment by michael-e** [comment]
> This is not true if I install symphony in a sub directory. I need `/directory/workspace`. This is why it's still needed even if not configurable.

No, it is not needed. If you install in a sub directory, you will have something like this in your `<params>`:

```xml
<root>http://example.com/lulu</root>
<workspace>http://example.com/lulu/workspace</workspace>
```

So again, the workspace parameter is superfluous as long as the name of the workspace folder is `workspace`. The value of the workspace parameter can always be written like this:

```xsl
<xsl:value-of select="concat(/data/params/root, '/workspace')"/>
```

> go from 'proto://domain.tld/workspace' to '/workspace'

I don't see why this would help. All I see is more confusion with the params.

Please think twice before changing this parameter in a backwards-incompatible manner.

**Comment by nitriques** [comment]
> Please think twice before changing this parameter in a backwards-incompatible (or more confusing) manner.

Well said. 

> Note that currently there is no param starting with a slash!)

current-path does.   
And it's a problem, not something I'd like to keep. It's a best practice to use urls that starts with /.

We also have `root` and `root-dir` 

I would then propose.

1. Make the workspace folder location configurable
2. Add `workspace-dir` ?

**Comment by michael-e** [comment]
> current-path does.

You are right, and we have `parent-path` as well starting with a slash.

> We also have `root` and `root-dir`

`root-dir`? Never seen this (Sym 2.6.7)! Is this in 2.7, maybe?

I agree with your proposal, but I am not sure about the naming. We have `parent-path` and `current-path`, so shouldn't we call it `workspace-path`?

Additionally, I suggest to deprecate the `workspace` parameter.

**Comment by nitriques** [comment]
> root-dir? Never seen this (Sym 2.6.7)! Is this in 2.7, maybe?

Yup you are right it's new! (I've been hacking it since a long time!) https://github.com/symphonycms/symphony-2/commit/b35eba86c4f7f42e63c3a5b2ce54a7039d2bd080

> I agree with your proposal, but I am not sure about the naming. We have parent-path and current-path, so shouldn't we call it workspace-path?

Ok! I would rename root-dir to root-path then ?

> Additionally, I suggest to deprecate the workspace parameter.

Agreed. I do not know if I will be able to deprecated in the docs, but at least, in the code and release notes.

**Comment by michael-e** [comment]
Hmmm. We must differentiate between a path (as part of a URL) and a `dir` (which is a part of the *file path* on the server).

The following are paths (or can be seen as paths):

* `parent-path` (e.g. `/articles`)
* `current-path` (e.g. `/articles/archive`)
* `workspace-path` (e.g. `/workspace`, **not depending** on Symphony being installed in a subdirectory!)

Regarding the `root-dir`, I am not sure what you are using this for. If it was a path as well, it would always be `/`. So is this the server's file path for the root directory, e.g. `/var/www/html`? Then is should called path, IMHO. But why do you need this in Symphony at all?

**Comment by michael-e** [comment]
Thinking about the above… is it all true? Does somebody have Symphony installed in a sub-directory and can give some quick pointers about the mentioned paths?

**Comment by michael-e** [comment]
OK, I verified it myself. `parent-path` and `current-path` do not include the sub-directory if Symphony is installed in a subdirectory. These paths start from the Symphony "index", e.g. `http://example-com/test`.

I should make it more clear. Example:

* The server's root can be reached using `http://example.com`.
* Symphony is installed in the sub-directory `lulu`.
* Symphony's index page will have the URL `http://example-com/lulu/`
* The `parent-path` and the `current-path` of the index page will be `/`, so the paths will not include the `/lulu` part of the URL.

We should use the same behaviour for the new `/workspace` parameter. Otherwise we will get a lot of confusion.

**Comment by munki-boy** [comment]
@michael-e I think @nitriques thought of this above when I asked

> 

    That's why I want to go from 'proto://domain.tld/workspace' to '/workspace' which should not break anything.

Yep :)

**Comment by nitriques** [comment]
Yeah the whole point of the discussion is that Symphony (most of the time) includes protocol (http/https) and domain in the path it gives.

I want the same information as we already have, without any of the protocol and domain part.

> Does somebody have Symphony installed in a sub-directory and can give some quick pointers about the mentioned paths?

I do.

> I should make it more clear.

Yes, what you say is right. But how can we achieve this ?

> Regarding the root-dir, I am not sure what you are using this for. 

That's why I must have named it that way: paths are for symphony.

For root-dir, it's the directory relative to the docroot. I have a symphony installed in `/symphony/2.6.7/` I need it to be `/symphony/2.6.7/` since my docroot (in httpd.conf) is `/`.

Adding the protocol and domain is generally a bad idea (for my use case)

**Comment by michael-e** [comment]
All right, so we should stick to `root-dir` and call the other ones `-path`, as suggested [in my above post](https://github.com/symphonycms/symphony-2/issues/2591#issuecomment-221383300).

But: It doesn't work properly. With the above example sub-directory, I get:

```xml
<root-dir>//lulu</root-dir>
```

Note the double-slash (or however this character is called).

**Comment by nitriques** [comment]
Ok I'll fix this ;) Thanks!

**Comment by nitriques** [comment]
@michael-e The issue with the double / should be resolve.

Also, I've kept the `workspace` parameter, since

1. It's used by some templates
1. Will be useful when it's customisable, which I plan do to.

**Comment by michael-e** [comment]
Yes, keeping `workspace` is good, but it should be deprecated for 3.0.

There is a bit of a mess now regarding trailing slashed, see https://github.com/symphonycms/symphony-2/commit/b6d9edbb4900bc6d6621fb5ff2492c26d4321c7d#commitcomment-17687348. In fact we never had trailing slashes in parameters, so I wonder why you start using a trailing slash just for a single parameter.

**Comment by nitriques** [comment]
> but it should be deprecated for 3.0.

Even if the value's configurable ?

> so I wonder why you start using a trailing slash just for a single parameter.

How would you deal with root, i.e. `/`, and `/folder` ? doing a xslt choose for this seems counter intuitive. I've made a lot of efforts in order to try to avoid the extra / at the end and it littered the code with `rtrim`. Both `*-dir` parameters and the `DIRROOT` constant are new to `2.7.0` and they deal with urls. It always seem odd that symphony enforces the `/` at the end of urls via `.htaccess` but never included them in the parameters. I would vote to add them all in `3.0.0`. The commit is my best effort to keep backward compat (which it 100% does) but trying to bring some sanity in urls which, IHMO, whould NEVER contain the protocol nor the domain name.

**Comment by nitriques** [comment]
BTW, I could live with an empty value for `/` and `folder` when there is a folder. But I would still vote for them to always be there, in order to make sense with the redirect rule.

**Comment by michael-e** [comment]
I wanted to take another look, but unfortunately I can not login to my test instance anymore...

<img width="889" alt="bildschirmfoto 2016-06-01 um 15 03 24" src="https://cloud.githubusercontent.com/assets/40072/15710366/0a1b3086-280a-11e6-849a-7f95a79b2be8.png">

This is the latest 2.7.x code (with the fixed cookie self url creation).

Any ideas?

**Comment by brendo** [comment]
`composer dumpautoload -o`

**Comment by michael-e** [comment]
Thanks! :-)

**Comment by brendo** [comment]
You're welcome :)

**Comment by michael-e** [comment]
@nitriques:

> > but it should be deprecated for 3.0.
>
> Even if the value's configurable ?

Well, it is potentially superfluous, depending an which other parameters will be changed or added.

Honestly, the whole thing feels bad to me. In its current (2.7.x) state the parameter pool is really inconsistent regarding the naming and trailing slashes alike, and I don't think that we should do it like this in Symphony 2.7. Think of somebody who is new to Symphony — don't you think that he/she will be deterred by this?

```xml
<root>http://maschine7.de/lulu</root>
<root-dir>/lulu/</root-dir>
<workspace>http://maschine7.de/lulu/workspace</workspace>
<workspace-dir>/lulu/workspace</workspace-dir>
<http-host>maschine7.de</http-host>
<root-page>home</root-page>
<current-page>home</current-page>
<current-page-id>1</current-page-id>
<current-path>/</current-path>
<parent-path>/</parent-path>
<current-query-string><![CDATA[debug]]></current-query-string>
<current-url>http://maschine7.de/lulu</current-url>
```

**Comment by michael-e** [comment]
BTW, the `workspace-dir` has no trailing slash, which is probably a mistake.

**Comment by nitriques** [comment]
> BTW, the workspace-dir has no trailing slash, which is probably a mistake (given your thoughts above)?

Yup! Like I've said, I had like 4 different version of it ;)

> I could live with an empty value for / and folder

Would this fix the issue ?

**Comment by michael-e** [comment]
> Would this fix the issue ?

I am afraid that I don't get the idea. Do you mean omitting the trailing slash everywhere, but also omitting the `/` ("root slash")?

**Comment by nitriques** [comment]
no I mean never trailing slash ever (which leads to an empty value when install at the root)

**Comment by michael-e** [comment]
Hmmmm, nope.

Take -NIX systems, for example. Use the `pwd` command to print the working directory:

* `cd / && pwd` will print `/` (so this is no empty response)
* `cd /var/www/ && pwd` will print `/var/www` (without trailing slash!)

See also <https://en.wikipedia.org/wiki/File_URI_scheme>.

Symphony uses trailing slashes for URLs, but this has been questioned several times and might not last forever.

So all in all I think that we should not invent trailing slashes in parameter values.

Regarding the naming issue:

We need some "local paths" as parameters, and also "parts of URLs". Unfortunately everything is a path in a URI. So we have to find naming rules which clearly indicate if we are talking about a "local path" or a "URL path". This is really hard. We have tried by using `path` vs. `dir`, but this is not very clear. Ideally one should recognize the meaning by reading the tag name only. :-)

Out of curiosity: Why do you need those `dir`-Parameters so desperately?

Wouldn't it be better to leave the params as they are now and do it differently/better/breaking in Symphony 3?

**Comment by nitriques** [comment]
> Why do you need those dir-Parameters so desperately?

Because I do not want protocol and domain names in my urls!

I understand your concerns. The unix way is wrong IMHO: we always have to deal with the edge-case that is / (but normally, nobody write to that path on unix, but we are in a different situation)

3.0.0 will be allowed to break things and we will do. I am just trying to find a backward compatible way of doing it.

So what's option C ?

**Comment by nitriques** [comment]
what about `url` instead of `dir` ?

**Comment by michael-e** [comment]
No, it's just a path.

You want to have `root` and `workspace` just without the protocol/domain part? So it is **not** the **local path** on the server, but the **URL path** of the root and the workspace?

> Because I do not want protocol and domain names in my urls!

I'd really like to know why! :-)

**Comment by michael-e** [comment]
If my above assumption is correct (meaning that you talk about URL paths, not server filesystem paths) it would surely be best to call these parameters `root-path` and `workspace-path`.

Unfortunately Symphony already has `current-path` and `parent-path` parameters using the NIX style that I described above. So if we use the word "path" for the new parameters as well, any inconsistency in the way we build the values is even worse. Especially in order to not deter new Symphony users, I suggest to use the NIX style for the new path parameters as well. We may re-visit this for Symphony 3.

Assumed that we install Symphony in a subfolder called `lulu`, and we are on the page `test`, it might look like this:

```xml
<root>http://example.com/lulu</root>
<root-path>/lulu</root-dir>
<workspace>http://example.com/lulu/workspace</workspace>
<workspace-path>/lulu/workspace</workspace-dir>
...
<current-path>/test</current-path>
<parent-path>/</parent-path>
<current-query-string><![CDATA[debug]]></current-query-string>
<current-url>http://example.com/lulu/test</current-url>
```

**Comment by nitriques** [comment]
> I'd really like to know why! :-)

1. You can waste as much as 5Kb with complete urls. (I do heavy image websites).
2. We make a difference between / and complete url in javascript to let the user choose between target=_blank or not
3. You can create static export without the need to remove the domain part everytime...

Right now, I am substringing it in xslt, and it seems counter intuitive (and everybody needs formation on that topic here)

**Comment by nitriques** [comment]
> meaning that you talk about URL paths, not server filesystem paths

Yes!

**Comment by nitriques** [comment]
> Unfortunately Symphony already has current-path and parent-path

That's why I went with `dir` ... Also `path` right now are symphony's path, not the complete, actual url (it's a page-path)

**Comment by michael-e** [comment]
Thanks for the rationale behind it!

Well, technically especially the new ones are paths (URL paths). Let me think about it tomorrow again! :-)

**Comment by nitriques** [comment]
No worries @michael-e it's always a pleasure to argue with you ;)

**Comment by nitriques** [comment]
@michael-e I did some research, and sadly, the part of the url I want is called the `path` as per the spec....

So... Could it be `root-url` + `root-url-path` but `workspace` + `workspace-url-path` ? Or deprecated `workspace` and add `workspace-url` ? Those name will be pretty accurate and self describing

**Comment by michael-e** [comment]
Yes, that is the problem: the two new parameters *are* paths, technically. So we should *call them* paths. The implications of this are in my [comment above](https://github.com/symphonycms/symphony-2/issues/2591#issuecomment-223102512), and — after discussing the whole thing with a friend – today I am even more convinced of what I wrote yesterday. Please don't add inconsistency. Think about my proposal, I really think this is the best we can do.

(BTW, personally, I don't share your antipathy regarding the "NIX-style" values. And they work fine in templating as well.)

The `root` and the `workspace` parameter must, of course, stay as they are (at least in Symphony 2).

**Comment by nitriques** [comment]
> The root and the workspace parameter must, of course, stay as they are (at least in Symphony 2).

Yeah that's right.

I'll add the `workspace-path` parameter, but will remove the root-path since it won't solve the problem I am trying to solve, which is to remove parsing it in xslt.

> I don't share your antipathy regarding the "NIX-style" values

I hate exceptions. '/' is a exception, since it both begins with and ends with '/'.

**Comment by michael-e** [comment]
Well, paths are, hmmm, what can I say…? <https://tools.ietf.org/html/rfc3986#section-3.3> At least the say:

> must either be empty or begin with a slash ("/") character

So we can re-visit this discussion for Symphony 3! :-))

**Comment by nitriques** [comment]
Wow. Both of our suggestions match the spec, that a good start.

At least, we have a valid plan for now ;)

**Comment by michael-e** [comment]
A friend of mine says:

> If you want to make god laugh, make a plan.

Nevertheless I like our valid plan!

**Comment by nitriques** [comment]
Hahaha, nice quote ;) And I like to make god laugh ;)

**Comment by nitriques** [comment]
@brendo @michael-e Could you review e23f2f2 and please 72801b4 ? Thanks!

**Comment by michael-e** [comment]
Nearly everything looks good to me, except one strange thing: Although the `__SYM_COOKIE_PATH__` constant has the correct value (.e.g. `/lulu`, if Symphony is installed in the "lulu" folder), the path of the cookie in the browser will have a trailing slash (`/lulu/`). This is not the case with Symphony 2.6.7.

Has anything else changed regarding Cookies?

Here is the corresponding response header:

>     Set-Cookie: PHPSESSID=l7ksh51bjggh53mho0v9u8oo61; expires=Sat, 18-Jun-2016 19:08:52 GMT; Max-Age=1209600; path=/lulu/; domain=example.com; httponly

And here's the header using Symphony 2.6.7:

>     Set-Cookie: PHPSESSID=l7ksh51bjggh53mho0v9u8oo61; expires=Sat, 18-Jun-2016 19:10:59 GMT; Max-Age=1209600; path=/lulu; domain= example.com; httponly

**Comment by nitriques** [comment]
Good find! I forgot to patch this new function `createCookieSafePath()` accordingly.

Can you test again please ? a58ff6b should address this

**Comment by michael-e** [comment]
Yep, looks good now.

**Comment by nitriques** [comment]
Awesome.  Thanks again @michael-e for all of this.

**Comment by michael-e** [comment]
I am happy that people like it. I mean: "me breaking things". :-)
