### ISSUE TITLE
Invalid default value for 'last_seen'

### ISSUE THREAD

**Issue by pixelninja** [symphonycms/symphony-2#2594]
New installs fail with MySQL 5.7. It returns a fatal error: `Invalid default value for 'last_seen'`

Log:

`05/24/2016 2:30 am > Notice: MYSQL: Establishing Connection`
`05/24/2016 2:30 am > Notice: MYSQL: Importing Table Schema`
`05/24/2016 2:30 am > Fatal Error: There was an error while trying to import data to the database. MySQL returned: 1067: Invalid default value for 'last_seen'`

Fix was to adjust line 10 of `install.sql`, located `/install/includes/install.sql` from `'last_seen' datetime DEFAULT '0000-00-00 00:00:00'` to `'last_seen' datetime DEFAULT '1971-01-01 11:59:59'`.

I was also getting an error using `storage_engine`, but that has been resolved here https://github.com/symphonycms/symphony-2/issues/2587

**Comment by brendo** [comment]
Yep, MySQL 5.7 sets the [default SQL Mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) to enforce [`NO_ZERO_DATE`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date). This can be changed at runtime, so potentially Symphony could detect the MySQL server version and update the SQL Mode to omit this mode, or we could update date fields to set the default to be epoch.

**Comment by Petertron** [comment]
A month ago I made a pull request on the 2.7.x branch which changed the default value for "last_seen" to "1000-01-01 00:00:00", the lowest value allowed .

**Comment by nitriques** [comment]
Yup @brendo, @Petertron already fixed that  error ;) @brendo Do we have to change something else ? Or just to make sure to never insert `0000-00-00` ?

**Comment by pixelninja** [comment]
Nice work guys

**Comment by nitriques** [comment]
Fixed in 1c074d23712ec5ed98b96ad75752cd025916ee5f

**Comment by twiro** [comment]
I stumbled upon this error with a project I recently updated from **2.6.1** to **2.7.7** and then migrated to another Server via the export ensemble extension. My exported 2.7.7-ensemble had the original `'last_seen' datetime DEFAULT '0000-00-00 00:00:00'` lines in the `install.sql` – so either these lines aren't fixed while updateing from Symphony 2.6 to 2.7 or the export ensemble extension is causing this error…

I don't have the time to investigate further right now, but wanted to leave this note here in case @nitriques wants to take care of this or I might find time in the future.

**Comment by nitriques** [comment]
@twiro thanks, I'll fix this

**Comment by nitriques** [comment]
@twiro it is fixed in #2863
