### ISSUE TITLE
Unable to demote developer

### ISSUE THREAD

**Issue by DavidOliver** [symphonycms/symphony-2#2596]
After having promoted an author to developer, I'm unable to demote it back to author or manager.

There are no error messages shown and the 'Authors' page loads successfully after form submission, but the 'User Type' select menu still shows 'Developer'.

By the way, what is the manager type for?

**Comment by nitriques** [comment]
> By the way, what is the manager type for?

They are essentially authors who can create other authors and change their password.

You cannot demote the primary account (the one created on install), but other one should be demotable... I'll see what can be done. Thanks!

**Comment by DavidOliver** [comment]
Ah, thanks. Yes, this was not a primary account but a newly-created one.

**Comment by nitriques** [comment]
Ok. For now, you can go into the DB and change the value if it's urgent ;)

**Comment by nitriques** [comment]
I can not reproduce the issue at the moment, using the latest 2.7.x branch. What version are you running ?

**Comment by DavidOliver** [comment]
2.7.6.

Enabled extensions:

Association Field
Association Output
Association UI: Editor
Association UI: Selector
Cross-Site Scripting (XSS) Filter
Debug Devkit
Default Event Values
Documenter
Email Template Manager
Entry URL Field
HTML5 Doctype
Incremental Number Field
Just In Time (JIT) Image Manipulation
Limit Section Entries
Markdown Text Formatter
Members
Order Entries
Page HTTP Caching
Reflection Field
Save and Return/New Buttons
Select Box Link Field
Subsection Manager
SymQL
Unique Text Input Field
Unique Upload Field

I'll try again with a fresh install and get back to you.

**Comment by munki-boy** [comment]
I can't replicate the problem

2.6.7
Cross-Site Scripting (XSS) Filter
Debug Devkit
Export Ensemble
Just In Time (JIT) Image Manipulation
Maintenance Mode
Markdown Text Formatter
Members
Profile Devkit
Select Box Link Field

**Comment by munki-boy** [comment]
I can't replicate the problem

2.6.7

Cross-Site Scripting (XSS) Filter
Debug Devkit
Export Ensemble
HTML5 Doctype
Just In Time (JIT) Image Manipulation
Maintenance Mode
Markdown Text Formatter
Profile Devkit
Select Box Link Field
Unique Upload Field

**Comment by nitriques** [comment]
Thanks guys.

**Comment by DavidOliver** [comment]
This is now working for me in both a 2.7.x branch install and the 2.6.7 install in which I found it wasn't working. Not sure what happened there.

**Comment by nitriques** [comment]
Please re-open if you encounter it again!
