### ISSUE TITLE
Ensure session id is regenerated after each request

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2598]
According to https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet#Session_Fixation it would be necessary.

I know work as already been done on session in `3.0.0`, but it can be done for `2.7.0`

@michael-e Do you see anything that could break with this change ?

**Comment by michael-e** [comment]
I am not sure, would browsers handle the session ID correctly across multiple tabs/windows?

**Comment by nitriques** [comment]
> would browsers handle the session ID correctly across multiple tabs/windows?

Yes: Cookie jars are shared across tabs since they are domain bounds. I've tested it and it works. But it could break other code that simply reads the cookie instead of using the core code.

**Comment by michael-e** [comment]
I wouldn't care too much for hardcoded stuff that doesn't use Symphony's public API. :-)

**Comment by nitriques** [comment]
Perf ;)

**Comment by nitriques** [comment]
cc @hyp3rlinx

**Comment by nitriques** [comment]
Pushed down to 2.8.0
