### ISSUE TITLE
2.7.0 Migration

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2600]
Accessing the backend for the first time after upgrading to the current `2.7.0` codebase (`2.7.x` branch) results in the following error, if not logged-in already:

> Symphony Warning: `call_user_func()` expects parameter 1 to be a valid callback, class 'migration_270' not found
> An error occurred in `/Users/johannahoerrmann/Sites/durchgedreht24.de/symphony/lib/core/class.symphony.php` around line 590

It's not possible to log in. Using the same install with an active session works without throwing an error.

**Comment by nilshoerrmann** [comment]
A file of the name `2.7.0.php` does exist in the `migrations` folder.

**Comment by brendo** [comment]
Try `composer dumpautoload -o`

**Comment by nilshoerrmann** [comment]
Removing that migration file resolves the login problem but something seems to be wrong here.

Some background information:

This is a Symphony install that exists on a remote and a local server. Both installs share the same database. I first accessed the site on the server after upgrading while having an active session – everything is fine there. The error above occured on the local server after trying to log in for the first time (no active session). The updater has only run remotely but there haven't been any relevant server or database changes (we were coming from Symphony 2.6.4).

I'm not sure if this is relavant but the local configuration still states the old system version number.

**Comment by nilshoerrmann** [comment]
> composer dumpautoload -o

I have to install this to do so, right?
https://getcomposer.org/

**Comment by nilshoerrmann** [comment]
That worked. 
What does this command do and why was it needed?

**Comment by nitriques** [comment]
Hey Nils, `2.7.0` is not super stable these days. I've fixed this yesterday tho via 581c99c

**Comment by nilshoerrmann** [comment]
Thanks for the info, Nicolas. Is there an ETA already?
(By the way, from what I see, it really _is_ quite stable.)

**Comment by nitriques** [comment]
No ETA sadly. There's still 15 issues left.

I do not want to rush anything: I'd rather ship when things are really stable (meaning I have a couple in staging working well)

**Comment by nilshoerrmann** [comment]
No hurry, for an unreleased version it really works well so far.

**Comment by nitriques** [comment]
Awesome. Please report any bugs or incongruities you may find!

**Comment by brendo** [comment]
> That worked. What does this command do and why was it needed?

You may notice through the codebase these days there are very few `require` or `include` statements. This is because we are making use of Composer's autoloading capabilities to load classes JIT using [`spl_autoload`](http://php.net/spl_autoload).

`composer dumpautoload -o` will regenerate the autoloading mapping from the codebase so that when a new class is referenced, Composer knows where to find it.
