### ISSUE TITLE
Weird alignment on author page

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2603]
![image](https://cloud.githubusercontent.com/assets/771169/16158892/a7206272-348d-11e6-90f7-0db07654d614.png)

I think the fields should be properly aligned.

cc @nilshoerrmann

**Comment by nilshoerrmann** [comment]
It should look like this:

![bildschirmfoto am 2016-06-20 um 09 53 27](https://cloud.githubusercontent.com/assets/25466/16186800/e0a3a284-36cc-11e6-9315-10a52cd3712d.png)

**Comment by johnpuddephatt** [comment]
Adding `display: block` to  `#password legend` should sort this.

![screen shot 2016-06-20 at 11 23 26](https://cloud.githubusercontent.com/assets/8030910/16190896/74454040-36d9-11e6-8711-e049b1fb6633.png)

**Comment by nitriques** [comment]
Thanks guys.

**Comment by nitriques** [comment]
![screen shot 2016-06-21 at 9 23 55 pm](https://cloud.githubusercontent.com/assets/771169/16251728/8cd31088-37f6-11e6-90a3-c82c41e3472f.png)
