### ISSUE TITLE
No way to subvert behaviour of GenericExceptionHandler::shutdown

### ISSUE THREAD

**Issue by pointybeard** [symphonycms/symphony-2#2605]
Once a shutdown method, in this case `GenericExceptionHandler::shutdown` (https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/core/class.genericexceptionhandler.php#L288), as been set using `register_shutdown_function`, it cannot be removed. 

This is problematic as whenever there is a fatal error, this method is called and sometimes Symphony is not being used in the browser (e.g. on the command line or in a JSON api). 

Currently there is no way to remove a shutdown method in PHP once it has been set.

I propose additional logic in this shutdown method, based on the `$enabled` flag, that will allow developers to turn off Symphony's generic exception handler in favour of their own, thus no longer having to worry about this particular shutdown method from throwing out HTML on a fatal error.

A solution would be to add the following code at the top of the `shutdown` method:

``` php
        if(!self::$enabled) {
            return;
        }
```

I am still checking if there is any unwanted side effects to this, and hope to submit a PR soon.

**Comment by nitriques** [comment]
@pointybeard I've already started to work on that. See https://github.com/DeuxHuitHuit/symphony-2/tree/errorhandler

The biggest problem is that Symphony treats the uninitialized state wrongly.

**Comment by pointybeard** [comment]
Agreed. I think there is 2 problems. 

First, as you say, Symphony is not treating the uninitialised state correctly. I see you've made good progress on this.

And secondly, currently the shutdown method being set with `register_shutdown_function` forces HTML output, regardless of context, when there is an `E_ERROR`. This wouldn't be such a problem if there was a way to remove methods added this way, however it is not possible.

I have, however, found a potential workaround. [According to the manual](<http://php.net/manual/en/function.register-shutdown-function.php>):

> Multiple calls to register_shutdown_function() can be made, and each will be called in the same order as they were registered. **If you call exit() within one registered shutdown function, processing will stop completely and no other registered shutdown functions will be called.**

I will see about adding my own shutdown method before Symphony adds its. That method will just `exit()`, thus preventing Symphony's shutdown method from ever being called. It's a little dirty, and I think there should be a better solution in the future, but hopefully the work you're doing @nitriques will address it.

I'll post here with my findings.

**Comment by nitriques** [comment]
Thanks Alistair!
