### ISSUE TITLE
Set up entries-per-page value not shown

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2624]
**Concerning Datasource XML output**

When a `datasource` does not return any entries, the `pagination` node attribute `entries-per-page` does not show the set up pagination size for given datasource. Instead, it shows a value of `1`.

The configured pagination size value is shown only when any number of entries are returned.

**Expected**
To always return the configured pagination size value when datasource pagination values are included into XML output, whether any entries are returned or not.

Symphony v2.6.7

**Comment by nitriques** [comment]
Fixed in 2.7.0. Thanks!
