### ISSUE TITLE
Data Source UI cannot filter for empty core Text Input or Date fields

### ISSUE THREAD

**Issue by cylkee** [symphonycms/symphony-2#2626]
Examples:
1. I have a Section with many fields. One is an optional core Text Input field.
2. I have another Section with some fields. One is an optional core Date field.

In each of the examples above want a Data Source to filter for entries where those fields are empty.  I have tried the following filter values but none worked:
- `regexp: ^$`
- `not-regexp: ^http` (in the case of a Text Input field that was expecting a URL)
- `not-regexp: .+`
- `not-regexp: ^.+$`
- `sql: NULL` *
- `is null` *

In all filter value cases the output XML is `<error>No records found.</error>`

\* In these filter value cases, where I've selected a parameter in the UI to be output, all `<item`s are output in the `<ds-` parameter, regardless of the filter.

The opposite does work. So `regexp: ^.+` will find the entries with non-empty Date fields, for example.

Symphony version is 2.6.3.

**Comment by nilshoerrmann** [comment]
You stumbled across this issue: is there a solution to this problem already?

**Comment by cylkee** [comment]
No, as far as I know.  I cannot provide a solution.  As a work-around, I guess hacking a data source would work.

**Comment by nilshoerrmann** [comment]
Thanks for the update @cylkee!

@nitriques and @brendo: Is there an easy way to make `sql: NULL` / `sql: NOT NULL` – [like we know it from AF or SBL](https://github.com/symphonists/association_field/blob/master/fields/field.association.php#L961-L981) – available to the date field? One important thing is to be able to unite different operators like so:

    equal to or earlier than today, sql: NULL

This would return all entries with a date that either meets the chronological requirements or is not specified at all.

**Comment by nitriques** [comment]
>  One important thing is to be able to unite different operators like so

Right now this is not possible, even in AF or SBL.

**Comment by nitriques** [comment]
Weird, but the core tag field already had it...

**Comment by nitriques** [comment]
@cylkee I have a working version with `sql: NULL` and `sql: NOT NULL` wanna test it ?

**Comment by nitriques** [comment]
@cylkee see #2666

**Comment by cylkee** [comment]
@nitriques Thank you.  To test, would I need to install a 2.7.x somewhere?

**Comment by nitriques** [comment]
@cylkee Yes, or do and update on a DEV setup!
