### ISSUE TITLE
Symphony never sets the "secure" flag on cookies

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2627]
Due to a typo in `class.cookie.php`, Symphony never sets the "secure" flag on cookies/sessions. (It is supposed to do this in SSL environments.)

Here are the lines in question:

``` php
if (defined(__SECURE__)) {
    $this->_secure = __SECURE__;
}
```

The fix is to add the missing (single) quotes:

``` php
if (defined('__SECURE__')) {
    $this->_secure = __SECURE__;
}
```

I can provide a pull request. To which branch should I send it?

**Comment by brendo** [comment]
Doh, that would of been me :(

`2.7.x` I believe, @nitriques will probably backport it to `2.6.x` too.

Thanks @michael-e!

**Comment by michael-e** [comment]
Thanks, @brendo. Will do.

**Comment by michael-e** [comment]
BTW, I noticed that fixing Symphony's behaviour as above has one negative side effect. It won't affect many users, however I think that it should be documented here.

If (and only if):

1. your website is running in "mixed mode", i.e. parts are SSL-encrypted, other parts are running over HTTP, and
2. you are **writing to the session** (using an extension) on **unencrypted** pages of the website

a secure cookie/session (used for Symphony login, for example) will be destroyed as soon as the second step happens.

This is probably due to the fact that the browser does not re-use a secure cookie on unencrypted pages of your site. As soon as a (non-secure) cookie/session is needed, a new session will be generated.

Why should you write to the session on unencrypted pages? Well, I do this in order to carry `GET` parameters in the session, especially when developing in the production ("live") system; these parameters are then added to the param pool and used in the templating layer in order to switch between versions. :-)

As I said, it's not a big deal... (Ideally everything should be SSL anyway.) Just documenting it.

**Comment by nitriques** [comment]
@michael-e Thanks for the edge case description. That's recurring problem on a lot of platform and I would not try to deal with it.

**Comment by michael-e** [comment]
I completely agree. These edge cases require special treatment (and knowledge) anyway. I just wanted to document it here, just in case someone will run into similar issues.

**Comment by brendo** [comment]
This was backported to 2.6.8 as well :)

**Comment by michael-e** [comment]
Thanks a lot, @brendo!

**Comment by nitriques** [comment]
Thanks @brendo !
