### ISSUE TITLE
"With selected …" should not post empty values

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2629]
While updating a lot of extensions, I noticed that the `With selected …` widget doesn't catch cases where no option has been selected:
### Current behaviour

The `With selected …` widget submits even with no option selected. The backend reloads as expected but – of course – no action has been executed due to the missing selection. 

The problem is that the reloading _makes you think_ an action took place while it has not.
### Expected behaviour

The `With selected …` widget should only submit when an option is selected.

**Comment by nitriques** [comment]
@nilshoerrmann would disabling the button work out ? Is this a UX only problem ?

**Comment by nilshoerrmann** [comment]
Yes, I think disabling the button should do the trick.

**Comment by nitriques** [comment]
Turns out, you already did this in 1724265a4
