### ISSUE TITLE
Add validation on author emails

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2632]
Authors can have invalid emails, which can crash the whole frontend.

Is this a feature ? Should we force authors to set valid emails ? Or should we patch the data sources to make sure the email is cdata'ed ?

**Comment by michael-e** [comment]
Force valid email addresses!

**Comment by brendo** [comment]
Valid how? Simply that is matches a string which resembles an email?

**Comment by michael-e** [comment]
Yes, that would me enough in my eyes. IMHO we could even be rather strict when validating the string (no IDNs, no "exotically constructed" email adresses).

**Comment by nitriques** [comment]
My point would be to never accept (or properly encode) `<` or `>`, since that's how I broke the frontend. But gain, `filter_var($email, FILTER_VALIDATE_EMAIL)` would be enough IMHO.

**Comment by michael-e** [comment]
+1 for `filter_var($email, FILTER_VALIDATE_EMAIL)`

**Comment by nitriques** [comment]
Turn out, we already validated it. But without including the validators :(

**Comment by nitriques** [comment]
@michael-e @brendo please check the attached commit ^^^

**Comment by brendo** [comment]
LGTM 👍

**Comment by michael-e** [comment]
Yep.
