### ISSUE TITLE
Unknown system variable 'storage_engine'

### ISSUE THREAD

**Issue by Manaus** [symphonycms/symphony-2#2633]
Hello,  
I'm trying to install latest version `2.6.8` on Wampserver, but I get this logged error: 

	INSTALLATION PROCESS STARTED (2016-11-05T15:19:36+00:00)
	============================================
	11/05/2016 3:19 pm > Notice: MYSQL: Establishing Connection
	11/05/2016 3:19 pm > Notice: MYSQL: Importing Table Schema
	11/05/2016 3:19 pm > Fatal Error: There was an error while trying to import data to the database. MySQL returned: 1193: Unknown system variable 'storage_engine'
	============================================
	INSTALLATION ABORTED: Execution Time - 1 sec (05.11.16 15:19:36)
	============================================

Wampserver has these settings: 

	Apache 2.4.23
	Php 5.6.25
	MySQL 5.7.14

I tried to look up the problem, in my `mysql.ini` file I see `default-storage-engine=MYISAM` though. 

Thanks

**Comment by brendo** [comment]
Hmm, the fix for this probably should of been backported to 2.6.8 as well. Doh.

MySQL 5.7.5 removed the `storage_engine` variable, replacing it with `default_storage_engine`. We have the fix on the [2.7.x branch](https://github.com/symphonycms/symphony-2/blob/2.7.x/symphony/lib/toolkit/class.mysql.php#L1039).

**Comment by timokleemann** [comment]
Temporary fix: Simply replace `storage_engine` with `default_storage_engine` in `symphony/lib/toolkit/class.mysql.php`

**Comment by nitriques** [comment]
> this probably should of been backported to 2.6.8 as well. Doh.

Indeed. But I prefer to work on 2.7.0 ;P
