### ISSUE TITLE
odd SymphonyCMS behaviour/error

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2634]
sections created / entries added / all fine.
i alter the data during development / all fine.

then suddely, a worse case scenario: live event with 200+ peoples, this error appeared.

**Symphony 2.6.7** used

![screencapture-vsfm2-dev-dashboard-publish-questions-1479589879593](https://cloud.githubusercontent.com/assets/2312755/20458444/1bafa0ae-aeae-11e6-863f-4007fe2c4957.png)

**Comment by nitriques** [comment]
Hopefully #2663 will fix this (in conjunction with many other things).
