### ISSUE TITLE
Version check for extensions is broken with Symphony 2.6.10

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2641]
After updating to Symphony 2.6.10, the extensions page is crowded with: `requires Symphony 2.6`. Obviously the version check doesn't work as advertised.

These complaints occur for all extensions that have `min="2.6.x"` or `min="2.6.0"` or `min="2.6"` requirement, in short words: Mimimum version is "2-6-something". All other extensions work fine in my case.

Examples:

* fine: Members ( `<release version="1.5.2" date="2016-06-23" min="2.4.0" max="2.x.x">`)
* fine: Remote Datasource ( `<release version="2.2.1" date="2015-12-01" min="2.4" max="2.6.x">`)
* complaining: Select Box Link Field (`<release version="1.33" date="2015-02-23" min="2.6.0">`)
* complaining: Email Newsletter Manager ( `<release version="3.3.0" date="2016-11-03" min="2.6" max="2.6.x">`)

**Comment by michael-e** [comment]
If I am not mistaken, the issue is in line 968 of `/symphony/lib/toolkit/class.extensionmanager.php`:

```php
$current_symphony_version = preg_replace(array('/dev/i', '/-?beta\.?\d/i', '/-?rc\.?\d/i', '/.0/i'), '', $
```

Shouldn't the last dot be escaped, like so:

```php
$current_symphony_version = preg_replace(array('/dev/i', '/-?beta\.?\d/i', '/-?rc\.?\d/i', '/\.0/i'), '', $
```

@brendo? @nitriques?

**Comment by brendo** [comment]
We may do well to start to reach outside of our circle for this, [composer/semver](https://github.com/composer/semver).

**Comment by michael-e** [comment]
But we need a bugfix first for the 2.6.x line, don't we?

**Comment by brendo** [comment]
> But we need a bugfix first for the 2.6.x line, don't we?

We can, but our handling still won't be as robust as a package that's sole purpose is to do this.

The issue right now is that we've never had a patch version greater than 9. The line highlighted above attempts to 'normalise' the version by removing `dev`, `beta`, `rc` and replacing it with nothing. eg.

```
2.6.7dev => 2.6.7
2.5.1-rc.1 => 2.5.1
```

This falls down right now because it also attempts to normalise versions:

```
2.5.0 => 2.5
2.6.10 => 2.6.10
```

I'm not quite sure how this is affecting the remaining logic.

**Comment by nilshoerrmann** [comment]
> But we need a bugfix first for the 2.6.x line, don't we?

This features has been fixed several times already, either within the core or within the extensions (all of them). It never worked reliably. Using a dedicated and tested package for this task sounds like a good idea to me.

**Comment by michael-e** [comment]
I understand your concerns. But won't this take some time? Isn't this something for 2.7, because it might as well introduce new issues?

**Comment by nilshoerrmann** [comment]
Yes, raising the version number sounds appropriate. I'm not sure if manual fixing would be faster (at least if you don't want it to break again soon).

**Comment by michael-e** [comment]
My fix above doesn't work correctly. The regex expression in question should be:

```php
/\.0(\.0)?$/i
```

Then we get:

	2.0.0     ->  2
	2.0.1     ->  2.0.1
	2.0.10    ->  2.0.10
	2.1.0     ->  2.1
	2.1.1     ->  2.1.1
	2.1.10    ->  2.1.10
	2.10.0    ->  2.10
	2.10.1    ->  2.10.1
	2.10.10.  ->  2.10.10

I simply try do fix a regex mistake. With this fix version `2.6.10` stays `2.6.10` instead of becoming `2.6`. So it would be a simple solution for the stable 2.6 branch, and we could release 2.6.11 rather fast. (The 2.7 branch already has lots of new stuff.)

This doesn't mean that I am against the composer package. But on the first hand I am **pro** a stable and production-ready 2.6 branch.

**Comment by animaux** [comment]
@michael-e I can confirm this to work!

**Comment by nitriques** [comment]
Yeah thanks @michael-e I'll fix this ASAP.

**Comment by nitriques** [comment]
2.6.10 also broke a couple of things on the getsymphony.com website.

**Comment by michael-e** [comment]
I can send a pull request for this "extension version check issue" if you agree that my solution just fixes a faulty regex (so it shouldn't make anything worse). Just tell me to which branch I should send it.

**Comment by michael-e** [comment]
The old regex — designed to strip `.0` from version numbers — was `/.0/i`. (The `i` modifier ist useless here.) The dot matches any alphanumeric character or number, so the expression will match the `10` in `2.6.10` (resulting in `2.6.`). My solution simply assumes that the desired output in this case is `2.6`. See https://github.com/symphonycms/symphony-2/issues/2641#issuecomment-273440454

**Comment by nitriques** [comment]
Please go ahead and submit against the `2.6.x` branch. Thanks Michael.
