### ISSUE TITLE
Date field filtering

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2645]
When viewing the database queries in the profile view I noticed an odd thing related to date field filtering in data sources: using `equal to or later than today` or `equal to or earlier than today` filters results in wrong date ranges.

### Later than

    (`t171`.date >= '1000-01-01 00:00:00' AND `t171`.date <= '2017-01-26 23:00:00')

Notice the time `23:00:00`. This should be `23:59:59`.

### Earlier than

    (`t100`.date >= '2017-01-26 23:00:00' AND `t100`.date <= '9999-12-31 23:59:59')

Notice the time `23:00:00`. This should be `00:00:00`.

---

I'm not sure where the `23:00:00` comes from in both cases but it makes Symphony miss dates (1 hour of today in the first case and even 23 hours in the second case). Maybe its an issue related to timezones (we are GMT+1:00).

**Comment by nilshoerrmann** [comment]
> Maybe its an issue related to timezones (we are GMT+1:00).

It certainly has to do with timezones: I just noticed that not just the time is offset but that `today` is actually shifted back one day. It should have been `2017-01-27` in this case, not `2017-01-26`.

**Comment by michael-e** [comment]
AFAIK, the `date`column in the database contains the GMT value (which corresponds to the localized value in the `value` column). So this looks correct to me.

**Comment by nilshoerrmann** [comment]
Right, that's a good point. Still, in the first case it should be `22:59:59`, shouldn't it? That's the last moment of the day – `24:00:00` doesn't exist – and it's the value used for all other comparison dates.

One question remains though: If relative dates are created with timezones in mind, what about dates passed as parameters from the frontend which are timezoneless?

**Comment by michael-e** [comment]
Yould it be that the examples are swapped in your first post?

Anyway. You said `equal to or …` – this includes 00:00:00, which is 23:00:00 GMT. So the query uses `<=` resp. `>=`.

> what about dates passed as parameters from the frontend which are timezoneless?

They are not timezoneless, because Symphony assumes the system timezone. :-) I think that this has been discussed a long time ago, and the major issue with "personalized timezones" is retrieving the right timezone. So this has never been implemented, as far as I know.

**Comment by nilshoerrmann** [comment]
> Yould it be that the examples are swapped in your first post?

D'oh! You're right! Not the right day for thinking about date as it seems ;)

> They are not timezoneless, because Symphony assumes the system timezone. :-)

Well, okay, I remember that discussion and it makes sense. But if the date comparison takes place in GMT (that's what used from the database and that's what relative dates are converted to) where do passed parameter dates converted to GMT (based on the shift of the system time)?

Entschuldige das Nachhaken, aber vielleicht stehe ich heute auch einfach nur völlig auf dem Schlauch … Macht gerade alles keinen Sinn hier …

**Comment by michael-e** [comment]
> … Macht gerade alles keinen Sinn hier …

Oh, das kenn ich. :-)

> where do passed parameter dates converted to GMT

Honestely, I have no idea if this happens at all. I would expect it, however. Have you tested it?

**Comment by nilshoerrmann** [comment]
After testing parameters and static values, it seems like the conversion to GMT is not consistent across all used dates (e. g. "endless" values like `9999-12-31 23:59:59` are not converted). But all dates that matter seem to be converted. So, although not being very intuitive to read, everything seems to be correct.
