### ISSUE TITLE
Parameter suggestions in DSE

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2646]
It seems like parameter suggestions for filters in the data source editor are broken for new data sources. They work for saved/existing data sources. The suggestion list is also shown correctly for other settings (like pagination or conditions).

**Comment by nitriques** [comment]
Actually, it is broken for new and saved DS.

**Comment by nitriques** [comment]
The lastest `2.7.x` branch contains the fix. Thanks Nils!

**Comment by nilshoerrmann** [comment]
Thanks for the fix!
