### ISSUE TITLE
Should sending emails break on missing attachments?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2656]
I noticed that sending emails breaks if attachments are set (e.g. using the Email Template Manager) but missing (unreadable/unexisting path or similar).

[This is intended](https://github.com/symphonycms/symphony-2/blob/2.7.x/symphony/lib/toolkit/class.emailgateway.php#L612-L620).

But this makes sending emails using the Email Newsletter Manager and the Email Template Manager less flexible. The definition of attachments requires the attachments to actually exist — in other words:  you can't provide email logic with *optional* attachments to your authors.

I myself already hacked the `EmailGateway` class in order to not break on missing attachments (and also set email headers and boundaries accordingly).

Is this a change that is interesting for the core?

**Comment by nitriques** [comment]
How would you patch it ? With an optional parameter that says skip non existing attachment ? Would you log that ?

Why not just validate the file yourself ? You want to avoid doing the check twice ?

**Comment by michael-e** [comment]
> You want to avoid doing the check twice ?

Exactly. And even if a first check would succeed, the actual loading might fail (because the file has gone away). So checking in advance would not prevent all problems.

> How would you patch it ?

I just implemented a "silent fail", as described above. The email will still be sent if an attachment can not be read. I don't need a parameter to configure this behaviour, and I don't need any logging in this case. If that is interesting for the core, I can send a PR. If this is not considered a good solution, well, never mind. :-)

**Comment by michael-e** [comment]
To be more clear:

I prefer to not let an email fail because of a missing attachment. I myself use this as the default behaviour. So I changed `EmailGateway::getSectionAttachments` (where an attachment actually gets loaded).

I also thought about logging such incidents (instead of throwing an exception, which stops the process and prevents the email from being sent). But in my case that doesn't make sense. I send emails to thousands of recipients, and if the attachment is *deliberately optional* (but still defined in the ETM using an XPath expression), the log would get polluted with thousands of messages.

There are good arguments for either behaviour, and I wouldn't say that the behaviour I implemented is *right*… But it's the best for me.

Doing this *really right* (make fail behaviour configurable, make logging configurable, thus breaking the API, probably more than that…) would increase complexity way too much, IMHO. We shouldn't do that without need.

**Comment by michael-e** [comment]
@nitriques: Please feel free to close this issue if you prefer the current default behaviour.

**Comment by nitriques** [comment]
Let's just add a private property on the class (with a getter and setter) to ignore attachments errors. No change to the API nor behavior. Would this suffice ?

**Comment by michael-e** [comment]
I will take a look. It might get a bit complicated in `EmailGateway::prepareMessageBody`, however.

Do we really need a getter method as well? Actually we don't have getters for most of the email properties. (The email gateway has a "magic function" `__get($name)` instead.)

To which branch should PRs be submitted? 2.7.x?

**Comment by nitriques** [comment]
> Do we really need a getter method as well? 

No we don't, you're right.

>  2.7.x

Yup. But I can now change the base of any PR, which is pretty awesome.

**Comment by michael-e** [comment]
> I can now change the base of any PR

I didn't know that. Thanks for this info!

**Comment by nitriques** [comment]
![image](https://cloud.githubusercontent.com/assets/771169/25407716/5fcf202e-29d9-11e7-9e68-4c6f830f2f05.png)
:)
