### ISSUE TITLE
Section entries cannot be selected after a reorder

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2657]
**How to reproduce:**
1. Go to Blueprints > Sections
2. Drag'n'drop reorder a section entry
3. Try to mouse-click-select any section entry
4. The section entry selection is lost, I think due to an incorrectly again-invoked reorder with step 3.

**I have:**
* Symphony v2.6.11
* Opera 44 / Firefox 52 / Ubuntu OS

**Comment by nitriques** [comment]
Test the latest `2.7.x` branch please! Thanks!
