### ISSUE TITLE
Hidden sections can't be used for associations

### ISSUE THREAD

**Issue by mprofitl** [symphonycms/symphony-2#2658]
A newly created section, if marked as hidden ("hide section from menu"), will be hidden in the backend from the association extension as well. Thus it is impossible create an association field and to connect it with the hidden section. One needs to unhide it first, then associate it and hide it again.

Wouldn't it be better to show all sections as possible associations in the backend, no matter what there visibility is?

<img width="1032" alt="list of possible associations" src="https://cloud.githubusercontent.com/assets/6146601/25008300/96abb938-2063-11e7-8c4f-90a8b753394d.png">

**Comment by nitriques** [comment]
This is not related to the core, so I've open a new issue in the right project. Closing here.

**Comment by mprofitl** [comment]
Thank you – I realised through your comment that it is an issue of the association field.

**Comment by nitriques** [comment]
Not a problem! It's better to report it at the wrong place, than letting it go unreported!
