### ISSUE TITLE
Sendmail security enhancement from Symphony 2.6 should be included in 2.7

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2660]
15dc8eb5311db0e1e5b83301f58954401471acdf should be included in 2.7.x as well.

Unfortunately the branches seem to have moved away from each other. @nitriques: Are you planning a rebase? (In this case there is no need to post issues like this.)

**Comment by nitriques** [comment]
> Are you planning a rebase?

Yup, see #2643

**Comment by nitriques** [comment]
All of 2.6.x will be included in 2.7.0
