### ISSUE TITLE
Too many calls to `clearstatcache`

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2671]
`General::writeFile` calls `clearstatcache` before checking a file with `General::checkFile`. This is completely unnecessary, because `General::checkFile` does it itself.

So why has [this been added](https://github.com/symphonycms/symphony-2/commit/2d8e41016314582631e4bbc6311f8421dc278be5)?

---

BTW, do we need to call `clearstatcache` at all in the General functions? Looking at the PHP manual I don't find any reason to do so. They say:

> This function caches information about specific filenames, so you only need to call clearstatcache() if you are performing multiple operations on the same filename and require the information about that particular file to not be cached.
> —http://php.net/manual/en/function.clearstatcache.php

So I wonder if `clearstatcache` should be removed from all `General` class methods (also work in progress, e.g. https://github.com/DeuxHuitHuit/symphony-2/commit/d8ce2b08e505c95c5544e29a592f579dc029ad8a).

Just thinking loud… It might be better to keep those calls, simply because it's hard to test what might happen otherwise. :-)

**Comment by nitriques** [comment]
> So why has this been added?

To prevent false positive ! Hahah! If you read/write the same file over and over, some other process could change it's right or even delete the file. From what I've seen, php functions might return a cached result, which would then render our check useless.

From the same manual page:

> PHP caches the information those functions return in order to provide faster performance. However, in certain cases, you may want to clear the cached information. For instance, if the same file is being checked multiple times within a single script, and that file is in danger of being removed or changed during that script's operation, you may elect to clear the status cache. In these cases, you can use the clearstatcache() function to clear the information that PHP caches about a file.

> Affected functions include stat(), lstat(), file_exists(), is_writable(), is_readable(), is_executable(), is_file(), is_dir(), is_link(), filectime(), fileatime(), filemtime(), fileinode(), filegroup(), fileowner(), filesize(), filetype(), and fileperms().

So I think, we need it.

**Comment by nitriques** [comment]
Maybe @brendo knows more then me about that detail.

**Comment by michael-e** [comment]
But not [the additional one in `General::writeFile`](https://github.com/symphonycms/symphony-2/commit/2d8e41016314582631e4bbc6311f8421dc278be5), right? :-)

**Comment by michael-e** [comment]
I mean, it's called twice, as mentioned in my intial post. Twice is a lot.

**Comment by nitriques** [comment]
Well my point was the fact that you still can't be sure.
But we might want to remove it AND remove the checks as well. I mean, the method's name is write, not check and write. But I guess that would be a breaking compat change (?)

SO maybe we should remove the checks but replace it with our new version, than remove that call from later releases ?

**Comment by michael-e** [comment]
I think I wasn't clear. At the moment `writeFile` calls `clearstatcache`, then `checkFile`. The latter function will also call `clearstatcache`. It's the double call to `clearstatcache` which seems useless to me.

I think it's OK for all `check` functions to call `clearstatcache`. (One might add another parameter to make this configurable, but that's "premature optimization", because probably nobody ever needs to switch this off).

So my suggestion is to remove `clearstatcache` from the `writeFile` function (but keep `static::checkFile`). This wouldn't break any behaviour.

(With the new `General::checkFile*able()` functions, we could also add a check to `General::deleteFile`.)

**Comment by nitriques** [comment]
Sorry I was looking at the wrong version of the file (`General::checkFile` wasn't used in `writeFile` in that version. Yes I totally agree with you. I'll fix it.
