### ISSUE TITLE
Make error_reporting configurable

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2674]
As proposed in #2673

Should it only be a "script_php" bool ?

**Comment by nitriques** [comment]
@michael-e name proposition for this value ? bool or configurable value ??

**Comment by michael-e** [comment]
What about `error_reporting_all` (boolean, meaning 'yes' or 'no' in the config file)? Developers would hopefully understand this.

It should set PHP's error_reporting to `E_ALL` only if the value is `yes`. If the setting is missing or has a value different from `yes`, it should do nothing.

I do not think we need anything more complicated, e.g. several reporting levels. It should be enough to choose between "Symphony's perferred reporting" level (config value is `no` or missing) and the "demanding show-all" level (`yes`).

**Comment by jensscherbl** [comment]
Can we push this back to `2.8.0`?

**Comment by michael-e** [comment]
Why would you like to push this back?

**Comment by jensscherbl** [comment]
> Why would you like to push this back?

I don’t think it's important enough (i.e. a bug or a security concern) to hold the `2.7.0` release back.

**Comment by michael-e** [comment]
I see your point, but AFAIK @nitriques wants to have as much as possible in 2.7. So I leave this to him.

**Comment by jensscherbl** [comment]
> So I leave this to him.

Sure.

> wants to have as much as possible in 2.7

Any idea why?

**Comment by michael-e** [comment]
It shall be an LTS version, AFAIK.

**Comment by nitriques** [comment]
> wants to have as much as possible in 2.7

Cause releasing takes time ;)

**Comment by michael-e** [comment]
@jensscherbl: making the error reporting configurable shouldn't take too much time. It will be a different story, of course, to fix all the warnings on `E_ALL` reporting. So I do not expect the latter to be done for 2.7.0, and it is not part of this issue.
