### ISSUE TITLE
Remove support for Dynamic XML Data sources

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2679]
The 2.4 updater states that

> Existing Dynamic XML Data Sources can be edited and will continue to function until Symphony 2.7.0.

So we can remove the support for 2.7.0. ?

Or should we wait for a major release ?

**Comment by nilshoerrmann** [comment]
If you think old-style Symphony then `2.7.0` is just fine.  
If you think semver-style then you shouldn't wait but should still raise the version number to `3.0.0`.

**Comment by nitriques** [comment]
Safety's first then.
