### ISSUE TITLE
Email::create will throw warnings

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2690]
The [Core Email API documentation](https://github.com/symphonycms/symphony-2/wiki/Email-in-Symphony#using-the-core-email-api-programatically) states that new Email objects are created using `Email::create()`. And this is how Symphony does it, and extensions alike.

However, a PHP warning may occur, because `create` [is not a static method](https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/lib/toolkit/class.email.php#L34)! See, for example: https://github.com/michael-e/email_template_manager/issues/92

Is there any reason why we should **not** make `Email::create()` static? To me it looks like an oversight, but maybe I don't see potential side effects?

**Comment by nitriques** [comment]
It should be static. Old PHP versions (<=5.6) allowed any method to be called via a static interface. Even if it used the `$this` keyword, (which would reference the caller object and lead to disastrous bugs. I hope this is not valid anymore. But anyhow, it should be avoided at all cost. Wanna send a PR ?

**Comment by michael-e** [comment]
Yes, if you expect no side effects, I will send a PR.

**Comment by michael-e** [comment]
https://github.com/symphonycms/symphony-2/pull/2691

**Comment by nitriques** [comment]
> Yes, if you expect no side effects, I will send a PR.

Since `$this` is not used, it should not change a thing. Thanks!
