### ISSUE TITLE
[Suggestion]: Log deprecated usage

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2693]
Would this helps extensions developers ?

**Comment by michael-e** [comment]
Sure it wood. If it was documented. :-)

(BTW, same applies to the new "secret setting" to throw all PHP warnings. Should we open an issue to add this to the README, or the Wiki?)

**Comment by nitriques** [comment]
>  If it was documented. :-)

If the logging of deprecate calls was documented ? I do not mind having secret stuff, it hides the complexity to beginners and make it easier for us to offer help here and on the chat...

Both will be listed in the change log, is that enough ? :P

**Comment by michael-e** [comment]
Yep, agreed.

**Comment by nitriques** [comment]
Great!

**Comment by brendo** [comment]
Node actually offers a utility function for this, [`util.deprecate`](https://nodejs.org/api/util.html#util_util_deprecate_function_string), that's simply a wrapper around the original function. I think it's a good idea.

**Comment by nitriques** [comment]
> Node actually offers a utility function for this

Lol, that were the idea comes from! I was reading node v8's change log which offers a switch to see those warnings in stdout.
