### ISSUE TITLE
Access-Control-Allow-Origin header should not be present

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2699]
According to the [Mozilla docs](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cross-origin_Resource_Sharing) the `Access-Control-Allow-Origin` header can be used to explicitely allow foreign origins to access the content of pages on your domain via scripts (e.g. XMLHttpRequest). It is some sort of "additional whitelisting" and **not** a lock-down-mechanism.

In other words, it makes no sense to set this header to the own domain, but Symphony does exactly this.

Mozilla states:

> These should not be present unless specifically needed.

I suggest to remove this header from Symphony pages (backend and frontend alike).

**Comment by nitriques** [comment]
This line was added with the [XSRF token](https://github.com/symphonycms/symphony-2/commit/4c0c622b133d357131c3cca4ba736d96b2b72485) feature.

We've had [the same issue](https://github.com/symphonycms/symphony-2/issues/2480) which proposed to removed it, but @brendo had a good argument to keep it [here](https://github.com/symphonycms/symphony-2/issues/1874#issuecomment-40071925)

> a previous security audit, (...) Access-Control header ensures other sites cannot load your site via AJAX where they could potentially capture the XSRF token and then use along with a POST.

So I think we still need it...

Does it causes a problem in your setup?

**Comment by michael-e** [comment]
@brendo said:

> We already had **X-Frame-Options** in the backend as recommended by a previous security audit

Aha, *that* header was requested by the audit.

> Access-Control header ensures other sites cannot load your site via AJAX where they could potentially capture the XSRF token and then use along with a POST.

Completely different story, this has nothing to do with the audit. IMHO @brendo misunderstood how this header is supposed to work. As mentioned above, it's not a necessary lock-down mechanism, but rather an "open doors explicitely" mechanism. CORS works like this — locking everything down unless you open it up explicitely; see https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS

Look at GitHub's response headers. They have done a lot for security (for example, they get [120/100 points at Mozilla Observatory](https://observatory.mozilla.org/analyze.html?host=github.com&third-party=false)!). But there is no `Access-Control-Allow-Origin` header in GitHub responses.

> So I think we still need it...

I don't think so.

> Does it causes a problem in your setup?

No, but in my head. If I understand everything correctly, Symphony is doing something stupid. :-(

@brendo?

**Comment by nitriques** [comment]
> Symphony is doing something stupid.

It sets a limit that is already the same as the same-origin policy...

I do not mind removing it, (as I already overwrite it to be something else via apache), but I'd like to get @brendo thoughts, if and when possible.

**Comment by michael-e** [comment]
Yep, agreed, let's hear what @brendo thinks.

**Comment by nitriques** [comment]
@brendo ping!

**Comment by brendo** [comment]
Scratching my brain to recall the details of this, but just responding based off the knowledge I have _now_ about CORS, I think the main error in implementation is always having that header present. I believe that header should only be present when the incoming request contains an [`Origin`](https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS#Origin) header.

**Comment by michael-e** [comment]
So should the Symphony core set such a header at all? I don't think so — it depends on the application. Do you agree?

**Comment by brendo** [comment]
It'd probably be better extracted out as an extension on reflection. One that allows for better configuration of the headers to send, and when to send them and for what resources.

I don't think it'd hurt the core to still conditionally set this from an AdministrationPage perspective.

**Comment by michael-e** [comment]
I don't agree. Without any further knowledge, we can only set the "superfluous value" that is used currently (see discussion above). It's better to omit the header altogether in this case.

**Comment by nitriques** [comment]
I tend to agree with @michael-e on that case @brendo. If it does not have any purpose, we can remove it. I just wanted to make sure it was not added as part of the security audit.

**Comment by nitriques** [comment]
OWASP tends to recommand the same thing:

> Use the Access-Control-Allow-Origin header only on chosen URLs that need to be accessed cross-domain. Don't use the header for the whole domain.

(Ref: https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet)

**Comment by brendo** [comment]
I guess the problem for us right now is we can't possibly know what pages or extensions already rely on this header. That's my fault for including it back then!

**Comment by nitriques** [comment]
> what pages or extensions already rely on this header. 

Nothing relies on it, since the restriction will be the same. Less bytes on the wire that's all.
