### ISSUE TITLE
Field integrity tests

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2703]
I don't know how it happens, but it sometimes occurs to me that database tables don't feature the expected columns required by the given field type. E. g. a Textbox field having the table columns of a core textarea. My guess is this happens when you remove a field and add a new field of the same name but of a different type. Maybe some of these mismatches are also caused by failed database merges or backups.

It would be handy to have some kind of field integrity test, where Symphony validates if field tables match their signature defined in the field's `createTable` function.

**Comment by nitriques** [comment]
@nilshoerrmann This **crazy** bug happen to me too. A LOT. Which version of Symphony to you run ?

**Comment by nitriques** [comment]
Hopefully, it is not 2.7.0 and [this is still a solution](https://github.com/symphonycms/symphony-2/pull/2659#issuecomment-297829904)...

**Comment by nilshoerrmann** [comment]
I'm currently using the latest stable release (that should be `2.6.11`, I think).  
But this happened on each and every Symphony version I worked with.

**Comment by nitriques** [comment]
Ok so there is still hope.

**Comment by nilshoerrmann** [comment]
What I was thinking of: 

1. When saving section, Symphony could validate the field signature and throw and error when it finds a mismatch.
2. It would also me nice to have a button in the preferences that initiated a field integrity test.

The latter is certainly something an extension could do best (don't bloat the core). But the first is actually something Symphony should take care of itself.

**Comment by nitriques** [comment]
Well I hear Michael in head telling me that we should not try to fix errors, we must avoid them ;)

**Comment by nilshoerrmann** [comment]
Well, my guess is – as mentioned in the initial post – that the integrity issues arise from saving a section. So validating field tables on section save is about avoiding this error.

**Comment by nitriques** [comment]
Yup, and that's what the mention commit does ;)

**Comment by michael-e** [comment]
> Well I hear Michael in head telling me that we should not try to fix errors, we must avoid them ;)

Wasn't this different? Don't try to *hide* errors but let 'em scream!

**Comment by nilshoerrmann** [comment]
> Yup, and that's what the mention commit does

But that works on the entry level not on the section level, right? So I'll be notified, when I save an _entry_, is that correct?

**Comment by nitriques** [comment]
The idea of the "timestamp validation" is to prevent you from overriding something that was done in between requests (in an another browser/tab or another user). The commit I pointed out was made in the same PR, but is unrelated: it checks that the field exists for real before trying to update it: before it could somehow think that the removed field == the new field.
