### ISSUE TITLE
Default date preferences

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/symphony-2#2704]
If – in the config – the date preferences are empty, Symphony doesn't default to any standard format. It just doesn't output dates anymore (showing `None`).

```php
'region' => array(
	'time_format' => null,
	'date_format' => null,
	'datetime_separator' => null,
	'timezone' => 'Europe/Berlin',
),
```

This caused me to think that something went terribly wrong and the database was corrupted. 

### Expected behaviour

I'd expect Symphony:

1. to log an error,
2. to show a warning in the interface,
3. to fall back to a default format.

**Comment by nitriques** [comment]
Wow, that's pretty cool ;)

**Comment by nitriques** [comment]
I bet there are a lot of things that goes wrong when some config is missing ;)

**Comment by nitriques** [comment]
@nilshoerrmann It's a problem everywhere we use config values: we rarely check if they are missing. 

How did you lost those values ?

**Comment by nilshoerrmann** [comment]
The German translation might be at fault. It happened after saving the prefs.

**Comment by nilshoerrmann** [comment]
Yes, it's the German translation: https://github.com/animaux/lang_german/blob/master/extension.driver.php#L81-L105

Besides providing the translations, it also toggles between German and English date and time formats. Like Symphony, it should default to fallback settings.

/cc @animaux

**Comment by nitriques** [comment]
Ok! Well I hope #2705 does not makes thing worst ?

**Comment by nilshoerrmann** [comment]
#2705 works great. Along with https://github.com/animaux/lang_german/issues/9, this issue should be fixed.
