### ISSUE TITLE
Rebase before releasing the next Beta?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2708]
It will probably be a big undertaking to rebase 2.7.x on 2.6.x., and we all know that things can go wrong. So shouldn't this be done before releasing the next 2.7 beta?

I think that we should have at least one "porperly rebased" beta before releasing the final product.

**Comment by nitriques** [comment]
yup, there's only 2 PR left before I rebase ;)

**Comment by michael-e** [comment]
Cool.

**Comment by nitriques** [comment]
[Those 2](https://github.com/symphonycms/symphony-2/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20milestone%3A2.7.0) :D

**Comment by nitriques** [comment]
@michael-e I've just tested the rebase operation, and it worked! 406 commits!!!
Will push tomorrow!

**Comment by nitriques** [comment]
I've [made a tool](https://github.com/DeuxHuitHuit/rebase-with-history) just for this occasion :)

**Comment by michael-e** [comment]
Sounds great!

**Comment by nitriques** [comment]
Pushed!

**Comment by nitriques** [comment]
Here's what to do if you already have the `2.7.x` branch on your computer.

```
git checkout master
git fetch --all
git pull upstream master
git branch -D 2.7.x
git checkout 2.7.x
git push origin 2.7.x -f
```
