### ISSUE TITLE
Copy text on Blueprints > Data Sources should be improved

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2710]
In https://github.com/symphonycms/symphony-2/pull/2702 changes to the data source GUI were introduced. Now we have:

> Enabling these conditions will send a 404 page not found error.

Please, read this aloud.

**Enabling the conditions** will throw an error?

We also have:

> Leaving these fields empty will always execute the data source.

The negation makes this hard to understand. Leaving something empty will do something…

We should improve this. Regarding the "Error Conditions", I would prefer "Error 404 Conditions". 

Maybe we don't need additional text at all?

@nils, @brendo

**Comment by nitriques** [comment]
The wording has been discussed in length in [the the PR](https://github.com/symphonycms/symphony-2/pull/2702#issuecomment-306506725). Maybe the sentence does not make sense because the <code> format is not that apparent.

> Enabling these conditions will send a 404 page not found error.

It should be understood as 

Enabling these conditions will send a "404 page not found" error.

> We also have:

>> Leaving these fields empty will always execute the data source.

[This wording has been introduced 4 years ago](https://github.com/symphonycms/symphony-2/blame/d1be054abbe03638b78c7d12fdb005d31c442d49/symphony/content/content.blueprintsdatasources.php)

In understand your concerns, but that  one is not related to #2702

**Comment by michael-e** [comment]
> It should be understood as: Enabling these conditions will send a "404 page not found" error.

No, this is semantically wrong. Please think about it. "Enabling conditions" won't send an error—the conditions must also be met when a datasource is executed. It would be much more correct to say: "If enabled conditions are met, a 404 error will be sent".

This should be fixed, really.

---

>> Leaving these fields empty will always execute the data source.

> This wording has been introduced 4 years ago

Ok, in this case this is nothing that must be fixed fast. Somehow the new layout made it more prominent to me.

**Comment by nitriques** [comment]
@brendo since you are the writer behind that sentence and since you are a native English speaker, I'd like to get your feedback on this.

I personally find @michael-e proposition to be clearer, but I would put the whole error name in there.

> If enabled conditions are met, a `404 page not found` error will be sent

**Comment by jensscherbl** [comment]
> Error 404 Conditions

I agree that the current wording is not perfect, and I like @michael-e’s suggestion as well, but this can always be improved in a patch release, so I wouldn't consider this to be a blocker for the `2.7.0` release.

**Comment by nitriques** [comment]
I'll leave this open for the 

> Leaving these fields empty will always execute the data source.

part.

**Comment by nitriques** [comment]
This has been fixed in 5763872ba7bb383995d94fd7e1d34f76c206f8ae
