### ISSUE TITLE
[2.7.0RC1] Symphony polluting the logs

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2711]
RC1 is polluting the log file with the following message:

> Deprecated Warning: The method `Datasource::grab()` is deprecated. It will be removed in Symphony 3.0.0. Please use `Datasource::execute()` instead. Called from `FrontendPage::processDatasources()` in class.frontendpage.php at line 895

If s.th. is deprecated, Symphony itself should not use it, right?

**Comment by michael-e** [comment]
Here's a second one which sounds more severe:

> Deprecated Warning: The use of `SHA1::hash()` is strongly discouraged due to severe security flaws. It will be removed in Symphony 3.0.0. Please use `PBKDF2::hash()` instead. Called from `Author::createAuthToken()` in class.author.php at line 157

**Comment by nitriques** [comment]
> If s.th. is deprecated, Symphony itself should not use it, right?

No, because it break compatibility with older setups.

> Here's a second one which sounds more severe:

Hashing passwords with SHA1 is not considered secure anymore. How come your users never got upgraded to PBKDF2 ?
---

Re #2701

**Comment by michael-e** [comment]
> Hashing passwords with SHA1 is not considered secure anymore. How come your users never got upgraded to PBKDF2 ?

This error occured in a new test setup. I installed Symphony 2.6.11 with the default workspace, then upgraded to Symphony 2.7.0RC1.

**Comment by nitriques** [comment]
Hum I wonder why then... Let me test that.

**Comment by nitriques** [comment]
I've found the problem: The SHA-1 is used to generate the remote login token.

We have 2 options:

1. A more secure one, would be to switch to PBKDF2 token (and BTW make them way bigger).
2. Do not use the SHA1 class and use directly php's function.

Votes are open!

**Comment by nitriques** [comment]
And I get that error with the workspace: The Section, 1, associated with the Data source, <code>Archive</code>, could not be found. on line 482 of file symphony\lib\toolkit\data-sources\class.datasource.section.php

**Comment by michael-e** [comment]
What do you mean by PHP'S function? Something like `password_hash('test', PASSWORD_DEFAULT)`?

Why is the remote login token a hash at all? I would expect it to be "simply random", at the same time as random as possible.

**Comment by nitriques** [comment]
> What do you mean by PHP's function? Something like password_hash('test', PASSWORD_DEFAULT)

Yup. Or `sha1()`, which would prevent the token from changing when updating from lower than 2.7.0

> Why is the remote login token a hash at all?

This is a good question...

> I would expect it to be "simply random", at the same time as random as possible.

Using the username and password as input is OK IMHO. It makes things deterministic unless the username or password changes (which is what we want)

I think that the best route would be to use `sha1()` to not break things, but also create an issue for future release where we would change that. I would at least MAKE IT LONGER

**Comment by michael-e** [comment]
I understand the compatibility argument. But the current solution is really insecure, because these tokens are too short. So improving this would feel like a legitimate bugfix to me (even if it breaks compatibility).

Well, SHA1 isn't regarded "secure" to hash passwords, but in our scenario I don't see an issue. What can you do if you "break" the hash? Log in? So what? You can do that anyway if you know the hash.

All in all I think that SHA 1 (160 bits, not truncated, which means 40 characters in HEX) would be a proper solution for our scenario. A bit better, for a future version, would be something as random as possible.

>  It makes things deterministic

Yes, exactly this is a common security issue. :-)

**Comment by nitriques** [comment]
Well we NEED it to be deterministic... or we need to save it in the DB.

> Well, SHA1 isn't regarded "secure" to hash passwords, but in our scenario I don't see an issue.

It is not, indeed. As we agree, length is the problem.

But I do not like the idea of breaking old logins url (And I do not want to have to answer to github issues for that mater)... so I'll switch to sha1() for now, but I'll open an issue for future releases.

**Comment by wdebusschere** [comment]
21/09/2017 2:00 pm > Deprecated Warning: The `system:date` data-source field is deprecated. It will be removed in Symphony 3.0.0. Please use `system:creation-date` or `system:modification-date` instead. Called from `SectionDatasource::execute()` in class.datasource.section.php at line 662

system:creation-date is not yet available

**Comment by nitriques** [comment]
> system:creation-date is not yet available

Can you explain a bit more ?

**Comment by wdebusschere** [comment]
In the log i get Deprecated Warning: The system:date data-source field is deprecated. It will be removed in Symphony 3.0.0. Please use system:creation-date or system:modification-date instead. I'm trying to solve the warnings, in order to faster detect errors in the log file.

I had changed the system:date field in the datasource to system:creation-date but it is not yet available. It might be a bit confusion to have this warning in an LTS version..

**Comment by nitriques** [comment]
> I had changed the system:date field in the datasource to system:creation-date but it is not yet available.

What do you mean by "not available yet" ? Where is it not available ?

**Comment by wdebusschere** [comment]
The warning advises me to update the system:date to system:creation-date, but when i edit the datasource and replace the content / Included Elements from system:date to system:creation-date it's not available..

Warnings are ok, but i want to solve them, because scrolling every day through a file of 25mb warnings is a hard job in order to detect errors..

Thanks.

**Comment by nitriques** [comment]
>  but when i edit the datasource 

This is the part I was not catching! Thanks! I'll fix this.

> Warnings are ok, but i want to solve them, because scrolling every day through a file of 25mb warnings is a hard job in order to detect errors

I would suggest to not read the log file directly, but with `grep`. Would would be able to search for errors only.

**Comment by nitriques** [comment]
Ok I remember why it is not there: it will in Symphon 3.0.0 since it is a breaking fix.
All of those breacking fixes will (should) be patched by the updater, so they should all go away.

**Comment by wdebusschere** [comment]
Ok for 3.0.0. but for 2.7.0? Does writing for each pageview 10 lines in the log doesn't make a cause a delay of some ms? I couldn't disable the log.

public static $enabled = false; or public static $logDisabled = true; didnt work in class.errorhandler.php

**Comment by michael-e** [comment]
I agree with @wdebusschere that it feels strange to have a log filled with "Deprecated Warnings" in an LTS version. We should find a way to prevent this (maybe only write these to the log if `error_reporting_all` is `yes`?).

**Comment by nitriques** [comment]
>  I couldn't disable the log.

I meant get rid of the implementation, i.e., delete [this line](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.log.php#L345)

> Deprecated Warnings" in an LTS version. 

node does it. Ubuntu does it.

But since is *CAN* cause a performance problem, I'll add a setting

**Comment by nitriques** [comment]
@michael-e @wdebusschere see #2762
