### ISSUE TITLE
[2.7.0RC1] Associations Drawer partially broken

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2713]
Using Symphony 2.6.11 and the default workspace, the associations drawer displays the link to the category "Symphony" for the first article:

<img width="1161" alt="bildschirmfoto 2017-06-18 um 16 49 34" src="https://user-images.githubusercontent.com/40072/27261589-63cb841e-5446-11e7-8710-aa4ddb7e0daa.png">

After upgrading to Symphony 2.7.0RC1, this relation is not shown—it reads:

    No links to Categories (1)

<img width="1151" alt="bildschirmfoto 2017-06-18 um 16 47 19" src="https://user-images.githubusercontent.com/40072/27261591-68074874-5446-11e7-9df5-f87dfb77e10e.png">

**Comment by nitriques** [comment]
Thanks, I'll fix this ASAP.

**Comment by nitriques** [comment]
Wow, even reverting https://github.com/symphonycms/symphony-2/commit/b85d998cfb670293c0cf4aa39bb154d57e63ef64 does not fix the issue. (it does, but creates new one)

**Comment by jensscherbl** [comment]
I have a project that heavily relies on the associations drawer, so I wouldn’t consider this the be a minor issue (would actually prevent me from updating the project to `2.7.0`).

**Comment by nitriques** [comment]
#2726 fixes this problem
