### ISSUE TITLE
JavaScript error in section editor

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2714]
In the section editor, when clicking either "Expand all" or "Collapse all" multiple times, you see a javaScript error in the console. It seems that this has been the same with Symphony 2.6.11, so this is not a newly introduced issue.

<img width="941" alt="bildschirmfoto 2017-06-18 um 17 02 34" src="https://user-images.githubusercontent.com/40072/27261680-419c5592-5448-11e7-9442-e999a132ef12.png">

**Comment by nitriques** [comment]
This should be fix. Make sure to build the assets before testing as they are not yet updated in this branch

**Comment by michael-e** [comment]
It's halfway fixed. As I said:

> when clicking either "Expand all" or "Collapse all" multiple times

You only fixed the "collapse" part. For expanding, the error still occurs.

**Comment by nitriques** [comment]
Thanks @michael-e ;) My last commit should address that. Everytime I push directly to the branch, I get bitten by it, I need to stop that... but it is SOOOOOO tempting...
