### ISSUE TITLE
[2.7.0RC1] Table "sym_sections" is missing column "modification_author_id"

### ISSUE THREAD

**Issue by twiro** [symphonycms/symphony-2#2715]
Just did a fresh install of Symphony 2.7.0.RC1 and got the following error when trying to save a section:

    Symphony Fatal Database Error: Unknown column 'modification_author_id' in 'field list'
    An error occurred while attempting to execute the following query
    INSERT INTO `sym_sections` (`modification_date`, `creation_date`, `modification_date_gmt`, `creation_date_gmt`, `author_id`, `modification_author_id`, `name`, `handle`, `navigation_group`, `hidden`, `filter`, `sortorder`) VALUES ('2017-06-19 13:17:48', '2017-06-19 13:17:48', '2017-06-19 11:17:48', '2017-06-19 11:17:48', '1', '1', 'Countries', 'countries', 'Content', 'no', 'no', '1')

Looks like this new column has [only been implemented in the updater](https://github.com/symphonycms/symphony-2/commit/eba83d4199a8068cf5771da30f573c1609b99321#diff-5d87d68eaaed91a9e8489d0622928ae6R37), but [not in the installer](https://github.com/symphonycms/symphony-2/blob/2.7.x/install/includes/install.sql#L232).

**Comment by twiro** [comment]
Looks like this new column is also missing in the table "**sym_entries**" if one doesn't [update](https://github.com/symphonycms/symphony-2/commit/eba83d4199a8068cf5771da30f573c1609b99321#diff-5d87d68eaaed91a9e8489d0622928ae6R49) but perform a [fresh install](https://github.com/symphonycms/symphony-2/blob/2.7.x/install/includes/install.sql#L40)!

**Comment by nitriques** [comment]
Thanks @twiro
