### ISSUE TITLE
Routing error with apache 2.4.26

### ISSUE THREAD

**Issue by neoteknic** [symphonycms/symphony-2#2716]
Strange bug started with Apache 2.4.26 :

Example in Prestashop 1.7 (link to module list) :
Link is  (apache 2.4.26) :
/module/catalog
instead of (apache 2.4.25) :
/adminXXXX/index.php/module/catalog

PHP version : php-fpm 7.1.6
Symfony 2.8.* lastest from composer

With same php version and Apache 2.4.25 it's ok.
Absolutly nothing was modified in php file or in php config (php-fpm was not restarted too, only Apache).

It's something related to Symfony\Component\Routing\Generator\UrlGenerator method doGenerate

**Comment by munki-boy** [comment]
This is Symphony CMS, you mean Symfony? :)

**Comment by neoteknic** [comment]
mistake not here sorry
