### ISSUE TITLE
2.7.x upgrade error

### ISSUE THREAD

**Issue by peterfleck** [symphonycms/symphony-2#2727]
I just did a fresh install rebasing the 2.7.x on my branch which is same as master but with some extensions. When I pressed *upgrade* I go this error.
```
============================================
Log Created: 2017-07-08T16:47:29+02:00
============================================
Symphony Log
Opened:  2017-07-08T16:47:29+02:00
Version: 2.6.11
Domain:  xx
--------------------------------------------
2017-07-08 16:47:32 > Fatal Error: Could not complete upgrading. MySQL returned: 1060: MySQL Error (1060): Duplicate column name 'author_id' in query: ALTER TABLE `sym_sections`
                        ADD COLUMN `author_id` int(11) unsigned NOT NULL DEFAULT 1,
                        ADD COLUMN `modification_author_id` int(11) unsigned NOT NULL DEFAULT 1,
                        ADD COLUMN `creation_date` datetime NOT NULL DEFAULT '2017-07-08 16:47:32',
                        ADD COLUMN `creation_date_gmt` datetime NOT NULL DEFAULT '2017-07-08 14:47:32',
                        ADD COLUMN `modification_date` datetime NOT NULL DEFAULT '2017-07-08 16:47:32',
                        ADD COLUMN `modification_date_gmt` datetime NOT NULL DEFAULT '2017-07-08 14:47:32',
                        ADD KEY `creation_date` (`creation_date`),
                        ADD KEY `creation_date_gmt` (`creation_date_gmt`),
                        ADD KEY `modification_date` (`modification_date`),
                        ADD KEY `modification_date_gmt` (`modification_date_gmt`);
2017-07-08 16:47:32 > Notice: Updater - Migration to 2.7.0.RC1 was unsuccessful
```

**Comment by jensscherbl** [comment]
Can you please elaborate a bit more on the steps to reproduce? “fresh install” along with “upgrade” is a bit confusing to me. Did you install everything from scratch with an empty database? Did you upgrade an existing project with a pre-existing database?

**Comment by peterfleck** [comment]
Hi @jensscherbl, here are the steps I took.

1. Cloned the master repository and added some extensions as submodules (before installing).
1. Rebased from 2.7.x . (All went fine.)
1. Installed using webinstaller.
1. From System -> Extensions installed the extensions.
1. On the top bar, there appeared the message - "An update has been found in your installation to upgrade Symphony to 2.7.0.RC1. View update."
1. When I clicked "View update" the error above appears. (Tried again there now and same happens).

**Comment by jensscherbl** [comment]
Created a branch that should resolve the issue:

https://github.com/jensscherbl/symphony/tree/2.7.x%232727

Can you please try it out and report back?

**Comment by peterfleck** [comment]
Thanks @jensscherbl I can confirm that this works. I also installed again from scratch to make sure.

**Comment by nitriques** [comment]
👍  @peterfleck the problem was that I did not properly set the version numbers. My bad.
The good thing is, I already have a branch ready for the 2.7.0 release and, as of right now, there are not more open PR for this release!

**Comment by nitriques** [comment]
Also: thanks @jensscherbl  ;)

**Comment by jensscherbl** [comment]
> The good thing is, I already have a branch ready for the 2.7.0 release and, as of right now, there are not more open PR for this release!

Damn. Was just about to open a new PR for that! :D

**Comment by nitriques** [comment]
No need, 2.7.0 is officially out!
