### ISSUE TITLE
Trailing slash rewrite should be simplified

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2730]
Affected Symphony version(s) : 2.x, 3.0
PHP version(s) : all
OS(es) : all

Symphony's trailing slash rule (in the `.htaccess` file) looks like this:

```apache
### CHECK FOR TRAILING SLASH - Will ignore files
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !/$
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteRule ^(.*)$ $1/ [L,R=301]
```

The third rewrite condition is superfluous, because the second condition's `!/$` will match everything that does not end with a slash. So the third condition can be removed, resulting in:

```apache
### CHECK FOR TRAILING SLASH - Will ignore files
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !/$
RewriteRule ^(.*)$ $1/ [L,R=301]
```

**Comment by nitriques** [comment]
Thanks @michael-e !
Which version of Apache did you tested with ?

**Comment by michael-e** [comment]
I tested with Apache 2.4.10, but IMHO it should be the same with every version, because it's a pure Regex thingie.

**Comment by nitriques** [comment]
> because it's a pure Regex thingie.

I'll test it with 2.2 just to be sure ;)

**Comment by nitriques** [comment]
@michael-e I confirm that it works on 2.2 as well.

I wonder why it was coded like that, and sadly, [this is as far as git can go](https://github.com/symphonycms/symphony-2/commit/4cb00cc18ba070f599be73d8e3e7806ecefcfed9)

**Comment by michael-e** [comment]
> I wonder why it was coded like that

I have no idea.

**Comment by nitriques** [comment]
Well, it's committed! Thanks Micheal.

**Comment by michael-e** [comment]
Thank you!
