### ISSUE TITLE
Errors updating from 2.7.0.RC1 to 2.7.0

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2732]
Affected Symphony version(s) : 2.7.0
PHP version(s) : 7.1
OS(es) : CentOS

    31. July 2017, 11:24 > Fatal Error: Could not complete upgrading. MySQL returned: 1060: MySQL Error (1060): Duplicate column name 'author_id' in query: ALTER TABLE `sym_sections`
                        ADD COLUMN `author_id` int(11) unsigned NOT NULL DEFAULT 1,
                        ADD COLUMN `modification_author_id` int(11) unsigned NOT NULL DEFAULT 1,
                        ADD COLUMN `creation_date` datetime NOT NULL DEFAULT '2017-07-31 11:24:34',
                        ADD COLUMN `creation_date_gmt` datetime NOT NULL DEFAULT '2017-07-31 09:24:34',
                        ADD COLUMN `modification_date` datetime NOT NULL DEFAULT '2017-07-31 11:24:34',
                        ADD COLUMN `modification_date_gmt` datetime NOT NULL DEFAULT '2017-07-31 09:24:34',
                        ADD KEY `creation_date` (`creation_date`),
                        ADD KEY `creation_date_gmt` (`creation_date_gmt`),
                        ADD KEY `modification_date` (`modification_date`),
                        ADD KEY `modification_date_gmt` (`modification_date_gmt`);
    31. July 2017, 11:24 > Notice: Updater - Migration to 2.7.0 was unsuccessful

**Comment by nilshoerrmann** [comment]
I'm getting the same error. Is there a working fix already?

**Comment by animaux** [comment]
Fix is:

1. Ignore Error
2. Update Version Number in `config.php`
3. Delete `install` folder

Strangely I only had this error on one site while some others updated normally.

**Comment by nilshoerrmann** [comment]
Okay, thanks!

**Comment by nitriques** [comment]
Yeah sorry about this, I should have written this somewhere.. :(
