### ISSUE TITLE
Symph 2.7 break backwards compatibility with PHP 5.4 and less

### ISSUE THREAD

**Issue by pauloricca** [symphonycms/symphony-2#2734]
Affected Symphony version(s) : 2.7
PHP version(s) : PHP 5.3 / 5.4
OS(es) : N/A

/toolkit/symphony/lib/toolkit/class.sectionmanager.php makes use of empty() passing a function as argument which breaks compatibility with versions of PHP earlier than 5.5 as described here: http://php.net/manual/en/function.empty.php.

 and error on /toolkit/symphony/lib/toolkit/class.administrationpage.php in line 475 empty(__SYM_DATE_FORMAT__) which I'm guessing is related to the same issue.

**Comment by nitriques** [comment]
I've found a couple of other cases while comparing [2.6.x with 2.7.0](https://github.com/symphonycms/symphony-2/compare/2.6.x...2.7.0). Thanks for reporting this and sorry for the bug. 2.7.1 should be released pretty quickly.

**Comment by nitriques** [comment]
@pauloricca you can test the fix by checking out the 2.7.x branch. Thanks for reporting.
