### ISSUE TITLE
Creating a new entry while using prepopulate throws PHP error

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2737]
Affected Symphony version(s) : `2.7.0`
PHP version(s) : `5.6.30`
OS(es) : `OS X 10.11.6`

![screen shot 2017-08-21 at 14 19 28](https://user-images.githubusercontent.com/1640033/29521060-26414244-8684-11e7-937c-fa1d55234936.png)

![screen shot 2017-08-21 at 14 18 00](https://user-images.githubusercontent.com/1640033/29521064-2ba012f6-8684-11e7-9e8c-dc917e3ec16b.png)

![screen shot 2017-08-21 at 14 18 15](https://user-images.githubusercontent.com/1640033/29521071-30829078-8684-11e7-85ce-013d3a007e9d.png)

**Comment by nitriques** [comment]
Confirmed. Thanks Jens.
