### ISSUE TITLE
Ampersand in static XML DS

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2748]
Affected Symphony version(s) : `2.6.11`
PHP version(s) : `5.6.x`
OS(es) : `Linux`

I have a static content with `ampersands` in a static XML data source. Ampersands are written as entities, tried out  `&#38;`, `&amp;` or `&amp;amp;`

**Issue:**
After save, DS editor returns those ampersands as `&` characters, which upon repeated save returns `XML is invalid.` error message.

**Expected:**
To not to need to repeatedly escape ampersands.

**Comment by nitriques** [comment]
I can confirm the issue still exists in the latest 2.7.x branch.
