### ISSUE TITLE
Read-only DS display bug

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2753]
Affected Symphony version(s) : 2.6.11
PHP version(s) : 5.6.x
OS(es) : Linux
Browsers : checked on Opera, Firefox - latest versions

The display of DS's `read-only` text is probably broken within selected rows at `/symphony/blueprints/datasources/` backend page.

**Not selected row (ok)**
![1](https://user-images.githubusercontent.com/2209893/30356162-c713f472-9837-11e7-926f-946bda1e079f.png)

**Not selected row hover (ok)**
![2](https://user-images.githubusercontent.com/2209893/30356167-cabb1b46-9837-11e7-907b-bbb56c391b0b.png)

**Selected row**
![3](https://user-images.githubusercontent.com/2209893/30356172-cd58832a-9837-11e7-8e4e-7ddb8db23cb0.png)

**Selected row hover**
![4](https://user-images.githubusercontent.com/2209893/30356173-cf0c45bc-9837-11e7-978b-df881c3fae0d.png)

**Comment by nitriques** [comment]
This has been fixed in 2.7.0 in 7084906dbf7c634838964cf09baadf3671e718fa
