### ISSUE TITLE
Make the default log size bigger

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2757]
Affected Symphony version(s) : 3.0.0, possibly 2.7.1

We now log more things, so the default log size should be increased to prevnent

1) loss of information
2) possible errors when unlinking the log file

cc @wdebusschere

**Comment by wdebusschere** [comment]
I think it should be 10 or 100 times more, so that visitors don't get this unlink error on the webpage.

**Comment by nitriques** [comment]
@wdebusschere You can also set the max_size to 0 to disable rotation...

**Comment by michael-e** [comment]
I have never seen this "unlink error". When does it happen? On log rotation?

**Comment by wdebusschere** [comment]
Yes, or when you delete the log, but you need to have all errors/warnings on in php

`Warning: unlink(/Users/xxx/Sites/framework/manifest/logs/main): No such file or directory in /Users/xxx/Sites/framework/symphony/lib/toolkit/class.general.php on line 1094
Symphony Fatal Error: Headers already sent. Cannot start session.
An error occurred in /Users/xxx/Sites/framework/symphony/lib/core/class.session.php around line 88`

**Comment by michael-e** [comment]
All errors on? That's nothing for a production site, is it? I would do that in development only.

**Comment by wdebusschere** [comment]
Yes, its in development.

**Comment by michael-e** [comment]
So it's not a big deal, is it?

**Comment by michael-e** [comment]
Ah, I see now, all those new deprectated errors fill up the log very quickly!
