### ISSUE TITLE
Include a count of entries in associated sections doesn't work when a section starts with a number

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2765]
Affected Symphony version(s) : 2.7.0 and previous versions?
PHP version(s) : 5.6
OS(es) : OS X

Include a count of entries in associated sections doesn't work when the associated section starts with a number.

```  
error parsing attribute name in Entity, line: 894
/data/sites/web/moovne/www/symphony/lib/toolkit/class.xsltprocess.php:141
```

**Comment by michael-e** [comment]
Interesting that we get an error in this case, because no error is thrown if the name of a Data Source starts with a number (which will result in invalid XML as well).

Symphony is all about XML, so I suggest that, for the following items, Symphony should ensure that the first character of the handle must be **a letter**:

* fields
* sections
* data sources

(AFAIK, letters and underscores are allowed in element names, but there is no big sense in a Symphony handle starting with an underscore.)

**Comment by nitriques** [comment]
Yup nice catch. But I think that this is a breaking change, and thus, should not be released in the LTS version.

**Comment by nitriques** [comment]
But we could also fix it easily, by replacing the number with its English equivalent.

`2fast4you` would become `twofast4you`

**Comment by michael-e** [comment]
But that would a breaking change as well, because existing handles would change. :-)

**Comment by nitriques** [comment]
> But that would a breaking change as well, because existing handles would change. :-)

I meant only in the XML output! Sorry I should have mention this ;)

I would never change anything in the DB: Just prevent the crash

**Comment by michael-e** [comment]
Hmm, yes that might work.

**Comment by nitriques** [comment]
Looks like it won't be the first time we change things values to output in xml: the query string `oauth_token` becomes `url-oauth-token` (notice the `_` which get translated to `-`).

Note that a Data Source that starts with a number is allowed, but also crashes the XML.

I wonder if we should add a little notice to tell the user what will happen.

@michael-e ? @wdebusschere ? @brendo ?

**Comment by michael-e** [comment]
+1 for a notice, e.g.:

> Hey, it's about XML here! You know XML, don't you? Your stupid naming will break things!

:-)

**Comment by michael-e** [comment]
That said, I don't oppose "fixing" the name if there is a message.

**Comment by nitriques** [comment]
Do we all still agree that the proper fix is to prevent the user from creating section, fields, data sources and events that start with a digit ?

**Comment by michael-e** [comment]
IMHO it's definitely better to completely prevent such names than to "magically fix the handle".

**Comment by nitriques** [comment]
Great, 3.0.0 will do this.
