### ISSUE TITLE
Addition to the code style guildeline

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2777]
Affected Symphony version(s) : All
PHP version(s) : All
OS(es) : All

The following (or something similar) should be added to [the docs](https://github.com/symphonycms/symphony-2/wiki/Contributing-to-Symphony#code-style):

> Additionally, multi-line arrays should use a trailing comma for the last array element as well.

**Comment by nitriques** [comment]
Done. Thanks.
