### ISSUE TITLE
Prepopulation of `fields[text]` via URL is broken

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2779]
Affected Symphony version(s) : 2.7.x latest
PHP version(s) : 7.0

Apparently prepopulation of `fields[text]` via URL is broken in recent `2.7.x` code. It was still working in `2.7.0.beta2`, e. g.

    /symphony/publish/SECTION/new/?prepopulate[FIELD-ID]=Testtext

**Comment by animaux** [comment]
`2.7.0` seems to be working too.

**Comment by animaux** [comment]
I’m guessing this one here is responsible —> https://github.com/symphonycms/symphony-2/commit/54b8622d3db62ca33446ff043061617983508b2a

**Comment by animaux** [comment]
Ok, bug apparently is that `field.textarea.php` is missing:

    public function canPrePopulate()
    {
        return true;
    }

**Comment by animaux** [comment]
Same probably goes for some other fields then …

**Comment by nitriques** [comment]
Thanks @animaux !

> Same probably goes for some other fields then …

Looks like we are ok!

**Comment by animaux** [comment]
Brilliant! Thanks @nitriques
