### ISSUE TITLE
PHP 7.2 & session save handler.

### ISSUE THREAD

**Issue by petertron** [symphonycms/symphony-2#2783]
Affected Symphony version(s) : 2.7.x latest
PHP version(s) : 7.2.0RC6
OS(es) : Ubuntu 17.10

Trying to use Symphony with PHP 7.2.0 gives the following error:

`ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name()`

I don't have much understanding of what is going on.

![screenshot-2017-11-27 symphony error](https://user-images.githubusercontent.com/3197654/33266229-aed3d6a0-d36c-11e7-8022-1ed9cac651c9.png)

**Comment by nitriques** [comment]
I can't find anything on Google and PHP.net about this change. The only thing I can find is that 'user' seems like a valid value. Maybe related: https://github.com/php-memcached-dev/php-memcached/pull/359/files

I'll keep this open, but won't try to fix it until PHP7.2 is officially out.

**Comment by petertron** [comment]
Now PHP 7.2.0 has been released and is installed on my computer. Not surprisingly the same error happens.

The solution is to simply delete line 60. Setting a custom save handler is just a matter of using `session_set_save_handler()`. There is no reason why PHP should ever have allowed the 'user' option to be specified with `ini_set`.

**Comment by nitriques** [comment]
@petertron Thanks. Do we need to ever call it ? Does it still works on 5.6 without that line ?

**Comment by petertron** [comment]
Symphony works on PHP 5.6 without that line.

**Comment by nitriques** [comment]
Great. I'll fix it ASAP.
