### ISSUE TITLE
Column 'modification_author_id' cannot be null

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2785]
Affected Symphony version(s) : 2.7.0
PHP version(s) :5.6.32
OS(es) : osX

I try to create an event in order to add some data to a section.
But soon after i submit the form i'm getting this error

**Symphony Fatal Database Error: Column 'modification_author_id' cannot be null**

Steps to reproduce:

1. create a section
2. create an event  to that section
3. add the event/html code to a page

![screencapture-vsm-test-test-1514942449394](https://user-images.githubusercontent.com/2312755/34506416-29787fde-f035-11e7-986a-932891b010ca.png)

**Comment by cmnstmntmn** [comment]
[this](https://github.com/symphonycms/symphony-2/issues/2731) was fixing the issue.

**Comment by nitriques** [comment]
Yup the fix is in https://github.com/symphonycms/symphony-2/commit/ac89cfe7f4a08a05631237293561a9d0ad9e6b6b So I'll close this. Thanks.
