### ISSUE TITLE
Cannot select enable, disable, uninstall extensions

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2786]
Affected Symphony version(s) : 2.7.x
PHP version(s) : 5.6
OS(es) :

It's not possible to select enable, disable, uninstall extensions in the symphony cms extension page, the only way to do it s by the google developer console and manually add selected attribute to the with-selected option..

I have this problem in all 2.7.x sites and also with fresh install..

**Comment by nitriques** [comment]
I am unable to reproduce :( Can you reproduce in all your browsers ?

**Comment by wdebusschere** [comment]
Only in Google chrome, Version 63.0.3239.132 (no extensions enabled) 
Probably not symphony related, will investigate more.

**Comment by peterfleck** [comment]
I had this problem. I needed to clear browser cache.

Peter


On 20 Jan 2018 10:32, "Wannes Debusschere" <notifications@github.com> wrote:

Only in Google chrome, Version 63.0.3239.132 (no extensions enabled)
Probably not symphony related, will investigate more.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/symphonycms/symphony-2/issues/2786#issuecomment-359158760>,
or mute the thread

**Comment by wdebusschere** [comment]
Clearing cache didnt help. We also have tested this in the incognito mode, so it's not an chrome extension issue.

If we remove this code  `<option value="enable">Enable</option>` in the developer console everything works as normal. 

If we remove this `control.text(label.join('/'));` line [backend.views.js#L877](https://github.com/symphonycms/symphony-2/blob/2f9dc2dcf345fa6b0859f4c18931a86475f7cb1c/symphony/assets/js/src/backend.views.js#L877) it works without problems.

**Comment by nitriques** [comment]
@wdebusschere And you are able to reproduce on multiple computers ?

**Comment by nitriques** [comment]
What extensions do you have ?

**Comment by wdebusschere** [comment]
@nitriques I had it with a blank symphony install with the default extensions, had it on multiple computers on multiple servers. My colleague also had this on safari..

**Comment by nitriques** [comment]
@wdebusschere can you try to checkout the 2.7.x branch and build it with grunt to see if the problem persists ? I must have 20 `2.7­.0` installed and none of them have this. How do you install it ?

**Comment by nitriques** [comment]
So with the help (and patience) of @wdebusschere I was able to reproduce. Looks like a MAC specific bug.
