### ISSUE TITLE
Profiler delivers wrong "zero" durations under certain conditions

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2792]
Affected Symphony version(s) : all
PHP version(s) : all
OS(es) : all

Symphony fills a `Profiler::$_samples` array during page build. (This array is then used by the Profiler extension in order to display the information to the developer.)

Under certain conditions I experienced wrong "zero" durations in certain samples, and finally I found the reason. It will probably be more clear if you look at the fixes that I will send, but I will try to explain anyway:

The `Profiler::sample` function can be called with a type of `PROFILE_RUNNING_TOTAL` (which is the function's default) or with `PROFILE_LAP`. If the latter is used, the function will call `Profiler::retrieveLast()` in order to find the last sample element and calculate a duration from that point in time. This is dangerous if you don't know which is the last element, of course. If, for example, delegate calls have added sample elements in the meantime, you may refer to a an unexpected sample.

Using `PROFILE_LAP` is only reliable if you are really sure about the last sample.

Another issue (see the second commit in my pull request): `Profiler::retrieveTotalRunningTime` shouldn't use `Profiler::retrieveLast()`, because again we can't be sure which sample this will be. Furtunately, retrieving the total running time can be achieved in a simler and more reliable way.

**Comment by nitriques** [comment]
Closed in  e80ac53
