### ISSUE TITLE
The core loses emails when mass mailing

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2795]
Affected Symphony version(s) : all
PHP version(s) : all
OS(es) : all

In the log of the Email Newsletter Manager extension you may find lines like this:

    [2018/02/02 09:04:53] newsletter-id: 24632 - <![CDATA[Only one call to MAIL may be made at a time.]]>

The error `Only one call to MAIL may be made…` is coming from the Symphony core. To be precise, it's issued by `SMTP::mail`, and it means that an email failed because of a bug.

The issue is always triggered by an error which is happening before, for example a `5.1.1 … Recipient address rejected: User unknown in virtual mailbox table` error. In such a case, `SMTP::mail` has already been called, so `$this->_mail` will be true. Thus attempts to issue another `mail` command will fail. In practice, multiple emails will fail only because of a single "real" error. A handful emails later, sending will work again. (Maybe because the SMTP server has reset the connection? I am not sure about this…)

Fortunately, my clients have never noticed that emails get lost. Nevertheless:

I thought about the simplest way to avoid this. The SMTP class always uses `SMTP::_expect`, passing desired response codes. If the response codes are different from the expected ones, an `SMTPException` will be thrown. IMHO `SMTP::_expect` should **reset** (as in: `SMTP::rset`) immediately before throwing the exception. Not meeting desired response codes always means "error", and "error" means that we should "properly give up".

So the solution (successfully tested in my "big machine") seems to be:

```php
$this->rset();
```

in `SMTP::_expect`, immediatley before throwing the exception.

I will send a PR.

**Comment by nitriques** [comment]
Fixed in  b49cf53
