### ISSUE TITLE
Managers can delete managers, but not change their password

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2812]
Affected Symphony version(s) : all
PHP version(s) : all
OS(es) : all

Is this by design ? I've had a co-worker that needed to change the password for a manager and he could not do it, but was able to delete and re-create the account.

I find this odd.

**Comment by michael-e** [comment]
Yep, that is not logical.

**Comment by nitriques** [comment]
@michael-e which one should it be ? Should we disable delete ? Or allow password change ?

**Comment by michael-e** [comment]
My expectation would be that managers can manage authors only. If they are permitted to manage managers as well, they can "fight each other", so that makes no sense to me.

**Comment by fhamon** [comment]
In that case, could a manager create another manager? 🤔

**Comment by michael-e** [comment]
The simplest thing would be:

* Developers can create/edit/delete managers and authors.
* Managers can create/edit/delete authors only.

**Comment by nitriques** [comment]
Great. That's my opinion also.

**Comment by fhamon** [comment]
Fixed in https://github.com/symphonycms/symphony-2/pull/2814
