### ISSUE TITLE
Empty Session creation

### ISSUE THREAD

**Issue by brendo** [symphonycms/symphony-2#2820]
Affected Symphony version(s) : 2.7.0+
PHP version(s) : 5.5.9
OS(es) : Ubuntu

When creating a session, there is a [short circuit](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.session.php#L186) to prevent saving "empty" sessions in the database by checking if `Session::read` returns null. [Since this commit](https://github.com/symphonycms/symphony-2/commit/fd4c0d3d96e96af5dd0af79490d0e8c73550a469), the `Session::read` casts it's output to a string, meaning the check will never fulfil, and empty sessions are likely created.

Fixing this will likely improve performance and reduce unnecessary session creation. This is a regression in the 2.7.x branch.

**Comment by michael-e** [comment]
How bad. I wouldn't even see this as "Minor" bug (see label). For sites with a significant number of page impressions this can be really bad.

**Comment by brendo** [comment]
Agree @michael-e, I submitted a PR with the patch that I added to my client's site so we can get 2.7.5 released quickly 👍

**Comment by nitriques** [comment]
Thanks guys !
