### ISSUE TITLE
Textareas in 2.7.5 are showing as blank in the publish / backend

### ISSUE THREAD

**Issue by Huttch** [symphonycms/symphony-2#2824]
Affected Symphony version(s) : 2.7.5

Textareas are blank in the publish view in the backend but data is still there when pulling from data-sources etc

**Comment by nitriques** [comment]
@Huttch Thanks for reporting !

**Comment by nitriques** [comment]
@Huttch Update to [2.7.6](https://github.com/symphonycms/symphony-2/releases/tag/2.7.6) when you can!
