### ISSUE TITLE
 Notice: Use of undefined constant rawurlencode $path = array_map(rawurlencode, $path);

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2828]
Affected Symphony version(s) :
PHP version(s) :
OS(es) :

 Notice: Use of undefined constant rawurlencode $path = array_map(rawurlencode, $path);

https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.session.php#L115

Please follow the guideline for security bug disclosure https://github.com/symphonycms/symphony-2/wiki/Security-Bug-Disclosure

**Comment by michael-e** [comment]
I think that the line should be:

```php
$path = array_map('rawurlencode', $path);
```

instead of:

```php
$path = array_map(rawurlencode, $path);
```

**Comment by nitriques** [comment]
@michael-e indeed. But still, it works ;) I'll fix it in 3.0.0

**Comment by michael-e** [comment]
We generate warnings in the logs, so it would be cool to fix this in the LTS version, too.

**Comment by wdebusschere** [comment]
I'm using the code below in manifest.config, thanks @nitriques 
but this gets overwritten in each symphony update

 ###### LOG ######
        'log' => array(
            'archive' => '1',
            'maxsize' => '10240000',
            'filter' => E_ALL ^ E_DEPRECATED,
        ),
        ########

**Comment by nitriques** [comment]
> We generate warnings in the logs, so it would be cool to fix this in the LTS version, too.

@michael-e even with the default filter ??

> but this gets overwritten in each symphony update

With 24575 ? (this is the same value!)

**Comment by nitriques** [comment]
```
$ php -r "echo E_ALL ^ E_DEPRECATED;"
24575
```

**Comment by michael-e** [comment]
> @michael-e even with the default filter ??

@wdebusschere will know — he told me about it.

**Comment by wdebusschere** [comment]
can't follow

**Comment by nitriques** [comment]
This warning will only show up in the logs if

1. The log filter allows it (the default filter should)...
1. AND if the php settings are configured with with e_notice on (as @wdebusschere told me on the chat)

We turn off E_NOTICE, so I do not think we need to do anything on lts.

**Comment by nilshoerrmann** [comment]
I'm just recently updated a few Symphony install to 2.7.6 and I got this on every install. Symphony throws an error pages: 

> Symphony Warning: Use of undefined constant rawurlencode - assumed 'rawurlencode' (this will throw an Error in a future version of PHP)

This is on PHP 7.2.1.
A fix in LTS would be very much appreciated!

**Comment by nitriques** [comment]
@nilshoerrmann What are your error_reporting settings ?

**Comment by nilshoerrmann** [comment]
Where would I find these settings?

**Comment by michael-e** [comment]
The setting is in the config file. In the `symphony` array you should have a key named `error_reporting_all`. It can be `yes` or `no`, the default is `no`, which will make Symphony suppress as much notices and warnings as possible — which is, currently, absolutely necessary in production.

What about your warning? Is it thrown on every page? Backend or frontend page? Can you post the complete warning (or ist this all you see)?

**Comment by nilshoerrmann** [comment]
Okay, I don’t have this setting. If it’s a needed setting, shouldn’t the updater have added it?

**Comment by michael-e** [comment]
As far as I see (in the code), the behaviour still defaults to "suppress as much as you can", so if the setting is missing in the config, nothing bad will happen.

See https://github.com/symphonycms/symphony-2/blob/3.0.x/symphony/lib/boot/bundle.php#L37-L40

But indeed, the updater does not care for adding the setting.

I will be AFG (Away From GitHub) for some days, and I can't do more right now without answers to my above questions. But I am sure that @nitriques will try and help you if you provide more details.

**Comment by michael-e** [comment]
From reading the above comments I think that @nitriques intended to fix this issue in 3.0.x only. I suggested to fix it in 2.7.x as well.

If you need a quick fix, please refer to my comment: https://github.com/symphonycms/symphony-2/issues/2828#issuecomment-384042141

**Comment by nilshoerrmann** [comment]
This is what I get:

![bildschirmfoto am 2018-06-13 um 11 03 34](https://user-images.githubusercontent.com/25466/41341865-10a49ed0-6efb-11e8-8418-f43261ed9502.png)

Symphony 2.7.6 on PHP **7.2** – PHP 7.1 is just fine.

**Comment by michael-e** [comment]
Yep, so this is the same issue. As I mentioned, the simple fix is to put single quotes around `rawurlencode` in [this line](https://github.com/symphonycms/symphony-2/blob/2.7.6/symphony/lib/core/class.session.php#L115).

**Comment by nilshoerrmann** [comment]
Yes, I’ve done this already :)

**Comment by nitriques** [comment]
> Symphony 2.7.6 on PHP 7.2

Officially 7.2, is not supported. But I'll fix it since I have a release to do anyways.
