### ISSUE TITLE
(Forward) slashes shouldn't be escaped in htaccess regex expressions

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2855]
Affected Symphony version(s) : all
PHP version(s) : all
OS(es) : all

In `.htaccess` regex expressions, some (but not all) forward slashes are escaped. This is useless and might even be considered bad practice, because a slash has no special meaning in regex.

The lines are:

* https://github.com/symphonycms/symphony-2/blob/2.7.7/install/includes/htaccess.txt#L37
* https://github.com/symphonycms/symphony-2/blob/2.7.7/install/includes/htaccess.txt#L41
* https://github.com/symphonycms/symphony-2/blob/2.7.7/install/includes/htaccess.txt#L46

**Comment by nitriques** [comment]
Hum, I never found the proper doc for this. Maybe Apache 2.2 required it ?

**Comment by michael-e** [comment]
I haven't found any explanation for escaped slashes on the interwebs.

**Comment by nitriques** [comment]
Since your last comment, I have been omitting them and did not ran into any issue. I mostly tested Apache 2.4 tho, not sure if I still have it somewhere.

Would you be ok if we target this for 3.0.0 ?

**Comment by michael-e** [comment]
If you say it's a bug, we might fix it in 2.7. But if you say it's not a bug (and from a functional perspective it isn't, because it works fine as it is), let's simply do it right next time (a.k.a 3.0.0)! :-)

**Comment by nitriques** [comment]
> because a slash has no special meaning in regex. 

Generally speaking, this is true. But not in php nor js, since it is the default delimiter, they need to be escaped. That's were the confusion lies.

I've never had experience with a RE engine that choked on escaped /, so I never bothered. But it makes the RE much more pleasant.
