### ISSUE TITLE
Date Field calendar widget not available when in error mode

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2857]
Affected Symphony version(s) : 2.7.7
PHP version(s) : All
OS(es) : All

**Issue:**
When in error, date field calendar is not being offered.

**Error**
![image](https://user-images.githubusercontent.com/2209893/43206637-81a63e12-9026-11e8-9184-e69df3a162df.png)

**No error**
![image](https://user-images.githubusercontent.com/2209893/43206558-512dbc2e-9026-11e8-8dfe-cdc446c838f0.png)

**Expected:**
To have the calendar available also in error mode. Because I can't write dates :baby:

**Notes:**
No errors present in browser's dev console a.k.a. Inspector.

**Comment by nitriques** [comment]
Thanks for reporting. A 4 years old bug, congrats.
