### ISSUE TITLE
Anti-spam software suggests modifications to the email core

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2858]
Affected Symphony version(s) : 2.7, 3.x
PHP version(s) : all
OS(es) : all

Anti-Spam software (e.g. [SpamAssassin](http://spamassassin.apache.org)) uses hundreds of criteria in order to build a spam score for email messages. Generally, emails built by the Symphony core are pretty "good", so in conjunction with a properly configured mail server your emails should pass Anti-Spam software without issues.

However, SpamAssassin is not alone. [Rspamd](https://rspamd.com), for example, is considered a more modern alternative by some people. When I integrated Rspamd into one of my mail servers, I noticed that it has two special rules that conflict with emails sent by Symphony:

* XM\_UA\_NO\_VERSION — *X-Mailer/User-Agent has no version*

	Symphony adds an "X-Mailer: Symphony Email Module" header to emails. Obviously Rspamd thinks that this is not really serious without a software version number. I wouldn't like to add the Symphony version here, because we shouldn't expose the exact Symphony version to the outer world without need. Do we need to advertise Symphony in email headers at all? I suggest to remove the "X-Mailer" header completely.

* SUBJ\_EXCESS\_QP — *Subect (sic!) is unnecessarily encoded in quoted-printable*

	Yes, the Symphony core always encodes the mail subject, even if it contains nothing but 7-Bit-ASCII. It's not difficult to fix this.

@nitriques: I can send a PR for both issues, if you agree with my above proposals. Would you consider this a bugfix (which would mean 2.7.x)?

**Comment by michael-e** [comment]
BTW: The "unnecessarily encoded" issue is important for other headers as well, so we should/can fix this in the corresponding helper function.

**Comment by nitriques** [comment]
@michael-e I guess that you've been running the patch in production for some time now ?

**Comment by michael-e** [comment]
Yep, sure. Works fine.

**Comment by nitriques** [comment]
:+1: Thanks

**Comment by froschdesign** [comment]
@nitriques @michael-e 
I have some ideas that could help to simplify this part of the CMS.
Interested in a deeper discussion? If so, where is the right place for this? Here?

**Comment by nitriques** [comment]
@froschdesign Please open a new issue on github or come join in the gitter.im chat!

**Comment by nitriques** [comment]
Fixed in  5ed669f
