### ISSUE TITLE
Fix PHP 7 warnings

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2870]
Affected Symphony version(s) : 2.7
PHP version(s) : 7.x
OS(es) : all

Some time ago we invented a configuration setting in Symphony in order to aid code improvements by outputting all PHP warnings.

My hope was that some experienced programmer would use this option to fix all those nasty warnings, simply because these warnings may become severe errors as PHP evolves. And I would love to see Symphony's LTS version work fine on the latest and greatest PHP version for the coming years.

Who ever dared to set `error_reporting_all` to `yes` for a real-world Symphony website (on PHP 7)?. I did! Well, yes, the result is a bit shocking at first sight. :-)

I will send a PR that fixes a bunch of warnings in the Symphony backend. It is far from complete, and I have not cared for the frontend at all, nor will I probably do. It just doesn't make much sense, because my programming knowledge and experience ist too limited. In other words: It would be much simpler for someone who really knows programming.

So this is really just a start (and nevertheless I am sure that some of my "fixes" should be discussed and/or improved). I would be glad to see someone taking this over, sending more PRs!

**Comment by nitriques** [comment]
:+1: !!! I also do it from time to time in order to find bugs ! I will try to make the unit test pass with error_reporting_all for 3.0.x !

**Comment by nitriques** [comment]
`2.7.8` is out with the fixes
