### ISSUE TITLE
Url parameters order[0][dir] in ? debug = url-order1.dir but in reality it is/should be $url-order.1.dir

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2880]
Affected Symphony version(s) : 2.7.7
PHP version(s) : 7.1
OS(es) :

I'm using an url-paramter (btw, comes from jquery datatables) order[0][dir], which gets encoded in the url as order%5B0%5D%5Bcolumn%5D%3D1.
In the ? debug i get $url-order1.dir but this is wrong should be $url-order.1.dir (=this is working in my datasource filter)

**Comment by nitriques** [comment]
Sadly, fixing it would be a breacking change...

**Comment by wdebusschere** [comment]
No problem, just a small bug, easy to bypass

**Comment by nitriques** [comment]
@wdebusschere I got a fix working ;)
