### ISSUE TITLE
Datasource Type navigation Sort By choice not remembered

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2881]
Affected Symphony version(s) : 2.7.7
PHP version(s) : 7.1
OS(es) :

Datasource Type navigation Sort By choice not remembered.

Please follow the guideline for security bug disclosure https://github.com/symphonycms/symphony-2/wiki/Security-Bug-Disclosure

**Comment by nitriques** [comment]
nice find. I've fixed it.

**Comment by wdebusschere** [comment]
nice find = daily symphony usage :)
