### ISSUE TITLE
PHP 7.2.8: Deprecated: idn_to_utf8(): INTL_IDNA_VARIANT_2003

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2883]
Affected Symphony version(s) :
PHP version(s) : 7.2.8
OS(es) :

Deprecated: idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated in /Users/xxx/Sites/xxx/symphony/lib/boot/defines.php on line 218

**Comment by michael-e** [comment]
There has already been a discussion (https://github.com/symphonycms/symphony-2/issues/2864) and a fix (https://github.com/symphonycms/symphony-2/commit/ad43faf7c9d82e151707f33d3fb44c8200cb3ecf). If you look at the commit history (https://github.com/symphonycms/symphony-2/commits/2.7.x), you see that it will be in the next release (which shouldn't be far away, I think). For now, you can simply simply check out the 2.7.x branch to solve your issue.
