### ISSUE TITLE
How to run Symphony in a subdirectory of another website?

### ISSUE THREAD

**Issue by timokleemann** [symphonycms/symphony-2#2889]
Affected Symphony version(s) : 2.7.7
PHP version(s) : 5.6
OS(es) : Unix

For a recent project, I implemented an NGINX proxy server to proxy requests from a Symphony installation on a subdomain (`blog.foo.com`) so that they appear to come from a subdirectory of the main domain (`www.foo.com/blog`).

This does work, however I still have to login to Symphony via `blog.foo.com/symphony`. Besides being cumbersome it brings with it the problem that no login cookie (I assume that's how it works) is created at `www.foo.com`.

So:

Is there a way to proxy the entire Symphony installation to `www.foo.com/blog` so that I can access Symphony via `www.foo.com/blog/symphony`?

What must be changed in the `.htaccess` file?

Thanks for any pointers!

**Comment by michael-e** [comment]
You posted the same question already twice:

* https://www.getsymphony.com/discuss/thread/113863/
* https://stackoverflow.com/questions/54890389/best-way-to-proxy-subdomain-to-subdirectory

Closed.

**Comment by michael-e** [comment]
Some pointers: https://www.getsymphony.com/discuss/thread/113863/1/#position-2
