### ISSUE TITLE
Unusual payloads may cause XML/XSLT errors 

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2892]
Affected Symphony version(s) : 2.7.x
PHP version(s) : all
OS(es) : all

Certain "evil" URLs/query strings or posted field values (sent by automated vulnerability scanners, for example) throw XML or XSLT exceptions in 500 responses.

These exceptions are not a big risk, because the information in these exceptions is not very useful to an attacker (IMHO). But it's not nice either that it's so simple to trigger XML/XSLT exceptions.

Fortunately, two small additions and one bugfix suffice to prevent nearly all exceptions that I noticed.

I will send (resp. add to existing) PRs, referencing this issue.

**Comment by michael-e** [comment]
I should mention that preventing the system from "breaking" (i.e. thowing an exeception) might — theoretically — disclose other weaknesses with unusual/evil payloads. However, I think that we should look forward, technically.

**Comment by nitriques** [comment]
> However, I think that we should look forward, technically.

It has been dealt with in 3.0.x

**Comment by michael-e** [comment]
> It has been dealt with in 3.0.x

Great!
