### ISSUE TITLE
Brackets in field handles not transliterated (removed) anymore

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2900]
Affected Symphony version(s) : 2.7.10 (since some version after 2.7.7)
PHP version(s) : 7.3 
OS(es) : all

Brackets used to be removed for autmatically created field handles. After creating a new field with brackets in its name, now this comes up, and the handles have to be cleared manually:

![Bildschirmfoto 2019-04-25 um 10 00 45](https://user-images.githubusercontent.com/446874/56719906-eab86900-6741-11e9-95eb-91d7601052d7.png)

**Comment by cylkee** [comment]
Is this related to #2890?

**Comment by animaux** [comment]
Oh yes, sorry it’s a duplicate!

**Comment by michael-e** [comment]
@animaux your issue is in your language extension (https://github.com/animaux/lang_german/blob/02ff2d44270000a32475d1b4b2cb70781a4dcb5c/lang/lang.de.php#L2145), which must be fixed as well. We only fixed it in the core.

**Comment by animaux** [comment]
Thanks @michael-e! Will this break the extension for older symphony versions?

**Comment by michael-e** [comment]
The bug was introduced in 2.3RC1 (https://github.com/symphonycms/symphony-2/commit/6983d12cf2d5f28935b1b0fd6bdeb00e234cbb9e). So yes, theoretically it would break the extension for Symphony < 2.3.

**Comment by animaux** [comment]
OK thanks. Strange that it worked fine all the time since then …

**Comment by michael-e** [comment]
Yep (see https://github.com/symphonycms/symphony-2/issues/2890#issue-416526962):

> It is almost unbelievable that we have not noticed this very old bug before.

No idea why.

**Comment by animaux** [comment]
¯\_(ツ)_/¯  The mysteries of complex software!
