### ISSUE TITLE
Backend subheading trim with diacritics

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2901]
Affected Symphony version(s) : 2.7.x (older versions probably too)
PHP version(s) : 7.2.17
OS(es) : GNU/Linux - Ubuntu 18.04

![image](https://user-images.githubusercontent.com/2209893/57264541-ca0dde80-7072-11e9-917a-1a8cce424bb1.png)

**Use case**
Editing an entry.

**Issue description**
When entry's subheading title is being trimmed in backend `header` (`context` id) and the last character is with diacritics (e.g. `í`, `é`, `č` etc), a "question" mark is shown instead of the last character.

**Comment by brendo** [comment]
What field is that value stored in? The default implementation for the Input field uses `prepareReadableValue` which uses Symphony's `General` functions to calculate the length and truncation. These functions make use of the `mb_*` methods which should support multibyte characters (so long as the server has mbstring enabled, which it _should_ do these days!)

**Comment by jurajkapsz** [comment]
Thanks @brendo I didn't had `mbstring` enabled on that server.
