### ISSUE TITLE
vendor directory missing from 3.0.0 branch

### ISSUE THREAD

**Issue by cylkee** [symphonycms/symphony-2#2918]
Affected Symphony version(s) : 3.0.0
PHP version(s) : 7.3
MySQL version(s): 10.3 MariaDB
OS(es) : Linux

I just tried to install 3.0.0 for the first time from a fresh Git clone and it wont run because the repo is missing the vendor directory.

`Warning: require_once(/path-redacted/vendor/autoload.php): failed to open stream: No such file or directory in /path-redacted/install/index.php on line 37`

**Comment by petertron** [comment]
Running "composer install" will create the vendor directory. But of course, it should be there already.

**Comment by designermonkey** [comment]
Composer's vendor directory should never be committed to a version control!!

**Comment by cylkee** [comment]
I went to check the [Git installation instructions](https://github.com/symphonycms/symphonycms/blob/master/.docs/dev/INSTALLING.md#via-git) and it appears there's a new step for 3.0:

> Run composer to install the dependencies and generate the auto-loader: `composer install --no-dev -o`

So I will try again and report back.

**Comment by cylkee** [comment]
Okay, new installation attempt successful.
