### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2945]
Not sure where to raise this any more @nitriques but the website is down with a crashed table. The only access I had was an admin login, not the infra level.

**Comment by nitriques** [comment]
Hey! Should be up now. Hosting php 5.3 is a pain. I have a couple of cron jobs that repairs the table at regular interval to help it, but yeah, we sometimes get down short and long donwtimes.

<img width="540" alt="image" src="https://github.com/symphonycms/symphonycms/assets/771169/8b29ba0d-78cb-47d7-81c9-6746daa14189">

I also had to edit the code myself to make this old version return 500 on failures, which was not the case at the time!

**Comment by designermonkey** [comment]
Thanks Nicolas.
